src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Default_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to store financial account on vendor invoice lines for the current vendor</description>
        <inlineHelpText>Financial Account for vendor invoice lines</inlineHelpText>
        <label>Default Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <description>Select this record type for member accounts.</description>
        <label>Household</label>
    </recordTypes>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Use Address for Billing</description>
        <label>Billing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <description>This is the start date that the member uses this address.</description>
        <inlineHelpText>This is the start date that the member uses this address.</inlineHelpText>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Statements__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Statements</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <description>This is the end date of the date range the Member or Guest uses this address.</description>
        <inlineHelpText>This is the end date of the date range the Member or Guest uses this address.</inlineHelpText>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Customer_Id__c</fullName>
        <label>Member Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <description>Select this record type for creating members.</description>
        <label>Member</label>
    </recordTypes>
</CustomObject>

src/objects/Default_Account__c.object
<CustomObject>
    <description>Contains TXN to financial Account Mapping</description>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>containing relation to financial account</description>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Default Accounts</relationshipLabel>
        <relationshipName>Txn_To_Financial_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Default Account</label>
    <nameField>
        <displayFormat>DA-{00000}</displayFormat>
        <label>Default Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Member_Dues__c.object
<CustomObject>
    <description>Dues  subscription for member on different categories</description>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Financial Account for crediting the amount charged through the due</description>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipName>Billing_Table</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Member Dues</label>
    <nameField>
        <label>Due Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Dues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Statements__c.object
<CustomObject>
    <description>the object is used to store member statements</description>
    <fields>
        <fullName>AddressId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AddressId</label>
        <referenceTo>Address__c</referenceTo>
        <relationshipLabel>Statements</relationshipLabel>
        <relationshipName>Statements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <formula>IF(ISBLANK(AddressId__c), &apos;&apos;, IF( ISBLANK( AddressId__r.Addressee__c ) ,  Member__r.Full_Member_Name__c , AddressId__r.Addressee__c)&amp;
IF( ISBLANK( AddressId__r.Street_1__c ) , &apos;&apos;, &apos; &apos; &amp; AddressId__r.Street_1__c)&amp;
IF( ISBLANK( AddressId__r.Street_2__c ) , &apos;&apos;, &apos; &apos; &amp; BR() &amp; AddressId__r.Street_2__c)&amp;
IF( ISBLANK( AddressId__r.Street_3__c ) , &apos;&apos;, &apos; &apos; &amp; AddressId__r.Street_3__c)&amp;
IF( ISBLANK( AddressId__r.City__c ) , &apos;&apos;, &apos; &apos; &amp; BR() &amp; AddressId__r.City__c )&amp;
IF( ISBLANK( TEXT(AddressId__r.State_Province__c )) , &apos;&apos;, &apos; &apos; &amp; TEXT(AddressId__r.State_Province__c))&amp;
IF( ISBLANK( TEXT(AddressId__r.Country__c  )) , &apos;&apos;, &apos; &apos; &amp; TEXT(AddressId__r.Country__c))&amp;
IF( ISBLANK( AddressId__r.Zip_Postal_Code__c ) , &apos;&apos;, &apos; &apos; &amp; AddressId__r.Zip_Postal_Code__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>only for member statement recordtype</description>
        <label>Member</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.Record_Type_Name__c</field>
                <operation>equals</operation>
                <value>Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Statements (Member)</relationshipLabel>
        <relationshipName>MemberStatements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Statement_Summary_Name__c</fullName>
        <description>contains the name of the summary record</description>
        <label>Statement Summary Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Statement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Statement</label>
        <referenceTo>Statements__c</referenceTo>
        <relationshipLabel>Statements</relationshipLabel>
        <relationshipName>Statements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <label>Statement</label>
    <nameField>
        <displayFormat>Stmt-{0000000}</displayFormat>
        <label>Statements Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TXN__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Transactions (Financial Account)</relationshipLabel>
        <relationshipName>Transactions3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member_Dues__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to fill the due id in this</description>
        <label>Member Dues</label>
        <referenceTo>Member_Dues__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Statement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to store the statement line id</description>
        <label>Statement</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Statements__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Statement Line</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Statements__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StatementsTest.cls
@isTest
private class StatementsTest
{
	/**
	* @Description : test method for GenerateStatementController And GenerateStatementBatch
	*/

	@testSetup
	static void setup(){
		Financial_Account__c fa = TxnTestUtility.createFinancialAccount('teest');
        Default_Account__c da =TxnTestUtility.getDefaultMapping('Accounts Receivable',fa);
        da =TxnTestUtility.getDefaultMapping('Accounts Payable',fa);
        da = TxnTestUtility.getDefaultPaymentMapping('Cash',fa) ;
	}

	@isTest
	static void GenerateStatementsTest1()
	{		
		Account acc = TxnTestUtility.createAccount(Utility.searchRecordType('Household','Account'));
		Contact member = TxnTestUtility.createMember(acc, 'Dependent', Utility.searchRecordType('Member','Contact'));
		member.Customer_Id__c = '3536';
		update member;
		//Member_Dues__c memDue = TxnTestUtility.getDue('Test statement due', 'Annual');
		//List<TXN__c> manualDueAndTaxes = TxnTestUtility.getManualDuesWithTaxes(memDue, member);
		//TXN__c payRec = TxnTestUtility.txnCreatePay(member);
		//TXN__C refRec = TxnTestUtility.getRefundFromPayment(payRec);
		//List<TXN__c> adjustments = TxnTestUtility.getAdjustmentRecordsOnDues(manualDueAndTaxes[0]);
		TXN__C eveCharge = TxnTestUtility.getEventCharges(member);
		Test.startTest();
		GenerateStatementController genStmt = new GenerateStatementController();
		genStmt.monthYear = Date.today().year()+' '+Date.today().addMonths(-1).month();
		genStmt.status = 'Confirm';
		genStmt.statementSummaryRec.Statement_Summary_Name__c = 'test statements';
		genStmt.generate();
		System.assert(genStmt.batchId!=null);
		Test.stopTest();
	}

	/**
	* @Description : test method 2 for GenerateStatementController And GenerateStatementBatch 
	*/
	@isTest
	static void GenerateStatementsTest2(){
		Account acc = TxnTestUtility.createAccount(Utility.searchRecordType('Household','Account'));
		Contact member = TxnTestUtility.createMember(acc, 'Dependent', Utility.searchRecordType('Member','Contact'));
		member.Customer_Id__c = '3536';
		update member;
		Statements__c stmtSumm = TxnTestUtility.getStatementSummary(member);
		Member_Dues__c memDue = TxnTestUtility.getDue('Test statement due', 'Annual');
		TxnTestUtility.getManualDuesWithTaxes(memDue, member);
		Test.startTest();
		GenerateStatementController genStmt = new GenerateStatementController();
		genStmt.statementSummaryRec.Statement_Summary_Name__c = 'test statements';
		try{
			genStmt.generate();
		}
		catch(Exception ex){
			System.assert(ex.getMessage().Contains('mandatory fields'));
		}	
		genStmt.monthYear = Date.today().year()+' '+Date.today().addMonths(-1).month();
		genStmt.status = 'Confirm';
		genStmt.generate();
		System.assert(genStmt.batchId!=null);
		genStmt.cancel();
		System.assertEquals('', genStmt.status);
		Test.StopTest();
	}

	/**
	* @Description : test method for ApproveRejectStatements batch
	*/
	@isTest
	static void ApproveRejectStatementSummary(){
		Account acc = TxnTestUtility.createAccount(Utility.searchRecordType('Household','Account'));
		Contact member = TxnTestUtility.createMember(acc, 'Dependent', Utility.searchRecordType('Member','Contact'));
		member.Customer_Id__c = '3536';
		update member;
		Statements__c stmtSumm = TxnTestUtility.getStatementSummary(member);
		Date todaysDate = Date.today();
		stmtSumm.Date__c = Date.newInstance(todaysDate.year(), todaysDate.month(), 1);
		update stmtSumm;
		Test.startTest();
		GenerateStatementController genStmt = new GenerateStatementController();
		genStmt.statementSummaryRec.Statement_Summary_Name__c = 'test statements';
		genStmt.monthYear = Date.today().year()+' '+Date.today().addMonths(-1).month();
		genStmt.status = 'Confirm';
		genStmt.generate();
		System.assertEquals(true, genStmt.confirmOnDup);
		genStmt.status = 'Generate';
		genStmt.generate();
		System.assert(genStmt.batchId!=null);
		Test.stopTest();
	}

	/**
	* @Description : Test class for approval process of statements - covered ApprovalStatementsController and ApproveRejectStatements
	*/
	@isTest
	static void ApprovalStatementsControllerTest(){
		Account acc = TxnTestUtility.createAccount(Utility.searchRecordType('Household','Account'));
		Contact member = TxnTestUtility.createMember(acc, 'Dependent', Utility.searchRecordType('Member','Contact'));
		member.Customer_Id__c = '3536';
		update member;
		Statements__c stmtSumm = TxnTestUtility.getStatementSummary(member);
		Test.startTest();
		ApproveStatementsController apc = new ApproveStatementsController();
		apc.approveAll = true;
		apc.approveAllStatements();
		apc.renderStatementTable();
		apc.refreshPageSize();
		System.assertEquals(false, apc.hasNext);
		System.assertEquals(false, apc.hasPrevious);
		System.assertEquals(1, apc.getTotalPages());
		System.assertEquals(1, apc.pageNumber);
		apc.approveStatemets();
		System.assert(apc.batchId!=null);
		Test.stopTest();
	}

	/**
	* @Description : test method for UpdateStatementBatch
	*/
	@isTest
	static void UpdateStatementBatchTest(){
		Account acc = TxnTestUtility.createAccount(Utility.searchRecordType('Household','Account'));
		Contact member = TxnTestUtility.createMember(acc, 'Dependent', Utility.searchRecordType('Member','Contact'));
		Statements__c stmtSumm = TxnTestUtility.getStatementSummary(member);
		Date todaysDate = Date.today();
		stmtSumm.Date__c = Date.newInstance(todaysDate.year(), todaysDate.month(), 1);
		stmtSumm.To_Date__c = Date.newInstance(todaysDate.year(), todaysDate.month(), todaysDate.addMonths(1).toStartOfMonth().addDays(-1).day());
		update stmtSumm;
		Statements__c stmtSumm1 = TxnTestUtility.getStatementSummary(member);
		stmtSumm1.Date__c = Date.newInstance(todaysDate.year(), todaysDate.addMonths(1).month(), 1);
		stmtSumm.To_Date__c = Date.newInstance(todaysDate.year(), todaysDate.month(), todaysDate.addMonths(2).toStartOfMonth().addDays(-1).day());
		stmtSumm1.Statement__c = stmtSumm.id;
		update stmtSumm1;
		GenerateStatementController genStmt = new GenerateStatementController();
		genStmt.statementSummaryRec.Statement_Summary_Name__c = 'test statements';
		genStmt.monthYear = Date.today().year()+' '+Date.today().addMonths(-1).month();
		genStmt.status = 'Confirm';
		genStmt.generate();
		System.assertEquals(true, genStmt.callRegenerate);
		Member_Dues__c memDue = TxnTestUtility.getDue('Test statement due', 'Annual');
		List<TXN__c> manualDueAndTaxes = TxnTestUtility.getManualDuesWithTaxes(memDue, member);
		TXN__c payRec = TxnTestUtility.txnCreatePay(member);
		TXN__C refRec = TxnTestUtility.getRefundFromPayment(payRec);
		List<TXN__c> adjustments = TxnTestUtility.getAdjustmentRecordsOnDues(manualDueAndTaxes[0]);
		Test.startTest();
		TXN__C eveCharge = TxnTestUtility.getEventCharges(member);
		genStmt.status = 'Update';
		genStmt.generate();
		System.assert(genStmt.batchId!=null);
		Test.stopTest();
	}

	@isTest
	static void StatementDetailTest(){
		Account acc = TxnTestUtility.createAccount(Utility.searchRecordType('Household','Account'));
		Contact member = TxnTestUtility.createMember(acc, 'Dependent', Utility.searchRecordType('Member','Contact'));
		Statements__c stmtSumm = TxnTestUtility.getStatementSummary(member);
		Statements__c memStmt = [Select Id, RecordType.Name from Statements__c where Statement__c=:stmtSumm.id];
		Statements__c stmtLine = [Select Id, RecordType.Name from Statements__c where Statement__c=:memStmt.id];
		PageReference pageRef = Page.StatementsDetail;
		Test.setCurrentPage(pageRef);
		pageRef.getParameters().put('retURL', 'GenerateStatements');
		pageRef.getParameters().put('delId', memStmt.id);
		Test.startTest();
		StatementsDetailController stdCont1 = new StatementsDetailController(new ApexPages.StandardController(memStmt));
		stdCont1.initializeActivity();
		System.assertEquals(true, stdCont1.isMemStmt);
		pageRef.getParameters().put('delId', stmtSumm.id);
		StatementsDetailController stdCont = new StatementsDetailController(new ApexPages.StandardController(stmtSumm));
		stdCont.initializeActivity();
		System.assert(stdCont.batchId!=null);
		pageRef.getParameters().put('delId', null);
		pageRef.getParameters().put('Id', stmtLine.id);
		StatementsDetailController stdCont2 = new StatementsDetailController(new ApexPages.StandardController(stmtLine));
		stdCont2.initializeActivity();
		System.assertEquals(true,stdCont2.isEdit);
		Test.stopTest();
	}

	/**
	* @Description : test method for statementsDomain
	*/
	@isTest
	static void statementDomainTest(){
		Account acc = TxnTestUtility.createAccount(Utility.searchRecordType('Household','Account'));
		Contact member = TxnTestUtility.createMember(acc, 'Dependent', Utility.searchRecordType('Member','Contact'));
		Contact member1 = TxnTestUtility.createContact('Testing statement', 'addresses', Utility.searchRecordType('Member','Contact'));
		Address__c address = TxnTestUtility.getAddress(member, 'Home');

		List<Address__c> addressesList = new List<Address__c>();
		Address__c address1 = TxnTestUtility.getAddress(member1, 'Home');
		address1.Billing__c = true;
		addressesList.add(address1);
		Address__c address2 = TxnTestUtility.getAddress(member1, 'Home');
		address2.From_Date__c = Date.today();
		address2.To_Date__c = Date.today();
		address2.Billing__c = true;
		addressesList.add(address2);
		update addressesList;
		Statements__c stmtSumm = TxnTestUtility.getStatementSummary(member);
		Statements__c memStmt = [Select Id, RecordType.Name, AddressId__c from Statements__c where Statement__c=:stmtSumm.id];
		System.assertEquals(address.id, memStmt.AddressId__c);
		Statements__c stmtSumm1 = TxnTestUtility.getStatementSummary(member1);
		Statements__c memStmt1 = [Select Id, RecordType.Name, AddressId__c from Statements__c where Statement__c=:stmtSumm1.id];
		System.assertEquals(address2.id, memStmt1.AddressId__c);
		Test.startTest();
		// bulk test
		List<Statements__c> stmtListToUpdate = new List<Statements__c>();
		for(Integer i=0; i<200; i++){
			Statements__c memStmt3 = new Statements__c(RecordTypeId=Utility.searchRecordType('Member Statement','Statements__c'));
			memStmt3.Statement__c = stmtSumm.id;
			memStmt3.Member__c = member.id;
			stmtListToUpdate.add(memStmt3);
		}
		insert stmtListToUpdate;
		Test.stopTest();
	}
}