src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Select this record type to create a vendor.</description>
        <label>Vendor</label>
    </recordTypes>
</CustomObject>

src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Vendor, Reciprocal Club</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vendor Invoices</relationshipLabel>
        <relationshipName>Vendor_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vendor Invoice</label>
    <nameField>
        <displayFormat>VNDRINVENTR-{0000000}</displayFormat>
        <label>Vendor Invoice Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice_Line__c.object
<CustomObject>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Vendor Invoice Lines (Financial Account)</relationshipLabel>
        <relationshipName>Vendor_Invoice_Lines</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoice__c</fullName>
        <label>Vendor Invoice</label>
        <referenceTo>Vendor_Invoice__c</referenceTo>
        <relationshipLabel>Vendor Invoice Lines</relationshipLabel>
        <relationshipName>Vendor_Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vendor Invoice Line</label>
    <nameField>
        <displayFormat>VNDRSTMTLNE-{0000000}</displayFormat>
        <label>Vendor Invoice Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VendInvLine.cls
/**
 * @Date: 20th May - 2017
 * @Author: Jyotig@mobifyi.com 
 * @group: Financial Management 
 * @Description: controller class for CreateVendInvLine page
 */

public with sharing class VendInvLine {
    public Vendor_Invoice__c vendInv {get; set;}
    public Vendor_Invoice_Line__c venInvLine {get; set;}

    // if invoice already posted then make isPosted true and request coming for edit make isEditBoolean true
    public boolean isEditBoolean {get; set;}
    public boolean isPosted {get; set;} 

    // service class variable
    public cmsft_VendInvLineService service;

    /**
    * @Description : fill vendor invoice variable vendInv with the coming record id or create new and assign to it in case of save&New
    */
    public VendInvLine(ApexPages.StandardController std) {
        service = new cmsft_VendInvLineService();
        venInvLine = (Vendor_Invoice_Line__c)std.getRecord();
        isEditBoolean = false;
        isPosted = false;
        if(ApexPages.currentPage().getParameters().get('id')!=null){
            isEditBoolean = true;
            venInvLine = service.getVendorInvoiceLineFullRecordService(ApexPages.currentPage().getParameters().get('id'));
            vendInv = service.getVendorInvoiceFullRecordService(venInvLine.Vendor_Invoice__c);
        }
        else if(std.getRecord()!=null && venInvLine.Vendor_Invoice__c!=null){
            vendInv = service.getVendorInvoiceForNewNEditVILService(venInvLine);
        }
        else if(ApexPages.currentPage().getParameters().get('vid')!=null){
            venInvLine = new Vendor_Invoice_Line__c(Vendor_Invoice__c = ApexPages.currentPage().getParameters().get('vid'));
            vendInv = service.getVendorInvoiceFullRecordService(ApexPages.currentPage().getParameters().get('vid'));
        }

        // fill the new financial account on records with default financial account on vendor
        if(venInvLine.Financial_Account__c==null)
        venInvLine = service.fillDefaultAccountService(new List<Vendor_Invoice_Line__c> {venInvLine}, vendInv.Vendor__c).get(0);
        isPosted = service.returnErrorIfInvoiceAlreadyPostedService(vendInv);
        if(isPosted) return;
    }

    /**
    * @Description : overriding default save method so that after save&New the record can be saved 
    * @return : redirect on vendor invoice detail page after save
    */
    public PageReference save(){
        return service.saveNewService(new List<Vendor_Invoice__c> {vendInv}, new List<Vendor_Invoice_Line__c> {venInvLine},  new List<String> {'save'});
    }

     /**
    * @Description : method to handle save&New action
    * @return : redirect to create new vendor invoice line after save
    */
    public pageReference savenew(){
        try{
        return service.saveNewService(new List<Vendor_Invoice__c>{vendInv}, new List<Vendor_Invoice_Line__c> {venInvLine}, new List<String> {'saveNew'});
        }
        catch(Exception ex){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,ex.getMessage()));
            return null;
        }
    }
    /**
    * @Description : cancel method overriding
    */
    public PageReference cancel()
    {
        PageReference pg = new PageReference(URL.getSalesforceBaseUrl().toExternalForm() + '/'+vendInv.id);
        pg.setRedirect(true);
        return pg;
    }
}