src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Default_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to store financial account on vendor invoice lines for the current vendor</description>
        <inlineHelpText>Financial Account for vendor invoice lines</inlineHelpText>
        <label>Default Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <description>Select this record type for member accounts.</description>
        <label>Household</label>
    </recordTypes>
</CustomObject>

src/objects/Apply_due_on_members__c.object
<CustomObject>
    <description>Object to store the members on which the due will get applied.</description>
    <fields>
        <fullName>Member_Dues__c</fullName>
        <label>Member Dues</label>
        <referenceTo>Member_Dues__c</referenceTo>
        <relationshipLabel>Apply due on members</relationshipLabel>
        <relationshipName>Auto_Apply_due_on_members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Membership_Type__c</fullName>
        <formula>TEXT(Contact__r.Membership_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Membership Type</label>
        <type>Text</type>
    </fields>
    <label>Apply due on members</label>
    <nameField>
        <displayFormat>APPLY-{0000000}</displayFormat>
        <label>Auto Apply due on members Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apply due on members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Membership_Type__c</fullName>
        <label>Membership Type</label>
        <picklist>
            <picklistValues>
                <fullName>Legacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Athletic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Junior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Type 1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <description>Select this record type for creating members.</description>
        <label>Member</label>
    </recordTypes>
</CustomObject>

src/objects/Default_Account__c.object
<CustomObject>
    <description>Contains TXN to financial Account Mapping</description>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>containing relation to financial account</description>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Default Accounts</relationshipLabel>
        <relationshipName>Txn_To_Financial_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Default Account</label>
    <nameField>
        <displayFormat>DA-{00000}</displayFormat>
        <label>Default Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Dues_Summary__c.object
<CustomObject>
    <description>the object is used to store due summary records and the failed records</description>
    <fields>
        <fullName>Member_Dues__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Dues</label>
        <referenceTo>Member_Dues__c</referenceTo>
        <relationshipLabel>Dues Summary</relationshipLabel>
        <relationshipName>Dues_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Post_Date__c</fullName>
        <description>the field is used to store the due date</description>
        <label>Post Date</label>
        <type>Date</type>
    </fields>
    <label>Dues Summary</label>
    <nameField>
        <displayFormat>DUESUM-{0000000}</displayFormat>
        <label>Dues Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dues Summary</pluralLabel>
    <recordTypes>
        <fullName>Dues</fullName>
        <active>true</active>
        <description>generated dues</description>
        <label>Dues</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Administrative &amp; General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aquatic Sports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clubhouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Common Area Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facility Maintenance &amp; Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fitness/Spa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Charges &amp; Income Taxes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Golf Course maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Golf Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Golf Shop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housekeeping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Locker Rooms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing &amp; Membership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Allocated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Operating Departments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overnight Rooms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payroll Taxes &amp; Employee Benefits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Racquet Shop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Racquet Sports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rentals &amp; Other Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special-purpose Funds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Club Rooms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Club Rooms (HSKP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gift Shop</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Member_Dues__c.object
<CustomObject>
    <description>Dues  subscription for member on different categories</description>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Financial Account for crediting the amount charged through the due</description>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipName>Billing_Table</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subtype__c</fullName>
        <globalPicklist>SubType</globalPicklist>
        <label>Subtype</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <globalPicklist>Type</globalPicklist>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Member Dues</label>
    <nameField>
        <label>Due Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Dues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tax_To_Account_Mapping__c.object
<CustomObject>
    <description>This object contains the mapping records for each tax, service charge, and use tax when they are mapped to a Financial Account.</description>
    <fields>
        <fullName>Financial_Accounts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Accounts</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Tax To Account Mappings</relationshipLabel>
        <relationshipName>Tax_To_Account_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Tax To Account Mapping</label>
    <nameField>
        <displayFormat>Tax-Acc-{000000}</displayFormat>
        <label>TaxToAccountMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax To Account Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Taxes__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Taxes</label>
</CustomObject>

src/objects/TxnChargeToTaxMapping__c.object
<CustomObject>
    <description>This object contains the mapping records for Type and Subtype and their taxes and service charges.</description>
    <fields>
        <fullName>Subtype__c</fullName>
        <description>global subtype picklist value</description>
        <globalPicklist>SubType</globalPicklist>
        <label>Subtype</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>global type picklist field</description>
        <globalPicklist>Type</globalPicklist>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>TxnChargeToTaxMapping</label>
    <nameField>
        <displayFormat>ctot-{000000}</displayFormat>
        <label>TxnChargeToTaxMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TxnChargeToTaxMappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ApplyDuesNBillingTableSetupDetailTest.cls
/**
* @Description : test class to cover ApplyDuesController and BillingTableSetupDetailController
* @Date : 2017
* @group : Financial Management
*/

@isTest
private class ApplyDuesNBillingTableSetupDetailTest
{
	/**
	* @Description : test method to cover ApplyDuesController class - for membership types
	*/
	@isTest
	static void ApplyDuesControllerTest1()
	{
	// create a member with the selected membership type
	Account acc = TxnTestUtility.createAccount(Utility.searchRecordType('Household', 'Account'));
	Contact con = TxnTestUtility.createMember(acc, 'Primary', Utility.searchRecordType('Member', 'Contact'));
	Member_Dues__c dueObj = TxnTestUtility.getDue('Apply Due Test', 'Installment');
	Test.setCurrentPage(Page.InstallmentBilling);
	ApexPages.currentPage().getParameters().put('dueId',dueObj.id);
	ApplyDuesController apc = new ApplyDuesController(new ApexPages.StandardController(dueObj));
	apc.selectedCategories.add(apc.allCategories[0]);
	con.Membership_Type__c = apc.allCategories[0].getValue();
	update con;
	Test.startTest();
	apc.allCategories.remove(0);
	apc.actionToPerform = 'confirm';
	apc.saveSetup();
	System.assertEquals(apc.delList.size(), 0);
	apc.actionToPerform = 'save';
	apc.saveSetup();
	List<Apply_due_on_members__c> apDOnMem = [select Id from Apply_due_on_members__c where Member_Dues__c=:apc.currentBillingObj.id];
	System.assertEquals(apDOnMem.size(), 1);

	// Test 2
	apc = new ApplyDuesController(new ApexPages.StandardController(dueObj));
	apc.allCategories.add(apc.selectedCategories[0]);
	apc.selectedCategories.remove(0);
	apc.actionToPerform = 'confirm';
	apc.saveSetup();
	System.assert(apc.delList.size()>0);
	apc.actionToPerform = '';
	apc.saveSetup();
	System.assertEquals(apc.selectedCategories.size(), 1);
	Test.stopTest(); 
	}

	/**
	* @Description : test method to cover ApplyDuesController, GenerateDuesController and GenerateDuesBatch class - for annual amount distribution
	*/
	@isTest
	static void ApplyDuesControllerTest2()
	{
		// create a member with the selected membership type
		Account acc = TxnTestUtility.createAccount(Utility.searchRecordType('Household', 'Account'));
		Contact con = TxnTestUtility.createMember(acc, 'Primary', Utility.searchRecordType('Member', 'Contact'));
		Member_Dues__c dueObj = TxnTestUtility.getDue('Apply Due Test', 'Installment');
		Test.setCurrentPage(Page.InstallmentBilling);
		ApexPages.currentPage().getParameters().put('dueId',dueObj.id);
		Test.startTest();
		ApplyDuesController apc = new ApplyDuesController(new ApexPages.StandardController(dueObj));
		apc.distrubtionMap.values().get(0).setPrimaryAmount(1000);
		apc.distrubtionMap.values().get(0).setSpouseAmount(1000);
		apc.distrubtionMap.values().get(0).setDependentAmount(1000);
		apc.SaveFull();
		System.assert(apc.existingInstallment[0].id!=null);

		// test code for GenerateDuesController and GenerateDuesBatch
		String Type = TxnChargeToTaxMapping__c.Type__c.getDescribe().getPicklistValues().get(0).getLabel();
		String Subtype = TxnChargeToTaxMapping__c.Subtype__c.getDescribe().getPicklistValues().get(0).getLabel();
		TxnChargeToTaxMapping__c tax = TxnTestUtility.getTaxMapping(Type, Subtype);
		TxnTestUtility.mapFinancialAccountOnPassedTaxes(tax);
		dueObj.Type__c = Type;
		dueObj.Subtype__c = Subtype;
		update dueObj;
		TxnTestUtility.applyDueOnMembers(dueObj, con);
		GenerateDuesController genObj = new GenerateDuesController();
		genObj.selectedBillingPeriod = apc.distrubtionMap.values().get(0).monthName;
		genObj.dueList.add(genObj.unSelectedDues[0]);
		genObj.unSelectedDues.remove(0);
		genObj.txnObjRec.Post_Date__c = Date.today();
		genObj.status = 'confirm';
		genObj.generateDues();
		genObj.status = 'generate';
		genObj.generateDues();
		Test.stopTest(); 
	}

	/**
	* @Description : test method to cover BillingTableSetupDetailController
	*/
	@isTest
	static void BillingTableSetupDetailControllerTest1()
	{
		Member_Dues__c dueObj = TxnTestUtility.getDue('Apply Due Test', 'Installment');
		BillingTableSetupDetailController btsdc = new BillingTableSetupDetailController(new ApexPages.StandardController(dueObj));
		btsdc.setupPage();
		System.assertEquals(btsdc.isInstalSele, true);
		Test.setCurrentPage(Page.InstallmentBilling);
		ApexPages.currentPage().getParameters().put('dueId',dueObj.id);
		ApplyDuesController apc = new ApplyDuesController(new ApexPages.StandardController(dueObj));
		apc.distrubtionMap.values().get(0).setPrimaryAmount(1000);
		apc.distrubtionMap.values().get(0).setSpouseAmount(1000);
		apc.distrubtionMap.values().get(0).setDependentAmount(1000);
		apc.SaveFull();
		btsdc = new BillingTableSetupDetailController(new ApexPages.StandardController(dueObj));
		btsdc.setupPage();
		System.assertEquals(btsdc.isInstalSele, false);
	}

	/**
	* @Description : test method to cover PostDuesController and PostDuesBatch for posting
	*/
	@isTest
	static void testPostDues()
	{
		Account acc = TxnTestUtility.createAccount(Utility.searchRecordType('Household', 'Account'));
		Contact con = TxnTestUtility.createMember(acc, 'Primary', Utility.searchRecordType('Member', 'Contact'));
		Member_Dues__c dueObj = TxnTestUtility.getDue('Post Dues Test', 'Installment');
		List<Dues_Summary__c> dueSummList = TxnTestUtility.getDueSummAndRelatedDues(dueObj, con);
		Financial_Account__c finAcc = TxnTestUtility.createFinancialAccount('Post Test Financial Account');
		Default_Account__c defAcc = TxnTestUtility.getDefaultMapping('Accounts Receivable', finAcc);
		Tax_To_Account_Mapping__c settingFinancialAccount = new Tax_To_Account_Mapping__c(Financial_Accounts__c=finAcc.id, Tax__c=Utility.getNameOfTax(new List<String>(Taxes__c.sObjectType.getDescribe().fields.getMap().keySet())[0]));
		Insert settingFinancialAccount;
		Test.startTest();
		PostDuesController pdc = new PostDuesController();
		pdc.renderDues();
		System.assertEquals('April', pdc.selectedBillingMonth);
		pdc.renderViewTable();
		pdc.selectedDuesListToBePosted.add(pdc.unSelectedDues[0]);
		pdc.unSelectedDues.remove(0);
		pdc.postReject = 'post';
		pdc.status = 'confirm';
		pdc.PostRejectDues();
		System.assertEquals('', pdc.confirmDuePostings);
		pdc.postReject = 'post';
		pdc.status = 'post';
		pdc.PostRejectDues();
		System.assert(pdc.dueIdsListToBePosted.size()>0);
		Test.stopTest();
	}

	/**
	* @Description : test method to cover PostDuesController and PostDuesBatch for rejecting
	*/
	@isTest
	static void testRejectDues()
	{
		Account acc = TxnTestUtility.createAccount(Utility.searchRecordType('Household', 'Account'));
		Contact con = TxnTestUtility.createMember(acc, 'Primary', Utility.searchRecordType('Member', 'Contact'));
		Member_Dues__c dueObj = TxnTestUtility.getDue('Post Dues Test', 'Installment');
		List<Dues_Summary__c> dueSummList = TxnTestUtility.getDueSummAndRelatedDues(dueObj, con);
		Financial_Account__c finAcc = TxnTestUtility.createFinancialAccount('Post Test Financial Account');
		Default_Account__c defAcc = TxnTestUtility.getDefaultMapping('Accounts Receivable', finAcc);
		Tax_To_Account_Mapping__c settingFinancialAccount = new Tax_To_Account_Mapping__c(Financial_Accounts__c=finAcc.id, Tax__c=Utility.getNameOfTax(new List<String>(Taxes__c.sObjectType.getDescribe().fields.getMap().keySet())[0]));
		Insert settingFinancialAccount;
		Test.startTest();
		PostDuesController pdc = new PostDuesController();
		pdc.selectedDuesListToBePosted.add(pdc.unSelectedDues[0]);
		pdc.unSelectedDues.remove(0);
		pdc.postReject = 'Reject';
		pdc.status = 'Reject';
		pdc.PostRejectDues();
		System.assert(pdc.dueIdsListToBePosted.size()>0);
		Test.stopTest();
	}
}