src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <description>Select this record type for member accounts.</description>
        <label>Household</label>
    </recordTypes>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <description>Select this record type for creating members.</description>
        <label>Member</label>
    </recordTypes>
</CustomObject>

src/objects/Credit_Book__c.object
<CustomObject>
    <description>Contains fields for Credit Book.</description>
    <fields>
        <fullName>CreditBookType__c</fullName>
        <label>CreditBookType</label>
        <picklist>
            <picklistValues>
                <fullName>Pro Shop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dining</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shop</fullName>
                <isActive>false</isActive>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Credit_Amount__c</fullName>
        <label>Credit Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Member_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Member_ID</description>
        <label>Member ID</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Credit Books</relationshipLabel>
        <relationshipName>Credit_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Credit Book</label>
    <nameField>
        <displayFormat>Credit-{0000}</displayFormat>
        <label>Credit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreditBookSetupControllerTest.cls
@isTest
private class CreditBookSetupControllerTest
{
	@isTest
	static void CreditBookSetupTestMethod1()
	{
		Financial_Account__c finAcc = TxnTestUtility.createFinancialAccount('CreditBookFinancials');
		PageReference pg = Page.CreditBookSetup;
		pg.getParameters().put('from','profilePage');
		Account acc = TxnTestUtility.createAccount(Utility.searchRecordType('Household','Account'));
		Contact member = TxnTestUtility.createMember(acc, 'Dependent', Utility.searchRecordType('Member','Contact'));
		pg.getParameters().put('Id',member.id);
		Credit_Book__c credit = TxnTestUtility.getCredits(member);
		Test.setCurrentPage(pg);
		Test.startTest();
		CreditBookSetupController cbcont = new CreditBookSetupController();
		System.assertEquals('profilePage', cbcont.fromPage);
		cbcont.creditRecord.Credit_Amount__c = 200;
		cbcont.creditRecord.CreditBookType__c = Credit_Book__c.CreditBookType__c.getDescribe().getPicklistValues()[0].getValue();
		cbcont.creditRecord.Description__c = 'Test credits';
		cbcont.creditRecord.Date__c = Date.today();
		pg.getParameters().put('type','memberPage');
		cbcont.save();
		TxnTestUtility.getDefaultMapping('Credit Book - Credit Account', finAcc);
		TxnTestUtility.getDefaultMapping('Credit Book - Debit Account', finAcc);
		cbcont.save();
		System.assert(cbcont.creditRecord.id!=null);
		Test.stopTest();
	}

	@isTest
	static void CreditBookSetupTestMethod2(){
		Financial_Account__c finAcc = TxnTestUtility.createFinancialAccount('CreditBookFinancials');
		TxnTestUtility.getDefaultMapping('Credit Book - Credit Account', finAcc);
		TxnTestUtility.getDefaultMapping('Credit Book - Debit Account', finAcc);
		PageReference pg = Page.CreditBookSetup;
		pg.getParameters().put('from','financialLandingPage');
		Account acc = TxnTestUtility.createAccount(Utility.searchRecordType('Household','Account'));
		Contact member = TxnTestUtility.createMember(acc, 'Dependent', Utility.searchRecordType('Member','Contact'));
		Test.setCurrentPage(pg);
		Test.startTest();
		CreditBookSetupController cbcont = new CreditBookSetupController();
		System.assertEquals('financialLandingPage', cbcont.fromPage);
		cbcont.creditRecord.Credit_Amount__c = 200;
		cbcont.creditRecord.CreditBookType__c = Credit_Book__c.CreditBookType__c.getDescribe().getPicklistValues()[0].getValue();
		cbcont.creditRecord.Description__c = 'Test credits';
		cbcont.creditRecord.Date__c = Date.today();
		pg.getParameters().put('type','saveFinancial');
		cbcont.membersToAdd[0].Member_ID__c = member.id;
		cbcont.save();
		cbcont.addMembers();
		System.assertEquals(2, cbcont.membersToAdd.size());
		pg.getParameters().put('type','saveNewFinancial');
		cbcont.save();
		Test.stopTest();
	}
}