src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Select this record type to create a vendor.</description>
        <label>Vendor</label>
    </recordTypes>
</CustomObject>

src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <fields>
        <fullName>Use_Tax__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Tax?</label>
        <type>Checkbox</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Journal_Line__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Journal Lines</relationshipLabel>
        <relationshipName>Financial_Journal_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Posted?</label>
        <type>Checkbox</type>
    </fields>
    <label>Financial Journal Line</label>
    <nameField>
        <displayFormat>FINJRNL-{000000}</displayFormat>
        <label>Financial Journal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Journal Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <formula>Post_Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Posted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Vendor, Reciprocal Club</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vendor Invoices</relationshipLabel>
        <relationshipName>Vendor_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vendor Invoice</label>
    <nameField>
        <displayFormat>VNDRINVENTR-{0000000}</displayFormat>
        <label>Vendor Invoice Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice_Line__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Remaining_To_Pay__c</fullName>
        <defaultValue>0</defaultValue>
        <description>this will display amount remaining to be paid by the user</description>
        <label>Amount Remaining To Distribute</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Vendor Invoice Lines (Financial Account)</relationshipLabel>
        <relationshipName>Vendor_Invoice_Lines</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Journal_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Journal Line</label>
        <referenceTo>Financial_Journal_Line__c</referenceTo>
        <relationshipLabel>Vendor Invoice Lines</relationshipLabel>
        <relationshipName>Vendor_Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Vendor Invoice Lines (Payment Financial Account)</relationshipLabel>
        <relationshipName>Vendor_Invoice_Lines1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Check</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Posted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_Tax__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Tax</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoice__c</fullName>
        <label>Vendor Invoice</label>
        <referenceTo>Vendor_Invoice__c</referenceTo>
        <relationshipLabel>Vendor Invoice Lines</relationshipLabel>
        <relationshipName>Vendor_Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vendor Invoice Line</label>
    <nameField>
        <displayFormat>VNDRSTMTLNE-{0000000}</displayFormat>
        <label>Vendor Invoice Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/cmsft_vendorInvoiceLineTriggerSelector.cls
/**
 * @Description: selector class for Vendor Invoice Line object - includes query logic for vendor invoice Line
 * @Date: 16th May - 2017
 * @group : Financial Management
 */
public class cmsft_vendorInvoiceLineTriggerSelector extends fflib_SObjectSelector {

/**
* @Description : fields list can be included in query
*/	
public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField> {
			Vendor_Invoice_Line__c.Id,
			Vendor_Invoice_Line__c.Name,
			Vendor_Invoice_Line__c.Amount__c,
			Vendor_Invoice_Line__c.Financial_Account__c,
			Vendor_Invoice_Line__c.Amount_Remaining_To_Pay__c,
			Vendor_Invoice_Line__c.Description__c,
			Vendor_Invoice_Line__c.Financial_Journal_Line__c,
			Vendor_Invoice_Line__c.Payment_Type__c,
			Vendor_Invoice_Line__c.Posted__c,
			Vendor_Invoice_Line__c.Vendor_Invoice__c,
			Vendor_Invoice_Line__c.Vendor_Invoice__r.Payment_Type__c,
			Vendor_Invoice_Line__c.Vendor_Invoice__r.Vendor__r.id,
			Vendor_Invoice_Line__c.Payment_Financial_Account__c,
            Vendor_Invoice_Line__c.Use_Tax__c 
		};
	}

	/**
    * @Description : used to return current object
    * @return Vendor Invoice line obj as SObjectType
    */
	public Schema.SObjectType getSObjectType() {
		return Vendor_Invoice_Line__c.sObjectType;
	}

	/**
    * @Description : get all records having id in passed id set
    * @return list of query result vendor invoice line records
    */
	public List<Vendor_Invoice_Line__c> selectById(Set<ID> idSet) {
		fflib_QueryFactory contQuey = newQueryFactory(true, true, true);
		return new List<SObject> (Database.query(contQuey.setCondition('id in :idSet').toSOQL()));
	}
    
    public double getInvoiceLineAmountTotal(string invoiceId) {
		assertIsAccessible();
        //AggregateResult[] TotalAmountQryResult = [select sum(Amount__c)total from Vendor_Invoice_Line__c where Vendor_Invoice__c =:invoiceId ];
        AggregateResult[] TotalAmountQryResult = (AggregateResult[])Data.read(
                'select sum(Amount__c)total from Vendor_Invoice_Line__c where Vendor_Invoice__c =:invoiceId',
                new Map<String,Object> {
                    'invoiceId'=>invoiceId
                }
            );
		return double.valueOf(TotalAmountQryResult[0].get('total')); 
	}
    
    public double getTotalInvoiceAmount(string invoiceId) {
		assertIsAccessible();
        //List<Vendor_Invoice__c> TotalAmountQryResult = [select Amount__c from Vendor_Invoice__c where id =:invoiceId ];
		 List<Vendor_Invoice__c> TotalAmountQryResult = (List<Vendor_Invoice__c>)Data.read(
                'select Amount__c from Vendor_Invoice__c where id =:invoiceId',
                new Map<String,Object> {
                    'invoiceId'=>invoiceId
                }
            );
        return double.valueOf(TotalAmountQryResult[0].get('Amount__c'));
	}
}