src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Default_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to store financial account on vendor invoice lines for the current vendor</description>
        <inlineHelpText>Financial Account for vendor invoice lines</inlineHelpText>
        <label>Default Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <description>Select this record type for member accounts.</description>
        <label>Household</label>
    </recordTypes>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <description>Select this record type for creating members.</description>
        <label>Member</label>
    </recordTypes>
</CustomObject>

src/objects/Default_Account__c.object
<CustomObject>
    <description>Contains TXN to financial Account Mapping</description>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>containing relation to financial account</description>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Default Accounts</relationshipLabel>
        <relationshipName>Txn_To_Financial_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <globalPicklist>Payment_Type</globalPicklist>
        <label>Payment Type</label>
        <type>Picklist</type>
    </fields>
    <label>Default Account</label>
    <nameField>
        <displayFormat>DA-{00000}</displayFormat>
        <label>Default Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Accounts</pluralLabel>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <label>Default</label>
    </recordTypes>
    <recordTypes>
        <fullName>Refund</fullName>
        <active>true</active>
        <label>Refund</label>
    </recordTypes>
    <recordTypes>
        <fullName>Transactions</fullName>
        <active>true</active>
        <label>Transactions</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TXN__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Transactions (Financial Account)</relationshipLabel>
        <relationshipName>Transactions3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <description>payment type of the payment</description>
        <globalPicklist>Payment_Type</globalPicklist>
        <inlineHelpText>payment type of the payment</inlineHelpText>
        <label>Payment Type</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Refund_Reason__c</fullName>
        <description>description of the refund of the payment</description>
        <label>Refund Reason</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Statement_Description__c</fullName>
        <label>Statement Description</label>
        <type>TextArea</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Charge</fullName>
        <active>true</active>
        <label>Charge</label>
    </recordTypes>
    <recordTypes>
        <fullName>Credit</fullName>
        <active>true</active>
        <description>club can add manual credit to the member&apos;s account so that credit amount will be added under this record type.</description>
        <label>Credit</label>
    </recordTypes>
    <recordTypes>
        <fullName>Payment</fullName>
        <active>true</active>
        <label>Payment</label>
    </recordTypes>
    <recordTypes>
        <fullName>Refund</fullName>
        <active>true</active>
        <label>Refund</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TxnRefundControllerTest.cls
@isTest
public class TxnRefundControllerTest {
    public  Static String  AccountMemberId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
    public  Static String ContactMemberId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Member').getRecordTypeId();

     
   	 //TxnTestUtitlity TTU=new TxnTestUtitlity();
    @isTest
    public static  void txnRef(){
         
     Account Acc=TxnTestUtility.createAccount(AccountMemberId);
	 Contact mem=TxnTestUtility.createMember(Acc,'Dependent',ContactMemberId);
      //create default account mapping for credit card payment
      Financial_Account__c fa = TxnTestUtility.createFinancialAccount('test');
        Default_Account__c da =TxnTestUtility.getDefaultMapping('Accounts Receivable',fa);
        da = TxnTestUtility.getDefaultMapping('Accounts Payable',fa) ;
        da = TxnTestUtility.getDefaultPaymentMapping('Cash',fa) ;
     TXN__c payment=TxnTestUtility.txnCreatePay(mem);
     TXN__c charge=TxnTestUtility.createChargeOnMember(mem,200);
  	 TXN__c mapping=TxnTestUtility.txnMapPaymentToCharge(charge,payment,100);

    	PageReference pageRef = Page.TxnRefund;
    	Test.setCurrentPage(pageRef);
    	ApexPages.currentPage().getParameters().put('PaymentId', payment.Id);
        
        TxnRefundController refCont=new TxnRefundController();
        refCont.Cancel();
        refCont.save();
        
        refCont=new TxnRefundController();
        refCont.Cancel();
        refCont.othCharge.Refund_Reason__c='test refund';
        refCont.othCharge.Payment_Type__c='Cash';
        refCont.othCharge.Amount__c=150;
       // MappingAndTaxUtilityTest.mapFinancialAccountToCharge('Default', 'Default Account Payable', '');
        //MappingAndTaxUtilityTest.mapFinancialAccountToCharge('Default', 'Bank Account Default', '');
        refCont.save();
        
        /*TxnRefundController refCont1=new TxnRefundController();
        refCont1.Cancel();
        refCont1.othCharge.Refund_Reason__c='test refund';
        refCont1.othCharge.Payment_Type__c='Check';
        refCont1.othCharge.Amount__c=20;
        MappingAndTaxUtilityTest.mapFinancialAccountToCharge('Default', 'Default Account Payable', '');
        MappingAndTaxUtilityTest.mapFinancialAccountToCharge('Transactions', 'Check', '');
        refCont1.save();
        
        refCont1=new TxnRefundController();
        refCont1.Cancel();
        refCont1.othCharge.Refund_Reason__c='test refund';
        refCont1.othCharge.Payment_Type__c='Check';
        refCont1.othCharge.Amount__c=20;
        refCont1.save();
        
        refCont1=new TxnRefundController();
        refCont1.Cancel();
        refCont1.othCharge.Refund_Reason__c='test refund';
        refCont1.othCharge.Payment_Type__c='Credit Card';
        refCont1.othCharge.Amount__c=20;
        MappingAndTaxUtilityTest.mapFinancialAccountToCharge('Default', 'Default Account Payable', '');
        MappingAndTaxUtilityTest.mapFinancialAccountToCharge('Transactions', 'Credit Card', '');
        refCont1.save();*/
    }

    /*public static void txnRef1(){
        Account Acc=TxnTestUtility.createAccount(AccountMemberId);
        Contact mem=TxnTestUtility.createMember(Acc,'Primary',ContactMemberId);
        TXN__c payment=TxnTestUtility.txnCreatePay(mem);
        TXN__c charge=TxnTestUtility.createChargeOnMember(mem,200);
        TXN__c mapping=TxnTestUtility.txnMapPaymentToCharge(charge,payment,100);

        PageReference pageRef = Page.TxnRefund;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('PaymentId', payment.Id);

        TxnRefundController refCont1=new TxnRefundController();
        refCont1.Cancel();
        refCont1.othCharge.Refund_Reason__c='test refund';
        refCont1.othCharge.Payment_Type__c='Cash';
        refCont1.othCharge.Amount__c=50;
        refCont1.othCharge.Statement_Description__c = 'test';
        Date currentDate = system.today();
        refCont1.othCharge.Date__c=Date.newInstance(currentDate.year(),currentDate.month(),currentDate.day());
        refCont1.save();
        MappingAndTaxUtilityTest.mapFinancialAccountToCharge('Default', 'Bank Account Default', '');
        refCont1.save();
        MappingAndTaxUtilityTest.mapFinancialAccountToCharge('Transactions', 'Cash', '');
        refCont1.save();
    } */
    
}