src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Default_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to store financial account on vendor invoice lines for the current vendor</description>
        <inlineHelpText>Financial Account for vendor invoice lines</inlineHelpText>
        <label>Default Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <description>Select this record type for member accounts.</description>
        <label>Household</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Select this record type to create a vendor.</description>
        <label>Vendor</label>
    </recordTypes>
</CustomObject>

src/objects/Check_Run__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Next_Check_Number__c</fullName>
        <label>Next Check Number</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Printed_Check_Digits__c</fullName>
        <label>Printed Check Digits</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Check Run</label>
</CustomObject>

src/objects/Default_Account__c.object
<CustomObject>
    <description>Contains TXN to financial Account Mapping</description>
    <fields>
        <fullName>Default_Type_Name__c</fullName>
        <label>Default Type Name</label>
        <picklist>
            <picklistValues>
                <fullName>Accounts Receivable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prepaid Deposits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accounts Receivable - Dues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Book</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accounts Payable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accounts Payable Discounts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>POS Discounts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Book - Debit Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Book - Credit Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>containing relation to financial account</description>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Default Accounts</relationshipLabel>
        <relationshipName>Txn_To_Financial_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Default Account</label>
    <nameField>
        <displayFormat>DA-{00000}</displayFormat>
        <label>Default Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Asset</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Income</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expense</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Journal_Line__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Check_Run__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Check Run</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Journal Lines</relationshipLabel>
        <relationshipName>Financial_Journal_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Journal Line</label>
    <nameField>
        <displayFormat>FINJRNL-{000000}</displayFormat>
        <label>Financial Journal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Journal Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoice_Check__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Invoice Check</label>
        <referenceTo>Vendor_Invoice_Check__c</referenceTo>
        <relationshipLabel>Vendor Invoices</relationshipLabel>
        <relationshipName>Vendor_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Vendor, Reciprocal Club</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vendor Invoices</relationshipLabel>
        <relationshipName>Vendor_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vendor Invoice</label>
    <nameField>
        <displayFormat>VNDRINVENTR-{0000000}</displayFormat>
        <label>Vendor Invoice Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice_Check__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Check_Date__c</fullName>
        <label>Check Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Check_Number__c</fullName>
        <label>Check Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Memo__c</fullName>
        <label>Memo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoice_Check_Batch__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vendor Invoice Check Batch</label>
        <referenceTo>Vendor_Invoice_Check_Batch__c</referenceTo>
        <relationshipLabel>Vendor Invoice Checks</relationshipLabel>
        <relationshipName>Vendor_Invoice_Checks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vendor Invoice Checks</relationshipLabel>
        <relationshipName>Vendor_Invoice_Checks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Vendor Invoice Check</label>
    <nameField>
        <displayFormat>VNDRINVCK-{0000000}</displayFormat>
        <label>Vendor Invoice Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice_Line__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <formula>Financial_Account__r.Account_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Vendor Invoice Lines (Financial Account)</relationshipLabel>
        <relationshipName>Vendor_Invoice_Lines</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoice_Check__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Invoice Check</label>
        <referenceTo>Vendor_Invoice_Check__c</referenceTo>
        <relationshipLabel>Vendor Invoice Lines</relationshipLabel>
        <relationshipName>Vendor_Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoice__c</fullName>
        <label>Vendor Invoice</label>
        <referenceTo>Vendor_Invoice__c</referenceTo>
        <relationshipLabel>Vendor Invoice Lines</relationshipLabel>
        <relationshipName>Vendor_Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vendor Invoice Line</label>
    <nameField>
        <displayFormat>VNDRSTMTLNE-{0000000}</displayFormat>
        <label>Vendor Invoice Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <formula>Vendor_Invoice_Line__r.Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoice_Check__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Invoice Check</label>
        <referenceTo>Vendor_Invoice_Check__c</referenceTo>
        <relationshipLabel>Vendor Invoice Payments</relationshipLabel>
        <relationshipName>Vendor_Invoice_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoice__c</fullName>
        <label>Vendor Invoice</label>
        <referenceTo>Vendor_Invoice__c</referenceTo>
        <relationshipLabel>Vendor Invoice Payments</relationshipLabel>
        <relationshipName>Vendor_Invoice_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vendor Invoice Payment</label>
    <nameField>
        <displayFormat>VNDRSTMTPAY-{0000000}</displayFormat>
        <label>Vendor Invoice Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/voidCheckOrCheckBatchTest.cls
/*
@Name           : VendorCheckRunControllerTest
@Author         : kiran@3embed.com
@Description    : Test methods for void check and check batch controller
*/
@isTest
public class voidCheckOrCheckBatchTest {
    public static String AccountMemberId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
    public static String vendorAcc = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Vendor').getRecordTypeId();
    static Integer jj=0;
    static testmethod void vendorCheckRunControllerTest1() {    
        
        Financial_Account__c fa1 = new Financial_Account__c(Active__c = true,Name='Test1',Account_Number__c='asd32sd1',Category__c='Liability');
        insert fa1;
        
        Financial_Account__c fa = new Financial_Account__c(Active__c = true,Name='Test',Account_Number__c='asd32sd',Category__c='Liability');
        insert fa;
        
        Vendor_Invoice_Check_Batch__c vicb = new Vendor_Invoice_Check_Batch__c();
        insert vicb;
        Check_Run__c cr = new Check_Run__c(Printed_Check_Digits__c = 8,Next_Check_Number__c='0');
        insert cr;
        
        
        Default_Account__c da =new Default_Account__c (Default_Type_Name__c ='Accounts Payable',Financial_Account__c = fa.Id);
        insert da;
        
        Account v= TxnTestUtility.createAccount(Utility.searchRecordType('Vendor','Account'));
        Vendor_Invoice_Check__c vicc = new Vendor_Invoice_Check__c(Amount__c = 300,Vendor__c = v.id,Check_Number__c = '63251478',
                                                                   Vendor_Invoice_Check_Batch__c = vicb.Id,Memo__c = 'New Memo',Check_Date__c = Date.Today());
        insert vicc;
        
        Vendor_Invoice__c vi = new Vendor_Invoice__c(Vendor_Invoice_Check__c = vicc.Id,Invoice_Date__c= Date.today(),Due_Date__c = Date.today(),Hold_Status__c = false,Vendor__c=v.id,Invoice_Number__c='156985', Amount__c=500);
        insert vi;
        Financial_Account__c viacc=TxnTestUtility.createFinancialAccount('test1');
        Vendor_Invoice_Line__c vil = new Vendor_Invoice_Line__c(Payment_Type__c = 'Check',Financial_Account__c=viacc.id,Vendor_Invoice__c = vi.Id, Amount__c=500);
        insert vil;
        Vendor_Invoice_Payment__c vip = new Vendor_Invoice_Payment__c(Amount_Paid__c = 1,Vendor_Invoice__c = vi.Id, Vendor_Invoice_Line__c=vil.Id);
        insert vip;
        Vendor_Invoice__c vi1 = new Vendor_Invoice__c(Due_Date__c = Date.today(),Invoice_Date__c = Date.today(),Vendor__c=v.id,Invoice_Number__c=string.valueOf(jj++), Amount__c=500,  Hold_Status__c = true);
        insert vi1;
        Vendor_Invoice_Line__c vil1 = new Vendor_Invoice_Line__c(Vendor_Invoice__c = vi1.Id, Amount__c=500,Financial_Account__c=viacc.id);
        insert vil1;
        Vendor_Invoice_Payment__c vip1 = new Vendor_Invoice_Payment__c(Amount_Paid__c = 500, Vendor_Invoice_Check__c=vicc.id ,Vendor_Invoice__c = vi1.Id, Vendor_Invoice_Line__c=vil1.Id);
        insert vip1;
        
         Test.startTest();
        //save financial journal entry
        List<Default_Account__c> tradeAccount = (List<Default_Account__c>)Data.read(
            'select id, Financial_Account__c from Default_Account__c where Default_Type_Name__c =:Value ',
            new Map<String,Object> {
                'Value'=>'Accounts Payable'
                    }
        ); 
        Financial_Journal_Entry__c fjEntry = new Financial_Journal_Entry__c();
        fjEntry.Description__c = 'Invoice Check Batch '+vicb.id;
        fjEntry.Entry_Date__c = vicb.Batch_Date__c;
        fjEntry.Posted__c = true;
        fjEntry.Post_Date__c = vicb.Batch_Date__c;
        insert fjEntry;
        
        Financial_Journal_Line__c tradeJournal = new Financial_Journal_Line__c();
        tradeJournal.Amount__c = 500;
        tradeJournal.Description__c = 'Invoice Check Batch '+vicb.id;
        
        tradeJournal.Financial_Account__c=tradeAccount[0].Financial_Account__c;
        tradeJournal.Financial_Journal_Entry__c = fjEntry.Id;
        tradeJournal.Post_Date__c = vicb.Batch_Date__c;
        tradeJournal.Posted__c = true;
        tradeJournal.Transaction_Date__c = vicb.Batch_Date__c;
        Financial_Journal_Line__c cashJournal = new Financial_Journal_Line__c();
        
        cashJournal.Description__c = 'Invoice Check Batch '+vicb.id;
        //check account is for credit or debit
        List<Financial_Account__c> CheckCreditDebit = (List<Financial_Account__c>)Data.read(
            'select Debit_Credit__c  from Financial_Account__c  where id =: AccId ',
            new Map<String,Object> {
                'AccId'=>fa1.id
                    }
        ); 
        cashJournal.Amount__c = 500 ;
        if(CheckCreditDebit[0].Debit_Credit__c == 'Credit'){
            cashJournal.Amount__c = 500 * -1;
        }
        cashJournal.Financial_Account__c=fa1.id;
        cashJournal.Financial_Journal_Entry__c = fjEntry.Id;
        cashJournal.Post_Date__c = vicb.Batch_Date__c;
        cashJournal.Posted__c = true;
        cashJournal.Transaction_Date__c = vicb.Batch_Date__c;
        List<Financial_Journal_Line__c> fjsToInsert = new List<Financial_Journal_Line__c>();
        fjsToInsert.add(tradeJournal);
        fjsToInsert.add(cashJournal);
        Data.create(fjsToInsert);
        
        vicb.Financial_Journal_Entry__c=fjEntry.id;
        update vicb;
        PageReference myVfPage = Page.voidCheckorCheckBatch;
        Test.setCurrentPage(myVfPage);
        // Put Id into the current page Parameters
        ApexPages.currentPage().getParameters().put('batchId',vicb.Id);
        voidCheckorCheckBatch voidCB=new voidCheckorCheckBatch();
        voidCB.returnToCheckPage();
        voidCB.returnToBatchPage();
        system.assertEquals(voidCB.alreadyVoided, false);
        voidCB.VoidBatch();
        
        
        myVfPage = Page.voidCheckorCheckBatch;
        Test.setCurrentPage(myVfPage);
        // Put Id into the current page Parameters
        ApexPages.currentPage().getParameters().put('batchId',vicb.Id);
        voidCB=new voidCheckorCheckBatch();
        voidCB.returnToCheckPage();
        voidCB.returnToBatchPage();
        system.assertEquals(voidCB.alreadyVoided, true);
        //voidCB.VoidBatch();
        
        
        myVfPage = Page.voidCheckorCheckBatch;
        Test.setCurrentPage(myVfPage);
        // Put Id into the current page Parameters
        ApexPages.currentPage().getParameters().put('checkId',vicc.Id);
        
        voidCB=new voidCheckorCheckBatch();
        voidCB.returnToCheckPage();
        voidCB.returnToBatchPage();
        
        voidCB.VoidCheck();
        system.assertEquals(voidCB.alreadyVoided, true);
        Test.StopTest();
        
    }
}