src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Select this record type to create a vendor.</description>
        <label>Vendor</label>
    </recordTypes>
</CustomObject>

src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Vendor Invoice</label>
    <nameField>
        <displayFormat>VNDRINVENTR-{0000000}</displayFormat>
        <label>Vendor Invoice Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice_Line__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Vendor Invoice Lines (Financial Account)</relationshipLabel>
        <relationshipName>Vendor_Invoice_Lines</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoice__c</fullName>
        <label>Vendor Invoice</label>
        <referenceTo>Vendor_Invoice__c</referenceTo>
        <relationshipLabel>Vendor Invoice Lines</relationshipLabel>
        <relationshipName>Vendor_Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vendor Invoice Line</label>
    <nameField>
        <displayFormat>VNDRSTMTLNE-{0000000}</displayFormat>
        <label>Vendor Invoice Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VendInvLineTest.cls
/**
 * @Description : test class for VendInvLine controller class
 */
@isTest
private class VendInvLineTest
{
    /**
     *  @Description : test method to check save and saveNew functionality
     */
	@isTest
	static void testNew()
 	{
 		Account vendor= TxnTestUtility.createAccount(Utility.searchRecordType('Vendor','Account'));
  		Vendor_Invoice__c vendInv = TxnTestUtility.createInvoice(Double.valueOf(500), '26598765', vendor.id);
  		Vendor_Invoice_Line__c vendInvLine = new Vendor_Invoice_Line__c(Vendor_Invoice__c=vendInv.id);
  		ApexPages.StandardController std = new ApexPages.StandardController(vendInvLine);
  		Financial_Account__c finAccount = TxnTestUtility.createFinancialAccount('Test Account');
  		VendInvLine venInvLineCon = new VendInvLine(std);
  		venInvLineCon.venInvLine.Amount__c = 100;
  		venInvLineCon.venInvLine.Financial_Account__c = finAccount.id;
        Test.startTest();
  		venInvLineCon.savenew();
        System.assert(venInvLineCon.venInvLine!=null);
  		PageReference pRef = Page.CreateVendInvLine;
  		pRef.getParameters().put('vid', vendInv.Id);
  		Test.setCurrentPage(pRef);
  		VendInvLine venInvLineCon1 = new VendInvLine(std);
  		venInvLineCon1.save();
  		System.assert(vendInvLine.id!=null);
        Test.stopTest();
 	}
	
    /**
     *  @Description : test method to check save on click of edit functionality
     */
	@isTest
	static void testEdit()
	{		
		Account vendor= TxnTestUtility.createAccount(Utility.searchRecordType('Vendor','Account')); 
		Vendor_Invoice__c vendInv = TxnTestUtility.createInvoice(Double.valueOf(500), '26598765', vendor.id);
		Vendor_Invoice_Line__c vendInvLine = TxnTestUtility.createInvoiceLines(Double.valueOf(500), vendInv.id);
		ApexPages.StandardController std = new ApexPages.StandardController(vendInvLine);
		PageReference pRef = Page.CreateVendInvLine;
		pRef.getParameters().put('id', vendInvLine.Id);
		Test.setCurrentPage(pRef);
		VendInvLine venInvLineCon = new VendInvLine(std);
        Test.startTest();
		venInvLineCon.save();
        System.assertEquals(vendInv.Amount__c, Double.valueOf(500));
        Test.stopTest();
	}
}