src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <description>Select this record type for member accounts.</description>
        <label>Household</label>
    </recordTypes>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <description>Select this record type for creating members.</description>
        <label>Member</label>
    </recordTypes>
</CustomObject>

src/objects/Deposit_Batch_Check_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Check_Date__c</fullName>
        <label>Check Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Check_Number__c</fullName>
        <label>Check Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Deposit Batch Check Payments</relationshipLabel>
        <relationshipName>Deposit_Batch_Check_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deposit Batch Check Payment</label>
    <nameField>
        <displayFormat>DepBaPay-{000000}</displayFormat>
        <label>Deposit Batch Check Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deposit Batch Check Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bank_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bank Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Asset</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Income</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expense</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice_Check_Batch__c.object
<CustomObject>
    <label>Vendor Invoice Check Batch</label>
    <nameField>
        <displayFormat>VICB-{0000000}</displayFormat>
        <label>Vendor Invoice Check Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Check Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CheckDepositControllerTest.cls
@isTest
public class CheckDepositControllerTest {
    private testMethod static void runAll() {
        Vendor_Invoice_Check_Batch__c vicb = new Vendor_Invoice_Check_Batch__c();
        insert vicb;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(vicb);
        CheckDepositController CDC = new CheckDepositController(sc);
        CDC.addMoreRows();
        integer amount=10;
        Financial_Account__c fa = new Financial_Account__c(Name='Test',Account_Number__c='asd32sd',Category__c='Liability' ,Bank_Account__c = true, Active__c=true);
        insert fa;
        CDC.bd.Financial_Account__c=fa.id;
        CDC.bd.Deposit_Slip_Number__c='1233';
        CDC.bd.Deposit_Date__c=date.today();
        CDC.bd.Total__c=100;
        Account acc = TxnTestUtility.createAccount(Utility.searchRecordType('Household', 'Account'));
        Contact member = TxnTestUtility.createMember(acc, 'Primary', Utility.searchRecordType('Member', 'Contact'));
        for(Integer i=1;i<=10;i++){
            Deposit_Batch_Check_Payment__c newObj=new Deposit_Batch_Check_Payment__c();
            newObj.Amount__c=amount;
            newObj.Check_Date__c=date.today();
            newObj.Check_Number__c='123'+amount;
            newObj.Customer__c=member.id;
            CDC.payList.put(i,new CheckDepositeService.PaymentWrapper(i, newObj));
            CDC.lastIndex=i;
           
        }
        CDC.getPayListV();
        CDC.getpayListToMergeV();
        CDC.cObjIndex=1;
        CDC.makeAmountFieldBlank();
        CDC.saveCheckDepositPayments();
        //update 
        CDC.selectedPastBD=CDC.bd.id;
        CDC.loadCheckDepositPayments();
        CDC.saveCheckDepositPayments();
        
        //CDC.bdForMerge=CDC.bd;
        //CDC.selectedPastBDForMerge=CDC.bd.id;
        //CDC.setPastBankDepsoit();
       // CDC.getDetailOfBatchToMerge();
        CDC.PostBatch();
        CDC.loadCheckDepositPaymentsForMerge();
        
        //mearge batch
        //CDC = new CheckDepositController(sc);
        CDC.bd.Financial_Account__c=fa.id;
        CDC.bd.Deposit_Slip_Number__c='1244';
        CDC.bd.Deposit_Date__c=date.today();
        CDC.bd.Total__c=100;
        for(Integer i=1;i<=10;i++){
            Deposit_Batch_Check_Payment__c newObj=new Deposit_Batch_Check_Payment__c();
            newObj.Amount__c=amount;
            newObj.Check_Date__c=date.today();
            newObj.Check_Number__c='123'+amount;
            newObj.Customer__c=member.id;
            CDC.payList.put(i,new CheckDepositeService.PaymentWrapper(i, newObj));
            CDC.lastIndex=i;
           
        }
        CDC.selectedPastBDForMerge=CDC.bd.id;
        CDC.saveCheckDepositPayments();
        CDC.MergeBoth();
    }
}