src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <description>Select this record type for member accounts.</description>
        <label>Household</label>
    </recordTypes>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Bill To Member)</relationshipLabel>
        <relationshipName>ContactBillTo</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <description>Select this record type for creating members.</description>
        <label>Member</label>
    </recordTypes>
</CustomObject>

src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TXN__c.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Bill To Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Bill To Member)</relationshipLabel>
        <relationshipName>TransactionBillTo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Transactions (Credit Financial Account)</relationshipLabel>
        <relationshipName>Transactions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Member or Guest the Transaction applies to</description>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Customer)</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Transactions (Financial Account)</relationshipLabel>
        <relationshipName>Transactions3</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Credit</fullName>
        <active>true</active>
        <description>club can add manual credit to the member&apos;s account so that credit amount will be added under this record type.</description>
        <label>Credit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ManualCreditControllerTest.cls
@isTest
public class ManualCreditControllerTest {
    @isTest
    static void ManualCreditTest1()
    {
        Test.setCurrentPage(Page.ManualCredit);
        ApexPages.currentPage().getParameters().put('message','success');
        // create a member with the selected membership type
        Account acc = TxnTestUtility.createAccount(Utility.searchRecordType('Household', 'Account'));
        Contact con = TxnTestUtility.createMember(acc, 'Primary', Utility.searchRecordType('Member', 'Contact'));
        Financial_Account__c creditFC = TxnTestUtility.createFinancialAccount('CreditFC');
        Financial_Account__c debit1 = TxnTestUtility.createFinancialAccount('debit1');
        Financial_Account__c debit2 = TxnTestUtility.createFinancialAccount('debit2');
        Test.startTest();
        ManualCreditController creditSetup = new ManualCreditController();
        creditSetup.txnObj.Customer__c =con.id;
        creditSetup.txnObj.Bill_To_Member__c =con.id;
        creditSetup.txnObj.Date__c =date.today();
        creditSetup.txnObj.Credit_Financial_Account__c =creditFC.id;
        creditSetup.TotalAmount =10;
        
        creditSetup.cObjIndex = 0;
        creditSetup.delMember();
        creditSetup.addMoreRows();
        creditSetup.getCreditListV();
        
        TXN__c txnRec=new TXN__c();
        txnRec.Financial_Account__c=debit1.id;
        creditSetup.CreditList.put(0,new ManualCreditService.CreditSplitWrapper(0,txnRec,'10'));
        creditSetup.save();
        Test.stopTest();
    }
    @isTest
    static void ManualCreditTest2()
    {
        // create a member with the selected membership type
        Account acc = TxnTestUtility.createAccount(Utility.searchRecordType('Household', 'Account'));
        Contact con = TxnTestUtility.createMember(acc, 'Primary', Utility.searchRecordType('Member', 'Contact'));
        Financial_Account__c creditFC = TxnTestUtility.createFinancialAccount('CreditFC');
        Financial_Account__c debit1 = TxnTestUtility.createFinancialAccount('debit1');
        Financial_Account__c debit2 = TxnTestUtility.createFinancialAccount('debit2');
        Test.startTest();
        ManualCreditController creditSetup = new ManualCreditController();
        creditSetup.txnObj.Customer__c =con.id;
        creditSetup.txnObj.Bill_To_Member__c =con.id;
        creditSetup.txnObj.Date__c =date.today();
        creditSetup.txnObj.Credit_Financial_Account__c =creditFC.id;
        creditSetup.TotalAmount =20;
        
        creditSetup.cObjIndex = 0;
        
        TXN__c txnRec=new TXN__c();
        txnRec.Financial_Account__c=debit1.id;
        creditSetup.CreditList.put(0,new ManualCreditService.CreditSplitWrapper(0,txnRec,'10'));
        creditSetup.CreditList.put(1,new ManualCreditService.CreditSplitWrapper(1,txnRec,'10'));
        creditSetup.save();
        
        Test.stopTest();
    }
    @isTest
    static void ManualCreditTest3()
    {
        // create a member with the selected membership type
        Account acc = TxnTestUtility.createAccount(Utility.searchRecordType('Household', 'Account'));
        Contact con = TxnTestUtility.createMember(acc, 'Primary', Utility.searchRecordType('Member', 'Contact'));
        Financial_Account__c creditFC = TxnTestUtility.createFinancialAccount('CreditFC');
        Financial_Account__c debit1 = TxnTestUtility.createFinancialAccount('debit1');
        Financial_Account__c debit2 = TxnTestUtility.createFinancialAccount('debit2');
           Test.startTest();
        try{
            ManualCreditController creditSetup = new ManualCreditController();
            creditSetup.save();
        }catch(Exception e){
                        
            System.assertEquals('Please enter amount.',e.getMessage() );
        }
        try{
            ManualCreditController creditSetup = new ManualCreditController();
            creditSetup.TotalAmount =20;
            creditSetup.save();
            
        }catch(Exception e){
            System.assertEquals('Please select date.',e.getMessage() );
        }
        try{
            ManualCreditController creditSetup = new ManualCreditController();
            creditSetup.TotalAmount =20;
            creditSetup.txnObj.Date__c =date.today();
            creditSetup.save();
            
        }catch(Exception e){
            System.assertEquals('Please select customer.',e.getMessage() );
        }
        try{
            ManualCreditController creditSetup = new ManualCreditController();
            creditSetup.TotalAmount =20;
            creditSetup.txnObj.Date__c =date.today();
            creditSetup.txnObj.Customer__c =con.id;
            creditSetup.txnObj.Bill_To_Member__c =con.id;
            creditSetup.save();
            
        }catch(Exception e){
            System.assertEquals('Enter credit financial account',e.getMessage() );
        }
        try{
            ManualCreditController creditSetup = new ManualCreditController();
            creditSetup.TotalAmount =20;
            creditSetup.txnObj.Date__c =date.today();
            creditSetup.txnObj.Customer__c =con.id;
            creditSetup.txnObj.Bill_To_Member__c =con.id;
            creditSetup.txnObj.Credit_Financial_Account__c =creditFC.id;
            creditSetup.save();
            
        }catch(Exception e){
            System.assertEquals('Enter at least one debit account.',e.getMessage() );
        }
        try{
            ManualCreditController creditSetup = new ManualCreditController();
            creditSetup.TotalAmount =20;
            creditSetup.txnObj.Date__c =date.today();
            creditSetup.txnObj.Customer__c =con.id;
            creditSetup.txnObj.Bill_To_Member__c =con.id;
            creditSetup.txnObj.Credit_Financial_Account__c =creditFC.id;
            TXN__c txnRec=new TXN__c();
            txnRec.Financial_Account__c=debit1.id;
            creditSetup.CreditList.put(0,new ManualCreditService.CreditSplitWrapper(0,txnRec,'5'));
            creditSetup.save();
            
        }catch(Exception e){
            System.assertEquals('Total of Debit amount should be same as total amount.',e.getMessage() );
        }
        Test.stopTest();
        
        
        
        
      
        
    }
}