src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Household_Name__c</fullName>
        <inlineHelpText>This should be a unique name that identifies the household. The format should include the family&apos;s member Id and should be formatted like this: Johnson - 1234</inlineHelpText>
        <label>Household Name</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Guest</fullName>
        <active>true</active>
        <description>Select this record type for guest accounts.</description>
        <label>Guest</label>
    </recordTypes>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <description>Select this record type for member accounts.</description>
        <label>Household</label>
    </recordTypes>
</CustomObject>

src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>The City in which the member resides</description>
        <inlineHelpText>The City in which the member resides</inlineHelpText>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Select country of which address belongs</description>
        <inlineHelpText>Select country of which address belongs</inlineHelpText>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>United States</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bouvet Island</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the link to the Customer that resides at this address.</description>
        <inlineHelpText>This is the link to the Customer that resides at this address.</inlineHelpText>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <description>This is the start date that the member uses this address.</description>
        <inlineHelpText>This is the start date that the member uses this address.</inlineHelpText>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <description>This field is the State or Province of the address.</description>
        <inlineHelpText>This field is the State or Province of the address.</inlineHelpText>
        <label>State/Province</label>
        <picklist>
            <picklistValues>
                <fullName>AB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street_1__c</fullName>
        <description>This field is the first line of the street address. Use for single line street addresses or multiple line street addresses.</description>
        <inlineHelpText>This field is the first line of the street address. Use for single line street addresses or multiple line street addresses.</inlineHelpText>
        <label>Street 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_2__c</fullName>
        <description>This field is the first line of the street address. Use for multiple line street addresses as needed.</description>
        <inlineHelpText>This field is the first line of the street address. Use for multiple line street addresses as needed.</inlineHelpText>
        <label>Street 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_3__c</fullName>
        <description>This field is the first line of the street address. Use for multiple line street addresses as needed.</description>
        <inlineHelpText>This field is the first line of the street address. Use for multiple line street addresses as needed.</inlineHelpText>
        <label>Street 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This field is a pick list used to designate the address as Home, Work, or Other type.</description>
        <inlineHelpText>This field is a pick list used to designate the address as Home, Work, or Other type.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Home</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Winter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Summer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Zip_Postal_Code__c</fullName>
        <description>This field is for the Zip Code or Postal Code for the address.</description>
        <inlineHelpText>This field is for the Zip Code or Postal Code for the address.</inlineHelpText>
        <label>Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Relationship__c</fullName>
        <globalPicklist>Relationship</globalPicklist>
        <label>Relationship</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Spouse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Spouse</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Spouse</relationshipLabel>
        <relationshipName>Spouse</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <globalPicklist>Status</globalPicklist>
        <label>Status</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Suffix__c</fullName>
        <label>Suffix</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Job Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Type 1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Guest</fullName>
        <active>true</active>
        <description>Select this record type for guest accounts.</description>
        <label>Guest</label>
    </recordTypes>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <description>Select this record type for creating members.</description>
        <label>Member</label>
    </recordTypes>
</CustomObject>

src/classes/cmsft_TestContact.cls
/**
 * See https://github.com/financialforcedev/fflib-apex-common for more info
 *
 * Install library via
 *   https://githubsfdeploy.herokuapp.com/app/githubdeploy/financialforcedev/fflib-apex-common
 */

/**
 * For more guidelines and details see
 * https://developer.salesforce.com/page/Apex_Enterprise_Patterns_-_Domain_Layer
 * @Author Nagendra kumar
 * @Date March 6, 2017
 * @Description Trigger to populate the household on member based on the household rules.
                      Terminate Member Subscription and Recurring Payments
                      Pass members to duplicate check
                      Create community User for Contact
 * @group Test Code Coverage
 */

@isTest
private class cmsft_TestContact {
    /**
    * @description this method covered test code for C62Contact Trigger
    */
    static testmethod void C62Contact() {
        Test.startTest();

        Id guestContactRT = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Guest').getRecordTypeId();

        Contact thisContact =  new Contact(FirstName = 'TestMember23', Suffix__c = 'SmithSecond3', LastName = 'Smith3',
                                           Birthdate = date.newInstance(1999, 03, 05), Title__c = 'Test new', Email = 'smith3@test.com', Relationship__c = 'Dependent', Status__c = 'Active', RecordTypeId = guestContactRT);
        Contact thisContactSpouse =  new Contact(FirstName = 'TestSpouse230', Suffix__c = '', LastName = 'Smith31',
                Birthdate = date.newInstance(1999, 03, 05), Title__c = 'Test new', Email = 'smith3@test.com', Relationship__c = 'Spouse/Partner', Status__c = 'Active', Spouse__c = thisContact.id,  RecordTypeId = guestContactRT);
        Contact thisContact2 =  new Contact(FirstName = 'TestMember1', Suffix__c = 'Smith', LastName = 'Smith',
                                            Birthdate = date.newInstance(1999, 03, 05), Title__c = 'Test new', Email = 'smith@test.com',  RecordTypeId = guestContactRT);
        Contact thisContact3 =  new Contact(FirstName = 'TestMember2', Suffix__c = 'SmithSecond', LastName = 'Smith2',
                                            Birthdate = date.newInstance(1999, 03, 05), Title__c = 'Test new', Email = 'smith2@test.com',  RecordTypeId = guestContactRT);
        Account thisAccount = new Account(Name = thisContact.LastName, Household_Name__c = 'Test');
        thisContact3.AccountId = thisAccount.id;
        thisContact2.AccountId = thisAccount.id;
        thisContact.AccountId = thisAccount.id;

        insert thisAccount;
        insert thisContact;
        insert thisContact2;
        insert thisContact3;
        insert thisContactSpouse;

        thisContact.Status__c = 'Resigned';
        update thisContact;
        thisContact.Status__c = 'Cancelled';
        update thisContact;
        thisContact.Status__c = 'Reinstated';
        update thisContact;
        thisContact.Status__c = 'Suspended';
        update thisContact;
        thisContact.Status__c = 'Expelled';
        update thisContact;
        thisContact.Spouse__c = thisContactSpouse.id;
        update thisContact;
        thisContact.Spouse__c = thisContact3.id;
        update thisContact;
        Address__c thisAddress = new Address__c(Name = 'Test Address1', From_Date__c = date.newInstance(1999, 03, 05), Customer__c = thisContact.Id,
                                                Country__c = 'United States', State_Province__c = 'NY', City__c = 'Lewiston', Street_1__c = '102 River Road',
                                                Street_2__c = 'Apt B', Street_3__c = 'Street 1', Zip_Postal_Code__c = '14095', Type__c = 'Home', Active__c = true);
        Address__c thisAddress2 = new Address__c(Name = 'Test Address2', From_Date__c = date.newInstance(1999, 03, 05), Customer__c = thisContact2.Id,
                Country__c = 'United States', State_Province__c = 'NY', City__c = 'Lewiston', Street_1__c = '102 River Road',
                Street_2__c = 'Apt B', Street_3__c = 'Street 2', Zip_Postal_Code__c = '14095', Type__c = 'Home', Active__c = true);
        Address__c thisAddress3 = new Address__c(Name = 'Test Address3', From_Date__c = date.newInstance(1999, 03, 05), Customer__c = thisContact3.Id,
                Country__c = 'United States', State_Province__c = 'NY', City__c = 'Lewiston', Street_1__c = '102 River Road',
                Street_2__c = 'Apt B', Street_3__c = 'Street 3', Zip_Postal_Code__c = '14095', Type__c = 'Home', Active__c = true);
        Address__c thisAddress4 = new Address__c(Name = 'Test Address2', From_Date__c = date.newInstance(1999, 03, 05), Customer__c = thisContact2.Id,
                Country__c = 'United States', State_Province__c = 'NY', City__c = 'Lewiston', Street_1__c = '102 River Road',
                Street_2__c = 'Apt B', Street_3__c = 'Street 2', Zip_Postal_Code__c = '14095', Type__c = 'Home', Active__c = true);
        Address__c thisAddress5 = new Address__c(Name = 'Test Address2', From_Date__c = date.newInstance(1999, 03, 05), Customer__c = thisContact3.Id,
                Country__c = 'United States', State_Province__c = 'NY', City__c = 'Lewiston', Street_1__c = '102 River Road',
                Street_2__c = 'Apt B', Street_3__c = 'Street 2', Zip_Postal_Code__c = '14095', Type__c = 'Home', Active__c = true);

        System.assertEquals(thisAddress.Name, 'Test Address1');

        List<Address__c> theseAddress = new List<Address__c>();

        theseAddress.add(thisAddress);
        theseAddress.add(thisAddress2);
        theseAddress.add(thisAddress3);
        theseAddress.add(thisAddress4);
        theseAddress.add(thisAddress5);
        insert theseAddress;
        Test.stopTest();

    }
    static testmethod void C62Contact2() {

        Test.startTest();

        Id guestContactRT = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Guest').getRecordTypeId();
        
        Contact thisContact =  new Contact(FirstName = 'TestMember23', Suffix__c = 'SmithSecond3', LastName = 'Smith3',
                                           Birthdate = date.newInstance(1999, 03, 05), Title__c = 'Test new', Email = 'smith3@test.com', Relationship__c = 'Dependent', Status__c = 'Active',  RecordTypeId = guestContactRT);

        Contact thisContactSpouse =  new Contact(FirstName = 'TestSpouse231', Suffix__c = '', LastName = 'Smith9',
                Birthdate = date.newInstance(1999, 03, 05), Title__c = 'Test new', Email = 'smith10@test.com', Relationship__c = 'Spouse/Partner', Status__c = 'Active', Spouse__c = thisContact.id,  RecordTypeId = guestContactRT);

        Contact thisContact2 =  new Contact(FirstName = 'TestMember1456', Suffix__c = 'Smith', LastName = 'Smith',
                                            Birthdate = date.newInstance(1999, 03, 05), Title__c = 'Test new', Email = 'smith@test.com', Relationship__c = 'Dependent',  RecordTypeId = guestContactRT);

        Contact thisContact3 =  new Contact(FirstName = 'TestMember2', Suffix__c = 'SmithSecond', LastName = 'Smith10',
                                            Birthdate = date.newInstance(1999, 03, 05), Title__c = 'Test new', Email = 'smith2@test.com', Relationship__c = 'Dependent',  RecordTypeId = guestContactRT);

        Account thisAccount = new Account(Name = thisContact3.LastName, Household_Name__c = 'TestC62Contact2');

        thisContact3.AccountId = thisAccount.id;
        thisContact2.AccountId = thisAccount.id;
        thisContact.AccountId = thisAccount.id;

        insert thisAccount;
        insert thisContact;
        insert thisContact2;
        insert thisContact3;
        insert thisContactSpouse;

        thisContact.Status__c = 'Resigned';
        update thisContact;
        thisContact.Status__c = 'Cancelled';
        update thisContact;
        thisContact.Status__c = 'Reinstated';
        update thisContact;
        thisContact.Status__c = 'Suspended';
        update thisContact;
        thisContact.Status__c = 'Expelled';
        update thisContact;
        thisContact.Spouse__c = thisContactSpouse.id;
        update thisContact;
        thisContact.Spouse__c = thisContact3.id;
        update thisContact;
        Address__c thisAddress = new Address__c(Name = 'Test Address1', From_Date__c = date.newInstance(1999, 03, 05), Customer__c = thisContact.Id,
                                                Country__c = 'United States', State_Province__c = 'NY', City__c = 'Lewiston', Street_1__c = '102 River Road',
                                                Street_2__c = 'Apt B', Street_3__c = 'Street 1', Zip_Postal_Code__c = '14095', Type__c = 'Home', Active__c = true);
        Address__c thisAddress2 = new Address__c(Name = 'Test Address2', From_Date__c = date.newInstance(1999, 03, 05), Customer__c = thisContact2.Id,
                Country__c = 'United States', State_Province__c = 'NY', City__c = 'Lewiston', Street_1__c = '102 River Road',
                Street_2__c = 'Apt B', Street_3__c = 'Street 2', Zip_Postal_Code__c = '14095', Type__c = 'Home', Active__c = true);
        Address__c thisAddress3 = new Address__c(Name = 'Test Address3', From_Date__c = date.newInstance(1999, 03, 05), Customer__c = thisContact3.Id,
                Country__c = 'United States', State_Province__c = 'NY', City__c = 'Lewiston', Street_1__c = '102 River Road',
                Street_2__c = 'Apt B', Street_3__c = 'Street 3', Zip_Postal_Code__c = '14095', Type__c = 'Home', Active__c = true);
        Address__c thisAddress4 = new Address__c(Name = 'Test Address2', From_Date__c = date.newInstance(1999, 03, 05), Customer__c = thisContact2.Id,
                Country__c = 'United States', State_Province__c = 'NY', City__c = 'Lewiston', Street_1__c = '102 River Road',
                Street_2__c = 'Apt B', Street_3__c = 'Street 2', Zip_Postal_Code__c = '14095', Type__c = 'Home', Active__c = true);
        Address__c thisAddress5 = new Address__c(Name = 'Test Address2', From_Date__c = date.newInstance(1999, 03, 05), Customer__c = thisContact3.Id,
                Country__c = 'United States', State_Province__c = 'NY', City__c = 'Lewiston', Street_1__c = '102 River Road',
                Street_2__c = 'Apt B', Street_3__c = 'Street 2', Zip_Postal_Code__c = '14095', Type__c = 'Home', Active__c = true);
        System.assertEquals(thisAddress.Name, 'Test Address1');

        List<Address__c> theseAddress = new List<Address__c>();
        theseAddress.add(thisAddress);
        theseAddress.add(thisAddress2);
        theseAddress.add(thisAddress3);
        theseAddress.add(thisAddress4);
        theseAddress.add(thisAddress5);
        insert theseAddress;
        Test.stopTest();

    }

}