src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Default_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to store financial account on vendor invoice lines for the current vendor</description>
        <inlineHelpText>Financial Account for vendor invoice lines</inlineHelpText>
        <label>Default Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Select this record type to create a vendor.</description>
        <label>Vendor</label>
    </recordTypes>
</CustomObject>

src/objects/Default_Account__c.object
<CustomObject>
    <description>Contains TXN to financial Account Mapping</description>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>containing relation to financial account</description>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Default Accounts</relationshipLabel>
        <relationshipName>Txn_To_Financial_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Default Account</label>
    <nameField>
        <displayFormat>DA-{00000}</displayFormat>
        <label>Default Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Journal_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Entry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Post_Date__c</fullName>
        <label>Post Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Posted?</label>
        <type>Checkbox</type>
    </fields>
    <label>Financial Journal Entry</label>
    <nameField>
        <displayFormat>FJE-{00000000}</displayFormat>
        <label>Financial Journal Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Journal_Line__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Journal Lines</relationshipLabel>
        <relationshipName>Financial_Journal_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Journal_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Journal Entry</label>
        <referenceTo>Financial_Journal_Entry__c</referenceTo>
        <relationshipName>Financial_Journals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Post_Date__c</fullName>
        <label>Post Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Posted?</label>
        <type>Checkbox</type>
    </fields>
    <label>Financial Journal Line</label>
    <nameField>
        <displayFormat>FINJRNL-{000000}</displayFormat>
        <label>Financial Journal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Journal Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Financial_Journal_Entry__c</fullName>
        <formula>HYPERLINK(Journal_Entry__c,Journal_Entry__r.Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Financial Journal Entry</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Post_Date__c</fullName>
        <label>Post Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Post_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <description>to fill status of post - not to be included in page layout</description>
        <label>Post Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <formula>Post_Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Posted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Vendor, Reciprocal Club</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vendor Invoices</relationshipLabel>
        <relationshipName>Vendor_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vendor Invoice</label>
    <nameField>
        <displayFormat>VNDRINVENTR-{0000000}</displayFormat>
        <label>Vendor Invoice Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice_Line__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Vendor Invoice Lines (Financial Account)</relationshipLabel>
        <relationshipName>Vendor_Invoice_Lines</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Journal_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Journal Line</label>
        <referenceTo>Financial_Journal_Line__c</referenceTo>
        <relationshipLabel>Vendor Invoice Lines</relationshipLabel>
        <relationshipName>Vendor_Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Post_Date__c</fullName>
        <label>Post Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Posted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoice__c</fullName>
        <label>Vendor Invoice</label>
        <referenceTo>Vendor_Invoice__c</referenceTo>
        <relationshipLabel>Vendor Invoice Lines</relationshipLabel>
        <relationshipName>Vendor_Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vendor Invoice Line</label>
    <nameField>
        <displayFormat>VNDRSTMTLNE-{0000000}</displayFormat>
        <label>Vendor Invoice Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountPayableControllerTest.cls
/**
* @Description : test class for PostInvoiceController and AccountPayableController
* @Date : 2017
*/

@isTest
private class AccountPayableControllerTest {
	
	/**
	* @Description : test method for AccountPayableController
	*/
	@isTest 
	static void AccountPayableControllerTestMethodOne() 
	{
        Financial_Account__c finAccount = TxnTestUtility.createFinancialAccount('TestAccPay');
        Default_Account__c defaultMapping = TxnTestUtility.getDefaultMapping('Accounts Payable', finAccount); 
        Account vendRec= TxnTestUtility.createAccount(Utility.searchRecordType('Vendor','Account'));
        
        Vendor_Invoice__c vendorInvoice = TxnTestUtility.createInvoice(500, '569874254', vendRec.id);
		Vendor_Invoice_Line__c vendorInvoiceLine = TxnTestUtility.createInvoiceLines(200, vendorInvoice.id);
		Vendor_Invoice_Line__c vendorInvoiceLine1 = TxnTestUtility.createInvoiceLines(300, vendorInvoice.id);
		Vendor_Invoice__c vendorInvoice1 = TxnTestUtility.createInvoice(500, '569874257', vendRec.id);
		Vendor_Invoice_Line__c vendorInvoiceLine2 = TxnTestUtility.createInvoiceLines(500, vendorInvoice1.id);

        Vendor_Invoice__c vInv = TxnTestUtility.createInvoice(Double.valueOf(500), '564625416484', vendRec.id);
		AccountsPayableController accPayObj = new AccountsPayableController();
        Test.startTest();
		accPayObj.SearchAPEnteries();
        
        // check unpostedVenInvList size must be greater than 0
        System.assert(accPayObj.unpostedVenInvList.size()>0);

        // mark them to be posted
        for(Vendor_Invoice__c vendInv :accPayObj.unpostedVenInvList){
        	vendInv.Post_Status__c = true;
        }
        accPayObj.takeConfirm = 'confirm';
		accPayObj.postEnteries();

		// check numberOfFailedPosting size must be 1
		System.assertEquals(1, accPayObj.numberOfFailedPosting);
		accPayObj.takeConfirm = 'post';
		accPayObj.postEnteries();
		vendorInvoice = [select Posted__c, Amount__c, Vendor__c from Vendor_Invoice__c where id=:vendorInvoice.id];

		// check posted checkbox should be true now
		System.assertEquals(true, vendorInvoice.Posted__c);
        Test.stopTest();
	}

	/**
	* @Description : test method to cover code selected from detail page
	*/
	@isTest
	static void testMethod2()
	{
		Financial_Account__c finAccount = TxnTestUtility.createFinancialAccount('TestAccPay');
        Default_Account__c defaultMapping = TxnTestUtility.getDefaultMapping('Accounts Payable', finAccount);
        Account vendRec= TxnTestUtility.createAccount(Utility.searchRecordType('Vendor','Account'));
		Vendor_Invoice__c vendorInvoice = TxnTestUtility.createInvoice(500, '569874254', vendRec.id);
		Vendor_Invoice_Line__c vendorInvoiceLine = TxnTestUtility.createInvoiceLines(200, vendorInvoice.id);
		Test.setCurrentPage(new PageReference('Page.AccountsPayable'));
		System.currentPageReference().getParameters().put('Vid', vendorInvoice.id);
		Test.startTest();
		AccountsPayableController accPayObj = new AccountsPayableController();
		// check unpostedVenInvList size should be greater than 0 now
		System.assert(accPayObj.unpostedVenInvList.size()>0);
		System.assertEquals(true, accPayObj.unpostedVenInvList[0].Post_Status__c);
		Test.stopTest();
	}

	/**
	* @Description : test method to cover change post date of a posted financial journal entry 
	*/
	@isTest
	static void testChangeFJEPostDate()
	{
		Financial_Account__c finAccount = TxnTestUtility.createFinancialAccount('TestChangeFJEPSD');
		Financial_Journal_Entry__c finEntry = new Financial_Journal_Entry__c(Posted__c=true, Post_Date__c=Date.today(), Entry_Date__c=Date.today());
		insert finEntry;
		Financial_Journal_Line__c finJeLine = new Financial_Journal_Line__c(Financial_Journal_Entry__c=finEntry.id, Financial_Account__c=finAccount.id, Posted__c=true, Post_Date__c=Date.today(), Amount__c= -200);
		Financial_Journal_Line__c finJeLine1 = new Financial_Journal_Line__c(Financial_Journal_Entry__c=finEntry.id, Financial_Account__c=finAccount.id, Posted__c=true, Post_Date__c=Date.today(), Amount__c=200);
		insert finJeLine;
		insert finJeLine1;
		Test.setCurrentPage(Page.changeInvoicePostDate);
		System.currentPageReference().getParameters().put('FjeId', finEntry.id);
		Test.startTest();
		AccountsPayableController apc = new AccountsPayableController();
		apc.finJeEntry.Post_Date__c = Date.today().addMonths(-1);
		apc.UpdateFinJEPostDate();
		Financial_Journal_Entry__c fjeEntrySaved = [Select id, Post_Date__c from Financial_Journal_Entry__c where id=:apc.finJeEntry.id];
		System.assertEquals(Date.today().addMonths(-1).month(), apc.finJeEntry.Post_Date__c.month());
		Test.stopTest();
	}
}