src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <description>Select this record type for member accounts.</description>
        <label>Household</label>
    </recordTypes>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <description>Select this record type for creating members.</description>
        <label>Member</label>
    </recordTypes>
</CustomObject>

src/objects/Member_Dues__c.object
<CustomObject>
    <description>Dues  subscription for member on different categories</description>
    <label>Member Dues</label>
    <nameField>
        <label>Due Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Dues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TXN__c.object
<CustomObject>
    <fields>
        <fullName>Adjustment_Reason__c</fullName>
        <label>Adjustment Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Member_Dues__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to fill the due id in this</description>
        <label>Member Dues</label>
        <referenceTo>Member_Dues__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Statement_Description__c</fullName>
        <label>Statement Description</label>
        <type>TextArea</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Dues</fullName>
        <active>true</active>
        <label>Dues</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AdjustmentTest.cls
@isTest
private class AdjustmentTest
{
	@isTest
	static void duesAdjustment()
	{
		Account acc = TxnTestUtility.createAccount(Utility.searchRecordType('Household', 'Account'));
		Contact con = TxnTestUtility.createMember(acc, 'Primary', Utility.searchRecordType('Member', 'Contact'));
		Member_Dues__c dueObj = TxnTestUtility.getDue('Post Dues Test', 'Installment');
		List<TXN__c> dueTxnRec = TxnTestUtility.getManualDuesWithTaxes(dueObj, con);
		Test.startTest();
		Test.setCurrentPage(Page.TxnChargesAdjustment);
		ApexPages.currentPage().getParameters().put('Id', dueTxnRec[0].id);
		TxnChargesAdjustmentController txnChargeAdjus = new TxnChargesAdjustmentController();
		txnChargeAdjus.adjustmentTxnRecord.Statement_Description__c = 'testing statement description dues adjust';
		txnChargeAdjus.adjustmentTxnRecord.Adjustment_Reason__c = 'test adjust reason dues adjust';
		txnChargeAdjus.saveDueAdjust();
		System.assert(txnChargeAdjus.adjustmentTxnRecord.id!=null);
		Test.stopTest();
	}
}