src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <description>Select this record type for member accounts.</description>
        <label>Household</label>
    </recordTypes>
</CustomObject>

src/objects/Billing_Custom_Distribution__c.object
<CustomObject>
    <description>stores each custom due distributions</description>
    <fields>
        <fullName>January__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>January</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Member_Dues__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Dues</label>
        <referenceTo>Member_Dues__c</referenceTo>
        <relationshipLabel>Billing Custom Distributions</relationshipLabel>
        <relationshipName>Billing_Custom_Distributions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>should store the relationship type for the current distrubtion</description>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Billing Custom Distribution</label>
    <nameField>
        <displayFormat>Dist-{0000000}</displayFormat>
        <label>Billing Custom Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Custom Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Type 1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <description>Select this record type for creating members.</description>
        <label>Member</label>
    </recordTypes>
</CustomObject>

src/objects/Member_Dues__c.object
<CustomObject>
    <description>Dues  subscription for member on different categories</description>
    <fields>
        <fullName>Default_Billing_Frequency__c</fullName>
        <description>Represents the default billing frequency to the members who have this due.</description>
        <label>Default Billing Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Annual</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Installment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quaterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One Time</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <globalPicklist>Type</globalPicklist>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Member Dues</label>
    <nameField>
        <label>Due Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Dues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MemberDuesDomainTest.cls
/**
* @Description : test class for BillingTableDomain 
* @group : Financial Management
*/
@isTest
private class MemberDuesDomainTest
{
    @isTest
    static void BillingTableDomainTest1()
    {
        Account acc = TxnTestUtility.createAccount(Utility.searchRecordType('Household', 'Account'));
        Contact member = TxnTestUtility.createMember(acc, 'Primary', Utility.searchRecordType('Member', 'Contact'));
        List<Member_Dues__c> duesList = new List<Member_Dues__c>();
        List<Billing_Custom_Distribution__c> billList = new List<Billing_Custom_Distribution__c>();
        Member_Dues__c dueObj = TxnTestUtility.getDue('Testing Due', 'Monthly');

        // bulk test
        for(Integer i=0; i<199; i++)
        {
            Member_Dues__c dueObj1 = dueObj.clone(false,false);
            dueObj1.Name = dueObj1.Name+i;
            duesList.add(dueObj1);
        }
        insert duesList;
        update duesList;
        for(Member_Dues__c due :duesList)
        {
            Billing_Custom_Distribution__c billCus = new Billing_Custom_Distribution__c(Type__c='Dependent', Member_Dues__c=due.Id, January__c=100);
            Billing_Custom_Distribution__c billCus1 = new Billing_Custom_Distribution__c(Type__c='Primary', Member_Dues__c=due.Id);
            Billing_Custom_Distribution__c billCus2 = new Billing_Custom_Distribution__c(Type__c='Spouse/Partner', Member_Dues__c=due.Id);
            billList.add(billCus);
            billList.add(billCus1);
            billList.add(billCus2);
            due.Default_Billing_Frequency__c = 'Annual';
        }
        insert billList;

        // apply this due on member
        Test.startTest();
        update duesList;
        Billing_Custom_Distribution__c distr = [select January__c from Billing_Custom_Distribution__c where Member_Dues__c=:duesList.get(0).id AND Type__c='Dependent'];
        System.assertEquals(distr.January__c, 0);
        Test.stopTest();        
    }
}