src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Select this record type to create a vendor.</description>
        <label>Vendor</label>
    </recordTypes>
</CustomObject>

src/objects/AP_Aging__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>used to store last effective date of APAgingBatch</description>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <label>AP Aging</label>
</CustomObject>

src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <formula>Post_Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Posted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Vendor, Reciprocal Club</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vendor Invoices</relationshipLabel>
        <relationshipName>Vendor_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vendor Invoice</label>
    <nameField>
        <displayFormat>VNDRINVENTR-{0000000}</displayFormat>
        <label>Vendor Invoice Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice_Line__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Vendor Invoice Lines (Financial Account)</relationshipLabel>
        <relationshipName>Vendor_Invoice_Lines</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Posted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoice__c</fullName>
        <label>Vendor Invoice</label>
        <referenceTo>Vendor_Invoice__c</referenceTo>
        <relationshipLabel>Vendor Invoice Lines</relationshipLabel>
        <relationshipName>Vendor_Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vendor Invoice Line</label>
    <nameField>
        <displayFormat>VNDRSTMTLNE-{0000000}</displayFormat>
        <label>Vendor Invoice Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BatchStatusControllerTest.cls
/**
* @Description : Test class for the BatchstatusController
*/
@isTest
private class BatchStatusControllerTest
{
	/**
	* @Description : Test method 1
	*/
	@isTest
	static void BatchstatusMeth1()
	{
		// Creating vendor, vendor invoice and invoice lines
		Account vendor = TxnTestUtility.createAccount(Utility.searchRecordType('Vendor', 'Account'));
		Vendor_Invoice__c vendorInvoice = TxnTestUtility.createInvoice(500, '569874254', vendor.id);
		Vendor_Invoice_Line__c vendorInvoiceLine = TxnTestUtility.createInvoiceLines(200, vendorInvoice.id);
		Vendor_Invoice_Line__c vendorInvoiceLine1 = TxnTestUtility.createInvoiceLines(300, vendorInvoice.id);
		Vendor_Invoice__c vendorInvoice1 = TxnTestUtility.createInvoice(500, '569874257', vendor.id);
		vendorInvoice1.Invoice_Date__c = Date.today().addDays(-60);
		update vendorInvoice1;
		Vendor_Invoice_Line__c vendorInvoiceLine2 = TxnTestUtility.createInvoiceLines(500, vendorInvoice1.id);

		// set default financial account
		Financial_Account__c finAcc = TxnTestUtility.createFinancialAccount('TestBatch123');
		TxnTestUtility.getDefaultMapping('Accounts Payable', finAcc);
		
		//posting invoices so that the batch can take it
		cmsft_AccountPayableServiceImpl.postInvoice(new List<Vendor_Invoice__c> {vendorInvoice, vendorInvoice1}, Date.today(), Date.today());
		vendorInvoice = [select Posted__c, Amount__c, Vendor__c from Vendor_Invoice__c where id=:vendorInvoice.id];
		vendorInvoice1 = [select Posted__c, Amount__c, Vendor__c from Vendor_Invoice__c where id=:vendorInvoice1.id];
		System.assert(vendorInvoice.Posted__c);

		AP_Aging__c apcus = new AP_Aging__c(name='Effective Date Record', Effective_Date__c=Date.today());
		insert apcus;
		Test.startTest();
		APAgingBatch ap =new APAgingBatch();
		Id batchId = Database.executeBatch(ap);
		BatchStatusController bsc = new BatchStatusController();
		bsc.redirectToPage = 'APAgingBatchRunner';
		bsc.batchId = batchId;
		BatchStatusController.BatchJobs bj = bsc.currentJob;
		bsc.updateProgress();
		System.assert(bj.isCompleted==false);
		bj = bsc.currentJob;
		Test.stopTest();
	}
}