src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Default_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to store financial account on vendor invoice lines for the current vendor</description>
        <inlineHelpText>Financial Account for vendor invoice lines</inlineHelpText>
        <label>Default Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Select this record type to create a vendor.</description>
        <label>Vendor</label>
    </recordTypes>
</CustomObject>

src/objects/Default_Account__c.object
<CustomObject>
    <description>Contains TXN to financial Account Mapping</description>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>containing relation to financial account</description>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Default Accounts</relationshipLabel>
        <relationshipName>Txn_To_Financial_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Default Account</label>
    <nameField>
        <displayFormat>DA-{00000}</displayFormat>
        <label>Default Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Accounts</pluralLabel>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <label>Default</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Posted__c</fullName>
        <formula>Post_Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Posted?</label>
        <type>Checkbox</type>
    </fields>
    <label>Vendor Invoice</label>
    <nameField>
        <displayFormat>VNDRINVENTR-{0000000}</displayFormat>
        <label>Vendor Invoice Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice_Line__c.object
<CustomObject>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Vendor Invoice Lines (Financial Account)</relationshipLabel>
        <relationshipName>Vendor_Invoice_Lines</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Posted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoice__c</fullName>
        <label>Vendor Invoice</label>
        <referenceTo>Vendor_Invoice__c</referenceTo>
        <relationshipLabel>Vendor Invoice Lines</relationshipLabel>
        <relationshipName>Vendor_Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vendor Invoice Line</label>
    <nameField>
        <displayFormat>VNDRSTMTLNE-{0000000}</displayFormat>
        <label>Vendor Invoice Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/cmsft_VendInvLineServiceImpl.cls
/**
 * https://developer.salesforce.com/page/Apex_Enterprise_Patterns_-_Service_Layer
 * @Date: 20th May - 2017
 * @Author: Jyotig@mobifyi.com 
 * @group: Financial Management 
 * @Description: service class for VendInvLine class
 */

public with sharing class cmsft_VendInvLineServiceImpl {

    /**
    * @Description : bussiness logic behing getting vendor invoice line complete record service with passed id
    * @return : returns vendor Invoice Line object after querying
    */
    public static Vendor_Invoice_Line__c getVendorInvoiceLineFullRecord(string vilId){
        Set<Id> vidSet = new Set<Id>();
        vidSet.add(vilId);
        return new cmsft_vendorInvoiceLineTriggerSelector().selectById(vidSet).get(0);
    }

    /**
    * @Description : bussiness logic behind getting vendor invoice complete record service with passed id
    * @return : returns vendor Invoice object after querying
    */
    public static vendor_invoice__c getVendorInvoiceForNewNEditVIL(Vendor_Invoice_Line__c vil){
        Set<Id> vidSet = new Set<Id>();
        vidSet.add(vil.Vendor_Invoice__c);
        return new cmsft_vendorInvoiceTriggerSelector().selectById(vidSet).get(0);
    }

   /**
    * @Description : bussiness logic behind getting vendor invoice with passed endor invoice line record
    * @return : returns vendor Invoice Line object after querying
    */
    public static vendor_invoice__c getVendorInvoiceFullRecord(String viId){
        Set<Id> vidSet = new Set<Id>();
        vidSet.add(viId);
        return new cmsft_vendorInvoiceTriggerSelector().selectById(vidSet).get(0);
    }
    
    /**
    * @Description : bussiness logic behind return error if the passed invoice is already posted
    * @return : returns boolean if true then error
    */
    public static boolean returnErrorIfInvoiceAlreadyPosted(Vendor_Invoice__c vendInv){
        if(vendInv.Posted__c){
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Invoice Lines can not be added/updated to posted invoice.'));
        return true;
        }
        return false;
    }

    /**
    * @Description : bussiness logic behind saving invoice lines , throw exception if no rights to the user to modify the Vendor_Invoice_Line__c object
    * @return : returns page to be refreshed
    */
    public static pageReference saveNew(List<Vendor_Invoice__c> vin, List<Vendor_Invoice_Line__c> vilRec, List<string> saveOrSaveNew){
        try{
        	Data.upsurt(vilRec, Vendor_Invoice_Line__c.Id.getDescribe().getSObjectField(), new Set<String>());    
        }catch (Exception e){
            return null;
        }
        
        if(saveOrSaveNew.get(0)=='save')
        {
            return new PageReference('/'+vin.get(0).id);
        }
        else {
            PageReference pg = new PageReference('/apex/CreateVendInvLine?vid='+vin.get(0).id);
            pg.setRedirect(true);
            return pg;
        }
    }

    /**
    * @Description : get vendor default account and fill this in vendor invoice line
    */
    public static List<Vendor_Invoice_Line__c> fillDefaultAccount(List<Vendor_Invoice_Line__c> vendInvLineList, String vendId)
    {
        String finAccId = new cmsft_AccountSelector().getAccountsWithPassedCondition('Id=\''+vendId+'\'').get(0).Default_Account__c;
        for(Vendor_Invoice_Line__c vendInvObj :vendInvLineList)
        {
            vendInvObj.Financial_Account__c = finAccId;
        }
        return vendInvLineList;
    }
}