src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Default_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to store financial account on vendor invoice lines for the current vendor</description>
        <inlineHelpText>Financial Account for vendor invoice lines</inlineHelpText>
        <label>Default Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <description>Select this record type for member accounts.</description>
        <label>Household</label>
    </recordTypes>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <description>Select this record type for creating members.</description>
        <label>Member</label>
    </recordTypes>
</CustomObject>

src/objects/Default_Account__c.object
<CustomObject>
    <description>Contains TXN to financial Account Mapping</description>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>containing relation to financial account</description>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Default Accounts</relationshipLabel>
        <relationshipName>Txn_To_Financial_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <globalPicklist>Payment_Type</globalPicklist>
        <label>Payment Type</label>
        <type>Picklist</type>
    </fields>
    <label>Default Account</label>
    <nameField>
        <displayFormat>DA-{00000}</displayFormat>
        <label>Default Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Accounts</pluralLabel>
    <recordTypes>
        <fullName>Payments</fullName>
        <active>true</active>
        <label>Payments</label>
    </recordTypes>
    <recordTypes>
        <fullName>Refund</fullName>
        <active>true</active>
        <label>Refund</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TXN__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Transactions (Financial Account)</relationshipLabel>
        <relationshipName>Transactions3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <description>payment type of the payment</description>
        <globalPicklist>Payment_Type</globalPicklist>
        <inlineHelpText>payment type of the payment</inlineHelpText>
        <label>Payment Type</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related To</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6 AND 7 AND 8)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Refund</value>
            </filterItems>
            <filterItems>
                <field>TXN__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Payment</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Adjustment</value>
            </filterItems>
            <filterItems>
                <field>TXN__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Charge, Dues, Taxes, Service Charges</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Refund</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Adjustment</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Dues</value>
            </filterItems>
            <filterItems>
                <field>TXN__c.RecordTypeId</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TXN__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Payment</fullName>
        <active>true</active>
        <label>Payment</label>
    </recordTypes>
    <recordTypes>
        <fullName>Refund</fullName>
        <active>true</active>
        <label>Refund</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/allPaymentsControllerTest.cls
@isTest
private class allPaymentsControllerTest
{
    public  Static String  AccountMemberId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
    public  Static String ContactMemberId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Member').getRecordTypeId();
    public  Static String refundId = Schema.SObjectType.TXN__c.getRecordTypeInfosByName().get('Refund').getRecordTypeId();

	@isTest
	static void allPaymentsControllerTest()
	{
        Test.startTest();
        Financial_Account__c fa = TxnTestUtility.createFinancialAccount('test');
        Default_Account__c da =TxnTestUtility.getDefaultMapping('Accounts Receivable',fa);
        da = TxnTestUtility.getDefaultPaymentMapping('Cash',fa) ;
        da = TxnTestUtility.getDefaultRefundMapping('Cash',fa) ;
    
        Account Acc=TxnTestUtility.createAccount(AccountMemberId);
        Contact mem=TxnTestUtility.createMember(Acc,'Primary',ContactMemberId);
        TXN__c payment=TxnTestUtility.txnCreatePay(mem);
        
        TXN__c newRefund = new TXN__c();
        newRefund.Amount__c = 50.00;
        newRefund.Related_To__c = payment.id;
        newRefund.RecordTypeId = refundId;
        newRefund.Payment_Type__c='Cash';
        insert newRefund;
        Apexpages.currentPage().getParameters().put('MemberId', mem.id);
		allPaymentsController payments=new allPaymentsController();

		Test.stopTest();
	}
}