src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <description>Select this record type for member accounts.</description>
        <label>Household</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Select this record type to create a vendor.</description>
        <label>Vendor</label>
    </recordTypes>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Select this record type for creating club vendors.</description>
        <label>Vendor</label>
    </recordTypes>
</CustomObject>

src/objects/Vendor_Invoice__c.object
<CustomObject>
    <label>Vendor Invoice</label>
    <nameField>
        <displayFormat>VNDRINVENTR-{0000000}</displayFormat>
        <label>Vendor Invoice Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice_Line__c.object
<CustomObject>
    <fields>
        <fullName>Vendor_Invoice__c</fullName>
        <label>Vendor Invoice</label>
        <referenceTo>Vendor_Invoice__c</referenceTo>
        <relationshipLabel>Vendor Invoice Lines</relationshipLabel>
        <relationshipName>Vendor_Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vendor Invoice Line</label>
    <nameField>
        <displayFormat>VNDRSTMTLNE-{0000000}</displayFormat>
        <label>Vendor Invoice Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/vendorInvoiceLinesTrigger_test.cls
@isTest
public class vendorInvoiceLinesTrigger_test {
    public static String AccountMemberId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
    public static String VendorRecordType = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Vendor').getRecordTypeId();
    private testMethod static void runAll() {
        Account account = TxnTestUtility.createAccount(Utility.searchRecordType('Vendor','Account'));   
        Vendor_Invoice__c NewInvoice=TxnTestUtility.createInvoice(100,'123',account.id);
        //on insert check
        Vendor_Invoice_Line__c invoiceLine_test1=TxnTestUtility.createInvoiceLines(100,NewInvoice.id);
        try{
        Vendor_Invoice_Line__c invoiceLine_test2=TxnTestUtility.createInvoiceLines(110,NewInvoice.id);  
        }catch(Exception e){
            //error on duplicate invoice number successfully came.
            Boolean expectedExceptionThrown =  e.getMessage().contains('Invoice lines total amount should not be more then invoice total amount') ? true : false;
            System.AssertEquals(expectedExceptionThrown, true);
        }
        
        //on updatecheck
        Vendor_Invoice_Line__c invoiceLine_updateTest1=TxnTestUtility.updateInvoiceLines(invoiceLine_test1.id,10);
        try{
            Vendor_Invoice_Line__c invoiceLine_updateTest2=TxnTestUtility.updateInvoiceLines(invoiceLine_test1.id,110);  
        }catch(Exception e){
            //error on duplicate invoice number successfully came.
            Boolean expectedExceptionThrown =  e.getMessage().contains('Invoice lines total amount should not be more then invoice total amount') ? true : false;
            System.AssertEquals(expectedExceptionThrown, true);
        }
    }
}