src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Default_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to store financial account on vendor invoice lines for the current vendor</description>
        <inlineHelpText>Financial Account for vendor invoice lines</inlineHelpText>
        <label>Default Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Default_Account__c.object
<CustomObject>
    <description>Contains TXN to financial Account Mapping</description>
    <fields>
        <fullName>Default_Type_Name__c</fullName>
        <label>Default Type Name</label>
        <picklist>
            <picklistValues>
                <fullName>Accounts Receivable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prepaid Deposits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accounts Receivable - Dues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Book</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accounts Payable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accounts Payable Discounts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>POS Discounts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Book - Debit Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Book - Credit Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Default Account</label>
    <nameField>
        <displayFormat>DA-{00000}</displayFormat>
        <label>Default Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Accounts</pluralLabel>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <label>Default</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DefaultAccountDomain.cls
/**
 * For more guidelines and details see 
 *   https://developer.salesforce.com/page/Apex_Enterprise_Patterns_-_Domain_Layer
 *
 * @Description : Encapsulates all behaviour logic relating to the Default_Account__c object
 * @Author : jyotig@mobifyi.com
 * @group : Financial Management
 **/
public class DefaultAccountDomain extends fflib_SObjectDomain 
{
	public DefaultAccountDomain(List<Default_Account__c> records) 
	{
		super(records);	
	}

	public override void onBeforeInsert()
	{
		validateTypeName(Records);
	}

	public override void onBeforeUpdate(Map<Id,SObject> existingRecords)
	{
		validateTypeName(Records);
	}

	/**
	* @Description : check for records having duplicate default type name
	*/
	public void validateTypeName(List<SObject> Records)
	{
		List<String> defaultTypeNames = new List<String>();

		for(Default_Account__c record : (List<Default_Account__c>) Records)
		{
			if(record.Default_Type_Name__c!=null && record.Default_Type_Name__c!='')
				defaultTypeNames.add(record.Default_Type_Name__c);
		}
		Map<Id, Default_Account__c> defAccountHaving = new Map<Id, Default_Account__c>(new cmsft_DefaultAccountSelector().selectByPassedCondition(defaultTypeNames));
		for(Integer i=0; i< Records.size(); i++)
		{
			Default_Account__c defRecord = (Default_Account__c)Records[i];

			// for loop to cover all saved records
			for(Default_Account__c defAccObj :defAccountHaving.values())
			{
				if(defRecord.id!=null && defRecord.id!=defAccObj.id) {
					if(defRecord.Default_Type_Name__c == defAccObj.Default_Type_Name__c)
					defRecord.Default_Type_Name__c.addError('Account mapping with this default type name already exist.');
					break;
				}
				else if(defRecord.id==null) {
					if(defRecord.Default_Type_Name__c == defAccObj.Default_Type_Name__c)
					defRecord.Default_Type_Name__c.addError('Account mapping with this default type name already exist.');
					break;
				}
			}

			// for loop to check in the coming list
			for(Integer j=i+1; j<Records.size(); j++)
			{
				Default_Account__c record1 = (Default_Account__c) Records[i];
				if(defRecord.Default_Type_Name__c == record1.Default_Type_Name__c){
					defRecord.Default_Type_Name__c.addError('Account mapping with this default type name already exist.');
					break;
				}
			}
		}
	}

	public class Constructor implements fflib_SObjectDomain.IConstructable2
	{
		public fflib_SObjectDomain construct(List<SObject> sObjectList)
		{
			return new DefaultAccountDomain(sObjectList);
		}

		public fflib_SObjectDomain construct(List<SObject> sObjectList, SObjectType sObjectType)
		{
			return new DefaultAccountDomain(sObjectList);
		}			
	}	
}