src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Aging_Effective_Date__c</fullName>
        <description>to store the effective date for Aging - vendor specific field</description>
        <label>Aging Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Default_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to store financial account on vendor invoice lines for the current vendor</description>
        <inlineHelpText>Financial Account for vendor invoice lines</inlineHelpText>
        <label>Default Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X0_30__c</fullName>
        <label>0-30</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X31_60__c</fullName>
        <description>to store 2nd month prior dues - vendor specific</description>
        <label>31-60</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X61_90__c</fullName>
        <description>stores 3rd moth prior dues on the vendor - vendor specific</description>
        <label>61-90</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X91__c</fullName>
        <label>91+</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/Default_Account__c.object
<CustomObject>
    <description>Contains TXN to financial Account Mapping</description>
    <label>Default Account</label>
    <nameField>
        <displayFormat>DA-{00000}</displayFormat>
        <label>Default Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/cmsft_AccountSelector.cls
/**
 * @Description :Class encapsulates query logic for Account
 * @Date : 6th June - 2017
 * https://developer.salesforce.com/page/Apex_Enterprise_Patterns_-_Selector_Layer
 */
public class cmsft_AccountSelector extends fflib_SObjectSelector
{
	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField> {
				Account.Id,
				Account.X0_30__c,
				Account.X31_60__c,
				Account.X61_90__c,
				Account.X91__c,
				Account.Aging_Effective_Date__c,
				Account.Default_Account__c
			};
	}

	public Schema.SObjectType getSObjectType()
	{
		return Account.sObjectType;
	}
	
	/**
    * @Description select all Accounts with passed condition 
    * @return A query locator is returned, can run at calling place
    */
    public String getAllAccounts(String condition) {
        return (String)(newQueryFactory(true, true, true)
                                        .setCondition(condition)
                                        .toSOQL());
    }

    /**
    * @Description select all Accounts with passed condition 
    * @return A list is returned of the result
    */
    public List<Account> getAccountsWithPassedCondition(String condition) {
        return Database.query(newQueryFactory(true, true, true)
                                        .setCondition(condition)
                                        .toSOQL());
    }
}