src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Default_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to store financial account on vendor invoice lines for the current vendor</description>
        <inlineHelpText>Financial Account for vendor invoice lines</inlineHelpText>
        <label>Default Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <description>Select this record type for member accounts.</description>
        <label>Household</label>
    </recordTypes>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Customer_Id__c</fullName>
        <label>Member Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Membership_Type__c</fullName>
        <label>Membership Type</label>
        <picklist>
            <picklistValues>
                <fullName>Legacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Athletic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Junior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <description>Select this record type for creating members.</description>
        <label>Member</label>
    </recordTypes>
</CustomObject>

src/objects/Default_Account__c.object
<CustomObject>
    <description>Contains TXN to financial Account Mapping</description>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>containing relation to financial account</description>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Default Accounts</relationshipLabel>
        <relationshipName>Txn_To_Financial_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Default Account</label>
    <nameField>
        <displayFormat>DA-{00000}</displayFormat>
        <label>Default Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Dues_Summary__c.object
<CustomObject>
    <description>the object is used to store due summary records and the failed records</description>
    <fields>
        <fullName>Billing_Period__c</fullName>
        <description>the field is used to store billing month</description>
        <label>Billing Period</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Dues Summary</relationshipLabel>
        <relationshipName>Dues_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member_Dues__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Dues</label>
        <referenceTo>Member_Dues__c</referenceTo>
        <relationshipLabel>Dues Summary</relationshipLabel>
        <relationshipName>Dues_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Post_Date__c</fullName>
        <description>the field is used to store the due date</description>
        <label>Post Date</label>
        <type>Date</type>
    </fields>
    <label>Dues Summary</label>
    <nameField>
        <displayFormat>DUESUM-{0000000}</displayFormat>
        <label>Dues Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dues Summary</pluralLabel>
    <recordTypes>
        <fullName>Dues</fullName>
        <active>true</active>
        <description>generated dues</description>
        <label>Dues</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Member_Dues__c.object
<CustomObject>
    <description>Dues  subscription for member on different categories</description>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Financial Account for crediting the amount charged through the due</description>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipName>Billing_Table</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Member Dues</label>
    <nameField>
        <label>Due Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Dues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Statements__c.object
<CustomObject>
    <description>the object is used to store member statements</description>
    <fields>
        <fullName>Billing_Period__c</fullName>
        <description>the field is used to store the billing month and year for statement generation</description>
        <label>Billing Period</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>only for member statement recordtype</description>
        <label>Member</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.Record_Type_Name__c</field>
                <operation>equals</operation>
                <value>Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Statements (Member)</relationshipLabel>
        <relationshipName>MemberStatements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Membership_Type__c</fullName>
        <description>the field is used to store the membership types generated for a particular billing period</description>
        <label>Membership Type</label>
        <picklist>
            <picklistValues>
                <fullName>--None--</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <label>Statement</label>
    <nameField>
        <displayFormat>Stmt-{0000000}</displayFormat>
        <label>Statements Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TXN__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Dues_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to relate unposted dues created before</description>
        <label>Dues Summary</label>
        <referenceTo>Dues_Summary__c</referenceTo>
        <relationshipLabel>Posted Dues</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Transactions (Financial Account)</relationshipLabel>
        <relationshipName>Transactions3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member_Dues__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to fill the due id in this</description>
        <label>Member Dues</label>
        <referenceTo>Member_Dues__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Dues</fullName>
        <active>true</active>
        <label>Dues</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ScheduleUpdateStatementBatchTest.cls
@isTest
private class ScheduleUpdateStatementBatchTest
{
	@isTest
	static void ScheduleUpdateStatementBatchTestMethod1()
	{
		Financial_Account__c fa = TxnTestUtility.createFinancialAccount('teest');
        Default_Account__c da =TxnTestUtility.getDefaultMapping('Accounts Receivable',fa);
        da =TxnTestUtility.getDefaultMapping('Accounts Payable',fa);
        da = TxnTestUtility.getDefaultPaymentMapping('Cash',fa) ;
		Account acc = TxnTestUtility.createAccount(Utility.searchRecordType('Household','Account'));
		Contact member = TxnTestUtility.createMember(acc, 'Dependent', Utility.searchRecordType('Member','Contact'));
		Statements__c stmtSumm = TxnTestUtility.getStatementSummary(member);
		Date todaysDate = Date.today();
		stmtSumm.Date__c = Date.newInstance(todaysDate.year(), todaysDate.month(), 1);
		stmtSumm.To_Date__c = Date.newInstance(todaysDate.year(), todaysDate.month(), todaysDate.addMonths(1).toStartOfMonth().addDays(-1).day());
		update stmtSumm;
		Test.startTest();
		Member_Dues__c memDue = TxnTestUtility.getDue('Test statement due', 'Annual');
		List<TXN__c> manualDueAndTaxes = TxnTestUtility.getManualDuesWithTaxes(memDue, member);
		TXN__c payRec = TxnTestUtility.txnCreatePay(member);
		TXN__C refRec = TxnTestUtility.getRefundFromPayment(payRec);
		List<TXN__c> adjustments = TxnTestUtility.getAdjustmentRecordsOnDues(manualDueAndTaxes[0]);
		TXN__C eveCharge = TxnTestUtility.getEventCharges(member);
		ScheduleUpdateStatementBatch sh1 = new ScheduleUpdateStatementBatch();
		String sch = '0 0 0 * * ?'; 
		system.schedule('Test Schedule USB', sch, sh1); 
		Test.stopTest(); 
	}

	/**
	* @Description : test method for dues in DataTableHelper
	*/
	@isTest
	static void DataTableHelperTest1(){
		Member_Dues__c memDue = TxnTestUtility.getDue('Test statement due', 'Annual');
		Account acc = TxnTestUtility.createAccount(Utility.searchRecordType('Household','Account'));
		Contact member = TxnTestUtility.createMember(acc, 'Dependent', Utility.searchRecordType('Member','Contact'));
		List<Dues_Summary__c> dues = TxnTestUtility.getDueSummAndRelatedDues(memDue, member);
		PageReference pg = Page.DataTableHelper;
		pg.getParameters().put('FromPage', '\'Dues\'');
		pg.getParameters().put('dueId', memDue.id);
		pg.getParameters().put('billingMonth', dues[0].Billing_Period__c);
		pg.getParameters().put('dueDate', String.valueOf(dues[0].Post_Date__c));
		pg.getParameters().put('search[value]', member.Name);
		pg.getParameters().put('start', String.valueOf(0));
		pg.getParameters().put('length', String.valueOf(10));
		pg.getParameters().put('order[0][column]', '0');
		pg.getParameters().put('order[0][dir]', 'asc');
		pg.getParameters().put('columns[0][data]', 'Contact__r.Name');
		Test.setCurrentPage(pg);
		Test.startTest();
		DataTableHelper dtable = new DataTableHelper();
		dtable.processData();
		System.assert(dtable.dataTableJson!=null);
		Test.stopTest();
	}

	/**
	* @Description : test method for statements in DataTableHelper
	*/
	@isTest
	static void DataTableHelperTest2(){
		Member_Dues__c memDue = TxnTestUtility.getDue('Test statement due', 'Annual');
		Account acc = TxnTestUtility.createAccount(Utility.searchRecordType('Household','Account'));
		Contact member = TxnTestUtility.createMember(acc, 'Dependent', Utility.searchRecordType('Member','Contact'));
		Statements__c stmtSumm = TxnTestUtility.getStatementSummary(member);
		PageReference pg = Page.DataTableHelper;
		pg.getParameters().put('FromPage', '\'Statements\'');
		pg.getParameters().put('stmtId', stmtSumm.id);
		pg.getParameters().put('memTypes', member.Membership_Type__c);
		pg.getParameters().put('fromMemId', member.Customer_Id__c);
		pg.getParameters().put('toMemId', member.Customer_Id__c);
		pg.getParameters().put('start', String.valueOf(0));
		pg.getParameters().put('length', String.valueOf(10));
		pg.getParameters().put('order[0][column]', '0');
		pg.getParameters().put('order[0][dir]', 'asc');
		pg.getParameters().put('columns[0][data]', 'Member__r.Name');
		Test.setCurrentPage(pg);
		Test.startTest();
		DataTableHelper dtable = new DataTableHelper();
		dtable.processData();
		System.assert(dtable.dataTableJson!=null);
		Test.stopTest();
	}
}