src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Guest</fullName>
        <active>true</active>
        <description>Select this record type for guest accounts.</description>
        <label>Guest</label>
    </recordTypes>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <description>Select this record type for member accounts.</description>
        <label>Household</label>
    </recordTypes>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Balance__c</fullName>
        <label>Account Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Guest</fullName>
        <active>true</active>
        <description>Select this record type for guest accounts.</description>
        <label>Guest</label>
    </recordTypes>
</CustomObject>

src/objects/Guest_Pass__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Expiration__c</fullName>
        <label>Expiration</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Guest_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Guest Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Record_Type_Name__c</field>
                <operation>equals</operation>
                <value>Guest</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Guest_Passes1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member_Sponsor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Member Sponsor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Record_Type_Name__c</field>
                <operation>equals</operation>
                <value>Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Guest_Passes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start__c</fullName>
        <label>Start</label>
        <type>DateTime</type>
    </fields>
    <label>Guest Pass</label>
    <nameField>
        <displayFormat>GP-{00000}</displayFormat>
        <label>Guest Pass Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Guest Passes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GuestPassScheduleTest.cls
@isTest
public with sharing class GuestPassScheduleTest
{

    @isTest
    static void testGuestPass()
    {
        Account acc = new Account(Name='testacc',RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId());
        insert acc;
        
		Contact con = new Contact(LastName='testGuest1',AccountId=acc.id,Account_Balance__c=1.00, RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Guest').getRecordTypeId());
        insert con;
        Contact con2 = new Contact(LastName='testMember1',AccountId=acc.id,Account_Balance__c=1.00);
        insert con2;
        
        Contact con3 = new Contact(LastName='testGuest2',AccountId=acc.id,Account_Balance__c=1.00, RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Guest').getRecordTypeId());
        insert con3;
        Contact con4 = new Contact(LastName='testMember2',AccountId=acc.id,Account_Balance__c=1.00);
        insert con4;

        Guest_Pass__c guestPassActivate= new Guest_Pass__c(Guest_Name__c=con.id,
                                                            Member_Sponsor__c=con2.id,
                                                            Start__c = Date.today() - 1,
                                                            Expiration__c = Date.today() + 1);
        insert guestPassActivate;

        Guest_Pass__c guestPassExpire= new Guest_Pass__c(Guest_Name__c=con3.id,
                                                            Member_Sponsor__c=con4.id,
                                                            Start__c = Date.today() - 2,
                                                            Expiration__c = Date.today() - 1,
                                                        	Active__c = true);
        insert guestPassExpire;

        Test.startTest();
        User ftUser = UserTest.createForeTeesUser();

        System.runAs(ftUser){
			GuestPassSchedule scheduledJob = new GuestPassSchedule();
            scheduledJob.execute(null);
		}
        Test.stopTest();
    }
}