src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Default_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to store financial account on vendor invoice lines for the current vendor</description>
        <inlineHelpText>Financial Account for vendor invoice lines</inlineHelpText>
        <label>Default Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Default_Account__c.object
<CustomObject>
    <description>Contains TXN to financial Account Mapping</description>
    <fields>
        <fullName>Default_Type_Name__c</fullName>
        <label>Default Type Name</label>
        <picklist>
            <picklistValues>
                <fullName>Accounts Receivable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prepaid Deposits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accounts Receivable - Dues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Book</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accounts Payable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accounts Payable Discounts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>POS Discounts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Book - Debit Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Book - Credit Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>containing relation to financial account</description>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Default Accounts</relationshipLabel>
        <relationshipName>Txn_To_Financial_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Default Account</label>
    <nameField>
        <displayFormat>DA-{00000}</displayFormat>
        <label>Default Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DefaultAccountDomainTest.cls
/**
* @Description : test class for DefaultAccountDomain class
* @group : Financial Management
*/
@isTest
private class DefaultAccountDomainTest
{
	@isTest
	static void TestMethod1()
	{
		List<Default_Account__c> defAccList = new List<Default_Account__c>();
		Financial_Account__c finAcc = TxnTestUtility.createFinancialAccount('DefaultFinancialAccount');

		// bulk insert test
		for(Integer i=0; i<199; i++){
			Default_Account__c defAcc = new Default_Account__c(Default_Type_Name__c='Accounts Payable', Financial_Account__c = finAcc.id);
			defAccList.add(defAcc);
		}
		try{
			Test.startTest();
			Database.insert(defAccList, false);
			Test.stopTest();
		}
		catch(Exception ex)
		{
			System.assert(ex.getMessage().contains('already exist'));
		}
		List<Default_Account__c> defAccsWithAcccPay = [select id from Default_Account__c where Default_Type_Name__c='Accounts Payable'];
		System.assertEquals(1,defAccsWithAcccPay.size());

		// test single record if some records already exist
		defAccList.clear();
		defAccList.add(new Default_Account__c(Default_Type_Name__c='Accounts Payable', Financial_Account__c = finAcc.id));
		try{
			insert defAccList;
		}
		catch(Exception ex)
		{
			System.assert(ex.getMessage().contains('already exist'));
		}
	}

	/**
	* @Description : method to check DefaultAccountDomain on update
	*/
	@isTest
	static void TestMethod2()
	{
		List<Default_Account__c> defAccList = new List<Default_Account__c>();
		Financial_Account__c finAcc = TxnTestUtility.createFinancialAccount('DefaultFinancialAccount');
		Default_Account__c defAcc = new Default_Account__c(Default_Type_Name__c='Bank Account', Financial_Account__c = finAcc.id);
		insert defAcc;
		Default_Account__c defAcc1 = new Default_Account__c(Default_Type_Name__c='Accounts Payable', Financial_Account__c = finAcc.id);
		insert defAcc1;
		defAcc.Default_Type_Name__c = 'Accounts Payable';
		try{
			Test.startTest();
			update defAcc;
			Test.stopTest();
		}
		catch(Exception ex){
			System.assert(ex.getMessage().contains('already exist'));
		}
	}
}