src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Select this record type to create a vendor.</description>
        <label>Vendor</label>
    </recordTypes>
</CustomObject>

src/objects/Vendor_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Distributed__c</fullName>
        <description>to store amount that is already distributed</description>
        <label>Amount Distributed</label>
        <summarizedField>Vendor_Invoice_Line__c.Amount__c</summarizedField>
        <summaryForeignKey>Vendor_Invoice_Line__c.Vendor_Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hold_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hold Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <label>Invoice #</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Journal_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>field used for development purpose</description>
        <label>Journal Entry</label>
        <referenceTo>Financial_Journal_Entry__c</referenceTo>
        <relationshipLabel>Vendor Invoices</relationshipLabel>
        <relationshipName>Vendor_Invoices1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Post_Date__c</fullName>
        <label>Post Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Post_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <description>to fill status of post - not to be included in page layout</description>
        <label>Post Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Posted_Date__c</fullName>
        <description>Field used to show posted date on vendor invoice detail page</description>
        <formula>Post_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Posted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <formula>Post_Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Posted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Vendor, Reciprocal Club</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vendor Invoices</relationshipLabel>
        <relationshipName>Vendor_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vendor Invoice</label>
    <nameField>
        <displayFormat>VNDRINVENTR-{0000000}</displayFormat>
        <label>Vendor Invoice Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice_Line__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Post_Date__c</fullName>
        <label>Post Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Posted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoice__c</fullName>
        <label>Vendor Invoice</label>
        <referenceTo>Vendor_Invoice__c</referenceTo>
        <relationshipLabel>Vendor Invoice Lines</relationshipLabel>
        <relationshipName>Vendor_Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vendor Invoice Line</label>
    <nameField>
        <displayFormat>VNDRSTMTLNE-{0000000}</displayFormat>
        <label>Vendor Invoice Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/cmsft_vendorInvoiceTriggerSelector.cls
/**
 * @Description: selector class for Vendor Invoice object - includes query logic for vendor invoice
 * @Date: 16th May - 2017
 * @group : Financial Management
 */
public class cmsft_vendorInvoiceTriggerSelector extends fflib_SObjectSelector {
 public List<Schema.SObjectField> getSObjectFieldList() {
  return new List<Schema.SObjectField> {
       Vendor_Invoice__c.Id,
                Vendor_Invoice__c.Posted__c,
                Vendor_Invoice__c.Post_Status__c,
                Vendor_Invoice__c.Hold_Status__c,
                Vendor_Invoice__c.Vendor__c,
                Vendor_Invoice__c.Invoice_Date__c,
                Vendor_Invoice__c.Post_Date__c,
                Vendor_Invoice__c.Invoice_Number__c,
                Vendor_Invoice__c.Amount__c,
                Vendor_Invoice__c.Due_Date__c,
                Vendor_Invoice__c.Name,
                Vendor_Invoice__c.Amount_Distributed__c,
                Vendor_Invoice__c.Journal_Entry__c,
                Vendor_Invoice__c.Posted_Date__c,
                Vendor_Invoice__c.Name
    };
 }

    /**
    * @Description : used to return current object
    * @return Vendor Invoice obj as SObjectType
    */
 public Schema.SObjectType getSObjectType() {
  return Vendor_Invoice__c.sObjectType;
 }

    /**
    * @Description : get all records having id in passed id set
    * @return list of query result vendor invoice records
    */
 public List<Vendor_Invoice__c> selectById(Set<ID> idSet) {
  fflib_QueryFactory contQuey = newQueryFactory(true, true, true);
        return new List<SObject> (Database.query(contQuey.setCondition('id in :idSet').toSOQL()));
 }
    

    public List<Vendor_Invoice__c> checkExistingRecord(string invoiceNumber, string vendorId) {
        assertIsAccessible();
        //query with the invoice number in database and return the result
        string query_condition = 'Invoice_Number__c =\'' + invoiceNumber + '\'';
        query_condition += ' and Vendor__c =\'' + vendorId + '\'';
        return (List<Vendor_Invoice__c>) Database.query(
                   'select id from Vendor_Invoice__c ' +
                   'where ' + query_condition  );

    }

    /**
    * @Description : get all records with passed condition
    * @return list of query result vendor invoice records
    */
 public List<Vendor_Invoice__c> selectVendorInvoicesWithPassedCondition(String queryCondition)
    {
        assertIsAccessible();
        fflib_QueryFactory contQuey = newQueryFactory(true, true, true);
        return new List<SObject> (Database.query(contQuey.setCondition(queryCondition).toSOQL()));
    }

    /**
    * @Description : get all records having id in passed venInvId list with its child vendor invoice line records
    * @return list of query result vendor invoice records with child records
    */
    public List<Vendor_Invoice__c> getVendorInvoiceWithLines(List<Id> venInvIds){
        assertIsAccessible();
        fflib_QueryFactory query = newQueryFactory(true, true, true).selectFields(new Set<String> {'Vendor__r.Name'});
        query.setCondition('Id IN :venInvIds');
        query.subselectQuery('Vendor_Invoice_Lines__r', true).selectFields(new cmsft_vendorInvoiceLineTriggerSelector().getSObjectFieldList());
        return (List<SObject>) Database.query( query.toSOQL() );
    }

    /**
    * @Description : get all vendor invoices whose amount is equal to the sum of all vendor invoice line amount
    * @return list of vendor invoices having total amount = sum of vendor invoice line
    */
    public List<Vendor_Invoice__c> getVendorInvoicesWithLinesAmountEqual(List<Id> vendInvIds, String condition)
    {
        List<Vendor_Invoice__c> vendInvList = getVendorInvoiceWithLines(vendInvIds);

        //list to be returned and filled based on the passed condition
        List<Vendor_Invoice__c> vendInvoicesList = new List<Vendor_Invoice__c>();
        
            for(Vendor_Invoice__c vendInvObj :vendInvList)
            {
                Decimal vendInvAmount = vendInvObj.Amount__c;
                Decimal vendInvLineAmount = 0;
                for(Vendor_Invoice_Line__c vendInvLineObj : vendInvObj.Vendor_Invoice_Lines__r )
                {
                    vendInvLineAmount += vendInvLineObj.Amount__c;
                }
                if(condition=='Amount Equal')
                    if(vendInvAmount==vendInvLineAmount)
                    vendInvoicesList.add(vendInvObj);
                if(condition=='Amount Not Equal')
                    if(vendInvAmount!=vendInvLineAmount)
                    vendInvoicesList.add(vendInvObj);
            }
        return vendInvoicesList;
    }
}