src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Addressee__c</fullName>
        <label>Addressee</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Use Address for Billing</description>
        <label>Billing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>The City in which the member resides</description>
        <inlineHelpText>The City in which the member resides</inlineHelpText>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Copied_From_Dependent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Copied From Dependent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Select country of which address belongs</description>
        <inlineHelpText>Select country of which address belongs</inlineHelpText>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>United States</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bouvet Island</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the link to the Customer that resides at this address.</description>
        <inlineHelpText>This is the link to the Customer that resides at this address.</inlineHelpText>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Text field provided to tell users how member uses the address. (i.e Summer Home)</description>
        <inlineHelpText>Text field provided to tell users how member uses the address. (i.e Summer Home)</inlineHelpText>
        <label>Notes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <description>This is the start date that the member uses this address.</description>
        <inlineHelpText>This is the start date that the member uses this address.</inlineHelpText>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MonthDayActive__c</fullName>
        <formula>IF(
  IF(To_Days_Remaining__c &gt; From_Days_Remaining__c,
    OR(Current_Days_Remaining__c &lt;= From_Days_Remaining__c, Current_Days_Remaining__c &gt;= To_Days_Remaining__c),
    IF(To_Days_Remaining__c &lt; From_Days_Remaining__c,
      AND(From_Days_Remaining__c &gt;= Current_Days_Remaining__c, Current_Days_Remaining__c&gt;=To_Days_Remaining__c
      ),
      IF(To_Days_Remaining__c = From_Days_Remaining__c,
        AND(From_Days_Remaining__c = Current_Days_Remaining__c
        ),false
      )
    )
),
true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Newsletter__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Addressed used to mail Newsletter</description>
        <label>Newsletter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Roster__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Use Address for Member Roster</description>
        <label>Roster</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <description>This field is the State or Province of the address.</description>
        <inlineHelpText>This field is the State or Province of the address.</inlineHelpText>
        <label>State/Province</label>
        <picklist>
            <picklistValues>
                <fullName>AB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street_1__c</fullName>
        <description>This field is the first line of the street address. Use for single line street addresses or multiple line street addresses.</description>
        <inlineHelpText>This field is the first line of the street address. Use for single line street addresses or multiple line street addresses.</inlineHelpText>
        <label>Street 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_2__c</fullName>
        <description>This field is the first line of the street address. Use for multiple line street addresses as needed.</description>
        <inlineHelpText>This field is the first line of the street address. Use for multiple line street addresses as needed.</inlineHelpText>
        <label>Street 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_3__c</fullName>
        <description>This field is the first line of the street address. Use for multiple line street addresses as needed.</description>
        <inlineHelpText>This field is the first line of the street address. Use for multiple line street addresses as needed.</inlineHelpText>
        <label>Street 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <description>This is the end date of the date range the Member or Guest uses this address.</description>
        <inlineHelpText>This is the end date of the date range the Member or Guest uses this address.</inlineHelpText>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This field is a pick list used to designate the address as Home, Work, or Other type.</description>
        <inlineHelpText>This field is a pick list used to designate the address as Home, Work, or Other type.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Home</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Winter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Summer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Zip_Postal_Code__c</fullName>
        <description>This field is for the Zip Code or Postal Code for the address.</description>
        <inlineHelpText>This field is for the Zip Code or Postal Code for the address.</inlineHelpText>
        <label>Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/cmsft_AddressSelector.cls
/**
 * See https://github.com/financialforcedev/fflib-apex-common for more info
 *
 * Install library via
 *   https://githubsfdeploy.herokuapp.com/app/githubdeploy/financialforcedev/fflib-apex-common
 */

/**
 * Class encapsulates query logic for Address
 *
 *  https://developer.salesforce.com/page/Apex_Enterprise_Patterns_-_Selector_Layer
 *  @author Nagendra kumar 
 *  @Date March 01, 2017
 *	@Description Encapsulates all SOQL logic relating to the Address object
 *  @group Member Management
 */
public class cmsft_AddressSelector extends fflib_SObjectSelector {
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            Address__c.Id,
            Address__c.Customer__c,
            Address__c.Name,
            Address__c.Primary__c,
            Address__c.Active__c,
            Address__c.MonthDayActive__c,
            Address__c.City__c,
            Address__c.Customer__c,
            Address__c.State_Province__c,
            Address__c.Addressee__c,
            Address__c.Street_1__c,
            Address__c.Street_2__c,
            Address__c.Street_3__c,
            Address__c.Type__c,
            Address__c.Zip_Postal_Code__c,
            Address__c.Country__c,
            Address__c.From_Date__c,
            Address__c.To_Date__c,
            Address__c.Billing__c,
            Address__c.Newsletter__c,
            Address__c.Primary__c,
            Address__c.Roster__c,
            Address__c.Description__c,
            Address__c.Copied_From_Dependent__c
        };
    }

    /**
    * @description	abstract method in fflib_SObjectSelector
    * @return returns the list of fields api name
    */
    public Schema.SObjectType getSObjectType() {
        return Address__c.sObjectType;
    }

    /**
    * @description method to fetch all Adress records with passed idSet
    * @param idSet contains set of ids of which the Adress records will be fetched
    * @return returns Address as SObjectType
    */
    public List<Address__c> selectById(Set<ID> idSet) {
        return (List<Address__c>) selectSObjectsById(idSet);
    }
    
    /**
    * @description method to get contacts by passed dynamic query
    * @condition condition represents the dynamic where clause in the query 
    * @return returns list of contacts
    */
    public List<Address__c> getAllAddressesWithTheDynamicCondition(String condition) {
        assertIsAccessible();

        List<String> str = new List<String> {
            getFieldListString(),
            getSObjectName(),
            condition
        };

        String query = String.format('select {0} ' + 'from {1} ' + '{2}', str);
        List<Address__c> adrList = Data.read(query, new Map<String, Object>());

        return adrList;
    }

}