src/objects/Address__c.object
<CustomObject>
    <fields>
        <fullName>Addressee__c</fullName>
        <label>Addressee</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Use Address for Billing</description>
        <label>Billing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>The City in which the member resides</description>
        <inlineHelpText>The City in which the member resides</inlineHelpText>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Select country of which address belongs</description>
        <inlineHelpText>Select country of which address belongs</inlineHelpText>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>United States</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bouvet Island</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the link to the Customer that resides at this address.</description>
        <inlineHelpText>This is the link to the Customer that resides at this address.</inlineHelpText>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <description>This is the start date that the member uses this address.</description>
        <inlineHelpText>This is the start date that the member uses this address.</inlineHelpText>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <description>This field is the State or Province of the address.</description>
        <inlineHelpText>This field is the State or Province of the address.</inlineHelpText>
        <label>State/Province</label>
        <picklist>
            <picklistValues>
                <fullName>AB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Statements__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Statements</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Street_1__c</fullName>
        <description>This field is the first line of the street address. Use for single line street addresses or multiple line street addresses.</description>
        <inlineHelpText>This field is the first line of the street address. Use for single line street addresses or multiple line street addresses.</inlineHelpText>
        <label>Street 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_2__c</fullName>
        <description>This field is the first line of the street address. Use for multiple line street addresses as needed.</description>
        <inlineHelpText>This field is the first line of the street address. Use for multiple line street addresses as needed.</inlineHelpText>
        <label>Street 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_3__c</fullName>
        <description>This field is the first line of the street address. Use for multiple line street addresses as needed.</description>
        <inlineHelpText>This field is the first line of the street address. Use for multiple line street addresses as needed.</inlineHelpText>
        <label>Street 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <description>This is the end date of the date range the Member or Guest uses this address.</description>
        <inlineHelpText>This is the end date of the date range the Member or Guest uses this address.</inlineHelpText>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This field is a pick list used to designate the address as Home, Work, or Other type.</description>
        <inlineHelpText>This field is a pick list used to designate the address as Home, Work, or Other type.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Home</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Winter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Summer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Statements__c.object
<CustomObject>
    <description>the object is used to store member statements</description>
    <fields>
        <fullName>Address__c</fullName>
        <formula>IF(ISBLANK(AddressId__c), &apos;&apos;, IF( ISBLANK( AddressId__r.Addressee__c ) ,  Member__r.Full_Member_Name__c , AddressId__r.Addressee__c)&amp;
IF( ISBLANK( AddressId__r.Street_1__c ) , &apos;&apos;, &apos; &apos; &amp; AddressId__r.Street_1__c)&amp;
IF( ISBLANK( AddressId__r.Street_2__c ) , &apos;&apos;, &apos; &apos; &amp; BR() &amp; AddressId__r.Street_2__c)&amp;
IF( ISBLANK( AddressId__r.Street_3__c ) , &apos;&apos;, &apos; &apos; &amp; AddressId__r.Street_3__c)&amp;
IF( ISBLANK( AddressId__r.City__c ) , &apos;&apos;, &apos; &apos; &amp; BR() &amp; AddressId__r.City__c )&amp;
IF( ISBLANK( TEXT(AddressId__r.State_Province__c )) , &apos;&apos;, &apos; &apos; &amp; TEXT(AddressId__r.State_Province__c))&amp;
IF( ISBLANK( TEXT(AddressId__r.Country__c  )) , &apos;&apos;, &apos; &apos; &amp; TEXT(AddressId__r.Country__c))&amp;
IF( ISBLANK( AddressId__r.Zip_Postal_Code__c ) , &apos;&apos;, &apos; &apos; &amp; AddressId__r.Zip_Postal_Code__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to store customer field of TXN in a statement line</description>
        <label>Customer</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.Record_Type_Name__c</field>
                <operation>equals</operation>
                <value>Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Statements (Customer)</relationshipLabel>
        <relationshipName>Statements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>only for member statement recordtype</description>
        <label>Member</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.Record_Type_Name__c</field>
                <operation>equals</operation>
                <value>Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Statements (Member)</relationshipLabel>
        <relationshipName>MemberStatements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Statement</label>
    <nameField>
        <displayFormat>Stmt-{0000000}</displayFormat>
        <label>Statements Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StatementsDomain.cls
/**
 * See https://github.com/financialforcedev/fflib-apex-common for more info
 *
 * Install library via 
 *   https://githubsfdeploy.herokuapp.com/app/githubdeploy/financialforcedev/fflib-apex-common
 */

/**
 * Encapsulates all behaviour logic relating to the Statements__c object
 * 
 * For more guidelines and details see 
 *   https://developer.salesforce.com/page/Apex_Enterprise_Patterns_-_Domain_Layer
 *
 **/
public class StatementsDomain extends fflib_SObjectDomain 
{
	public StatementsDomain(List<Statements__c> records) 
	{
		super(records);	
	}

	public override void onBeforeInsert()
	{
		List<Statements__c> memberStmtList = new List<Statements__c>();
		Id recTypeId = Utility.searchRecordType('Member Statement', 'Statements__c');
		for(Statements__c record : (List<Statements__c>) Records)
		{
			if(record.recordTypeId==recTypeId){
				memberStmtList.add(record);
			}
		}
		updateAddressOnMemberStatements(memberStmtList);
	}

	public override void onBeforeUpdate(map<id, SObject> existing)
	{
		List<Statements__c> memberStmtList = new List<Statements__c>();
		Id recTypeId = Utility.searchRecordType('Member Statement', 'Statements__c');
		for(Statements__c record : (List<Statements__c>) Records)
		{
			if(record.recordTypeId==recTypeId){
				memberStmtList.add(record);
			}
		}
		updateAddressOnMemberStatements(memberStmtList);
	}

	public void updateAddressOnMemberStatements(List<Statements__c> memberStatements){
		Set<Id> memberIds = new Set<Id>();
		Map<Id, List<Address__c>> mapOfMemIdAndAddresses = new Map<Id, List<Address__c>>();
		Map<Id, List<Statements__c>> mapOfMemIdAndstmt = new Map<Id, List<Statements__c>>();

		for(Statements__c memStmtObj : memberStatements){
			memberIds.add(memStmtObj.Member__c);
			if(!mapOfMemIdAndstmt.containsKey(memStmtObj.Member__c)){
				mapOfMemIdAndstmt.put(memStmtObj.Member__c, new List<Statements__c>());
			}
			mapOfMemIdAndstmt.get(memStmtObj.Member__c).add(memStmtObj);
		}

		for(Address__c addressOne :(List<Address__c>) Data.read('Select Customer__c, Type__c, Addressee__c, Street_1__c, Street_2__c, Street_3__c, To_Date__c, From_Date__c, Billing__c, Primary__c, City__c, Country__c, State_Province__c, Zip_Postal_Code__c from Address__c where Customer__c in : memberIds',
			new Map<String, object> {'memberIds' => memberIds }
			)){
			if(!mapOfMemIdAndAddresses.containsKey(addressOne.Customer__c)){
				mapOfMemIdAndAddresses.put(addressOne.Customer__c, new List<Address__c>());
			}
			mapOfMemIdAndAddresses.get(addressOne.Customer__c).add(addressOne);
		}

		for(Id memIdOne : mapOfMemIdAndAddresses.keySet()){
			List<Address__c> billingAddress = new List<Address__c>();
			List<Address__c> primaryAdresses = new List<Address__c>();
			List<Address__c> homeAddresses = new List<Address__c>();

			Address__c adressToBeAdded;

			for(Address__c addressOne : mapOfMemIdAndAddresses.get(memIdOne)){
				if(addressOne.Billing__c){
					billingAddress.add(addressOne);
				}
				if(addressOne.Primary__c){
					primaryAdresses.add(addressOne);
				}
				if(addressOne.Type__c=='Home'){
					homeAddresses.add(addressOne);
				}
			}
			if(billingAddress.size()>1){
				for(Address__c addressOne : billingAddress){
					if(addressOne.From_Date__c.month()<=Date.today().month() && addressOne.To_Date__c.month()>=Date.today().month()){
						adressToBeAdded = addressOne;
					}
					if(adressToBeAdded==null){
						continue;
					}
					else{
						break;
					}
				}
			}
			else if(billingAddress.size()==1){
				adressToBeAdded = billingAddress[0];
			}

			// if billing address can not be filled then get primary or home address
			if(adressToBeAdded==null){
				if(primaryAdresses.size()>0){
					adressToBeAdded = primaryAdresses[0];
				}
				else if(homeAddresses.size()>0){
					adressToBeAdded = homeAddresses[0];
				}
			}

			if(adressToBeAdded!=null){
				for(Statements__c stmt : mapOfMemIdAndstmt.get(memIdOne)){
					stmt.AddressId__c = adressToBeAdded.id;
				}
			}
		}
	}

	public class Constructor implements fflib_SObjectDomain.IConstructable2
	{
		public fflib_SObjectDomain construct(List<SObject> sObjectList)
		{
			return new StatementsDomain(sObjectList);
		}

		public fflib_SObjectDomain construct(List<SObject> sObjectList, SObjectType sObjectType)
		{
			return new StatementsDomain(sObjectList);
		}			
	}	
}