src/objects/AP_Aging__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>used to store last effective date of APAgingBatch</description>
    <fields>
        <fullName>Last_Run_Of_Member_Aging__c</fullName>
        <description>stores the date of the last run of the member aging batch</description>
        <label>Last Run Of Member Aging</label>
        <type>Date</type>
    </fields>
    <label>AP Aging</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Bill To Member)</relationshipLabel>
        <relationshipName>ContactBillTo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Aging_Effective_Date_Dev__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>This field is used for development purpose</description>
        <label>Last Aging Effective Date Dev</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X0_30_Days__c</fullName>
        <description>Represents current month balance</description>
        <label>0-30 Days</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X120_days__c</fullName>
        <label>120+ days</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X31_60_Days__c</fullName>
        <label>31-60 Days</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X61_90_Days__c</fullName>
        <label>61- 90 Days</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X91_120_Days__c</fullName>
        <label>91-120 Days</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <description>Select this record type for creating members.</description>
        <label>Member</label>
    </recordTypes>
</CustomObject>

src/objects/TXN__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bill_To_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Bill To Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Bill To Member)</relationshipLabel>
        <relationshipName>TransactionBillTo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related To</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6 AND 7 AND 8)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Refund</value>
            </filterItems>
            <filterItems>
                <field>TXN__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Payment</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Adjustment</value>
            </filterItems>
            <filterItems>
                <field>TXN__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Charge, Dues, Taxes, Service Charges</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Refund</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Adjustment</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Dues</value>
            </filterItems>
            <filterItems>
                <field>TXN__c.RecordTypeId</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TXN__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Deposit</fullName>
        <active>true</active>
        <label>Deposit</label>
    </recordTypes>
    <recordTypes>
        <fullName>Taxes</fullName>
        <active>true</active>
        <description>Used to store tax amounts</description>
        <label>Taxes</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ARAgingBatch.cls
global class ARAgingBatch implements Database.Batchable<sObject> {
	
	@TestVisible
	private Date effectiveDate;
	
	global ARAgingBatch(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Data.Locator('Select Id from Contact', 
			new Map<String, Object>());
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {

   		Set<Id> memberIds = new Set<Id>();
   		List<Contact> conListToBeUpdated = new List<Contact>();

   		for(sObject memObj : scope){
   			memberIds.add(memObj.id);
   		}
		Map<Id, Contact> consMap = new Map<Id, Contact>((List<Contact>)Data.read('Select Id, Last_Aging_Effective_Date_Dev__c, X0_30_Days__c, X120_days__c, X31_60_Days__c, X61_90_Days__c, X91_120_Days__c from Contact where id in :memId',
			new Map<String, Object> {'memId' => memberIds}));

		//prepare the dates
		Date days30 = effectiveDate.addDays(-30);
		Date days31 = effectiveDate.addDays(-31);
		Date days60 = effectiveDate.addDays(-60);
		Date days61 = effectiveDate.addDays(-61);
		Date days90 = effectiveDate.addDays(-90);
		Date days91 = effectiveDate.addDays(-91);
		Date days120 = effectiveDate.addDays(-120);

		Set<Id> recIds = new Set<Id> {Utility.searchRecordType('Taxes', 'TXN__c'), Utility.searchRecordType('Service Charges', 'TXN__c')};
		Map<Id, Map<String, Decimal>> contactAndAgingMap = new Map<Id, Map<String, Decimal>>();

		/**
		* @Description : sum of txns in 1st month
		*/
		for(AggregateResult month1Ag : (List<AggregateResult>) Data.read('Select SUM(Amount__c) amount, Bill_To_Member__c from TXN__c where RecordTypeId !=:depRecId AND (Date__c<=:effectiveDate OR (RecordTypeId in :recIds AND Related_To__r.Date__c<=:effectiveDate)) AND (Date__c>=:days30 OR (RecordTypeId in :recIds AND Related_To__r.Date__c>=:days30)) AND Bill_To_Member__c in :memId group by Bill_To_Member__c',
			new Map<String, Object> {'memId' => memberIds,
									 'effectiveDate' => effectiveDate,
									 'recIds' => recIds,
									 'depRecId' => Utility.searchRecordType('Deposit', 'TXN__c'),
									 'days30' => days30
			})){
			contactAndAgingMap.put((Id)month1Ag.get('Bill_To_Member__c'), new Map<String, Decimal> {'month1'=> (Decimal)month1Ag.get('amount')});
		}

		/**
		* @Description : sum of txns in 2nd month
		*/
		for(AggregateResult month2Ag : (List<AggregateResult>) Data.read('Select SUM(Amount__c) amount, Bill_To_Member__c from TXN__c where RecordTypeId !=:depRecId AND (Date__c<=:days31 OR (RecordTypeId in :recIds AND Related_To__r.Date__c<=:days31)) AND (Date__c>=:days60 OR (RecordTypeId in :recIds AND Related_To__r.Date__c>=:days60)) AND Bill_To_Member__c in :memId group by Bill_To_Member__c',
			new Map<String, Object> {'memId' => memberIds,
									 'days31' => days31,
									 'recIds' => recIds,
									 'depRecId' => Utility.searchRecordType('Deposit', 'TXN__c'),
									 'days60' => days60
			})){
			if(contactAndAgingMap.containsKey((Id)month2Ag.get('Bill_To_Member__c'))){
				contactAndAgingMap.get((Id)month2Ag.get('Bill_To_Member__c')).put('month2', (Decimal)month2Ag.get('amount'));
			}
			else{
				contactAndAgingMap.put((Id)month2Ag.get('Bill_To_Member__c'), new Map<String, Decimal> {'month2'=> (Decimal)month2Ag.get('amount')});
			}
		}

		/**
		* @Description : sum of txns in 3rd month
		*/
		for(AggregateResult month2Ag : (List<AggregateResult>) Data.read('Select SUM(Amount__c) amount, Bill_To_Member__c from TXN__c where RecordTypeId !=:depRecId AND (Date__c<=:days61 OR (RecordTypeId in :recIds AND Related_To__r.Date__c<=:days61)) AND (Date__c>=:days90 OR (RecordTypeId in :recIds AND Related_To__r.Date__c>=:days90)) AND  Bill_To_Member__c in :memId group by Bill_To_Member__c',
			new Map<String, Object> {'memId' => memberIds,
									 'days61' => days61,
									 'recIds' => recIds,
									 'depRecId' => Utility.searchRecordType('Deposit', 'TXN__c'),
									 'days90' => days90
			})){
			if(contactAndAgingMap.containsKey((Id)month2Ag.get('Bill_To_Member__c'))){
				contactAndAgingMap.get((Id)month2Ag.get('Bill_To_Member__c')).put('month3', (Decimal)month2Ag.get('amount'));
			}
			else{
				contactAndAgingMap.put((Id)month2Ag.get('Bill_To_Member__c'), new Map<String, Decimal> {'month3'=> (Decimal)month2Ag.get('amount')});
			}
		}

		/**
		* @Description : sum of txns in 4th month
		*/
		for(AggregateResult month2Ag : (List<AggregateResult>) Data.read('Select SUM(Amount__c) amount, Bill_To_Member__c from TXN__c where RecordTypeId !=:depRecId AND (Date__c<=:days91 OR (RecordTypeId in :recIds AND Related_To__r.Date__c<=:days91)) AND (Date__c>=:days120 OR (RecordTypeId in :recIds AND Related_To__r.Date__c>=:days120)) AND Bill_To_Member__c in :memId group by Bill_To_Member__c',
			new Map<String, Object> {'memId' => memberIds,
									 'days91' => days91,
									 'recIds' => recIds,
									 'depRecId' => Utility.searchRecordType('Deposit', 'TXN__c'),
									 'days120' => days120
			})){
			if(contactAndAgingMap.containsKey((Id)month2Ag.get('Bill_To_Member__c'))){
				contactAndAgingMap.get((Id)month2Ag.get('Bill_To_Member__c')).put('month4', (Decimal)month2Ag.get('amount'));
			}
			else{
				contactAndAgingMap.put((Id)month2Ag.get('Bill_To_Member__c'), new Map<String, Decimal> {'month4'=> (Decimal)month2Ag.get('amount')});
			}
		}

		/**
		* @Description : sum of txns in 5th month
		*/
		for(AggregateResult month2Ag : (List<AggregateResult>) Data.read('Select SUM(Amount__c) amount, Bill_To_Member__c from TXN__c where RecordTypeId !=:depRecId AND (Date__c<:days120 OR (RecordTypeId in :recIds AND Related_To__r.Date__c<:days120)) AND Bill_To_Member__c in :memId group by Bill_To_Member__c',
			new Map<String, Object> {'memId' => memberIds,
									 'recIds' => recIds,
									 'depRecId' => Utility.searchRecordType('Deposit', 'TXN__c'),
									 'days120' => days120
			})){
			if(contactAndAgingMap.containsKey((Id)month2Ag.get('Bill_To_Member__c'))){
				contactAndAgingMap.get((Id)month2Ag.get('Bill_To_Member__c')).put('month5', (Decimal)month2Ag.get('amount'));
			}
			else{
				contactAndAgingMap.put((Id)month2Ag.get('Bill_To_Member__c'), new Map<String, Decimal> {'month5'=> (Decimal)month2Ag.get('amount')});
			}
		}

		for(Id memberIdOne : consMap.keySet()){
			Contact member = consMap.get(memberIdOne);
			member.Last_Aging_Effective_Date_Dev__c = effectiveDate;
			member.X0_30_Days__c = 0;
			member.X31_60_Days__c = 0;
			member.X61_90_Days__c = 0;
			member.X91_120_Days__c = 0;
			member.X120_days__c = 0;
			if(contactAndAgingMap.containsKey(memberIdOne)){
				if(contactAndAgingMap.get(memberIdOne).containsKey('month1')){
					member.X0_30_Days__c = contactAndAgingMap.get(memberIdOne).get('month1');
				}
				if(contactAndAgingMap.get(memberIdOne).containsKey('month2')){
					member.X31_60_Days__c = contactAndAgingMap.get(memberIdOne).get('month2');
				}
				if(contactAndAgingMap.get(memberIdOne).containsKey('month3')){
					member.X61_90_Days__c = contactAndAgingMap.get(memberIdOne).get('month3');
				}
				if(contactAndAgingMap.get(memberIdOne).containsKey('month4')){
					member.X91_120_Days__c = contactAndAgingMap.get(memberIdOne).get('month4');
				}
				if(contactAndAgingMap.get(memberIdOne).containsKey('month5')){
					member.X120_days__c = contactAndAgingMap.get(memberIdOne).get('month5');
				}
			}
			// add to updating list
			conListToBeUpdated.add(member);
		}
		Data.modify(conListToBeUpdated);
	}
	
	global void finish(Database.BatchableContext BC) {
		AsyncApexJob a = (AsyncApexJob) Data.read('Select Id, Status, NumberOfErrors, JobItemsProcessed,TotalJobItems, CreatedBy.Email, ExtendedStatus from AsyncApexJob where Id = :jobId', new Map<String, Object> {'jobId' => BC.getJobId()}).get(0); 
		if(a.TotalJobItems != 0)
		{
			// Send an email to the Apex job's submitter notifying of job completion.                                          
			Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();         
			String[] toAddresses = new String[] {a.CreatedBy.Email};			
			mail.setToAddresses(toAddresses);
			mail.setSubject('Member Aging Batch ' + a.Status);
			if(a.NumberOfErrors>0){
				mail.setPlainTextBody('The batch Apex job processed ' + a.TotalJobItems + ' batches (' + ' items) with '+ a.NumberOfErrors 
					+' failures. \n'+a.ExtendedStatus); 
			}
			else{
				mail.setPlainTextBody('The batch Apex job processed ' + a.TotalJobItems + ' batches (' + ' items) with '+ a.NumberOfErrors 
					+' failures.');
				List<AP_Aging__c> apCust = Data.read('Select Last_Run_Of_Member_Aging__c from AP_Aging__c where Name=:recName', new Map<String, Object> {'recName' => 'Effective Date Record'});
				AP_Aging__c custToUpdate;
				if(apCust.size()>0){
					custToUpdate = apCust[0];
					custToUpdate.Last_Run_Of_Member_Aging__c = effectiveDate;
				}
				else{
					custToUpdate = new AP_Aging__c(Name='Effective Date Record', Last_Run_Of_Member_Aging__c=effectiveDate);
				}
				Data.upsurt(new List<AP_Aging__c> {custToUpdate}, Schema.AP_Aging__c.Id, new Set<String>());
			}
			Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
		}
	}
}