src/objects/Bank_Deposit__c.object
<CustomObject>
    <fields>
        <fullName>Deposit_Date__c</fullName>
        <description>This is the date the lock box check was deposited.</description>
        <inlineHelpText>This is the date the lock box check was deposited.</inlineHelpText>
        <label>Deposit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposit_Slip_Number__c</fullName>
        <description>This is the Deposit Ticket Number from the lock box deposit.</description>
        <inlineHelpText>This is the Deposit Ticket Number from the lock box deposit.</inlineHelpText>
        <label>Deposit Slip Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Bank_Account__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Bank Deposits</relationshipLabel>
        <relationshipName>Bank_Deposits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Posted</label>
        <type>Checkbox</type>
    </fields>
    <label>Bank Deposit</label>
    <nameField>
        <displayFormat>BD-{0000000}</displayFormat>
        <label>Bank Deposit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Deposits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Bill To Member)</relationshipLabel>
        <relationshipName>ContactBillTo</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Deposit_Batch_Check_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bank_Deposit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Deposit</label>
        <referenceTo>Bank_Deposit__c</referenceTo>
        <relationshipLabel>Deposit Batch Check Payments</relationshipLabel>
        <relationshipName>Deposit_Batch_Check_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Check_Date__c</fullName>
        <label>Check Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Check_Number__c</fullName>
        <label>Check Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Deposit Batch Check Payments</relationshipLabel>
        <relationshipName>Deposit_Batch_Check_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>TXN__c</referenceTo>
        <relationshipLabel>Deposit Batch Check Payments</relationshipLabel>
        <relationshipName>Deposit_Batch_Check_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deposit Batch Check Payment</label>
    <nameField>
        <displayFormat>DepBaPay-{000000}</displayFormat>
        <label>Deposit Batch Check Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deposit Batch Check Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TXN__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bill_To_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Bill To Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Bill To Member)</relationshipLabel>
        <relationshipName>TransactionBillTo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Check_Date__c</fullName>
        <label>Check Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Check_Number__c</fullName>
        <label>Check Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Member or Guest the Transaction applies to</description>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Customer)</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Debit_Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Debit Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Transactions (Debit Financial Account)</relationshipLabel>
        <relationshipName>Transactions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Transactions (Financial Account)</relationshipLabel>
        <relationshipName>Transactions3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name_on_Check__c</fullName>
        <label>Name on Check</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <description>payment type of the payment</description>
        <globalPicklist>Payment_Type</globalPicklist>
        <inlineHelpText>payment type of the payment</inlineHelpText>
        <label>Payment Type</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Posted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Statement_Description__c</fullName>
        <label>Statement Description</label>
        <type>TextArea</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Deposit</fullName>
        <active>true</active>
        <label>Deposit</label>
    </recordTypes>
    <recordTypes>
        <fullName>Payment</fullName>
        <active>true</active>
        <label>Payment</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CheckDepositeService.cls
public with sharing class CheckDepositeService {
    public CheckDepositeService(){
        
    }
    public class PaymentWrapper{
        public Integer index{get;set;}
        public Deposit_Batch_Check_Payment__c BCDP{get;set;}
        public PaymentWrapper(Integer i, Deposit_Batch_Check_Payment__c data){
            index = i;
            BCDP=data;
        }
    }
    public class PaymentWrapperToMerge{
        public Integer index{get;set;}
        public Deposit_Batch_Check_Payment__c BCDP{get;set;}
        public PaymentWrapperToMerge(Integer i, Deposit_Batch_Check_Payment__c data){
            index = i;
            BCDP=data;
        }
    }
    public Map<Integer,PaymentWrapper> addMoreRows(integer LastIndex, Map<Integer,PaymentWrapper> payList){
        lastIndex++;
        integer max=lastIndex + 10;
        for(Integer i=lastIndex;i<max;i++){
            system.debug('i am in with :'+i);
            Deposit_Batch_Check_Payment__c newObj=new Deposit_Batch_Check_Payment__c();
            payList.put(i,new CheckDepositeService.PaymentWrapper(i, newObj));
            lastIndex=i;
        }
        return payList;
    }
    public boolean PostBatch(id selectedPastBD,Map<Integer,PaymentWrapper> payList, string DebitAcc){
        Savepoint sp = Database.setSavepoint();
        List<Deposit_Batch_Check_Payment__c> updateList=new List<Deposit_Batch_Check_Payment__c>();
        List<TXN__c> addNewList=new List<TXN__c>();
        for(CheckDepositeService.PaymentWrapper p : payList.values()){
            
            if(p.BCDP.Customer__c!=null){
                if(p.BCDP.Amount__c == 0 || p.BCDP.Check_Number__c == '' ||p.BCDP.Check_Number__c == '0' ){
                    ApexPages.AddMessage(new  ApexPages.Message(ApexPages.Severity.ERROR,'Please enter valid Amount or Check number.'));
                    Database.rollback(sp);
                    return false;
                }else{
                    TXN__c txnRecord=new TXN__c ();
                    txnRecord.Amount__c=p.BCDP.Amount__c * -1;
                    txnRecord.Customer__c=p.BCDP.Customer__c;
                    txnRecord.Bill_To_Member__c = Utility.getBillToMember(new List<Id>{p.BCDP.Customer__c}).get(p.BCDP.Customer__c);
                    txnRecord.Payment_Type__c='Check';
                    txnRecord.Check_Date__c=p.BCDP.Check_Date__c;
                    txnRecord.Check_Number__c=p.BCDP.Check_Number__c;
                    txnRecord.Name_on_Check__c=p.BCDP.Customer__r.name;
                    txnRecord.Date__c=date.today();
                    txnRecord.Debit_Financial_Account__c=DebitAcc;
                    txnRecord.Statement_Description__c='check payment';
                    String PyamentRecordTypeId = Schema.SObjectType.TXN__c.getRecordTypeInfosByName().get('Payment').getRecordTypeId();
                    txnRecord.RecordTypeId=PyamentRecordTypeId;
                    addNewList.add(txnRecord);
                }
            }
        }
        data.create(addNewList);
        integer i=0;
        for(CheckDepositeService.PaymentWrapper p : payList.values()){
            if(p.BCDP.Customer__c!=null){
                if(p.BCDP.Amount__c == 0 || p.BCDP.Check_Number__c == '' ||p.BCDP.Check_Number__c == '0' ){

                }else{
                    p.BCDP.Transaction__c=addNewList[i].id;
                    i++;
                    updateList.add(p.BCDP);
                }
            }
            
        }
        data.modify(updateList);
        Bank_Deposit__c Deposit=new Bank_Deposit__c ();
        Deposit.id=selectedPastBD;
        Deposit.Posted__c=true;
        data.modify(Deposit);
        return true;
    }
    public boolean MergeBoth(id selectedPastBD, id selectedPastBDForMerge,Map<Integer,PaymentWrapperToMerge> payListToMerge){
        
        if(selectedPastBD == selectedPastBDForMerge){
            ApexPages.AddMessage(new  ApexPages.Message(ApexPages.Severity.ERROR,'You can not mearge same batch.'));
            return false;
        }
        List<Deposit_Batch_Check_Payment__c> GetLastIndex = (List<Deposit_Batch_Check_Payment__c>)Data.read(
            'Select Index__c from Deposit_Batch_Check_Payment__c where Bank_Deposit__c=:selectedPastBD order by Index__c DESC',
            new Map<String,Object> {
                'selectedPastBD' => selectedPastBD
                    }
        );
        integer LastIndex = integer.valueOf(GetLastIndex.get(0).Index__c); 
        List<Deposit_Batch_Check_Payment__c> updateList=new List<Deposit_Batch_Check_Payment__c>();      
        for(CheckDepositeService.PaymentWrapperToMerge p : payListToMerge.values()){
            p.BCDP.Bank_Deposit__c=selectedPastBD;
            p.BCDP.Index__c=++LastIndex;
            updateList.add(p.BCDP);
        }
        data.modify(updateList);
        List<Bank_Deposit__c> OldBatch= (List<Bank_Deposit__c>)Data.read('Select Id From Bank_Deposit__c Where id =:selectedPastBDForMerge',
                                                                         new Map<String,Object> {
                                                                             'selectedPastBDForMerge'=> selectedPastBDForMerge
                                                                                 }
                                                                        );
        data.remove(OldBatch);
        return true;
    }
    public boolean saveCheckDepositPayments(Bank_Deposit__c bd,List<PaymentWrapper> payListToDelete, id selectedPastBD,Map<Integer,PaymentWrapper> payList){
        if(bd.Financial_Account__c==null){
            ApexPages.AddMessage(new  ApexPages.Message(ApexPages.Severity.ERROR,'Bank account is required'));
            return false;
        }
        if(bd.Deposit_Slip_Number__c==null || bd.Deposit_Slip_Number__c==''){
            ApexPages.AddMessage(new  ApexPages.Message(ApexPages.Severity.ERROR,'Deposite slip number is required'));
            return false;
        }
        if(bd.Deposit_Date__c==null){
            ApexPages.AddMessage(new  ApexPages.Message(ApexPages.Severity.ERROR,'Deposite date required.'));
            return false;
        }
        Savepoint sp = Database.setSavepoint();
        
        List<Deposit_Batch_Check_Payment__c> dbcpList = new List<Deposit_Batch_Check_Payment__c>();
        for(CheckDepositeService.PaymentWrapper pw : payListToDelete){
            if(pw.BCDP!=null){
                dbcpList.add(pw.BCDP);
            }
        }
        data.remove(dbcpList);
        payListToDelete.clear();
        List<Deposit_Batch_Check_Payment__c> updateList=new List<Deposit_Batch_Check_Payment__c>(); 
        List<Deposit_Batch_Check_Payment__c> addNewList=new List<Deposit_Batch_Check_Payment__c>(); 
        try{
            if(selectedPastBD != null){
                data.modify(bd);
                for(CheckDepositeService.PaymentWrapper p : payList.values()){
                    
                    if(p.BCDP.Customer__c!=null){
                        if(p.BCDP.Amount__c == 0 || p.BCDP.Check_Number__c == '' ||p.BCDP.Check_Number__c == '0' ){
                            ApexPages.AddMessage(new  ApexPages.Message(ApexPages.Severity.ERROR,'Please enter valid Amount or Check number.'));
                            Database.rollback(sp);
                            return false;
                        }
                        if(p.BCDP.id==null){
                            p.BCDP.Index__c=P.Index;
                            p.BCDP.Bank_Deposit__c=bd.Id;
                            addNewList.add(p.BCDP);
                        }else{
                            updateList.add(p.BCDP);
                        }
                    }
                }
                data.create(addNewList);
                data.modify(updateList);
            }else{
                data.create(bd);
                addNewList=new List<Deposit_Batch_Check_Payment__c>(); 
                for(CheckDepositeService.PaymentWrapper p : payList.values()){
                    if(p.BCDP.Customer__c!=null){
                        if(p.BCDP.Amount__c == 0 || p.BCDP.Check_Number__c == '' ||p.BCDP.Check_Number__c == '0' ){
                            ApexPages.AddMessage(new  ApexPages.Message(ApexPages.Severity.ERROR,'Please enter valid Amount or Check number.'));
                            Database.rollback(sp);
                            return false;
                        }
                        p.BCDP.Bank_Deposit__c=bd.id;
                        p.BCDP.Index__c=P.Index;
                        addNewList.add(p.BCDP);
                    }
                }
                data.create(addNewList);
            }
        }catch(Exception e){
            ApexPages.AddMessage(new  ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage()));
            Database.rollback(sp);
            return false;
        }
        return true;
    }
}