src/objects/Bank_Deposit__c.object
<CustomObject>
    <fields>
        <fullName>Deposit_Date__c</fullName>
        <description>This is the date the lock box check was deposited.</description>
        <inlineHelpText>This is the date the lock box check was deposited.</inlineHelpText>
        <label>Deposit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposit_Slip_Number__c</fullName>
        <description>This is the Deposit Ticket Number from the lock box deposit.</description>
        <inlineHelpText>This is the Deposit Ticket Number from the lock box deposit.</inlineHelpText>
        <label>Deposit Slip Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Bank_Account__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Bank Deposits</relationshipLabel>
        <relationshipName>Bank_Deposits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Posted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <description>This is the total of the deposit from the lock box. This amount should tie to the deposit total on the bank statement.</description>
        <inlineHelpText>This is the total of the deposit from the lock box. This amount should tie to the deposit total on the bank statement.</inlineHelpText>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Bank Deposit</label>
    <nameField>
        <displayFormat>BD-{0000000}</displayFormat>
        <label>Bank Deposit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Deposits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deposit_Batch_Check_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bank_Deposit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Deposit</label>
        <referenceTo>Bank_Deposit__c</referenceTo>
        <relationshipLabel>Deposit Batch Check Payments</relationshipLabel>
        <relationshipName>Deposit_Batch_Check_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Check_Date__c</fullName>
        <label>Check Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Check_Number__c</fullName>
        <label>Check Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Deposit Batch Check Payments</relationshipLabel>
        <relationshipName>Deposit_Batch_Check_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Deposit Batch Check Payment</label>
    <nameField>
        <displayFormat>DepBaPay-{000000}</displayFormat>
        <label>Deposit Batch Check Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deposit Batch Check Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CheckDepositController.cls
public with sharing class CheckDepositController {
    public CheckDepositeService serviceImpObj;
    public Bank_Deposit__c bd{get;set;}
    public Bank_Deposit__c bdForMerge{get;set;}
    public String strGridField{get;set;}
    public Map<Integer,CheckDepositeService.PaymentWrapper> payList{get;set;}
    public Map<Integer,CheckDepositeService.PaymentWrapperToMerge> payListToMerge{get;set;}
    public List<String> autoApplyOptions{get;set;}
    public List<SelectOption> unPostedBDSO{get;set;}
    public List<SelectOption> unPostedBDSOForMerge{get;set;}
    public Map<Id,Bank_Deposit__c> unPostedBDMap{get;set;}
    public integer cObjIndex{get;set;}
    public Id selectedPastBD{get;set;}
    public Id selectedPastBDForMerge{get;set;}
    public integer lastIndex{get;set;}
    public boolean canIPost{get;set;}
    public List<CheckDepositeService.PaymentWrapper> payListToDelete{get;set;}
    
    public CheckDepositController(ApexPages.StandardController stdController) {
        canIPost=false;
        string message=''+ApexPages.CurrentPage().GetParameters().Get('message');
        if(message!=''&&message!='null'){
            ApexPages.AddMessage(new  ApexPages.Message(ApexPages.Severity.CONFIRM,message));
        }
        serviceImpObj=new CheckDepositeService();
        bd=new Bank_Deposit__c(Total__c=0.00);
        bdForMerge=new Bank_Deposit__c(Total__c=0.00);
        payList = new Map<Integer,CheckDepositeService.PaymentWrapper>();
        payListToMerge = new Map<Integer,CheckDepositeService.PaymentWrapperToMerge>();
        autoApplyOptions = new List<String>();
        for(Integer i=1;i<=10;i++){
            Deposit_Batch_Check_Payment__c newObj=new Deposit_Batch_Check_Payment__c();
            payList.put(i,new CheckDepositeService.PaymentWrapper(i, newObj));
            lastIndex=i;
        }
        unPostedBDMap = new Map<Id,Bank_Deposit__c>();
        loadPastBankDeposits();
        payListToDelete = new List<CheckDepositeService.PaymentWrapper>();
    }
    public void addMoreRows(){
        payList = serviceImpObj.addMoreRows(lastIndex, payList);       
    }
    public void makeAmountFieldBlank(){
        CheckDepositeService.PaymentWrapper PLVal = payList.get(cObjIndex);
        if(PLVal.BCDP.Amount__c>0){
            recalcTotal();
        }else{
            PLVal.BCDP.Amount__c = null;
        }
        if(PLVal.BCDP.Check_Number__c=='0'){
            PLVal.BCDP.Check_Number__c = null;
        }
        system.debug('check check :'+PLVal.BCDP.Check_Date__c);
        if(PLVal.BCDP.Check_Date__c==date.valueOf('2017-08-01 00:00:00')){
            PLVal.BCDP.Check_Date__c = null;
        }
        recalcTotal();
    }
    public void recalcTotal(){
        
        bd.Total__c = 0.00;
        integer flag=0;
        for(CheckDepositeService.PaymentWrapper pw : payList.values()){
            flag++;
            if(pw.BCDP != null){
                if(pw.BCDP.Customer__c !=null && pw.BCDP.amount__c!=null){
                    bd.Total__c+=pw.BCDP.Amount__c;
                    CheckDepositeService.PaymentWrapper PLVal = payList.get(flag);
                    if(pw.BCDP.amount__c == 0){
                        PLVal.BCDP.Amount__c = null;
                    }
                    if(pw.BCDP.Check_Number__c == '0'){
                        PLVal.BCDP.Check_Number__c = null;
                    }
                    system.debug('check check :'+pw.BCDP.Check_Date__c);
                    if(pw.BCDP.Check_Date__c==date.valueOf('2017-08-01 00:00:00')){
                        PLVal.BCDP.Check_Date__c = null;
                    }
                }
            }
        }
        
    }
    
    public void setPastBankDepsoit(){
        if(selectedPastBD != null){
            bd = unPostedBDMap.get(selectedPastBD);
            payList.clear();
            cObjIndex = null;
            loadCheckDepositPayments();
            recalcTotal();
            canIPost=true;
        }else{
            bd = new Bank_Deposit__c(Total__c=0.00);
            payList.clear();
            Integer lastIndex = 0;
            for(Integer i=lastIndex;i<10;i++){
                Deposit_Batch_Check_Payment__c newObj=new Deposit_Batch_Check_Payment__c();
                payList.put(i,new CheckDepositeService.PaymentWrapper(i,newObj));
                lastIndex=i;
            }
            recalcTotal();
            canIPost=false;
            cObjIndex = null;
        }
        payListToDelete.clear();
    }
    public void getDetailOfBatchToMerge(){
        if(selectedPastBDForMerge != null){
            bdForMerge = unPostedBDMap.get(selectedPastBDForMerge);
            payListToMerge.clear();
            loadCheckDepositPaymentsForMerge();
        }else{
            payListToMerge.clear();
        }
    }
    
    public Integer loadCheckDepositPayments(){
        //Querying associated deposit batch check payment.
        List<Deposit_Batch_Check_Payment__c> dpcpList = (List<Deposit_Batch_Check_Payment__c>)Data.read(
            'SELECT Customer__r.Name,'+Utility.getFields('Deposit_Batch_Check_Payment__c')+' FROM Deposit_Batch_Check_Payment__c where Bank_Deposit__c =:ID order By Index__c ASC',
            new Map<String,Object> {
                'ID' => bd.Id
                    }
        );
        //system.debug('i am here with data ' + dpcpList);
        //Preparing wrapper
        for(Deposit_Batch_Check_Payment__c dpcp : dpcpList){
            CheckDepositeService.PaymentWrapper p = new CheckDepositeService.PaymentWrapper(Integer.valueOf(dpcp.Index__c),dpcp);
            p.BCDP = dpcp;            
            payList.put(Integer.valueOf(dpcp.Index__c),p);
            if(dpcp.Index__c>lastIndex){
                lastIndex = Integer.valueOf(dpcp.Index__c);
            }
        }
        return lastIndex;
    }
    public void loadCheckDepositPaymentsForMerge(){
        //Querying associated deposit batch check payment.
        List<Deposit_Batch_Check_Payment__c> dpcpList = (List<Deposit_Batch_Check_Payment__c>)Data.read(
            'SELECT Customer__r.Name,'+Utility.getFields('Deposit_Batch_Check_Payment__c')+' FROM Deposit_Batch_Check_Payment__c where Bank_Deposit__c =:ID order By Index__c ASC',
            new Map<String,Object> {
                'ID' => bdForMerge.Id
                    }
        );
        //Preparing wrapper
        for(Deposit_Batch_Check_Payment__c dpcp : dpcpList){
            CheckDepositeService.PaymentWrapperToMerge p = new CheckDepositeService.PaymentWrapperToMerge(Integer.valueOf(dpcp.Index__c),dpcp);
            p.BCDP = dpcp;            
            payListToMerge.put(Integer.valueOf(dpcp.Index__c),p);
        }
    }
    
    public void loadPastBankDeposits(){
        
        if(unPostedBDSO!=null){unPostedBDSO.clear();}else{unPostedBDSO=new List<SelectOption>();}
        if(unPostedBDSOForMerge!=null){unPostedBDSOForMerge.clear();}else{unPostedBDSOForMerge=new List<SelectOption>();}
        List<Bank_Deposit__c> bdLst = [Select id,name,Total__c,Financial_Account__c,Deposit_Date__c,Deposit_Slip_Number__c,createdBy.Name from Bank_Deposit__c where Posted__c = false];
        unPostedBDSo.add(new SelectOption('','New Deposit'));
        unPostedBDSOForMerge.add(new SelectOption('','Select Deposit'));
        for(Bank_Deposit__c pastBD : bdLst){
            unPostedBDSOForMerge.add(new SelectOption(pastBD.Id,pastBD.Deposit_Slip_Number__c));
            unPostedBDSO.add(new SelectOption(pastBD.Id,pastBD.Deposit_Slip_Number__c));
            unPostedBDMap.put(pastBD.Id,pastBD);
        }
    }
    public void delMember(){
        if(cObjIndex!=null){
            payListToDelete.add(payList.get(cObjIndex));
            payList.remove(cObjIndex);
        }
        recalcTotal();
    }
    public List<CheckDepositeService.PaymentWrapper> getPayListV(){
        return payList.values();
    }
    public List<CheckDepositeService.PaymentWrapperToMerge> getpayListToMergeV(){
        return payListToMerge.values();
    }
    public pagereference PostBatch(){
        try {
            if(selectedPastBD == null){
                ApexPages.AddMessage(new  ApexPages.Message(ApexPages.Severity.ERROR,'Select batch to post.'));
                return null;
            }
            if(!serviceImpObj.saveCheckDepositPayments(bd,payListToDelete,selectedPastBD,payList)){
                return null;
            }
            if(!serviceImpObj.PostBatch(selectedPastBD,payList,bd.Financial_Account__c)){
                return null;
            }
        } catch(DMLException e) {
            return null;
        }
        
        PageReference pg;
        pg=page.CheckDepositHere;
        pg.getParameters().put('message','Batch Posted Successfully');
        pg.setRedirect(true);
        return pg;
    }
    public pagereference MergeBoth(){
        if(selectedPastBDForMerge == null || selectedPastBD == null){
            ApexPages.AddMessage(new  ApexPages.Message(ApexPages.Severity.ERROR,'Select batches to merge.'));
            return null;
        }
        if(!serviceImpObj.saveCheckDepositPayments(bd,payListToDelete,selectedPastBD,payList)){
            return null;
        }
        if(!serviceImpObj.MergeBoth(selectedPastBD,selectedPastBDForMerge,payListToMerge)){
            return null;
        }
        PageReference pg;
        pg=page.CheckDepositHere;
        pg.getParameters().put('message','Both Batches Merged Successfully');
        pg.setRedirect(true);
        return pg;
    }
    public pagereference saveCheckDepositPayments(){
        if(!serviceImpObj.saveCheckDepositPayments(bd,payListToDelete,selectedPastBD,payList)){
            return null;
        }
        
        //page reference
        PageReference pg;
        pg=page.CheckDepositHere;
        pg.getParameters().put('message','Saved Successfully');
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,'Saved Successfully'));
        pg.setRedirect(true);
        return pg;
    }
}