src/objects/Billing_Custom_Distribution__c.object
<CustomObject>
    <description>stores each custom due distributions</description>
    <fields>
        <fullName>April__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>April</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>August__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>August</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>December__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>December</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>February__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>February</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fiscal_Month__c</fullName>
        <description>Stores the fiscal month for which the distribution happend</description>
        <label>Fiscal Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>January__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>January</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>July__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>July</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>June__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>June</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>March__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>March</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>May__c</fullName>
        <label>May</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Member_Dues__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Dues</label>
        <referenceTo>Member_Dues__c</referenceTo>
        <relationshipLabel>Billing Custom Distributions</relationshipLabel>
        <relationshipName>Billing_Custom_Distributions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>November__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>November</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>October__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>October</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>September__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>September</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_distributed_amount__c</fullName>
        <formula>January__c  +  February__c  +  March__c  +  April__c  +  May__c  +  June__c  +  July__c  +  August__c  +  September__c  +  October__c  +  November__c  +  December__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total distributed amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>should store the relationship type for the current distrubtion</description>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Billing Custom Distribution</label>
    <nameField>
        <displayFormat>Dist-{0000000}</displayFormat>
        <label>Billing Custom Distribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Custom Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Member_Dues__c.object
<CustomObject>
    <description>Dues  subscription for member on different categories</description>
    <fields>
        <fullName>Auto_Apply_On_Membership_Types__c</fullName>
        <description>used for development purpose</description>
        <label>Auto Apply On Membership Types</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Default_Billing_Frequency__c</fullName>
        <description>Represents the default billing frequency to the members who have this due.</description>
        <label>Default Billing Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Annual</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Installment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quaterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One Time</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Dependent_Annual_Amount__c</fullName>
        <label>Dependent Annual Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Primary_Annual_Amount__c</fullName>
        <label>Primary Annual Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Spouse_Partner_Annual_Amount__c</fullName>
        <label>Spouse/Partner Annual Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <globalPicklist>Type</globalPicklist>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Member Dues</label>
    <nameField>
        <label>Due Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Dues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BillingTableSetupDetailController.cls
/**
* @Description : controller class for BillingCustomDistributionDetail page - to show message if the annual amount is changed and distribution is not correct.
* @Date : 2017
* @group : Financial Management
*/
public with sharing class BillingTableSetupDetailController {

	public Member_Dues__c billTableObj {get; set;}

	// boolean var to check if any membership type exist to apply yhis due on
	public boolean isMembershipTypeSel {get; set;}

	//Refer to the page if Auto_Apply_On_Membership_Types__c is empty
	public string redirectTo {get; set;}

	// if installment is selected as default frequency
	public boolean isInstalSele {get; set;}
	

	public BillingTableSetupDetailController(ApexPages.StandardController std) {
		isInstalSele = false;
		isMembershipTypeSel = true;
		billTableObj = (Member_Dues__c) std.getRecord();
		billTableObj = (Member_Dues__c) Data.read('Select Auto_Apply_On_Membership_Types__c, Primary_Annual_Amount__c, Spouse_Partner_Annual_Amount__c, Dependent_Annual_Amount__c, Default_Billing_Frequency__c From Member_Dues__c where id=:billTId', new Map<String, Object> {'billTId' => billTableObj.id}).get(0);
	}

	public void setupPage()
	{
		Integer currentFiscalMonth = [SELECT FiscalYearStartMonth FROM Organization limit 1].FiscalYearStartMonth;
		if((billTableObj.Auto_Apply_On_Membership_Types__c==null || billTableObj.Auto_Apply_On_Membership_Types__c==''))
		isMembershipTypeSel = false;
		redirectTo = '/apex/InstallmentBilling?dueId='+billTableObj.id;
		List<Billing_Custom_Distribution__c> updateDistributions = new List<Billing_Custom_Distribution__c>();

		// make isInstalSele var true if Default billing frequency is selected as installment
		List<Billing_Custom_Distribution__c> billingCusDist = new List<Billing_Custom_Distribution__c>();
		billingCusDist = Data.read('Select Fiscal_Month__c , Total_distributed_amount__c, Type__c from Billing_Custom_Distribution__c where Member_Dues__c=:billingTableId', new Map<String, Object> {'billingTableId'=> billTableObj.id});
		if(billTableObj.Default_Billing_Frequency__c!='One Time'){
			if(billingCusDist==null || billingCusDist.size()<1){
				isInstalSele = true;
			}
			else
			{
				for(Billing_Custom_Distribution__c billCusDistr :billingCusDist)
				{
					boolean makeDistributionNull = false;
					if(billCusDistr.Type__c=='Primary'){
						if(billCusDistr.Total_distributed_amount__c!=billTableObj.Primary_Annual_Amount__c){
							if(billTableObj.Primary_Annual_Amount__c==0) {
								makeDistributionNull = true;
							}
							else {
							    isInstalSele = true;
							}
						}
					}
					else if(billCusDistr.Type__c=='Spouse/Partner'){
						if(billCusDistr.Total_distributed_amount__c!=billTableObj.Spouse_Partner_Annual_Amount__c) {
							if(billTableObj.Spouse_Partner_Annual_Amount__c==0) {
								makeDistributionNull = true;
							}
							else { 
								isInstalSele = true;
							}
						}
					}
					else if(billCusDistr.Type__c=='Dependent'){
						if(billCusDistr.Total_distributed_amount__c!=billTableObj.Dependent_Annual_Amount__c) {
							if(billTableObj.Dependent_Annual_Amount__c==0) {
								makeDistributionNull = true;
							}
							else {
								isInstalSele = true;
							}
						}
					}

					if(makeDistributionNull){
						updateDistributions.add(removeDistrAmounts(billCusDistr));
					}
				}
			}
		}
		if(updateDistributions.size()>0){
			Data.modify(updateDistributions);
		}
	}

	public static Billing_Custom_Distribution__c removeDistrAmounts(Billing_Custom_Distribution__c billCusDistr)
	{
		billCusDistr.January__c = 0;
		billCusDistr.February__c = 0;
		billCusDistr.March__c = 0;
		billCusDistr.April__c = 0;
		billCusDistr.May__c = 0;
		billCusDistr.June__c = 0;
		billCusDistr.July__c = 0;
		billCusDistr.August__c = 0;
		billCusDistr.September__c = 0;
		billCusDistr.October__c = 0;
		billCusDistr.November__c = 0;
		billCusDistr.December__c = 0;
		return billCusDistr;
	}
}