src/objects/Charge_Item__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <picklist>
            <picklistValues>
                <fullName>Liquor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gratuity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miscellaneous Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <globalPicklist>SubType</globalPicklist>
        <label>SubType</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <globalPicklist>Type</globalPicklist>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Charge Item</label>
    <nameField>
        <label>Charge Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Additions__c</fullName>
        <label>Additions</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Beverage_Amount__c</fullName>
        <label>Beverage Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Beverage_Service_Charges__c</fullName>
        <label>Beverage Service Charges</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Beverage_Taxes__c</fullName>
        <label>Beverage Taxes</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Food_Amount__c</fullName>
        <label>Food Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Food_Service_Charges__c</fullName>
        <label>Food Service Charges</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Food_Taxes__c</fullName>
        <label>Food Taxes</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gratuity_Amount__c</fullName>
        <label>Gratuity Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gratuity_Service_Charges__c</fullName>
        <label>Gratuity Service Charges</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_Revenue__c</fullName>
        <label>Gross Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Liquor_Amount__c</fullName>
        <label>Liquor Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Liquor_Service_Charges__c</fullName>
        <label>Liquor Service Charges</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Liquor_Taxes__c</fullName>
        <label>Liquor Taxes</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Post_Close_Date_Time__c</fullName>
        <label>Post Close Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <label>Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Tentative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed/Posted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospective</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-opened</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Charge_Amount__c</fullName>
        <label>Total Charge Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Tax_Exempt__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if checked then none of the tax will be calculated on reservation</description>
        <label>Total Tax Exempt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Special Interest Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inter-Club Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lectures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panels</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dining</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Athletics/Squash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holiday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Happy Hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Princeton Connection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pilates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lessons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spinning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Trainer</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Line_Item__c.object
<CustomObject>
    <description>The role of this object is to include different kinds of products, services and fees for specific event. When events will get posted/closed it will generate the transactions for used resources from this object.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <formula>Qty__c *  Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Charge_Item__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Charge Item</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Charge_Item__c.isActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Charge_Item__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Charge_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <picklist>
            <picklistValues>
                <fullName>Liquor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gratuity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Labor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miscellaneous Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Original_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original_Line_Item</label>
        <referenceTo>Line_Item__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Override_Price__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this if you want to override the sales price from reservation line choice object and enter in price.</inlineHelpText>
        <label>Override Price</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reservation_line__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Reservation</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>Events</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Charge_Adjustment_Quantity__c</fullName>
        <label>Service Charge Adjustment Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Charge__c</fullName>
        <description>field contains service charge for this charge</description>
        <label>Service Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Charge_Name__c</fullName>
        <label>Service Charge Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Adjustment_Quantity__c</fullName>
        <label>Tax Adjustment Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tax_Amount__c</fullName>
        <label>Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax_Name__c</fullName>
        <label>Tax Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Exempt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tax Exempt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <formula>Amount__c   +  Tax_Amount__c +  Service_Charge__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000000}</displayFormat>
        <label>Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <recordTypes>
        <fullName>Adjustment</fullName>
        <active>true</active>
        <description>Use when creating an adjustment on your event.</description>
        <label>Adjustment</label>
    </recordTypes>
    <recordTypes>
        <fullName>Charge</fullName>
        <active>true</active>
        <description>Use when entering items you wish to charge to your event.</description>
        <label>Charge</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Revenue_Split__c.object
<CustomObject>
    <fields>
        <fullName>Charge_Item__c</fullName>
        <label>Charge Item</label>
        <referenceTo>Charge_Item__c</referenceTo>
        <relationshipLabel>Revenue Splits</relationshipLabel>
        <relationshipName>Revenue_Splits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <formula>Charge_Item__r.Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Revenue Split</label>
    <nameField>
        <displayFormat>revenuesplit-{0000000}</displayFormat>
        <label>Revenue Split Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LineItemTriggerHandler.cls
/**
 * Method to handle behavior when trigger is fired on Line_Item__c object.
 */
public class LineItemTriggerHandler {
    private static boolean run = true;

    public static void OnAfterInsert(Map<Id, Line_Item__c> records) {
        EventStatusValidation(records);
    }

    public static void OnBeforeUpdate(List<Line_Item__c> records) {
        preSetup(records,'update');
        EventStatusValidation(records);
    }

    public static void OnBeforeDelete(List<Line_Item__c> records) {
        EventStatusValidation(records);
    }

    public static void OnBeforeInsert(List<Line_Item__c> records) {
        preSetup(records,'insert');
    }
    /**
     * EventStatusValidation Verifies Status on the associated Event and determines whether changes may be made
     * to Event Charge Item records accordingly.
     * @param  records records Event Charge Items being modified.
     */
    public static void EventStatusValidation(List<Line_Item__c> records) {
        Map<Id, String> lineItemErrors = new Map<Id, String>();
        for (Line_Item__c lineItem : [SELECT Id, Reservation_Line__r.Status__c FROM Line_Item__c WHERE Id IN : records]) {
            if ('Closed/Posted'.equals(lineItem.Reservation_Line__r.Status__c)) {
                lineItemErrors.put(lineItem.Id, 'Closed/Posted');
            } else if ('Cancelled'.equals(lineItem.Reservation_Line__r.Status__c)) {
                lineItemErrors.put(lineItem.Id, 'Cancelled');
            }
        }
        for (Line_Item__c record : records) {
            if (lineItemErrors.containsKey(record.Id)) {
                if ('Closed/Posted'.equals(lineItemErrors.get(record.Id))) {
                    record.AddError('This event is Closed/Posted. If you wish to make changes, you must re-open your event.');
                } else if ('Cancelled'.equals(lineItemErrors.get(record.Id))) {
                    record.AddError('This event is Cancelled. You can no longer make changes.');
                }
            }
        }
    }
    /**
     * EventStatusValidation Verifies Status on the associated Event and determines whether changes may be made
     * to Event Charge Item records accordingly.
     * @param  records records Event Charge Items being modified.
     */
    public static void EventStatusValidation(Map<Id, Line_Item__c> records) {
        Map<Id, String> lineItemErrors = new Map<Id, String>();
        for (Line_Item__c lineItem : [SELECT Id, Reservation_Line__r.Status__c FROM Line_Item__c WHERE Id IN : records.keyset()]) {
            if ('Closed/Posted'.equals(lineItem.Reservation_Line__r.Status__c)) {
                lineItemErrors.put(lineItem.Id, 'Closed/Posted');
            } else if ('Cancelled'.equals(lineItem.Reservation_Line__r.Status__c)) {
                lineItemErrors.put(lineItem.Id, 'Cancelled');
            }
        }
        for (Line_Item__c record : records.values()) {
            if (lineItemErrors.containsKey(record.Id)) {
                if ('Closed/Posted'.equals(lineItemErrors.get(record.Id))) {
                    record.AddError('This event is Closed/Posted. If you wish to make changes, you must re-open your event.');
                } else if ('Cancelled'.equals(lineItemErrors.get(record.Id))) {
                    record.AddError('This event is Cancelled. You can no longer make changes.');
                }
            }
        }
    }

    /**
     * @description
     * Validate the price if override checkbox is ticked than price must be filled.
     * if price is not overriden than fill the price from the charge item object.
     * calculate the service tax and tax amount from the mapping based on the selected charge.
     * calculate the summary
     * @param  records records Event Charge Items being added newly.
     */
    public static void preSetup(List<Line_Item__c> records,String action) {
        Set<Id> chargeItemIds = new Set<Id>();
        Set<Id> eventIds = new Set<Id>();
        Id adjRecTypeId  = Schema.SObjectType.Line_Item__c.getRecordTypeInfosByName().get('Adjustment').getRecordTypeId();
        for (Line_Item__c record : records) {
            chargeItemIds.add(record.Charge_Item__c);
            eventIds .add(record.Reservation_line__c);
        }
        Map<Id,Event__c> eventsWithIdMap = new Map<Id,Event__c>((List<Event__c>)Data.read('SELECT Id, Total_Tax_Exempt__c FROM Event__c WHERE Id IN :eventIds', new Map<String, Object>{'eventIds' => eventIds}));
        
        Map<Id,Charge_Item__c> chargeItems = new Map<Id,Charge_Item__c>((List<Charge_Item__c>)Data.read(
                                               'SELECT Id, Price__c, Group__c, Type__c, SubType__c FROM Charge_Item__c' +
                                               ' WHERE Id in :chargeIds',
        new MAP<String, object> {
            'chargeIds' => chargeItemIds
        }));
        List<Revenue_Split__c> revSplit = (List<Revenue_Split__c>)Data.read(
                                               'SELECT Id, Charge_Item__c FROM Revenue_Split__c' ,
        new MAP<String, object> {
        });
        Set<Id> originalLIIdSet = new Set<Id>();
        Map<Id,Line_Item__c> orginalLineItemMap = null;
        for (Line_Item__c record : records) {
            if(record.Original_Line_Item__c != null) {
                originalLIIdSet.add(record.Original_Line_Item__c);
            }
        }  

        if(!originalLIIdSet.isEmpty()) {
            orginalLineItemMap = new Map<Id,Line_Item__c>((List<Line_Item__c>)Data.read('SELECT Id,Tax_Exempt__c, Amount__c from Line_Item__c where id IN: originalLIIdSet',
                                                                                            new Map<String, Object>{'originalLIIdSet' => originalLIIdSet}));            
        }       

        for (Line_Item__c record : records) 
        {
            if (record.Override_Price__c && record.Price__c == null) {                
                record.AddError('Price is mandatory if you are overriding the price.');
                continue;
            }

            if(record.Price__c == null)
            {
                record.Price__c = chargeItems.get(record.Charge_Item__c).Price__c;
            } 
            integer flag=0;
            for(Revenue_Split__c splits : revSplit){
                if(splits.Charge_Item__c == record.Charge_Item__c){
                    flag=1;
                    break;
                }
            }
            if(flag == 1 && chargeItems.get(record.Charge_Item__c).Price__c != record.Price__c){
                record.AddError('The sum of your revenue splits do not equal to  the price of your charge item. Please update your split amounts in order to save.');
                continue;
            }
            

            if(record.Group__c == null && chargeItems.get(record.Charge_Item__c).Group__c !=null)
            {
                record.Group__c = chargeItems.get(record.Charge_Item__c).Group__c;                
            }
             
            if(record.recordTypeId ==adjRecTypeId && record.Original_Line_Item__c != null) {
                if(orginalLineItemMap != null && orginalLineItemMap.get(record.Original_Line_Item__c) != null) {
                    record.Tax_Exempt__C = orginalLineItemMap.get(record.Original_Line_Item__c).Tax_Exempt__C;
                }
            }
            if(record.Qty__c == 0 && record.recordTypeId == adjRecTypeId ) {
                
                if(record.Tax_Adjustment_Quantity__c == null)  record.Tax_Adjustment_Quantity__c = 0;
                if(record.Service_Charge_Adjustment_Quantity__c == null)  record.Service_Charge_Adjustment_Quantity__c = 0;
                TaxesAndServiceCharge taxAndSCAmount = new TaxesAndServiceCharge(chargeItems.get(record.Charge_Item__c).Type__c,
                                                                                    chargeItems.get(record.Charge_Item__c).SubType__c,
                                                                                    (-1 * orginalLineItemMap.get(record.Original_Line_Item__c).Amount__c).setScale(2),
                                                                                    (record.Tax_Adjustment_Quantity__c * record.Price__c).setScale(2),
                                                                                    (record.Service_Charge_Adjustment_Quantity__c * record.Price__c).setScale(2));        
                record.Tax_Amount__c = 0.0;
                for(TaxesAndServiceCharge.Taxes TaxAmount : taxAndSCAmount.taxesList)
                {
                    record.Tax_Amount__c = record.Tax_Amount__c + TaxAmount.amount;
                    record.Tax_Name__c = TaxAmount.taxName;
                }
                record.Service_Charge__c = taxAndSCAmount.SCAmount;
                record.Service_Charge_Name__c = taxAndSCAmount.serviceCharge;
            }else {
                TaxesAndServiceCharge taxAndSCAmount = new TaxesAndServiceCharge(chargeItems.get(record.Charge_Item__c).Type__c, chargeItems.get(record.Charge_Item__c).SubType__c,(record.Qty__c * record.Price__c).setScale(2));        
                record.Tax_Amount__c = 0.0;
                for(TaxesAndServiceCharge.Taxes TaxAmount:taxAndSCAmount.taxesList)
                {
                    record.Tax_Amount__c = record.Tax_Amount__c + TaxAmount.amount;
                    record.Tax_Name__c = TaxAmount.taxName;
                }
                record.Service_Charge__c = taxAndSCAmount.SCAmount;
                record.Service_Charge_Name__c = taxAndSCAmount.serviceCharge;
            }
            if(record.Qty__c != null && record.Qty__c != 0 && record.recordTypeId ==adjRecTypeId ) {
                record.Service_Charge_Adjustment_Quantity__c = record.Qty__c;
                record.Tax_Adjustment_Quantity__c = record.Qty__c;
            }
            if(action == 'insert' && eventsWithIdMap != null && eventsWithIdMap.get(record.Reservation_line__c) != null && eventsWithIdMap.get(record.Reservation_line__c).Total_Tax_Exempt__c) {
               record.Tax_Exempt__c = eventsWithIdMap.get(record.Reservation_line__c).Total_Tax_Exempt__c;
               record.Tax_Amount__c = 0.0;
            }
            
            if(record.Tax_Exempt__c) {
                record.Tax_Amount__c = 0.0;
            }
        }
    }

    /**
     * @description
     * This method will sum of the amount of all added line items for the event.
     * @param  eevent id on which we have to store the total of all line items added.
     */
    public static void postSetup(Id eventId) {
        //Update revenue section.
        Decimal itemRevenue = 0;
        Decimal chargeAmountWithoutTaxSc = 0;
        Decimal totalChargeAmount = 0;
        Event__c event = (Event__c)Data.read(
                             'SELECT Id, Gross_Revenue__c, Revenue__c, Liquor_Amount__c, Total_Charge_Amount__c, Post_Close_Date_Time__c, Additions__c FROM Event__c' +
                             ' WHERE Id = :eventId',
        new MAP<String, object> {
            'eventId' => eventId
        }).get(0);

        List<Line_Item__c> lineItems = (List<Line_Item__c>)Data.read(
                                           'SELECT Id, Amount__c, Total_Amount__c, Tax_Amount__c, Service_Charge__c, Group__c, CreatedDate FROM Line_Item__c' +
                                           ' WHERE  Reservation_line__c =:eventId',
        new MAP<String, object> {
            'eventId' => eventId
        });

        final String NAMESPACE_PREFIX = NameSpaceUtils.getNamespaceWithPrefix();
        Map<String,Map<String,Decimal>> revenueApiNames = new Map<String,Map<String,Decimal>>{
            'Liquor'=>new Map<String,Decimal>{NAMESPACE_PREFIX+'Liquor_Amount__c'=>0,NAMESPACE_PREFIX+'Liquor_Service_Charges__c'=>0,NAMESPACE_PREFIX+'Liquor_Taxes__c'=>0},
            'Beverage'=>new Map<String,Decimal>{NAMESPACE_PREFIX+'Beverage_Amount__c'=>0,NAMESPACE_PREFIX+'Beverage_Service_Charges__c'=>0,NAMESPACE_PREFIX+'Beverage_Taxes__c'=>0},                         
            'Food'=>new Map<String,Decimal>{NAMESPACE_PREFIX+'Food_Amount__c'=>0,NAMESPACE_PREFIX+'Food_Service_Charges__c'=>0,NAMESPACE_PREFIX+'Food_Taxes__c'=>0},                
            'Gratuity'=>new Map<String,Decimal>{NAMESPACE_PREFIX+'Gratuity_Amount__c'=>0,NAMESPACE_PREFIX+'Gratuity_Service_Charges__c'=>0,NAMESPACE_PREFIX+'Gratuity_Taxes__c'=>0},
            'Labor'=>new Map<String,Decimal>{NAMESPACE_PREFIX+'Labor_Amount__c'=>0,NAMESPACE_PREFIX+'Labor_Service_Charges__c'=>0,NAMESPACE_PREFIX+'Labor_Taxes__c'=>0},
            'Miscellaneous Fees'=>new Map<String,Decimal>{NAMESPACE_PREFIX+'Miscellaneous_Fees_Amount__c'=>0,NAMESPACE_PREFIX+'Miscellaneous_Fees_Service_Charges__c'=>0,NAMESPACE_PREFIX+'Miscellaneous_Fees_Taxes__c'=>0},
            'Other'=>new Map<String,Decimal>{NAMESPACE_PREFIX+'Other_Amount__c'=>0,NAMESPACE_PREFIX+'Other_Service_Charges__c'=>0,NAMESPACE_PREFIX+'Other_Taxes__c'=>0},
            'Rental'=>new Map<String,Decimal>{NAMESPACE_PREFIX+'Rental_Amount__c'=>0,NAMESPACE_PREFIX+'Rental_Service_Charges__c'=>0,NAMESPACE_PREFIX+'Rental_Taxes__c'=>0}            
        };

        for (Line_Item__c item : lineItems) {
            if (event.Post_Close_Date_Time__c == null || item.CreatedDate < event.Post_Close_Date_Time__c) {
                itemRevenue = itemRevenue + item.Total_Amount__c;
            }

            chargeAmountWithoutTaxSc = chargeAmountWithoutTaxSc + item.Amount__c;
            totalChargeAmount = totalChargeAmount + item.Total_Amount__c;

            if(revenueApiNames.containsKey(item.Group__c))
            {
                Map<String,Decimal> groupRevenue = revenueApiNames.get(item.Group__c);
                for (String fieldName : groupRevenue.keySet())
                {
                    Decimal money = groupRevenue.get(fieldName);                    
                    if(fieldName.contains('Amount__c'))
                    {
                        money = money + item.Amount__c;                    
                    }
                    else if(fieldName.contains('Service_Charges__c') && item.Service_Charge__c!=null)
                    {
                        money = money + item.Service_Charge__c;
                    }
                    else
                    {
                        money = money + item.Tax_Amount__c;
                    }
                    groupRevenue.put(fieldName,money);
                }
                revenueApiNames.put(item.Group__c,groupRevenue);      
            }            
        }   

        for (String revenueKeys : revenueApiNames.keySet())
        {
                Map<String,Decimal> groupRevenue = revenueApiNames.get(revenueKeys);
                for (String fieldName : groupRevenue.keySet())
                {
                    Decimal money = groupRevenue.get(fieldName);                    
                    event.put(fieldName,money);
                }            
        }    
        event.Gross_Revenue__c = itemRevenue;
        event.Revenue__c = chargeAmountWithoutTaxSc;
        event.Total_Charge_Amount__c = totalChargeAmount;
        Data.modify(event);
    }
}