src/objects/Charge_Item__c.object
<CustomObject>
    <label>Charge Item</label>
    <nameField>
        <label>Charge Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Revenue_Split__c.object
<CustomObject>
    <fields>
        <fullName>Charge_Item__c</fullName>
        <label>Charge Item</label>
        <referenceTo>Charge_Item__c</referenceTo>
        <relationshipLabel>Revenue Splits</relationshipLabel>
        <relationshipName>Revenue_Splits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Split_Amount__c</fullName>
        <label>Split Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Revenue Split</label>
    <nameField>
        <displayFormat>revenuesplit-{0000000}</displayFormat>
        <label>Revenue Split Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/splitChargeItemController.cls
public with sharing class splitChargeItemController {
    public Revenue_Split__c revSplit {get; set;}
    public Charge_Item__c  chargeItem {get; set;}
    public boolean isEditBoolean{get;set;}
    public double total{get;set;}
    // service class variable
    public splitChargeItemService service;
    
    public splitChargeItemController(ApexPages.StandardController std) {
        service =new splitChargeItemService();
        revSplit = (Revenue_Split__c)std.getRecord();
        isEditBoolean=false;
        
        if(ApexPages.currentPage().getParameters().get('id')!=null){
            isEditBoolean = true;
            revSplit = service.getRevenueSplitFullRecordService(ApexPages.currentPage().getParameters().get('id'));
            chargeItem = service.getChargeItemFullRecordService(revSplit.Charge_Item__c);
            total=service.getTotalAmountSplitService(revSplit.Charge_Item__c);
        }
        else if(std.getRecord()!=null && revSplit.Charge_Item__c!=null){
            chargeItem = service.getChargeItemFullRecordService(revSplit.Charge_Item__c);
            total=service.getTotalAmountSplitService(revSplit.Charge_Item__c);
        }else if(ApexPages.currentPage().getParameters().get('sid')!=null){
            revSplit = new Revenue_Split__c(Charge_Item__c = ApexPages.currentPage().getParameters().get('sid'));
            chargeItem = service.getChargeItemFullRecordService(ApexPages.currentPage().getParameters().get('sid'));
        }
    }
    public PageReference save(){
        if(revSplit.Split_Amount__c == 0){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Split amount should be more then 0'));
            return null;
        }
        return service.saveNewService(new List<Revenue_Split__c> {revSplit}, new List<Charge_Item__c> {chargeItem},  new List<String> {'save'});
    }
    public pageReference savenew(){
        if(revSplit.Split_Amount__c == 0){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Split amount should be more then 0'));
            return null;
        }
        try{
            return service.saveNewService(new List<Revenue_Split__c> {revSplit}, new List<Charge_Item__c> {chargeItem}, new List<String> {'saveNew'});
        }
        catch(Exception ex){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,ex.getMessage()));
            return null;
        }
    }
    /**
* @Description : cancel method overriding
*/
    public PageReference cancel()
    {
        PageReference pg = new PageReference(URL.getSalesforceBaseUrl().toExternalForm() + '/'+chargeItem.id);
        pg.setRedirect(true);
        return pg;
    }
}