src/objects/Charge_Item__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Item_Code__c</fullName>
        <label>Item Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Charge Item</label>
    <nameField>
        <label>Charge Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Bill To Member)</relationshipLabel>
        <relationshipName>ContactBillTo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <globalPicklist>Status</globalPicklist>
        <label>Status</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tax_Exempt_Number__c</fullName>
        <label>Tax Exempt Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Exempt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tax Exempt?</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <description>Select this record type for creating members.</description>
        <label>Member</label>
    </recordTypes>
</CustomObject>

src/objects/TXN__c.object
<CustomObject>
    <fields>
        <fullName>Adjustment_Reason__c</fullName>
        <label>Adjustment Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bill_To_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Bill To Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Bill To Member)</relationshipLabel>
        <relationshipName>TransactionBillTo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charge_Amount_Left__c</fullName>
        <label>Charge Amount Left</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Charge_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Charge Item</label>
        <referenceTo>Charge_Item__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Member or Guest the Transaction applies to</description>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Customer)</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>GlobalSubType__c</fullName>
        <globalPicklist>SubType</globalPicklist>
        <label>SubType</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GlobalType__c</fullName>
        <globalPicklist>Type</globalPicklist>
        <label>Type</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Internal_Notes__c</fullName>
        <label>Internal Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Is_Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Item_Code__c</fullName>
        <label>Item Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related To</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6 AND 7 AND 8)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Refund</value>
            </filterItems>
            <filterItems>
                <field>TXN__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Payment</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Adjustment</value>
            </filterItems>
            <filterItems>
                <field>TXN__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Charge, Dues, Taxes, Service Charges</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Refund</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Adjustment</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Dues</value>
            </filterItems>
            <filterItems>
                <field>TXN__c.RecordTypeId</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TXN__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Charge_Name__c</fullName>
        <description>name of the service charge applied</description>
        <inlineHelpText>name of the service charge applied</inlineHelpText>
        <label>Service Charge Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Charge__c</fullName>
        <description>service charge on this transaction</description>
        <inlineHelpText>service charge on this transaction</inlineHelpText>
        <label>Service Charge</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Statement_Description__c</fullName>
        <label>Statement Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fully Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queued Retry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refunded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requesting Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unpaid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tax_Exempt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tax Exempt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tax_Name__c</fullName>
        <description>used to store name of the tax</description>
        <label>Tax Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <formula>IF(
	(RecordType.Name==&apos;Charge&apos; || RecordType.Name==&apos;Adjustment&apos; || RecordType.Name==&apos;Dues&apos;),
	ROUND(Amount__c+Service_Charge__c+Tax__c,2),
	Amount__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Adjustment</fullName>
        <active>true</active>
        <label>Adjustment</label>
    </recordTypes>
    <recordTypes>
        <fullName>Charge</fullName>
        <active>true</active>
        <label>Charge</label>
    </recordTypes>
    <recordTypes>
        <fullName>Taxes</fullName>
        <active>true</active>
        <description>Used to store tax amounts</description>
        <label>Taxes</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TxnAdjustChargeController.cls
public with sharing class TxnAdjustChargeController
{
    public String transactionId{get;set;}
    public String paymentType{get;set;}
    public Boolean isGuest{get;set;}
    public Boolean isMember{get;set;}
    public String breadCrumb{get;set;}
    public String nickName{get;set{nickName=value;}}
    public Boolean isTaxEnabled{get;set;}
    public Boolean DetailPage{get;set;}

    public String serviceChargeStatusText{get;set;}
    public String serviceChargeName{get;set;}
    private String serviceChargeAPIName{get;set;}
    public String serviceChargePercent{get;set;}
    public double serviceChargeAmount{get;set;}
    public Boolean isServiceChargeEnabled{get;set;}
    public Boolean tax_applied_on_Service_charge{get;set;}
    public String taxes_on_service_charge{get;set;}

    public Date todayDate{get;set;}
    public Boolean EditPg{get;set;}
    public Boolean EditPg1{get;set;}
    public Map<String,String> taxMap{get;set;}
    public Map<String,String> taxMapWithId{get;set;}
    public String memberId{get;set;}
    public TXN__c othCharge{get;set;}
    public List<TXN__c> othChargeRelatedTaxes{get;set;}
    public List<taxesWrapper> othChargeRelatedTaxesWrapper{get;set;}
    public String ChargeType{get;set;}
    public String ChargeSubType{get;set;}
    public String Charge_Amount{get;set;}
    public TXN__c adjustmentCharge{get;set;}
    public String adj_Amount{get;set;}

    public String charge_desc{get;set;}
    public String StatusOfStatus{get;set;}
    public String memName{get;set;}
    public String Final_Total{get;set;}

    public String ChargeId{get;set;}
    public String TxnIdForDetail{get;set;}
    public String FromLink{get;set;}
    public String currentPage{get;set;}
    public double Sub_Total{get;set;}
    public double Total{get;set;}
    public Boolean Tax_exempt{get;set;}
    public String tax_exempt_number{get;set;}
    public String TypeofContact{get;set;}
    public Contact refmem{get;set;}
    public String reference{get;set;}
    public Boolean displaylookup{get;set;}
    public String totalAdjustments{get;set;}
    public String itemCode{get;set;}

    public double Adjt_amt_detail{get;set;}

    public TxnAdjustChargeController()
    {
        ChargeId=Apexpages.currentPage().getParameters().get('ChargeId');
        adj_amount = '0.00';
		totalAdjustments = '0.00';
        transactionId='none';

        todayDate=date.Today();
        DetailPage=false;
        EditPg=true;
        EditPg1=false;
        isTaxEnabled=false;
        isServiceChargeEnabled=false;
        othCharge=new TXN__c();
        adjustmentCharge=new TXN__c();
        Sub_Total = 0;
        adjustmentCharge.Date__c = todayDate;
        Final_Total = '0.00';

        TypeofContact=Apexpages.currentPage().getParameters().get('ContactType');
        String message=''+ApexPages.CurrentPage().GetParameters().Get('message');

        if(message!='' && message!='null')
            ApexPages.AddMessage(new  ApexPages.Message(ApexPages.Severity.CONFIRM,message));
        isMember = false;
        if(TypeofContact=='member')
        {
            breadCrumb='Member Page';
            isGuest=false;
            isMember=true;
            displaylookup=false;
        }

        if(ChargeId!='' && ChargeId!=null)
        {
            DetailPage=true;
            EditPg=false;
            EditPg1=true;

            List<TXN__c> chargeDetailsList = (List<TXN__c>)Data.read(
                'SELECT ID,Name,Bill_To_Member__c,Customer__c,Tax__c,Date__c,RecordTypeId, Quantity__c, GlobalSubType__c,GlobalType__c, '+
                'Description__c,Total_Amount__c,Status__c,service_charge__c,Amount__c,Charge_Amount_Left__c, Statement_Description__c, Internal_Notes__c, Charge_Item__r.Name FROM TXN__c WHERE Id=:ChargeId',
                new Map<String, Object> {
                    'ChargeId' => ChargeId
                }
            );
            
            List<TXN__c> relatedTaxesList = (List<TXN__c>)Data.read(
            	'SELECT ID, Name, Bill_To_Member__c, Date__c, Amount__c, Service_Charge_Name__c, Tax_Name__c FROM TXN__c WHERE Related_To__c =:ChargeId AND (RecordType.Name =:taxes OR RecordType.Name =:servicecharge)',
                new Map<String, Object> {
                    'ChargeId' => ChargeId,
                     'taxes' => 'Taxes',
                    'servicecharge' => 'Service Charges'
                }
            );
            
            system.debug('*** charge details' + chargeDetailsList + ' related details' + relatedTaxesList);

            String guestIdIfAny;

            TXN__C chargeDetails = null;
            if(chargeDetailsList.size()>0)
            {
                chargeDetails=chargeDetailsList.get(0);
				othCharge = chargeDetailsList.get(0);
                if (relatedTaxesList.size()>0) {
                    othChargeRelatedTaxesWrapper = new List<taxesWrapper>();
                    for (TXN__c txn : relatedTaxesList) {
                        taxesWrapper tempWrap = new taxesWrapper();
                        tempWrap.txn = txn;
                        tempWrap.adjustment_amount = 0.00;
                        tempWrap.adjustment_quantity = 0;
                        othChargeRelatedTaxesWrapper.add(tempWrap);
                    }
                    othChargeRelatedTaxes = relatedTaxesList;
                }
              
                Id conId = String.valueOf(chargeDetails.Bill_To_Member__c);
                List<Contact> ContDetails = (List<Contact>)Data.read(
                    'SELECT ID,Name,Tax_Exempt__c,Tax_Exempt_Number__c FROM Contact WHERE Id=:conId',
                    new Map<String, Object> {
                        'conId' => conId
                    }
                );

                if(ContDetails.size()>0)
                {
                    Contact ContDetail=ContDetails.get(0);
                    memberId=String.valueOf(ContDetail.ID);
                    if(guestIdIfAny==null)
                        guestIdIfAny=String.valueOf(chargeDetailsList.get(0).Customer__c);
                    memName=String.valueOf(ContDetail.Name);
                    Tax_exempt=Boolean.valueOf(ContDetail.Tax_Exempt__c);
                    tax_exempt_number=String.valueOf(ContDetail.Tax_Exempt_Number__c);
                }
            }


            Adjt_amt_detail=0.00;

            List<TXN__c> adjustmentDetails = (List<TXN__c>)Data.read(
                    'SELECT ID,Adjustment_Reason__c,Amount__c FROM TXN__c WHERE Related_To__c=:ChargeId',
                    new Map<String, Object> {
                        'ChargeId' => ChargeId
                    }
                );

            for(TXN__c trans : adjustmentDetails)
            {
                Adjt_amt_detail += trans.Amount__c;
            }
            ChargeType=String.valueOf(chargeDetails.GlobalType__c);
            ChargeSubType=String.valueOf(chargeDetails.GlobalSubType__c);
            charge_desc=String.valueOf(chargeDetails.Description__c);
            Charge_Amount=String.valueOf(chargeDetails.Amount__c);
            StatusOfStatus=String.valueOf(chargeDetails.Status__c);
            if(chargeDetails.service_charge__c!=null)
            {
                serviceChargeAmount=double.valueOf(chargeDetails.service_charge__c);
            }
            else
            {
                serviceChargeAmount=0.00;
            }

            Sub_Total = Utility.Round2(double.valueOf(Charge_Amount)+double.valueOf(serviceChargeAmount));
            Total=double.valueOf(chargeDetails.Total_Amount__c);
            Final_Total=String.valueOf(chargeDetails.Total_Amount__c + Adjt_amt_detail);
            TxnIdForDetail=String.valueOf(chargeDetails.Id);
        }

        String fromPage=Apexpages.currentPage().getParameters().get('from');
        if((fromPage == 'MemberPage' || fromPage == null))
        {
            FromLink='/'+memberId;
            if(ChargeId!=''&&ChargeId!=null)
                currentPage='Charge Detail';
            else
                currentPage='New Charge';
        }

    }


    /*public List<aTableRow> allCharges
    {
        get{
            return new  List<aTableRow>();
        }
        private set;
    }*/

    public List<aTableAdjustment> allAdjustments
    {
        get{
            List<aTableAdjustment> tableData=new  List<aTableAdjustment>();

            List<TXN__c> transactions = (List<TXN__c>)Data.read(
                    'SELECT Id, Name, Amount__c,Date__c,Adjustment_Reason__c, Service_Charge_Name__c,Tax_Name__c, Charge_Item__r.Name FROM TXN__c WHERE Related_To__c=:ChargeId AND RecordType.Name =: adjustment',
                    new Map<String, Object> {
                        'ChargeId' => ChargeId,
                        'adjustment' => 'Adjustment'
                    }
                );

            for(TXN__c trans : transactions) 
            {
                String dateString = '';
                if (trans.Date__c != null) {
                   dateString = trans.Date__c.format();
                }
                if (trans.Charge_Item__r != null) tableData.add(new aTableAdjustment(trans.Name, trans.id,trans.Charge_Item__r.Name,String.valueOf(Round2(double.valueOf(trans.Amount__c * -1))),dateString));
            	else if (trans.Service_Charge_Name__c != '' && trans.Service_Charge_Name__c != null) tableData.add(new aTableAdjustment(trans.Name,trans.id,trans.Service_Charge_Name__c,String.valueOf(Round2(double.valueOf(trans.Amount__c * -1))),dateString));         
                else if (trans.Tax_Name__c != '' && trans.Tax_Name__c != null) tableData.add(new aTableAdjustment(trans.Name,trans.id,trans.Tax_Name__c,String.valueOf(Round2(double.valueOf(trans.Amount__c * -1))),dateString));
            }
            return tableData;
        }
        private set;
    }

    public TXN__c txn
    {
        get{
            if(txn==null)
                txn=new TXN__c();
            return txn;
        }
        set;
    }

    public double Round2(Double valuetoRound)
    {
        return Utility.Round2(valuetoRound);
    }

    public PageReference save()
    {
        Savepoint sp= Database.setSavepoint();
        txn = new TXN__c();

        if(Charge_Amount == '' || Charge_Amount == null || double.valueOf(Charge_Amount) <= 0)
        {
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR,'Error No : TxnChargesError00003, Message: Enter Positive Amount.'));
            return null;
        } else if (adj_Amount == '' || adj_Amount == null || Decimal.valueOf(adj_Amount) > 0) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR,'Error No : TxnChargesError00004, Message: Adjustment Amount must be negative.'));
            return null;
        }

       

        if(TypeofContact=='member')
        {
            txn.Bill_To_Member__c=memberId;
            txn.Customer__c=memberId;
        }

        txn.RecordTypeId=Utility.searchRecordType('Adjustment', 'TXN__c');
        txn.GlobalSubType__c=othCharge.GlobalSubType__c;
        txn.GlobalType__c=othCharge.GlobalType__c;
        txn.Item_Code__c = itemCode;
        txn.Internal_Notes__c = othCharge.Internal_Notes__c;
        txn.Statement_Description__c = othCharge.Statement_Description__c;
        txn.Quantity__c = adjustmentCharge.Quantity__c;
        txn.Related_To__c = ChargeId;

        String Txn_Id='';

        Charge_Amount = String.valueOf(ROUND2(Double.valueOf(Charge_Amount)));
        List<String> exempted=new List<String>();
       

        txn.Description__c=charge_desc;
        //txn.Status__c='Unpaid';
        txn.Amount__c=Decimal.valueOf(adj_Amount);
        txn.Date__c=adjustmentCharge.Date__c;
        txn.Charge_Item__c = othCharge.Charge_Item__c;
        txn.Customer__c = othCharge.Customer__c;
        txn.Adjustment_Reason__c = adjustmentCharge.Adjustment_Reason__c;
        txn.Is_Parent__c = true;
        
        List<TXN__c> insertTXNs = new List<TXN__c>();
        if (Math.abs(txn.Amount__c) > 0) insertTXNs.add(txn);
                
        for (taxesWrapper txnWrap : othChargeRelatedTaxesWrapper) {
            decimal unitPrice = txnWrap.txn.Amount__c / othCharge.Quantity__c ;
            //txnWrap.txn.Related_To__c = ChargeId;
            TXN__c newTXN = new TXN__c();
            newTXN.Related_To__c = ChargeId;
            newTxn.Bill_To_Member__c=memberId;
            newTXN.RecordTypeId = txn.RecordTypeId;
            //newTXN.Amount__c = -Math.abs(txnWrap.txn.Amount__c);
            system.debug('*** adj amount: ' + txnWrap.adjustment_quantity + ' unitPrice:' + unitPrice);
            newTXN.Amount__c = -Math.abs((txnWrap.adjustment_quantity * unitPrice));
            newTXN.Date__c = adjustmentCharge.Date__c;
            newTXN.Service_Charge_Name__c = txnWrap.txn.Service_Charge_Name__c;
            newTXN.Tax_Name__c = txnWrap.txn.Tax_Name__c;
            newTXN.Customer__c = txn.Customer__c;
            newTxn.Is_Parent__c = false;
            if (Math.abs(newTXN.Amount__c) > 0) insertTXNs.add(newTXN);
        }
        upsert(insertTXNs);

        String latest_charge_id=txn.id;
        double Final_total=Round2(double.valueOf(Charge_Amount)); //+SC_amt);
        double guestFinal_total=Final_total;

        Txn_Id=txn.Id;

        
        isServiceChargeEnabled=false;
        isTaxEnabled=false;
        PageReference reRend;

        if(nickName=='save')
        {
            reRend=new PageReference('/'+memberId);
            reRend.setRedirect(true);
            return reRend;
        }

        return reRend;
    }

    public class aTableAdjustment
    {
        public String Name {get;set;}
        public String ID {get;set;}
        public String Amount{get;set;}
        public String Dt{get;set;}
        public String Reason{get;set;}
        public aTableAdjustment(String recName, String recID, String txnReason,String txnAmt,String txnDt)
        {
            Name = recName;
            Id = recID;
            Reason=txnReason;
            Amount=txnAmt;
            Dt=txnDt;

        }
    }
    public class taxesWrapper {
        public TXN__c txn {get;set;}
        public double adjustment_amount {get;set;}
        public integer adjustment_quantity {get;set;}
    }
}