src/objects/Charge_Item__c.object
<CustomObject>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Charge Items (Financial Account)</relationshipLabel>
        <relationshipName>Reservation_Line_Choices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <globalPicklist>SubType</globalPicklist>
        <label>SubType</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <globalPicklist>Type</globalPicklist>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Charge Item</label>
    <nameField>
        <label>Charge Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Asset</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Income</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expense</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Administrative &amp; General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aquatic Sports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clubhouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Common Area Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facility Maintenance &amp; Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fitness/Spa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Charges &amp; Income Taxes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Golf Course maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Golf Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Golf Shop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housekeeping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Locker Rooms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing &amp; Membership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Allocated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Operating Departments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overnight Rooms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payroll Taxes &amp; Employee Benefits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Racquet Shop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Racquet Sports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rentals &amp; Other Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special-purpose Funds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Club Rooms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Club Rooms (HSKP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gift Shop</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Revenue_Split__c.object
<CustomObject>
    <fields>
        <fullName>Charge_Item__c</fullName>
        <label>Charge Item</label>
        <referenceTo>Charge_Item__c</referenceTo>
        <relationshipLabel>Revenue Splits</relationshipLabel>
        <relationshipName>Revenue_Splits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Revenue Splits</relationshipLabel>
        <relationshipName>Revenue_Splits</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <formula>Charge_Item__r.Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Split_Amount__c</fullName>
        <label>Split Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Revenue Split</label>
    <nameField>
        <displayFormat>revenuesplit-{0000000}</displayFormat>
        <label>Revenue Split Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TxnChargeToTaxMapping__c.object
<CustomObject>
    <description>This object contains the mapping records for Type and Subtype and their taxes and service charges.</description>
    <fields>
        <fullName>Allow_in_POS__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Allow in POS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Charge_applicable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if service charge is applicable then true.</description>
        <label>Service _Charge_applicable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subtype__c</fullName>
        <description>global subtype picklist value</description>
        <globalPicklist>SubType</globalPicklist>
        <label>Subtype</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Taxes_applicable_on_service_charge__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if this is checked then the selected taxes will also apply on the service charge.</description>
        <label>Taxes_applicable_on_service_charge</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>global type picklist field</description>
        <globalPicklist>Type</globalPicklist>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>TxnChargeToTaxMapping</label>
    <nameField>
        <displayFormat>ctot-{000000}</displayFormat>
        <label>TxnChargeToTaxMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TxnChargeToTaxMappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/splitChargeItemContTest.cls
@isTest
public class splitChargeItemContTest {
	@isTest
	static void splitChargeItemContTest1()
	{
		Financial_Account__c fa = new Financial_Account__c(Name='Test',Account_Number__c='asd32sd',Category__c='Liability');
        insert fa;
        
        TxnChargeToTaxMapping__c taxObj= new TxnChargeToTaxMapping__c();
        taxObj.Type__c='Breakfast';
        taxObj.Subtype__c = 'Buffet';
        taxObj.Allow_in_POS__c=true;
        taxObj.Taxes_applicable_on_service_charge__c=false;
        taxObj.Service_Charge_applicable__c=false;
        insert taxObj;
        
		Id recId = Utility.searchRecordType('Misc Charges','Charge_Item__c');

		Charge_Item__c ci = new Charge_Item__c();
		ci.Type__c = 'Breakfast';
		ci.SubType__c = 'Buffet';
		ci.RecordTypeId = recId;
		ci.Price__c = 10;
		insert ci;
        
        Test.startTest();
        Revenue_Split__c revSplit = new Revenue_Split__c();
        revSplit.Split_Amount__c=10;
        revSplit.Charge_Item__c=ci.id;
        revSplit.Financial_Account__c=fa.id;
        insert revSplit;
        ApexPages.StandardController sc = new ApexPages.StandardController(revSplit);
        splitChargeItemController scic = new splitChargeItemController(sc);
        scic.revSplit.Split_Amount__c=10;
        scic.revSplit.Financial_Account__c=fa.id;
        scic.save();
        scic.savenew();
        scic.cancel();
        
        
        ci.Price__c = 20;
        update ci;
        
        PageReference pRef = Page.CreateVendInvLine;
  		pRef.getParameters().put('id', revSplit.Id);
        Test.setCurrentPage(pRef);
        scic = new splitChargeItemController(sc);
        scic.revSplit.Financial_Account__c=fa.id;
        scic.revSplit.Split_Amount__c=0;
        try{
             scic.save(); 
        }catch(exception e){
             System.assertEquals('Split amount should be more then 0', e.getMessage());
        }
       
        scic.revSplit.Split_Amount__c=20;
        scic.save();
        scic.revSplit.Split_Amount__c=0;
        try{
             scic.savenew(); 
        }catch(exception e){
             System.assertEquals('Split amount should be more then 0', e.getMessage());
        }
        scic.revSplit.Split_Amount__c=20;
        scic.savenew();
       test.stopTest();
    }
}