src/objects/Charge_Item__c.object
<CustomObject>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Charge Items (Financial Account)</relationshipLabel>
        <relationshipName>Reservation_Line_Choices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_Split__c</fullName>
        <label>Price Split</label>
        <summarizedField>Revenue_Split__c.Split_Amount__c</summarizedField>
        <summaryForeignKey>Revenue_Split__c.Charge_Item__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Charge Item</label>
    <nameField>
        <label>Charge Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Revenue_Split__c.object
<CustomObject>
    <fields>
        <fullName>Charge_Item__c</fullName>
        <label>Charge Item</label>
        <referenceTo>Charge_Item__c</referenceTo>
        <relationshipLabel>Revenue Splits</relationshipLabel>
        <relationshipName>Revenue_Splits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Revenue Splits</relationshipLabel>
        <relationshipName>Revenue_Splits</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <formula>Charge_Item__r.Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Split_Amount__c</fullName>
        <label>Split Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Revenue Split</label>
    <nameField>
        <displayFormat>revenuesplit-{0000000}</displayFormat>
        <label>Revenue Split Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/splitChargeItemService.cls
public with sharing class splitChargeItemService {
    
    /**
* @Description : get revenue split complete record service with passed id
* @return : returns revenue split object after querying
*/
    public Revenue_Split__c  getRevenueSplitFullRecordService(string recId){
        return (Revenue_Split__c)Data.read(
            'Select Name,Charge_Item__c, Financial_Account__c ,Split_Amount__c  from Revenue_Split__c where Id=:Value ',
            new Map<String,Object> {
                'Value'=>recId
                    }
        ).get(0); 
    }
    
    /**
* @Description : get Charge_Item__c complete record service with passed id
* @return : returns Charge_Item__c object after querying
*/
    public Charge_Item__c  getChargeItemFullRecordService(string recId){
        return (Charge_Item__c)Data.read(
            'Select Name,Price__c, Price_Split__c   from Charge_Item__c where Id=:Value ',
            new Map<String,Object> {
                'Value'=>recId
                    }
        ).get(0); 
    }
    /*
* @Description : get total split amount complete record service with passed id
* @return : returns total split object after querying
*/
    public double  getTotalAmountSplitService(string recId){
        AggregateResult[] TotalAmountQryResult = (AggregateResult[])Data.read(
            'Select sum(Price__c) total  from Revenue_Split__c where Charge_Item__c=:Value',
            new Map<String,Object> {
                'Value'=>recId
                    }
        );
        return double.valueOf(TotalAmountQryResult[0].get('total')); 
    }
    public pageReference saveNewService(List<Revenue_Split__c> revSplit, List<Charge_Item__c> chargeItem, List<string> saveOrSaveNew){
        try{
            Data.upsurt(revSplit, Revenue_Split__c.Id.getDescribe().getSObjectField(), new Set<String>());    
        }catch (Exception e){
            return null;
        }
        
        if(saveOrSaveNew.get(0)=='save')
        {
            return new PageReference('/'+chargeItem.get(0).id);
        }
        else {
            PageReference pg = page.splitChargeItem;
            pg.getParameters().put('sid', chargeItem.get(0).id);
            pg.setRedirect(true);
            return pg;
        }
    }
}