src/objects/Charge_Item__c.object
<CustomObject>
    <fields>
        <fullName>SubType__c</fullName>
        <globalPicklist>SubType</globalPicklist>
        <label>SubType</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <globalPicklist>Type</globalPicklist>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Charge Item</label>
    <nameField>
        <label>Charge Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TxnChargeToTaxMapping__c.object
<CustomObject>
    <description>This object contains the mapping records for Type and Subtype and their taxes and service charges.</description>
    <fields>
        <fullName>Subtype__c</fullName>
        <description>global subtype picklist value</description>
        <globalPicklist>SubType</globalPicklist>
        <label>Subtype</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>global type picklist field</description>
        <globalPicklist>Type</globalPicklist>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>TxnChargeToTaxMapping</label>
    <nameField>
        <displayFormat>ctot-{000000}</displayFormat>
        <label>TxnChargeToTaxMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TxnChargeToTaxMappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ChargeItemTriggerHandler.cls
public with sharing class ChargeItemTriggerHandler 
{
	public static void handleBeforeInsert(List<Charge_Item__c> newCharges)
	{
		ChargeItemTriggerHandler.checkTypeAndSubType(newCharges, 'creating');
	}

	public static void handleBeforeUpdate(List<Charge_Item__c> newCharges, Map<Id, Charge_Item__c> oldMap)
	{
		ChargeItemTriggerHandler.checkTypeAndSubType(newCharges, 'updating');
	}

	private static void checkTypeAndSubType(List<Charge_Item__c> newCharges, String callType)
	{
		List<TxnChargeToTaxMapping__c> mappings = (List<TxnChargeToTaxMapping__c>)Data.read(
            'SELECT Id, Name, Type__c, SubType__c FROM TxnChargeToTaxMapping__c ',
            new Map<String, Object> {}
        );

        for(Charge_Item__c charge : newCharges)
        {
        	if(!ChargeItemTriggerHandler.areTypeAndSubValid(charge, mappings))
        		charge.addError('Type and Subtype are not mapped. Please map the combination before '+callType+' the record');
        }
	}

	private static Boolean areTypeAndSubValid(Charge_Item__c charge, List<TxnChargeToTaxMapping__c> mappings)
	{
		for(TxnChargeToTaxMapping__c tcm : mappings)
		{
			if(tcm.Type__c == charge.Type__c)
			{
				if(charge.SubType__c == null && tcm.Subtype__c == null)
					return true; // Type matched, no Sub, so we're good
				else if(charge.SubType__c!=null && tcm.SubType__c == charge.SubType__c)
					return true; // Type matched, Subs matched, so we're good
			}
		}

		return false;
	}
}