src/objects/Charge_Item__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <globalPicklist>SubType</globalPicklist>
        <label>SubType</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <globalPicklist>Type</globalPicklist>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Charge Item</label>
    <nameField>
        <label>Charge Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Customer_Id__c</fullName>
        <label>Member Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Membership_Type__c</fullName>
        <label>Membership Type</label>
        <picklist>
            <picklistValues>
                <fullName>Legacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Athletic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Junior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <globalPicklist>Relationship</globalPicklist>
        <label>Relationship</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <globalPicklist>Status</globalPicklist>
        <label>Status</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Type 1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Employee</fullName>
        <active>true</active>
        <description>Select this record type for creating club employees.</description>
        <label>Employee</label>
    </recordTypes>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Reservations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Tentative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed/Posted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospective</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-opened</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Special Interest Groups</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inter-Club Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lectures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panels</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dining</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Athletics/Squash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holiday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Happy Hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Princeton Connection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pilates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lessons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spinning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Trainer</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Line_Item__c.object
<CustomObject>
    <description>The role of this object is to include different kinds of products, services and fees for specific event. When events will get posted/closed it will generate the transactions for used resources from this object.</description>
    <fields>
        <fullName>Charge_Item__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Charge Item</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Charge_Item__c.isActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Charge_Item__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Charge_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Employee</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items_Employee</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reservation_line__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Reservation</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>Events</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000000}</displayFormat>
        <label>Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <recordTypes>
        <fullName>Charge</fullName>
        <active>true</active>
        <description>Use when entering items you wish to charge to your event.</description>
        <label>Charge</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Line_Item_Employee__c.object
<CustomObject>
    <description>Used to associate an employee(s) to each Charge Item.</description>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Point to the employee you wish to connect to the Reservation Line Item.</description>
        <label>Employee</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Employee</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Line Item Employees</relationshipLabel>
        <relationshipName>Reservation_Line_Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>Line_Item_Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Points the employee to the desired Event Charge Item.</description>
        <label>Line Item</label>
        <referenceTo>Line_Item__c</referenceTo>
        <relationshipName>Line_Item_Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Split_Amount__c</fullName>
        <label>Split Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Line Item Employee</label>
    <nameField>
        <displayFormat>ECIE-{00000}</displayFormat>
        <label>Line Item Employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Item Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>North Campus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Campus</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Use</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Repairs</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Sport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dining</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Room</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lesson</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TxnChargeToTaxMapping__c.object
<CustomObject>
    <description>This object contains the mapping records for Type and Subtype and their taxes and service charges.</description>
    <fields>
        <fullName>Allow_in_POS__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Allow in POS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Charge_applicable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if service charge is applicable then true.</description>
        <label>Service _Charge_applicable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subtype__c</fullName>
        <description>global subtype picklist value</description>
        <globalPicklist>SubType</globalPicklist>
        <label>Subtype</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Taxes_applicable_on_service_charge__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if this is checked then the selected taxes will also apply on the service charge.</description>
        <label>Taxes_applicable_on_service_charge</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>global type picklist field</description>
        <globalPicklist>Type</globalPicklist>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>TxnChargeToTaxMapping</label>
    <nameField>
        <displayFormat>ctot-{000000}</displayFormat>
        <label>TxnChargeToTaxMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TxnChargeToTaxMappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LineItemEmployeeTriggerTest.cls
@isTest
private class LineItemEmployeeTriggerTest {
    
    private static testmethod void testAllocatingGratuities()
    {
        Location__c loc = new Location__c();
        loc.Name = 'Test Location';
        insert loc;
        
        Event__c evt = TestHandler.getEvent();

        TxnChargeToTaxMapping__c taxObj= new TxnChargeToTaxMapping__c();
        taxObj.Type__c='Cash';
        taxObj.Subtype__c = null;
        taxObj.Allow_in_POS__c=true;
        taxObj.Taxes_applicable_on_service_charge__c=false;
        taxObj.Service_Charge_applicable__c=false;
        insert taxObj;
        
        Charge_Item__c ci = new Charge_Item__c();
        ci.Name = 'Test Charge Item';
        ci.Type__c = 'Cash';
        ci.Price__c = 100;
        insert ci;
        
        Line_Item__c eci = new Line_Item__c();
        eci.Charge_Item__c = ci.id;
        eci.Qty__c = 1;
        eci.Reservation_line__c = evt.id;
        eci.Price__c = 100;
        insert eci;
        
        Line_Item_Employee__c split1 = new Line_Item_Employee__c();
        split1.Line_Item__c = eci.id;
        split1.Split_Amount__c = 50;
        insert split1;
        
        Line_Item_Employee__c split2 = new Line_Item_Employee__c();
        split2.Line_Item__c = eci.id;
        split2.Split_Amount__c = 50;
        insert split2;
        
        for(Line_Item_Employee__c lineItemEmployee:[Select id, Split_Amount__c from Line_Item_Employee__c])
        {
            system.assertequals(50,lineItemEmployee.Split_Amount__c);
        }
        
        split2.Split_Amount__c = 25;
        update split2;
    }
    
    private static testmethod void testOverAllocatingGratuities()
    {
        Location__c loc = new Location__c();
        loc.Name = 'Test Location';
        insert loc;
        
        Event__c evt = TestHandler.getEvent();

        TxnChargeToTaxMapping__c taxObj= new TxnChargeToTaxMapping__c();
        taxObj.Type__c='Cash';
        taxObj.Subtype__c = null;
        taxObj.Allow_in_POS__c=true;
        taxObj.Taxes_applicable_on_service_charge__c=false;
        taxObj.Service_Charge_applicable__c=false;
        insert taxObj;
        
        Charge_Item__c ci = new Charge_Item__c();
        ci.Name = 'Test Charge Item';
        ci.Type__c = 'Cash';
        ci.Price__c = 100;
        insert ci;
        
        Line_Item__c eci = new Line_Item__c();
        eci.Charge_Item__c = ci.id;
        eci.Qty__c = 1;
        eci.Reservation_line__c = evt.id;
        eci.Price__c = 100;
        insert eci;
        
        List<Line_Item_Employee__c> splitsToInsert = new List<Line_Item_Employee__c>();
        Line_Item_Employee__c split1 = new Line_Item_Employee__c();
        split1.Line_Item__c = eci.id;
        split1.Split_Amount__c = 50;
        splitsToInsert.add(split1);
        
        Line_Item_Employee__c split2 = new Line_Item_Employee__c();
        split2.Line_Item__c = eci.id;
        split2.Split_Amount__c = 75;
        splitsToInsert.add(split2);
        
        try{  
            insert splitsToInsert;
        }
        catch(Exception e)
        {
            Boolean expectedExceptionThrown =  e.getMessage().contains('Your split amounts are greater than your charge item total. Please update your split amount and click save.');
            System.assertEquals(expectedExceptionThrown, true);
        } 
        
    }
    
    @isTest static void TestEventUpdateOnInsert(){
        
        Id clubId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Home Club').getRecordTypeId();
        Id employeeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Employee').getRecordTypeId();
        
        User ftUser = UserTest.createForeTeesUser();
        
        System.runAs(ftUser){
            Account account = new Account(RecordTypeId = clubId, Name = 'Doe');
            insert account;
            Contact contact = new Contact(RecordTypeId = employeeId, Account = account, AccountId = account.Id, Customer_Id__c = '001',
                                          Membership_Type__c = 'Legacy', Relationship__c = 'Primary', Status__c = 'Active', 
                                          Substatus__c = 'Active', LastName = 'Doe');
            insert contact;
            Location__c location = new Location__c(Name = 'Patio');
            insert location;
            List<Event__c> events = new List<Event__c>();
            Event__c event1 = TestHandler.getEvent();
            event1.Name = 'Party';
            update event1; 
            
            Event__c event2= TestHandler.getEvent();
            event2.Name = 'Wedding';
            update event2;
            
            Event__c event3 = TestHandler.getEvent();
            event3.Name = 'Fundraiser';
            update event3;                       

            TxnChargeToTaxMapping__c taxObj= new TxnChargeToTaxMapping__c();
            taxObj.Type__c='Bar';
            taxObj.Subtype__c = null;
            taxObj.Allow_in_POS__c=true;
            taxObj.Taxes_applicable_on_service_charge__c=false;
            taxObj.Service_Charge_applicable__c=false;
            insert taxObj;
            
            List<Charge_Item__c> chargeItems = new List<Charge_Item__c>();
            Charge_Item__c chargeItem1 = new Charge_Item__c(Name = 'Cocktail', Type__c = 'Bar', Price__c = 15.00);
            Charge_Item__c chargeItem2 = new Charge_Item__c(Name = 'Beer', Type__c = 'Bar', Price__c = 15.00);
            Charge_Item__c chargeItem3 = new Charge_Item__c(Name = 'Wine', Type__c = 'Bar', Price__c = 15.00);
            chargeItems.add(chargeItem1);
            chargeItems.add(chargeItem2);
            chargeItems.add(chargeItem3);
            insert chargeItems;
            List<Line_Item__c> lineItems = new List<Line_Item__c>();
            Line_Item__c lineItem1 = new Line_Item__c(Charge_Item__c = chargeItem1.Id, Qty__c = 50, Reservation_Line__c = event1.Id);
            Line_Item__c lineItem2 = new Line_Item__c(Charge_Item__c = chargeItem2.Id, Qty__c = 100, Reservation_Line__c = event2.Id);
            Line_Item__c lineItem3 = new Line_Item__c(Charge_Item__c = chargeItem3.Id, Qty__c = 75, Reservation_Line__c = event3.Id);
            lineItems.add(lineItem1);
            lineItems.add(lineItem2);
            lineItems.add(lineItem3);
            insert lineItems;
            
            Test.startTest();
            Set<Id> lineItemEmployeeIds = new Set<Id>();
            for(Integer i = 0; i < 3; i++){
                Line_Item_Employee__c lineItemEmployee = new Line_Item_Employee__c(Employee__c = contact.Id, Line_Item__c = lineItems.get(i).Id);
                lineItemEmployeeIds.add(lineItemEmployee.Id);
            }
            Test.stopTest();
            for(Line_Item_Employee__c newLineItemEmployee: [SELECT Id, Event__c FROM Line_Item_Employee__c WHERE Id IN :lineItemEmployeeIds]){
                if(events.iterator().hasNext()){
                    System.assertEquals(events.iterator().next().Id, newLineItemEmployee.Event__c); 
                }
            } 
        }    
    }
}