src/objects/Charge_Item__c.object
<CustomObject>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Charge Items (Financial Account)</relationshipLabel>
        <relationshipName>Reservation_Line_Choices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <globalPicklist>SubType</globalPicklist>
        <label>SubType</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <globalPicklist>Type</globalPicklist>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Charge Item</label>
    <nameField>
        <label>Charge Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Default_Account__c.object
<CustomObject>
    <description>Contains TXN to financial Account Mapping</description>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>containing relation to financial account</description>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Default Accounts</relationshipLabel>
        <relationshipName>Txn_To_Financial_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Default Account</label>
    <nameField>
        <displayFormat>DA-{00000}</displayFormat>
        <label>Default Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Administrative &amp; General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aquatic Sports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clubhouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Common Area Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facility Maintenance &amp; Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fitness/Spa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Charges &amp; Income Taxes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Golf Course maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Golf Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Golf Shop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housekeeping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Locker Rooms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing &amp; Membership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Allocated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Operating Departments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overnight Rooms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payroll Taxes &amp; Employee Benefits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Racquet Shop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Racquet Sports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rentals &amp; Other Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special-purpose Funds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Club Rooms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Club Rooms (HSKP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gift Shop</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>North Campus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Campus</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Sport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dining</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Room</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lesson</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TxnChargeToTaxMapping__c.object
<CustomObject>
    <description>This object contains the mapping records for Type and Subtype and their taxes and service charges.</description>
    <fields>
        <fullName>Allow_in_POS__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Allow in POS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Charge_applicable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if service charge is applicable then true.</description>
        <label>Service _Charge_applicable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subtype__c</fullName>
        <description>global subtype picklist value</description>
        <globalPicklist>SubType</globalPicklist>
        <label>Subtype</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Taxes_applicable_on_service_charge__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if this is checked then the selected taxes will also apply on the service charge.</description>
        <label>Taxes_applicable_on_service_charge</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>global type picklist field</description>
        <globalPicklist>Type</globalPicklist>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>TxnChargeToTaxMapping</label>
    <nameField>
        <displayFormat>ctot-{000000}</displayFormat>
        <label>TxnChargeToTaxMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TxnChargeToTaxMappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/cmsft_FinancialAccountDomainTest.cls
@isTest
private class cmsft_FinancialAccountDomainTest
{
	@isTest
	static void testInsertFinancialAccount()
	{
		Financial_Account__c fa = TestHandler.getFinancialAccount(); // method does the insert
		System.assert(fa.Id != null);
	}

	@isTest
	static void testUpdateEmptyFinancialAccount()
	{
		Location__c loc= TestHandler.getLocation();// method does the insert

		Financial_Account__c faOther = TestHandler.getFinancialAccountWithChecks(loc.Id); // method does the insert
		
		Financial_Account__c fa = TestHandler.getFinancialAccount1();// method does the insert
		fa.Notes__c='Test';
		fa.Active__c = false;
		update fa;

		fa = [select Id, Name, Notes__c from Financial_Account__c where Id =: fa.Id];
		System.assert(fa.Notes__c=='Test');

		try
		{
			delete fa;
		}
		catch(Exception thisShouldFail)
		{
			fa = [select Id, Name, Notes__c from Financial_Account__c where Id =: fa.Id];
			System.assert(fa !=null);
		}
	}

	@isTest
	static void testUpdateFinancialAccountStatus()
	{
		Financial_Account__c fa = TestHandler.getFinancialAccount(); // method does the insert

		TxnChargeToTaxMapping__c taxObj= new TxnChargeToTaxMapping__c();
        taxObj.Type__c='Breakfast';
        taxObj.Subtype__c = null;
        taxObj.Allow_in_POS__c=true;
        taxObj.Taxes_applicable_on_service_charge__c=false;
        taxObj.Service_Charge_applicable__c=false;
        insert taxObj;

		Charge_Item__c item = TestHandler.getChargeItem();
		item.Financial_Account__c = fa.Id;
		insert item;

		fa.Notes__c='Test';
		fa.Active__c = false;
		
		try
		{
			update fa;
		}
		catch(Exception thisShouldFail)
		{
			fa = [select Id, Name, Notes__c from Financial_Account__c where Id =: fa.Id];
			System.assert(fa.Notes__c==null);
		}

	}

	@isTest
	static void testUpdateFinancialAccountOnDefaultAccount()
	{
		Financial_Account__c fa = TestHandler.getFinancialAccount(); // method does the insert

		Default_Account__c da = TestHandler.getDefaultAccount();
		da.Financial_Account__c = fa.Id;
		insert da;

		fa.Notes__c='Test';
		fa.Active__c = false;
		
		try
		{
			update fa;
		}
		catch(Exception thisShouldFail)
		{
			fa = [select Id, Name, Notes__c from Financial_Account__c where Id =: fa.Id];
			System.assert(fa.Notes__c==null);
		}

	}
}