src/objects/Charge_Item__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <globalPicklist>SubType</globalPicklist>
        <label>SubType</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <globalPicklist>Type</globalPicklist>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Charge Item</label>
    <nameField>
        <label>Charge Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TxnChargeToTaxMapping__c.object
<CustomObject>
    <description>This object contains the mapping records for Type and Subtype and their taxes and service charges.</description>
    <fields>
        <fullName>Allow_in_POS__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Allow in POS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Charge_applicable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if service charge is applicable then true.</description>
        <label>Service _Charge_applicable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subtype__c</fullName>
        <description>global subtype picklist value</description>
        <globalPicklist>SubType</globalPicklist>
        <label>Subtype</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Taxes_applicable_on_service_charge__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if this is checked then the selected taxes will also apply on the service charge.</description>
        <label>Taxes_applicable_on_service_charge</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>global type picklist field</description>
        <globalPicklist>Type</globalPicklist>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>TxnChargeToTaxMapping</label>
    <nameField>
        <displayFormat>ctot-{000000}</displayFormat>
        <label>TxnChargeToTaxMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TxnChargeToTaxMappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ChargeItemTriggerTest.cls
@isTest
private class ChargeItemTriggerTest
{
	@isTest
	static void testHappyPath()
	{
		TxnChargeToTaxMapping__c taxObj= new TxnChargeToTaxMapping__c();
        taxObj.Type__c='Breakfast';
        taxObj.Subtype__c = 'Buffet';
        taxObj.Allow_in_POS__c=true;
        taxObj.Taxes_applicable_on_service_charge__c=false;
        taxObj.Service_Charge_applicable__c=false;
        insert taxObj;

        Id recId = Utility.searchRecordType('Misc Charges','Charge_Item__c');

		Charge_Item__c ci = new Charge_Item__c();
		ci.Type__c = 'Breakfast';
		ci.SubType__c = 'Buffet';
		ci.RecordTypeId = recId;
		ci.Price__c = 10;
		insert ci;

		System.assert(ci.Id != null);

		ci.Price__c = 100;
		update ci;

		Charge_Item__c ci2 = [select Id, Price__c from Charge_Item__c where Id =: ci.Id];
		System.assert(ci2.Price__c == 100);
	}

	@isTest
	static void testHappyPathLarge()
	{
		TxnChargeToTaxMapping__c taxObj= new TxnChargeToTaxMapping__c();
        taxObj.Type__c='Breakfast';
        taxObj.Subtype__c = 'Buffet';
        taxObj.Allow_in_POS__c=true;
        taxObj.Taxes_applicable_on_service_charge__c=false;
        taxObj.Service_Charge_applicable__c=false;
        insert taxObj;

        Id recId = Utility.searchRecordType('Misc Charges','Charge_Item__c');

        List<Charge_Item__c> items = new List<Charge_Item__c>();
        for(Integer i=0;i<200;i++)
        {
			Charge_Item__c ci = new Charge_Item__c();
			ci.Type__c = 'Breakfast';
			ci.SubType__c = 'Buffet';
			ci.RecordTypeId = recId;
			ci.Price__c = 10;
			items.add(ci);
		}
		insert items;
	}

	@isTest
	static void testErrorPathInsert()
	{
        Id recId = Utility.searchRecordType('Misc Charges','Charge_Item__c');

		Charge_Item__c ci = new Charge_Item__c();
		ci.Type__c = 'Breakfast';
		ci.SubType__c = 'Buffet';
		ci.RecordTypeId = recId;
		ci.Price__c = 10;
		
		try
		{
			insert ci;
		}
		catch(Exception weShouldBeHere)
		{ }
		System.assert(ci.Id == null);
	}

	@isTest
	static void testErrorPathUpdate()
	{
		TxnChargeToTaxMapping__c taxObj= new TxnChargeToTaxMapping__c();
        taxObj.Type__c='Breakfast';
        taxObj.Subtype__c = 'Buffet';
        taxObj.Allow_in_POS__c=true;
        taxObj.Taxes_applicable_on_service_charge__c=false;
        taxObj.Service_Charge_applicable__c=false;
        insert taxObj;

        Id recId = Utility.searchRecordType('Misc Charges','Charge_Item__c');

		Charge_Item__c ci = new Charge_Item__c();
		ci.Type__c = 'Breakfast';
		ci.SubType__c = 'Buffet';
		ci.RecordTypeId = recId;
		ci.Price__c = 10;
		insert ci;

		System.assert(ci.Id != null);

		ci.SubType__c = 'Bad Sub';
		try
		{
			update ci;
		}
		catch(Exception weShouldBeHere)
		{ }
	}
}