src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Tax_Exempt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tax Exempt?</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Default_Account__c.object
<CustomObject>
    <description>Contains TXN to financial Account Mapping</description>
    <fields>
        <fullName>Default_Type_Name__c</fullName>
        <label>Default Type Name</label>
        <picklist>
            <picklistValues>
                <fullName>Accounts Receivable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prepaid Deposits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accounts Receivable - Dues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Book</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accounts Payable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accounts Payable Discounts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>POS Discounts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Book - Debit Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Book - Credit Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Financial_Account_Name_And_Number__c</fullName>
        <description>financial account name with number will store here</description>
        <label>Financial Account Name And Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>containing relation to financial account</description>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Default Accounts</relationshipLabel>
        <relationshipName>Txn_To_Financial_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Default Account</label>
    <nameField>
        <displayFormat>DA-{00000}</displayFormat>
        <label>Default Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Accounts</pluralLabel>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <label>Default</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <fields>
        <fullName>A_P_Trade__c</fullName>
        <defaultValue>false</defaultValue>
        <label>A/P Trade</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Asset</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Income</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expense</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceCharges__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>stored service charges</description>
    <fields>
        <fullName>Banquet_Bar_Service_Charge__c</fullName>
        <description>each item service charge for banquet bar</description>
        <label>Banquet Bar Service Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Banquet_Beverage_Service_Charge__c</fullName>
        <description>service charge on beverages each item of banquet</description>
        <label>Banquet Beverage Service Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Banquet_Fitness_Service_Charge__c</fullName>
        <label>Banquet Fitness Service Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Banquet_Food_Service_Charge__c</fullName>
        <description>food service charge on each banquet item</description>
        <label>Banquet Food Service Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Banquet_Other_Service_Charge__c</fullName>
        <label>Banquet Other Service Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Service_Charge_Guest__c</fullName>
        <description>Service Charge Guest</description>
        <inlineHelpText>Use this service charge to charge non-member events and banquets</inlineHelpText>
        <label>Service Charge Guest</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Service_Charge_Member__c</fullName>
        <description>Member Service Charge %</description>
        <label>Service Charge Member</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Service_Charge_for_food__c</fullName>
        <description>Service Charge for food</description>
        <inlineHelpText>Service Charge for food</inlineHelpText>
        <label>Service Charge for food</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Service_Charge_general__c</fullName>
        <description>Service Charge general</description>
        <inlineHelpText>Service Charge general</inlineHelpText>
        <label>Service Charge general</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <label>ServiceCharges</label>
</CustomObject>

src/objects/Tax_To_Account_Mapping__c.object
<CustomObject>
    <description>This object contains the mapping records for each tax, service charge, and use tax when they are mapped to a Financial Account.</description>
    <fields>
        <fullName>Financial_Accounts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Accounts</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Tax To Account Mappings</relationshipLabel>
        <relationshipName>Tax_To_Account_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Charge_Value__c</fullName>
        <description>Service Charge Value</description>
        <label>Service Charge Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Charge__c</fullName>
        <description>Service Charge Names</description>
        <label>Service Charge</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Value__c</fullName>
        <description>Tax Value</description>
        <label>Tax Value</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Tax To Account Mapping</label>
    <nameField>
        <displayFormat>Tax-Acc-{000000}</displayFormat>
        <label>TaxToAccountMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax To Account Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Taxes__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Liquor_Sales_Tax__c</fullName>
        <description>Sales Tax on Liquor</description>
        <label>Liquor Sales Tax</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <description>General Sales Tax</description>
        <label>Sales Tax</label>
        <precision>6</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Tax_Exempt__c</fullName>
        <description>Tax Exempt Sale</description>
        <label>Tax Exempt</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <label>Tax ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transit_Improvement_Sales_Tax__c</fullName>
        <label>Transit Improvement Sales Tax</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <label>Taxes</label>
</CustomObject>

src/objects/TXN__c.object
<CustomObject>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Transactions (Financial Account)</relationshipLabel>
        <relationshipName>Transactions3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Charge__c</fullName>
        <description>service charge on this transaction</description>
        <inlineHelpText>service charge on this transaction</inlineHelpText>
        <label>Service Charge</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax_Exempt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tax Exempt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Charge</fullName>
        <active>true</active>
        <label>Charge</label>
    </recordTypes>
    <recordTypes>
        <fullName>Credit</fullName>
        <active>true</active>
        <description>club can add manual credit to the member&apos;s account so that credit amount will be added under this record type.</description>
        <label>Credit</label>
    </recordTypes>
    <recordTypes>
        <fullName>Tax</fullName>
        <active>true</active>
        <label>Tax</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UtilityTest.cls
@isTest
private class UtilityTest {

    @isTest static void testSearchRecordType() {

        String recordTypeId = Utility.searchRecordType('Credit', 'TXN__c');
        Id recTypeId = Schema.getGlobalDescribe().get('TXN__c').getDescribe().getRecordTypeInfosByName().get('Credit').getRecordTypeId();

        System.assertEquals(recordTypeId, recTypeId);
    }

    @isTest
    static void testRound2()
    {
        Double result = Utility.Round2(Double.valueOf(2.534));
        System.assert(result == 2.53);
    }

    @isTest
    static void testGetNameOfTax()
    {
        Taxes__c settings = Taxes__c.getOrgDefaults();
        /**settings.Adjust_Taxes__c = true;
        settings.Catering_Bar_Sales_Tax_Percentage__c = .1;
        settings.Catering_Beverage_Sales_Tax_Percentage__c = .1;
        settings.Catering_Fitness_Sales_Tax_Percentage__c = .1;
        settings.Catering_Food_Sales_Tax_Percentage__c = .1;
        settings.Catering_Other_Sales_Tax_Percentage__c  = .1; **/
        settings.Liquor_Sales_Tax__c = .1;
        settings.Sales_Tax__c = .1;
        settings.Tax_Exempt__c = .1;
        settings.Tax_ID__c ='1234';
        settings.Transit_Improvement_Sales_Tax__c = .1;
        upsert settings;

        String result = Utility.getNameOfTax('Sales_Tax__c');
        System.assert(result != null);

        Decimal percent = Utility.getPercentageOfTax('Sales_Tax__c');
        System.assert(percent == .1);
    }

    @isTest
    static void testGetNameOfServiceCharge()
    {
        ServiceCharges__c settings = ServiceCharges__c.getOrgDefaults();
        settings.Banquet_Bar_Service_Charge__c = .1;
        settings.Banquet_Beverage_Service_Charge__c = .1;
        settings.Banquet_Fitness_Service_Charge__c = .1;
        settings.Banquet_Food_Service_Charge__c = .1;
        settings.Banquet_Other_Service_Charge__c = .1;
        settings.Service_Charge_for_food__c  = .1;
        settings.Service_Charge_general__c = .1;
        settings.Service_Charge_Guest__c = .1;
        settings.Service_Charge_Member__c = .1;
        upsert settings;

        String result = Utility.getNameOfServiceCharge('Service_Charge_Member__c');
        System.assert(result != null);

        Decimal percent = Utility.getPercentageOfServiceCharge('Service_Charge_Member__c');
        System.assert(percent == .1);
    }

    @isTest
    static void testGetFinancialAccountForTax()
    {
        Financial_Account__c fa = TestHandler.getFinancialAccount(); // method does the insert

        Tax_To_Account_Mapping__c tam = new Tax_To_Account_Mapping__c();
        tam.Financial_Accounts__c = fa.Id;
        tam.Service_Charge__c = 'Service Charge';
        tam.Tax__c = 'Tax';
        tam.Service_Charge_Value__c = 'Value';
        tam.Tax_Value__c = 'Value';
        insert tam;

        String fin = Utility.getFinancialAccountForTax('Service Charge', true);
        System.assert(fin == fa.Id);

        fin = Utility.getFinancialAccountForTax('Tax', false);
        System.assert(fin == fa.Id);
    }

    @isTest
    static void testGetFinancialAccountForTxnRecTypes()
    {
        Financial_Account__c fa = TestHandler.getFinancialAccount(); // method does the insert
        String defRecTypeId = Utility.searchRecordType('Default', 'Default_Account__c');
        Default_Account__c tfm2 = new Default_Account__c();
        tfm2.Financial_Account__c = fa.Id;
        tfm2.Default_Type_Name__c = 'Lunch';
        tfm2.Financial_Account_Name_And_Number__c = 'Test 2';
        tfm2.RecordTypeId = defRecTypeId;
        insert tfm2;

        String fin = Utility.getFinancialAccountForTxnRecTypes('Default', 'Lunch', 'Other');
        System.assert(fin == fa.Id);
    }

    @isTest
    static void testGetCredDebitStatus()
    {
        Financial_Account__c fa = TestHandler.getFinancialAccount(); // method does the insert

        String result = Utility.getCredDebitStatus(fa.id);
        System.assert(result == null);

        fa.Category__c = 'Asset';
        fa.A_P_Trade__c = false;
        update fa;

        result = Utility.getCredDebitStatus(fa.id);
        System.assert(result != null);

    }

    @isTest
    static void testGetFields()
    {
        String result = Utility.getFields('Contact');
        System.assert(result != null);

        result = Utility.getFields('Reservation_Registration__c');
    }
}