src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Customer_Id__c</fullName>
        <label>Member Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <description>Select this record type for creating members.</description>
        <label>Member</label>
    </recordTypes>
</CustomObject>

src/objects/Member_statement_pdf__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>spacing for member statement pdf page.</description>
    <fields>
        <fullName>total_rows_to_show__c</fullName>
        <label>total rows to show</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Member statement pdf</label>
</CustomObject>

src/objects/Statements__c.object
<CustomObject>
    <description>the object is used to store member statements</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>the field is used to store the net amount of TXN records, it is for statement line recordtype</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billing_Period__c</fullName>
        <description>the field is used to store the billing month and year for statement generation</description>
        <label>Billing Period</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to store customer field of TXN in a statement line</description>
        <label>Customer</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.Record_Type_Name__c</field>
                <operation>equals</operation>
                <value>Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Statements (Customer)</relationshipLabel>
        <relationshipName>Statements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>the field is used to store description for the statement line</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>only for member statement recordtype</description>
        <label>Member</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.Record_Type_Name__c</field>
                <operation>equals</operation>
                <value>Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Statements (Member)</relationshipLabel>
        <relationshipName>MemberStatements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Charge__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Service Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Statement_Balance__c</fullName>
        <description>the field is used to store balance of the member attached</description>
        <label>Statement Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Statement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Statement</label>
        <referenceTo>Statements__c</referenceTo>
        <relationshipLabel>Statements</relationshipLabel>
        <relationshipName>Statements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Statement</label>
    <nameField>
        <displayFormat>Stmt-{0000000}</displayFormat>
        <label>Statements Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MemberStatementPDFCont.cls
public with sharing class MemberStatementPDFCont {
     public Member_statement_pdf__c   spacing{get;set;}
    public List<Statements__c> statement{get;set;}
    public List<Statements__c> statementLines{get;set;}
    public Organization OrgDet{get;set;}
    public Map<integer,List<Statements__c>> sclns{get;set;}
    public List<integer> pages{get;set;}
    public integer totalPage{get;set;}
    public integer totalRowsToShow{get;set;}
    public MemberStatementPDFCont(){
        pages= new List<integer>();
         sclns=new Map<integer,List<Statements__c>>();
        spacing = new Member_statement_pdf__c  ();
        
        if(Member_statement_pdf__c.getall().values().size()>0){
            spacing = new Member_statement_pdf__c  ();
        	spacing = Member_statement_pdf__c.getall().values();
        }else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Please set the values for check spacing in "Member statement PDF" custom setting first.'));
        }
        totalRowsToShow=integer.valueOf(spacing.total_rows_to_show__c);
    }
    public void getprintCheckList(){
        OrgDet=[select id,name,Address, Phone,fax, Street from Organization];
        String StatementId = ApexPages.currentPage().getparameters().get('id');
        
        if(StatementId==null || StatementId==''){
            return;
        }
        statement = (List<Statements__c>)Data.read(
            'Select Amount__c , Billing_Period__c, Customer__c, Member__r.Customer_Id__c, Date__c , '+
            'Statement_Balance__c  '+
            'from Statements__c  where id=:StatementId order by Date__c ASC',
            new Map<String,Object> {
                'StatementId' => StatementId
                    }
        );
        statementLines= (List<Statements__c>)Data.read(
            'Select Amount__c , Billing_Period__c, Description__c , Service_Charge__c , Tax__c , Customer__c, Date__c , '+
            'Statement_Balance__c  '+
            'from Statements__c  where Statement__c=:StatementId order by Date__c ASC',
            new Map<String,Object> {
                'StatementId' => StatementId
                    }
        );
        integer i=0;
        for(i = 1;i<=100;i++){
            Statements__c sc=new Statements__c();
            sc.Amount__c=i *-1;
            sc.Description__c='testing' + i;
            sc.Date__c=date.today();
            sc.Tax__c=0;
            sc.Service_Charge__c=0;
            statementLines.add(sc);
        }
        for(i =1;i<=statementLines.size()/totalRowsToShow;i++){
            pages.add(i);
        }
        pages.add(i);
         i=1;
        integer tot=1;
        List<Statements__c> lc=new List<Statements__c>();
        for(Statements__c scc : statementLines){
            system.debug('check this list : '+  scc);
            lc.add(scc);
            if(tot==totalRowsToShow){
                sclns.put(i, lc);
                lc=new List<Statements__c>();
                tot=1;
                i++;
            }
            tot++;
        }
        sclns.put(i, lc);
        totalPage = i;
        system.debug('check this map : '+  sclns);
        
    }
}