src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Balance__c</fullName>
        <label>Account Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bill_To_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Bill To Member)</relationshipLabel>
        <relationshipName>ContactBillTo</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/TXN__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Remaining_formatted__c</fullName>
        <formula>CASE(RecordType.Name,
&quot;Payment&quot;, (Amount_Remaining__c * -1),
&quot;Adjustment&quot;, (Amount_Remaining__c * -1),
&quot;Charge&quot;, Amount_Remaining__c, 
&quot;Dues&quot;, Amount_Remaining__c, 
&quot;Refund&quot;, Amount_Remaining__c, 
&quot;Taxes&quot;, Amount_Remaining__c,
&quot;Service Charges&quot;, Amount_Remaining__c,
&quot;Credit&quot;, (Amount_Remaining__c * -1),
&quot;Deposit&quot;, (Amount_Remaining__c * -1),
Amount_Remaining__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount Remaining (Formatted)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bill_To_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Bill To Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Bill To Member)</relationshipLabel>
        <relationshipName>TransactionBillTo</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContactRollupService.cls
public class ContactRollupService {
     /****
    Method is to update Account Balance in Contact Object.
    ****/
    public static void updateContactWithAccountBalance(List<Id> contactIds) {
        try {
            List<Contact> contactsListToUpdate = new List<Contact>();
            if(contactIds != null && !contactIds.isEmpty() ) {
                AggregateResult[] transactionBillToAmountResults = Data.read('SELECT Bill_To_Member__c, Sum(Amount_Remaining_formatted__c) remainingSum '
                                                                                + 'FROM TXN__c '
                                                                                + 'WHERE Bill_To_Member__c IN :contactIds Group by Bill_To_Member__c',
                                                                                new Map<String, Object>{'contactIds' => contactIds}
                                                                            );
                        
                for (AggregateResult billToIdAmountRemainingSum : transactionBillToAmountResults)  {
                    if(billToIdAmountRemainingSum.get('Bill_To_Member__c') != null) {
                        Contact contact_Ex = new Contact();
                        contact_Ex.Id = String.valueOf(billToIdAmountRemainingSum.get('Bill_To_Member__c'));
                        if(billToIdAmountRemainingSum.get('remainingSum') != null) {
                            contact_Ex.Account_Balance__c = decimal.valueOf(String.valueOf(billToIdAmountRemainingSum.get('remainingSum')));
                            contactsListToUpdate.add(contact_Ex);
                        }
                    }
                }
            }
            if(!contactsListToUpdate.isEmpty()) {
                data.modify(contactsListToUpdate);
            }
        }Catch(Exception e) {
            System.debug(e.getMessage());
        }
    }
}