src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Balance__c</fullName>
        <label>Account Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bill_To_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Bill To Member)</relationshipLabel>
        <relationshipName>ContactBillTo</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/TXN__c.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Bill To Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Bill To Member)</relationshipLabel>
        <relationshipName>TransactionBillTo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Member or Guest the Transaction applies to</description>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Customer)</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>GlobalSubType__c</fullName>
        <globalPicklist>SubType</globalPicklist>
        <label>SubType</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GlobalType__c</fullName>
        <globalPicklist>Type</globalPicklist>
        <label>Type</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <formula>IF(
	(RecordType.Name==&apos;Charge&apos; || RecordType.Name==&apos;Adjustment&apos; || RecordType.Name==&apos;Dues&apos;),
	ROUND(Amount__c+Service_Charge__c+Tax__c,2),
	Amount__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Deposit</fullName>
        <active>true</active>
        <label>Deposit</label>
    </recordTypes>
    <recordTypes>
        <fullName>Taxes</fullName>
        <active>true</active>
        <description>Used to store tax amounts</description>
        <label>Taxes</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountHistoryPageController.cls
public with sharing class AccountHistoryPageController {
    public String startDateStr { get; set; }
    public Date startDate { get; set; }
    public Date endDate { get; set; }
    public List<TXN__c> txnList { get; set; }
    private final Contact contact;

    public AccountHistoryPageController(ApexPages.StandardController stdController) {

        if (!Test.isRunningTest()) stdController.addFields(new List<String> {'Bill_To_Member__c', 'Account_Balance__c'});
        this.contact = (Contact)stdController.getRecord();
        String billToMember = contact.Id;
        if (contact.Bill_To_Member__c != null) {

            billToMember = contact.Bill_To_Member__c;
        }

        txnlist = (List<TXN__c>)Data.read('SELECT Date__c, Customer__r.Name, Bill_To_Member__c, Recordtype.Name, Name,'
                                          + ' Description__c, GlobalType__c, GlobalSubType__c, Total_Amount__c, Bill_to_Member__r.Name'
                                          + ' FROM TXN__c WHERE Bill_To_Member__c = :billToMember AND RecordType.Name != :taxes AND RecordType.Name != :serviceCharge AND RecordType.Name != :deposit',
        new map<String, Object> {
            'billToMember' => billToMember,
            'taxes' => 'Taxes',
            'serviceCharge' => 'Service Charges',
            'deposit' => 'Deposit'
        });

        system.debug(txnlist.size());
        startDate = System.Date.today().toStartOfMonth();
        endDate = System.Date.today().addMonths(1).toStartofMonth().addDays(-1);

    }
    public String getAccountBalanceByDate() {
        String accountTotal;
        system.debug('startdate: ' + startDate + 'txnlist: ' + txnlist);
        if (startDate != null) {
            for (TXN__c txn : txnList) {
                if (txn.Date__c <= startDate) accountTotal += txn.Total_Amount__c;
            }
        }
        return accountTotal;
    }
    @RemoteAction
    public static String AccountBalanceByDate(Date startDate, String txnListstr) {
        Decimal accountTotal = 0.00;
        system.debug('startdate: ' + startDate + 'txnlist: ' + txnliststr);
        txnListstr = txnListstr.replace('[', '');
        txnListstr = txnListstr.replace(']', '');
        List<String> txnListsplit = txnliststr.split(',');       
        List<TXN__c> txnlist = (List<TXN__c>)Data.read('SELECT Date__c, Customer__r.Name,'
                               + ' Bill_To_Member__c, Recordtype.Name, Name, Description__c, GlobalType__c,'
                               + ' GlobalSubType__c, Total_Amount__c, Bill_to_Member__r.Name'
                               + ' FROM TXN__c WHERE Id IN :txnids',

        new Map<String, Object> {
            'txnids' => txnListsplit
        });

        if (startDate != null) {
            for (TXN__c txn : txnList) {
                if (txn.Date__c <= startDate) accountTotal += txn.Total_Amount__c;
            }
        }
        accountTotal.setScale(2);
        return string.valueOf(accountTotal);
    }
    public String getCurrentAccountBalanceFormat() {
        Decimal conTotal = 0.00;
        if (contact.Account_Balance__c != null) conTotal = contact.Account_Balance__c.setScale(2);
        return string.valueOf(conTotal);
    }
}