src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Balance__c</fullName>
        <label>Account Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bill_To_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Bill To Member)</relationshipLabel>
        <relationshipName>ContactBillTo</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <description>Select this record type for creating members.</description>
        <label>Member</label>
    </recordTypes>
</CustomObject>

src/objects/TXN__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bill_To_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Bill To Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Bill To Member)</relationshipLabel>
        <relationshipName>TransactionBillTo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountHistoryPageControllerTest.cls
@isTest
public with sharing class AccountHistoryPageControllerTest
{

    @isTest
    static void testAccountHistoryPage()
    {
        PageReference pageRef = Page.AccountHistory;
        Test.setCurrentPage(pageRef);
        Account acc = new Account(Name='testacc');
		Contact con = new Contact(LastName='test',AccountId=acc.id,Account_Balance__c=1.00);
        TXN__c txn = new TXN__c(Bill_To_member__c = con.id, Amount__c = 5.00, Date__c = Date.today());
        //System.currentPageReference().getParameters().put('Id', 'member');
		ApexPages.StandardController sc = new ApexPages.StandardController(con);
        AccountHistoryPageController accountHistory = new AccountHistoryPageController(sc);
        accountHistory.startDate = Date.today();

        Test.startTest();
        String accountBalance = accountHistory.getCurrentAccountBalanceFormat();
		String accountBalanceByDate = accountHistory.getAccountBalanceByDate();
        String passedTXNList = '[' + txn.id + ']';
        String remoteBalance = AccountHistoryPageController.AccountBalanceByDate(Date.today(), passedTXNList);
        Test.stopTest();
    }
}