src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Bill To Member)</relationshipLabel>
        <relationshipName>ContactBillTo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Exempt_Number__c</fullName>
        <label>Tax Exempt Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Exempt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tax Exempt?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Type 1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <description>Select this record type for creating members.</description>
        <label>Member</label>
    </recordTypes>
</CustomObject>

src/objects/Default_Account__c.object
<CustomObject>
    <description>Contains TXN to financial Account Mapping</description>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>containing relation to financial account</description>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Default Accounts</relationshipLabel>
        <relationshipName>Txn_To_Financial_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Default Account</label>
    <nameField>
        <displayFormat>DA-{00000}</displayFormat>
        <label>Default Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Administrative &amp; General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aquatic Sports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clubhouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Common Area Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facility Maintenance &amp; Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fitness/Spa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Charges &amp; Income Taxes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Golf Course maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Golf Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Golf Shop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housekeeping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Locker Rooms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing &amp; Membership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Allocated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Operating Departments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overnight Rooms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payroll Taxes &amp; Employee Benefits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Racquet Shop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Racquet Sports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rentals &amp; Other Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special-purpose Funds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Club Rooms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Club Rooms (HSKP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gift Shop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taxes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Member_Dues__c.object
<CustomObject>
    <description>Dues  subscription for member on different categories</description>
    <fields>
        <fullName>Default_Billing_Frequency__c</fullName>
        <description>Represents the default billing frequency to the members who have this due.</description>
        <label>Default Billing Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Annual</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Installment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quaterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One Time</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Financial Account for crediting the amount charged through the due</description>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipName>Billing_Table</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Statements_Description__c</fullName>
        <label>Statements Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Subtype__c</fullName>
        <globalPicklist>SubType</globalPicklist>
        <label>Subtype</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tax_exempt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tax exempt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <globalPicklist>Type</globalPicklist>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Member Dues</label>
    <nameField>
        <label>Due Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Dues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tax_To_Account_Mapping__c.object
<CustomObject>
    <description>This object contains the mapping records for each tax, service charge, and use tax when they are mapped to a Financial Account.</description>
    <fields>
        <fullName>Financial_Accounts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Accounts</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Tax To Account Mappings</relationshipLabel>
        <relationshipName>Tax_To_Account_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Charge__c</fullName>
        <description>Service Charge Names</description>
        <label>Service Charge</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Tax To Account Mapping</label>
    <nameField>
        <displayFormat>Tax-Acc-{000000}</displayFormat>
        <label>TaxToAccountMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax To Account Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TXN__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bill_To_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Bill To Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Bill To Member)</relationshipLabel>
        <relationshipName>TransactionBillTo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Transactions (Credit Financial Account)</relationshipLabel>
        <relationshipName>Transactions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Member or Guest the Transaction applies to</description>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Customer)</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Debit_Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Debit Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Transactions (Debit Financial Account)</relationshipLabel>
        <relationshipName>Transactions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Transactions (Financial Account)</relationshipLabel>
        <relationshipName>Transactions3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member_Dues__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to fill the due id in this</description>
        <label>Member Dues</label>
        <referenceTo>Member_Dues__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Charge_Name__c</fullName>
        <description>name of the service charge applied</description>
        <inlineHelpText>name of the service charge applied</inlineHelpText>
        <label>Service Charge Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Charge__c</fullName>
        <description>service charge on this transaction</description>
        <inlineHelpText>service charge on this transaction</inlineHelpText>
        <label>Service Charge</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Statement_Description__c</fullName>
        <label>Statement Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Tax_Exempt__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tax Exempt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Dues</fullName>
        <active>true</active>
        <label>Dues</label>
    </recordTypes>
    <recordTypes>
        <fullName>Tax</fullName>
        <active>true</active>
        <label>Tax</label>
    </recordTypes>
    <recordTypes>
        <fullName>Taxes</fullName>
        <active>true</active>
        <description>Used to store tax amounts</description>
        <label>Taxes</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ManualDueSetupController.cls
public with sharing class ManualDueSetupController {

	public Contact memberRecord {get; set;}
	public Member_Dues__c memDues {get; set;}
	public TXN__c dueRec {get; set;}
	public boolean renderTaxes {get; set;}
	public boolean renderSC {get; set;}
	public taxesAndSCharges taxesAndSC {get; set;}
	public String currencySymbol {get; set;}
	public String SCTaxableStatus {get; set;}
	public String TaxesAppliedOnSC {get; set;}

	public ManualDueSetupController() {
		currencySymbol = Utility.getcurrencySymbol();
		renderSC = false;
		renderTaxes = false;
		Id passedId = ApexPages.currentPage().getParameters().get('id');
		memberRecord = (Contact)Data.read('Select id, Name, Tax_Exempt__c, Tax_Exempt_Number__c from Contact where RecordTypeId=:recId AND Id=:passedId', 
			new Map<String, Object> {'recId' => Utility.searchRecordType('Member', 'Contact'),
									 'passedId'	=> passedId})[0];
		if(memberRecord==null){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'The member is not valid.'));
			return;
		}
		dueRec = new TXN__c(RecordTypeId=Utility.searchRecordType('Dues', 'TXN__c'), Date__c = Date.today(), Amount__c=0.00);
	}

	public void changeDueSelected()
	{
		if(dueRec.Member_Dues__c!=null){
		memDues = (Member_Dues__c)Data.read('Select Id, Financial_Account__c, Default_Billing_Frequency__c, Type__c, Subtype__c, Statements_Description__c from Member_Dues__c where Id=:memDueId', 
			new Map<String, Object> {'memDueId' => dueRec.Member_Dues__c})[0];
		dueRec.Statement_Description__c = memDues.Statements_Description__c;
		updateTaxesAndSCList(memDues.Type__c, memDues.Subtype__c, dueRec.Amount__c);
		}
	}

	public void updateTaxesAndSCList(String type, String subtype, Decimal Amount)
	{	
		SCTaxableStatus = '';
		TaxesAppliedOnSC = '';
		renderSC = false;
		renderTaxes = false;
		taxesAndSCharges taxesAndSCL = new taxesAndSCharges(type, subtype, Amount);
		taxesAndSC = new taxesAndSCharges(type, subtype);
		taxesAndSC.serviceCharge = taxesAndSCL.serviceCharge;
		taxesAndSC.SCAmount = taxesAndSCL.SCAmount;
		taxesAndSC.SCPercentage = taxesAndSCL.SCPercentage;
		taxesAndSC.taxesList = new List<TaxesAndServiceCharge.Taxes>();
		for(TaxesAndServiceCharge.Taxes taxesObj :taxesAndSCL.taxesList)
		{
			boolean dupFound = false;
			for(TaxesAndServiceCharge.Taxes taxesObj1 :taxesAndSC.taxesList){
				if(taxesObj.taxName==taxesObj1.taxName){
					SCTaxableStatus = 'Taxable';
					if(TaxesAppliedOnSC=='')
					{
						TaxesAppliedOnSC += taxesObj1.taxName;
					}
					TaxesAppliedOnSC += ','+taxesObj1.taxName;
					taxesObj1.Amount += taxesObj.Amount;
					taxesObj1.taxAppliedOnSC = true;
					dupFound = true;
				}
			}
			if(!dupFound){
				taxesAndSC.taxesList.add(taxesObj);
			}
		}
		if(taxesAndSC.serviceCharge!=null)
		{
			renderSC = true;
		}
		if(taxesAndSC.taxesList.size()>0)
		{
			renderTaxes = true;
		}
	}

	public class taxesAndSCharges extends TaxesAndServiceCharge
	{
		public taxesAndSCharges(String type, String subtype, Decimal Amount)
		{
			super(type, subtype, Amount);
		}

		public taxesAndSCharges(String type, String subtype)
		{
			super(type, subtype);
		}
	}

	public PageReference save()
	{
		Map<String, Tax_To_Account_Mapping__c> mapOfTaxesAndFinAccount = Utility.getTaxAndFinancialAccountMappings();
		Map<Id, Id> contactToBillToMemberMap = Utility.getBillToMember(new List<Id>{memberRecord.Id});
		PageReference pg = Page.ManualDueSetup;
		pg.getParameters().put('id', memberRecord.id);
		pg.getParameters().put('message', 'Saved Successfully');
		if(dueRec.Date__c==null){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Post date is required.'));
			return null;
		}
		if(dueRec.Member_Dues__c==null){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Due selection is mandatory.'));
			return null;
		}
		Default_Account__c defAcc = Utility.getDefaultFinancialAccount('Accounts Receivable');
		Savepoint sp = Database.setSavepoint();
		try{
			Map<String, Tax_To_Account_Mapping__c> taxesAndSCMap = Utility.getTaxAndFinancialAccountMappings();
			List<TXN__c> txnRecsToInsert = new List<TXN__c>();
			dueRec.Bill_To_Member__c = contactToBillToMemberMap.get(memberRecord.Id);
			dueRec.Customer__c = memberRecord.id;
			dueRec.Tax__c = 0;
			dueRec.Service_Charge__c = 0;
			dueRec.Debit_Financial_Account__c = defAcc.Financial_Account__c;
			dueRec.Credit_Financial_Account__c = memDues.Financial_Account__c;
			txnRecsToInsert.add(dueRec);
			Data.create(txnRecsToInsert);
			txnRecsToInsert = new List<TXN__c>();
			if(taxesAndSC.serviceCharge!=null && taxesAndSC.SCAmount!=null){
			TXN__c SCRec = new TXN__c(RecordTypeId=Utility.searchRecordType('Service Charges', 'TXN__c'));
			SCRec.Debit_Financial_Account__c = defAcc.Financial_Account__c;
			SCRec.Credit_Financial_Account__c = mapOfTaxesAndFinAccount.get(taxesAndSC.serviceCharge).Financial_Accounts__c;
			SCRec.Amount__c = taxesAndSC.SCAmount;
			SCRec.Service_Charge_Name__c = taxesAndSC.serviceCharge;
			SCRec.Bill_To_Member__c = contactToBillToMemberMap.get(memberRecord.Id);
			SCRec.Customer__c = memberRecord.id;
			SCRec.Related_To__c = dueRec.id;
			SCRec.Date__c = dueRec.Date__c;
			dueRec.Service_Charge__c = SCRec.Amount__c;
			txnRecsToInsert.add(SCRec);
			}
			Boolean taxExempt = false;
			for(TaxesAndServiceCharge.Taxes taxesObj :taxesAndSC.taxesList)
			{
				if(taxesObj.taxExemption==null || !taxesObj.taxExemption)
				{
					TXN__c taxes = new TXN__c(RecordTypeId=Utility.searchRecordType('Taxes', 'TXN__c'));
					taxes.Amount__c =  taxesObj.Amount;
					taxes.Debit_Financial_Account__c = defAcc.Financial_Account__c;
					taxes.Credit_Financial_Account__c = mapOfTaxesAndFinAccount.get(taxesObj.taxName).Financial_Accounts__c;
					taxes.Tax_Name__c = taxesObj.taxName;
					taxes.Bill_To_Member__c = contactToBillToMemberMap.get(memberRecord.Id);
					taxes.Customer__c = memberRecord.id;
					taxes.Date__c = dueRec.Date__c;
					taxes.Related_To__c = dueRec.id;
					if(taxesObj.taxAppliedOnSC!=null && taxesObj.taxAppliedOnSC){
						taxes.Tax_Applied_On_Service_Charge__c = taxesObj.taxAppliedOnSC;
					}
					dueRec.Tax__c += taxes.Amount__c;
					txnRecsToInsert.add(taxes);
				}
				else
				{
					taxExempt = true;
				}
			}
			if(taxExempt)
			{
				if(memberRecord.Tax_Exempt__c==false){
					Database.rollback(sp);
					ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Please set Tax Exempt status on member profile page.'));
					return null;
				}
			}
			Data.modify(dueRec);
			Data.create(txnRecsToInsert);
			pg.setRedirect(true);
			return pg;
		}
		catch(Exception ex)
		{
			Database.rollback(sp);
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Failed - '+ex.getMessage()));
			return null;
		}
	}
}