src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts (Bill To Member)</relationshipLabel>
        <relationshipName>ContactBillTo</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/TXN__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bill_To_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Bill To Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Bill To Member)</relationshipLabel>
        <relationshipName>TransactionBillTo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Member or Guest the Transaction applies to</description>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Customer)</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <description>payment type of the payment</description>
        <globalPicklist>Payment_Type</globalPicklist>
        <inlineHelpText>payment type of the payment</inlineHelpText>
        <label>Payment Type</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related To</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6 AND 7 AND 8)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Refund</value>
            </filterItems>
            <filterItems>
                <field>TXN__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Payment</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Adjustment</value>
            </filterItems>
            <filterItems>
                <field>TXN__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Charge, Dues, Taxes, Service Charges</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Refund</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Adjustment</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Dues</value>
            </filterItems>
            <filterItems>
                <field>TXN__c.RecordTypeId</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TXN__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Payment</fullName>
        <active>true</active>
        <label>Payment</label>
    </recordTypes>
    <recordTypes>
        <fullName>Refund</fullName>
        <active>true</active>
        <label>Refund</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/allPaymentsController.cls
public with sharing class allPaymentsController {
    public List<TXN__c> txnList {get; set;}
    public List<paymentWrapper> wrapperList {get; set;}
    public String memberId {get; set;}
    public String memberName {get; set;}
    public String PaymentId {get; set;}
    public String linkToRefund {get; set;}
    public String FromLink {get; set;}
    public String currentPage {get; set;}
    Public  allPaymentsController() {

        //String recType = [SELECT ID FROM RecordType WHERE SobjectType =:'TXN__c' AND DeveloperName =:'Payment'].id;
        String recType = Utility.searchRecordType('Payment', 'TXN__c');
        memberId = Apexpages.currentPage().getParameters().get('memberId');
        memberName = Apexpages.currentPage().getParameters().get('memberName');
        PaymentId = Apexpages.currentPage().getParameters().get('PaymentId');
        linkToRefund = '/apex/allPayments?memberId=' + memberId;
        FromLink = '/' + memberId;
        currentPage = 'All-Payments';

        //Map<Id, TXN__c> temptxnList = new Map<Id, TXN__c>([Select Id, RecordType.Name, Name, Amount__c, Payment_Type__c, Date__c, Description__c, Bill_To_Member__c, Customer__c, Bill_To_member__r.Name, Customer__r.Name
        //           From TXN__c
        //           Where Bill_To_Member__c = :string.escapeSingleQuotes(Apexpages.currentPage().getParameters().get('memberId')) AND RecordType.Name = 'Payment']);

        Map<Id, TXN__c> temptxnList = new Map<Id, TXN__c>((List<TXN__c>)Data.read('Select Id, RecordType.Name, Name, Amount__c,'
                + ' Payment_Type__c, Date__c, Description__c, Bill_To_Member__c, Customer__c, Bill_To_member__r.Name,'
                + ' Customer__r.Name From TXN__c Where Bill_To_Member__c = :billToMember AND RecordType.Name = :rtypeName',
        new Map<String, Object> {
            'billToMember' => Apexpages.currentPage().getParameters().get('memberId'),
            'rtypeName' => 'Payment'
        }));

        txnList = new List<TXN__c>();
        wrapperList = new List<paymentWrapper>();
        Map<Id, List<TXN__c>> testMap = new Map<Id, List<TXN__c>>();

        //for (TXN__c tx : [SELECT Id, Related_To__c, Related_To__r.Amount__c, Amount__c
        //                  FROM TXN__c
        //                  WHERE Related_To__c IN :temptxnlist.keySet() AND RecordType.Name = 'Refund']) 
        for (TXN__c tx : (List<TXN__c>)Data.read('SELECT Id, Related_To__c, Related_To__r.Amount__c, Amount__c'
                        +' FROM TXN__c'
                        +' WHERE Related_To__c IN :relatedToList AND RecordType.Name =:recTypeName',
                        new Map<String,Object>{
                            'relatedToList'=>temptxnlist.keySet(),
                            'recTypeName' =>  'Refund'
                            })) 
        {
            List<TXN__c> temp = testMap.get(tx.Related_To__c);
            if (temp == null) {
                testMap.put(tx.Related_To__c, new List<TXN__c> {tx});
            } else {
                temp.add(tx);
            }
        }

        if (testMap.size() > 0) {
            for (Id relatedID : testMap.keySet()) {
                List<TXN__c> tempTXN = testMap.get(relatedID);
                Double parentAmount = tempTXN[0].Related_To__r.Amount__c;
                Double childAmounts = 0.00;
                for (TXN__c childTXN : tempTXN) {
                    childAmounts += childTXN.Amount__c;
                }

                if (childAmounts < Math.abs(parentAmount)) {
                    paymentWrapper tempWrapper = new paymentWrapper();
                    tempWrapper.txn = temptxnList.get(relatedID);
                    tempWrapper.refunded = childAmounts;
                    tempWrapper.amount_left = Math.abs(parentAmount) - childAmounts;

                    wrapperList.add(tempWrapper);

                    temptxnList.remove(relatedId);
                } else {
                    temptxnList.remove(relatedId);
                }
            }
        }
        system.debug(temptxnList);
        for (TXN__c txn : temptxnList.values()) {
            paymentWrapper tempWrapper = new paymentWrapper();
            tempWrapper.txn = txn;
            tempWrapper.refunded = 0.00;
            tempWrapper.amount_left = Math.abs(txn.Amount__c);
            wrapperList.add(tempWrapper);
        }
    }
    public class paymentWrapper {
        public TXN__c txn {get; set;}
        public double refunded {get; set;}
        public double amount_left {get; set;}
    }
}