src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <globalPicklist>Status</globalPicklist>
        <label>Status</label>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Member</fullName>
        <active>true</active>
        <description>Select this record type for creating members.</description>
        <label>Member</label>
    </recordTypes>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Cleanup_Time__c</fullName>
        <label>Cleanup Time</label>
        <picklist>
            <picklistValues>
                <fullName>Half Hour</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 Hour</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Hours</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contract_Due_Date__c</fullName>
        <label>Contract Due Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EndTime__c</fullName>
        <label>End Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Reservations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Set</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Setup_Time__c</fullName>
        <label>Setup Time</label>
        <picklist>
            <picklistValues>
                <fullName>Half Hour</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 Hour</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Hours</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SponsoringMember__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sponsoring Member</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Your member sponsor must have a record type of Member.</errorMessage>
            <filterItems>
                <field>Contact.Record_Type_Name__c</field>
                <operation>equals</operation>
                <value>Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Events (Sponsoring Member)</relationshipLabel>
        <relationshipName>ReservationsContact</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sponsoring_Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account to Bill</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Events (Account to Bill)</relationshipLabel>
        <relationshipName>EventsSC</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Tentative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed/Posted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospective</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-opened</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EventCalendarOptions__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Event calendar option to allow dragging and setting few options like start hour and end hour on the calendar.</description>
    <fields>
        <fullName>End_Hour__c</fullName>
        <defaultValue>22</defaultValue>
        <inlineHelpText>Set the end of the Day view. Uses 0-23 for hours</inlineHelpText>
        <label>End Hour</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Slot_Minutes__c</fullName>
        <defaultValue>30</defaultValue>
        <inlineHelpText>Length of time per block in the calendar. 1-60 minutes.</inlineHelpText>
        <label>Slot Minutes</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Hour__c</fullName>
        <defaultValue>6</defaultValue>
        <inlineHelpText>Set the start of the Day view. Uses 0-23 for hours.</inlineHelpText>
        <label>Start Hour</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>EventCalendarOptions</label>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>North Campus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Campus</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Parent_Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Facility</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Facilities</relationshipLabel>
        <relationshipName>Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Use</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Repairs</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EventsControllerTest.cls
/**
* @author joshi Prakash
* @date 07-18-2017
* @group Event management
* @description Controller class containing the test code for event calendar.
 **/
@isTest
private class EventsControllerTest {
	@isTest
	static void filterEventsTest() {
		/*Set event calendar as test page.*/
		PageReference pageRef = Page.Events;
		Test.setCurrentPage(pageRef);

		Contact contact = TestHandler.getContact('Member');

		Event__c event = new Event__c();
		event.Name = 'Test Event';
		event.Location__c = TestHandler.getLocation().id;
		event.Status__c = 'Tentative';
		event.Sponsoring_Customer__c = contact.id;
		event.SponsoringMember__c = contact.id;
		event.StartTime__c = System.now();
		event.EndTime__c = System.now().addHours(2);
		event.Setup_Time__c = 'Half Hour';
		event.Cleanup_Time__c = 'Half Hour';
		event.Contract_Due_Date__c = System.today();
		event.Max_Seats__c = 20;
		insert event;

		Test.startTest();

		EventsController apc = new EventsController();
		apc.filterEvent.StartTime__c = System.now().addDays(-1);
		apc.filterEvent.EndTime__c = System.now().addDays(1);
		apc.filterEvent.Status__c = 'Tentative';
		apc.filterEvent.SponsoringMember__c = contact.id;
		apc.filterEvent.Sponsoring_Customer__c = contact.id;

		apc.getFilteredEvents();
		System.assertEquals(1, apc.filterResultList.size());

		Test.stopTest();
	}

	@isTest
	static void calendarTest() {
		/*Set event calendar as test page.*/
		PageReference pageRef = Page.Events;
		Test.setCurrentPage(pageRef);

		//Create contact
		Contact contact = TestHandler.getContact('Member');

		//Create event calendar options
		EventCalendarOptions__c calenderOption = new EventCalendarOptions__c();
		calenderOption.End_Hour__c = 23;
		calenderOption.Slot_Minutes__c = 30;
		calenderOption.Start_Hour__c = 8;
		Data.create(calenderOption);

		//Create parent and child location.
		Location__c parentLoc = TestHandler.getLocation();
		Location__c childLoc = TestHandler.getLocation();
		childLoc.Parent_Facility__c = parentLoc.Id;
		data.modify(childLoc);

		Test.startTest();

		EventsController apc = new EventsController();
		System.assertEquals(8, apc.getStartHour());
		System.assertEquals(23, apc.getEndHour());
		System.assertEquals(30, apc.getSlotMinutes());

		System.assertNotEquals(null, apc.getResources());

		//Create reservation equvals to the drag on the calendar.
		apc.cStartDt = System.now().getTime();
		apc.cEndDt = System.now().addHours(2).getTime();
		apc.cFacId = parentLoc.Id;
		apc.cRTName = 'Sponsored Event';
		apc.createReservation();

		//fill all the required field from the pop up.
		apc.cReservation.Name = 'Test Event';
		apc.cReservation.Location__c = parentLoc.Id;
		apc.cReservation.Sponsoring_Customer__c = contact.id;
		apc.cReservation.SponsoringMember__c = contact.id;
		apc.cReservation.Contract_Due_Date__c = System.today();
		apc.cReservation.Max_Seats__c = 20;
		apc.cReservation.Status__c = 'Tentative';
		apc.cReservation.StartTime__c = System.now();
        apc.cReservation.EndTime__c = System.now().addHours(2);              
        apc.cReservation.Setup_Time__c = 'Half Hour';
        apc.cReservation.Cleanup_Time__c = 'Half Hour';

		apc.saveReservation();

		System.assertEquals(2,Data.read('SELECT id from Event__c',new  Map<String,Object>()).size());

		DateTime currentDate = System.today();
		DateTime startTime = currentDate.addHours(8);
		DateTime endTime = currentDate.addHours(23);

		//Get all created reservations to show on the calendar
		EventsController.getEvents(startTime.getTime(), endTime.getTime(), new List<String> {'Sponsored Event'}, new List<String> {'Event'});				
		//Other manual functions
		apc.closePopup();
		apc.gotoDetails();

		EventsController.cmapRT = null;
		EventsController.cmapVARs  = null;

		System.assertNotEquals(null,EventsController.cmapRT);
		System.assertNotEquals(null,EventsController.cmapVARs);

		/** make sure this method is also covering createUnavailableReservation method of evenObjectTrigger**/

		Event__c event = (Event__c)Data.read('SELECT Id, Name from Event__c where Name = :name',
			new  Map<String,Object>{
				'name'=>'Test Event'
			}).get(0);

		Data.modify(event);
		Test.stopTest();
	}
}