src/objects/Default_Account__c.object
<CustomObject>
    <description>Contains TXN to financial Account Mapping</description>
    <fields>
        <fullName>Default_Type_Name__c</fullName>
        <label>Default Type Name</label>
        <picklist>
            <picklistValues>
                <fullName>Accounts Receivable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prepaid Deposits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accounts Receivable - Dues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Book</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accounts Payable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accounts Payable Discounts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>POS Discounts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Book - Debit Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Book - Credit Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>containing relation to financial account</description>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Default Accounts</relationshipLabel>
        <relationshipName>Txn_To_Financial_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Default Account</label>
    <nameField>
        <displayFormat>DA-{00000}</displayFormat>
        <label>Default Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Accounts</pluralLabel>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <label>Default</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/cmsft_DefaultAccountSelector.cls
/**
 * @Description : Class encapsulates query logic for Default_Account__c
 * @Date : 27th May - 2017
 * https://developer.salesforce.com/page/Apex_Enterprise_Patterns_-_Selector_Layer
 **/
public class cmsft_DefaultAccountSelector extends fflib_SObjectSelector
{
	/**
	* @Description : get the list of fields to include in select query
	*/
	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField> {
				Default_Account__c.Id,
				Default_Account__c.Default_Type_Name__c,
				Default_Account__c.Financial_Account__c
			};
	}

	/**
	* @Description : get the type of sObject
	*/
	public Schema.SObjectType getSObjectType()
	{
		return Default_Account__c.sObjectType;
	}

	/**
	* @Description : method used to query Default_Account__c and return list of records with passed ids set
	*/
	public List<Default_Account__c> selectById(Set<ID> idSet)
	{
		fflib_QueryFactory contQuey = newQueryFactory(true, true, true);
		return new List<SObject> (Database.query(contQuey.setCondition('id in :idSet').toSOQL()));
	}	

	/**
	 * @Description : returns list of records matching the passed condition
	 */
	public List<Default_Account__c> selectByPassedCondition(String condition)
	{
		assertIsAccessible();
		return (List<Default_Account__c>) Database.query(
        /**
         * Query factory has been pre-initialised by calling
         * getSObjectFieldList(), getOrderBy() for you.
        */
        newQueryFactory(true, true, true).
        /**
         * Now focus on building the remainder of the
         * query needed for this method.
        */
        setCondition(condition).
        // Finally build the query to execute
        toSOQL());
	}

	/**
	 * @Description : returns list of records having default type name in passed list
	 */
	public List<Default_Account__c> selectByPassedCondition(List<String> defaultTypeName)
	{
		assertIsAccessible();
		return (List<Default_Account__c>) Database.query(
        /**
         * Query factory has been pre-initialised by calling
         * getSObjectFieldList(), getOrderBy() for you.
        */
        newQueryFactory(true, true, true).
        /**
         * Now focus on building the remainder of the
         * query needed for this method.
        */
        setCondition('Default_Type_Name__c in: defaultTypeName').
        // Finally build the query to execute
        toSOQL());
	}
}