src/objects/Default_Account__c.object
<CustomObject>
    <description>Contains TXN to financial Account Mapping</description>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>containing relation to financial account</description>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Default Accounts</relationshipLabel>
        <relationshipName>Txn_To_Financial_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Default Account</label>
    <nameField>
        <displayFormat>DA-{00000}</displayFormat>
        <label>Default Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Accounts</pluralLabel>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <label>Default</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Asset</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Income</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expense</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Administrative &amp; General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aquatic Sports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clubhouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Common Area Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facility Maintenance &amp; Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fitness/Spa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Charges &amp; Income Taxes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Golf Course maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Golf Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Golf Shop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housekeeping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Locker Rooms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing &amp; Membership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Allocated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Operating Departments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overnight Rooms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payroll Taxes &amp; Employee Benefits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Racquet Shop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Racquet Sports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rentals &amp; Other Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special-purpose Funds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Club Rooms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Club Rooms (HSKP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gift Shop</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceCharges__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>stored service charges</description>
    <fields>
        <fullName>Service_Charge_Member__c</fullName>
        <description>Member Service Charge %</description>
        <label>Service Charge Member</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <label>ServiceCharges</label>
</CustomObject>

src/objects/Tax_To_Account_Mapping__c.object
<CustomObject>
    <description>This object contains the mapping records for each tax, service charge, and use tax when they are mapped to a Financial Account.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Accounts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Accounts</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Tax To Account Mappings</relationshipLabel>
        <relationshipName>Tax_To_Account_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Charge__c</fullName>
        <description>Service Charge Names</description>
        <label>Service Charge</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Tax To Account Mapping</label>
    <nameField>
        <displayFormat>Tax-Acc-{000000}</displayFormat>
        <label>TaxToAccountMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax To Account Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Taxes__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <description>General Sales Tax</description>
        <label>Sales Tax</label>
        <precision>6</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transit_Improvement_Sales_Tax__c</fullName>
        <label>Transit Improvement Sales Tax</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <label>Taxes</label>
</CustomObject>

src/objects/TXN__c.object
<CustomObject>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Transactions (Financial Account)</relationshipLabel>
        <relationshipName>Transactions3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GlobalSubType__c</fullName>
        <globalPicklist>SubType</globalPicklist>
        <label>SubType</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GlobalType__c</fullName>
        <globalPicklist>Type</globalPicklist>
        <label>Type</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service_Charge_Name__c</fullName>
        <description>name of the service charge applied</description>
        <inlineHelpText>name of the service charge applied</inlineHelpText>
        <label>Service Charge Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Charge__c</fullName>
        <description>service charge on this transaction</description>
        <inlineHelpText>service charge on this transaction</inlineHelpText>
        <label>Service Charge</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Charge</fullName>
        <active>true</active>
        <label>Charge</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TxnChargeToTaxMapping__c.object
<CustomObject>
    <description>This object contains the mapping records for Type and Subtype and their taxes and service charges.</description>
    <fields>
        <fullName>Allow_in_POS__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Allow in POS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Charge_Name__c</fullName>
        <label>Service Charge Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Charge_applicable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if service charge is applicable then true.</description>
        <label>Service _Charge_applicable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subtype__c</fullName>
        <description>global subtype picklist value</description>
        <globalPicklist>SubType</globalPicklist>
        <label>Subtype</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TaxId__c</fullName>
        <description>tax id this is coming from customer setting and setting name taxes.</description>
        <label>TaxId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Taxes_applicable_on_service_charge__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if this is checked then the selected taxes will also apply on the service charge.</description>
        <label>Taxes_applicable_on_service_charge</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>global type picklist field</description>
        <globalPicklist>Type</globalPicklist>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>tax_on_service_charge__c</fullName>
        <description>if tax on service charge is applicable then this field will contain the tax id which is applicable</description>
        <label>tax_on_service_charge</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>TxnChargeToTaxMapping</label>
    <nameField>
        <displayFormat>ctot-{000000}</displayFormat>
        <label>TxnChargeToTaxMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TxnChargeToTaxMappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TxnChargesToTaxMappingControllerTest.cls
@isTest
public class TxnChargesToTaxMappingControllerTest 
{
    @testSetup static void setup(){
        Financial_Account__c financialAccount = new Financial_Account__c(Name = 'TEST_FIN_ACCOUNT', Account_Number__c = '123456789', Category__c = 'Expense');
        insert financialAccount;

        Taxes__c taxesCustomSettings = new Taxes__c();
        taxesCustomSettings.Sales_Tax__c = 10.00;
        taxesCustomSettings.Transit_Improvement_Sales_Tax__c = 1.00;
        insert taxesCustomSettings;

        ServiceCharges__c servicesCustomSettings = new ServiceCharges__c();
        servicesCustomSettings.Service_Charge_Member__c = 5.00;
        insert servicesCustomSettings;
        List<Tax_To_Account_Mapping__c> taxToAccounts = new List<Tax_To_Account_Mapping__c>();

        Tax_To_Account_Mapping__c taxToAccount1 = new Tax_To_Account_Mapping__c(Account_Name__c = 'TEST_TAX_TO_ACCOUNT1', Financial_Accounts__c = financialAccount.Id, Tax__c = Utility.getNameOfTax('Sales_Tax__c'));
        Tax_To_Account_Mapping__c taxToAccount2 = new Tax_To_Account_Mapping__c(Account_Name__c = 'TEST_TAX_TO_ACCOUNT2', Financial_Accounts__c = financialAccount.Id, Service_Charge__c = Utility.getNameOfServiceCharge('Service_Charge_Member__c'));
        taxToAccounts.add(taxToAccount1);
        taxToAccounts.add(taxToAccount2);
        insert taxToAccounts;

        List<TxnChargeToTaxMapping__c> mappings = new List<TxnChargeToTaxMapping__c>();
        TxnChargeToTaxMapping__c taxObj1= new TxnChargeToTaxMapping__c();
        taxObj1.Type__c='Dinner';
        taxObj1.Subtype__c = null;
        taxObj1.Allow_in_POS__c=true;
        taxObj1.Taxes_applicable_on_service_charge__c=false;
        taxObj1.Service_Charge_applicable__c=true;
        taxObj1.Service_Charge_Name__c = 'Service_Charge_Member__c';
        taxObj1.TaxId__c = 'Sales_Tax__c';
        mappings.add(taxObj1);
        insert mappings;
    }
    static testMethod void testMethod1() 
    { 
        PageReference pageRef = Page.TxnChargesToTaxMapping;
        Test.setCurrentPage(pageRef);
        
        

        String type = 'Dinner';
        String subtype = null;
        Schema.DescribeFieldResult fieldResult = TXN__c.GlobalType__c.getDescribe();
        List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();
        // for( Schema.PicklistEntry pick : picklistValues)
        // {
        //     type = pick.getValue();
        //     break;
        // }
        
        // Schema.DescribeFieldResult fieldResult1 = TXN__c.GlobalSubType__c.getDescribe();
        // List<Schema.PicklistEntry> picklistValues1 = fieldResult1.getPicklistValues();
        // for( Schema.PicklistEntry pick : picklistValues1)
        // {
        //     subtype = pick.getValue();
        //     break;
        // }
        TxnChargeToTaxMapping__c taxMappingOnThisType = MappingAndTaxUtilityTest.createTaxMapping(type, subtype);
        // Integer accNumber = ++MappingAndTaxUtilityTest.financialAccountNumber;
        //Financial_Account__c financialAccount = MappingAndTaxUtilityTest.createFinancialAccount(accNumber);

        //Tax_To_Account_Mapping__c tam = new Tax_To_Account_Mapping__c();
        // tam.Tax__c = Schema.getGlobalDescribe().get('Taxes__c').getDescribe().fields.getMap().get(taxMappingOnThisType.TaxId__c).getDescribe().getLabel();
        // if(taxMappingOnThisType.Service_Charge_Name__c != null)
        // {
        //     tam.Service_Charge__c = Schema.getGlobalDescribe().get('ServiceCharges__c').getDescribe().fields.getMap().get(taxMappingOnThisType.Service_Charge_Name__c).getDescribe().getLabel();
        // }
        // tam.Financial_Accounts__c = financialAccount.Id;
        // insert tam;
        
        TxnChargesToTaxMappingController testController = new TxnChargesToTaxMappingController();              
        testController.autoRun();
        testController.getRecordTypeOptions();
        testController.othCharge.Type__c = type;
        testController.Get_other_data_based_on_type();
        testController.othCharge.SubType__c = subtype;
        testController.Get_other_data_based_on_Subtype();
        
        testController.save();
        testController.ChargeType = type;
        testController.ChargeSubType = subtype;
        testController.save();
        System.debug('++ TaxMappingOnThisType.TaxId__c ' + TaxMappingOnThisType.TaxId__c);

        string name = Utility.getNameOfTax(TaxMappingOnThisType.TaxId__c);
        Decimal value = Utility.getPercentageOfTax(TaxMappingOnThisType.TaxId__c);
        
        testController.SelectedTaxes.add(new SelectOption(TaxMappingOnThisType.TaxId__c, name+'('+value+')'));
        testController.saveAction = 'saveAdd';
        testController.save();
        testController.saveAction = 'save';
        testController.save();
    }
    
    static testMethod void editPage()
    {
        
        PageReference pageRef = Page.TxnChargesToTaxMapping;
        Test.setCurrentPage(pageRef);
        
        String type;
        String subtype;
        Schema.DescribeFieldResult fieldResult = TXN__c.GlobalType__c.getDescribe();
        List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();
        for(Schema.PicklistEntry pick : picklistValues)
        {
            type = pick.getValue();
            break;
        }
        Schema.DescribeFieldResult fieldResult1 = TXN__c.GlobalSubType__c.getDescribe();
        List<Schema.PicklistEntry> picklistValues1 = fieldResult1.getPicklistValues();
        for(Schema.PicklistEntry pick : picklistValues1)
        {
            subtype = pick.getValue();
            break;
        }
        TxnChargeToTaxMapping__c taxMapping = MappingAndTaxUtilityTest.createTaxMapping(type, subtype);
        
        Financial_Account__c financialAccountForTest=new Financial_Account__c();
        financialAccountForTest.Name='Test finance1';
        financialAccountForTest.Account_Number__c='1234567';
        financialAccountForTest.Category__c='Asset';
        insert financialAccountForTest;
        Default_Account__c financialMapping =new Default_Account__c();
        financialMapping.RecordtypeId=Utility.searchRecordType('Default','Default_Account__c');
        insert financialMapping;
        
        TxnChargeToTaxMapping__c chargeToTaxMapping = new TxnChargeToTaxMapping__c();
        chargeToTaxMapping.Type__c = type;
        chargeToTaxMapping.SubType__c = '';
        chargeToTaxMapping.TaxId__c = taxMapping.id;
        insert chargeToTaxMapping;
        
        System.currentPageReference().getParameters().put('charge', [select id from recordType where name=:'Charge' and SobjectType=:'TXN__c'].id);
        System.currentPageReference().getParameters().put('type', type);
        System.currentPageReference().getParameters().put('subtype', subtype);
        
        string servCharge;
        Map<String,Schema.SObjectField> fieldsMap1=ServiceCharges__c.sObjectType.getDescribe().fields.getMap();
        for(String field:fieldsMap1.keySet())
        {
            Schema.SObjectField F=fieldsMap1.get(field);
            Schema.DescribeFieldResult R=F.getDescribe();
            servCharge = R.getLabel();
        }
        
        TxnChargesToTaxMappingController testController = new TxnChargesToTaxMappingController(); 
        testController.Get_other_data_based_on_type();
        testController.Get_other_data_based_on_Subtype();
        testController.get_ServiceChargeData();
    }

    static testMethod void editPageNoSubType()
    {
        PageReference pageRef = Page.TxnChargesToTaxMapping;
        Test.setCurrentPage(pageRef);
        
        String type = null;
        String subtype = null;
        Schema.DescribeFieldResult fieldResult = TXN__c.GlobalType__c.getDescribe();
        List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();

        for(Schema.PicklistEntry pick : picklistValues)
        {
            type = pick.getValue();
            break;
        }

        TxnChargeToTaxMapping__c taxMapping = MappingAndTaxUtilityTest.createTaxMapping(type, subtype);
        
        Financial_Account__c financialAccountForTest=new Financial_Account__c();
        financialAccountForTest.Name='Test finance1';
        financialAccountForTest.Account_Number__c='1234567';
        financialAccountForTest.Category__c='Asset';
        insert financialAccountForTest;

        Default_Account__c financialMapping =new Default_Account__c();
        financialMapping.RecordtypeId=Utility.searchRecordType('Default','Default_Account__c');
        insert financialMapping;
        
        TxnChargeToTaxMapping__c chargeToTaxMapping = new TxnChargeToTaxMapping__c();
        chargeToTaxMapping.Type__c = type;
        chargeToTaxMapping.SubType__c = '';
        chargeToTaxMapping.TaxId__c = taxMapping.id;
        insert chargeToTaxMapping;
        
        System.currentPageReference().getParameters().put('charge', [select id from recordType where name=:'Charge' and SobjectType=:'TXN__c'].id);
        System.currentPageReference().getParameters().put('type', type);
        System.currentPageReference().getParameters().put('subtype', subtype);
        
        string servCharge;
        Map<String,Schema.SObjectField> fieldsMap1=ServiceCharges__c.sObjectType.getDescribe().fields.getMap();
        for(String field:fieldsMap1.keySet())
        {
            Schema.SObjectField F=fieldsMap1.get(field);
            Schema.DescribeFieldResult R=F.getDescribe();
            servCharge = R.getLabel();
        }
        
        TxnChargesToTaxMappingController testController = new TxnChargesToTaxMappingController(); 
        testController.Get_other_data_based_on_type();
        testController.Get_other_data_based_on_Subtype();
        testController.get_ServiceChargeData();
    }

    static testMethod void saveEdit()
    {
        PageReference pageRef = Page.TxnChargesToTaxMapping;
        Test.setCurrentPage(pageRef);
        
        String type;
        String subtype;
        Schema.DescribeFieldResult fieldResult = TXN__c.GlobalType__c.getDescribe();
        List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();
        for(Schema.PicklistEntry pick : picklistValues)
        {
            type = pick.getValue();
            break;
        }
        Schema.DescribeFieldResult fieldResult1 = TXN__c.GlobalSubType__c.getDescribe();
        List<Schema.PicklistEntry> picklistValues1 = fieldResult1.getPicklistValues();
        for(Schema.PicklistEntry pick : picklistValues1)
        {
            subtype = pick.getValue();
            break;
        }
        TxnChargeToTaxMapping__c taxMapping = MappingAndTaxUtilityTest.createTaxMapping(type, subtype);
        Financial_Account__c financialAccountForTest=new Financial_Account__c();
        financialAccountForTest.Name='Test finance1';
        financialAccountForTest.Account_Number__c='1234567';
        financialAccountForTest.Category__c='Asset';
        insert financialAccountForTest;
        Default_Account__c financialMapping =new Default_Account__c();
        financialMapping.RecordtypeId=Utility.searchRecordType('Default','Default_Account__c');
        insert financialMapping;
        
        TxnChargeToTaxMapping__c chargeToTaxMapping = new TxnChargeToTaxMapping__c();
        chargeToTaxMapping.Type__c = type;
        chargeToTaxMapping.SubType__c = subtype;
        chargeToTaxMapping.TaxId__c = taxMapping.id;
        chargeToTaxMapping.tax_on_service_charge__c = '0.00';
        insert chargeToTaxMapping;
        
        System.currentPageReference().getParameters().put('charge', [select id from recordType where name=:'Charge' and SobjectType=:'TXN__c'].id);
        System.currentPageReference().getParameters().put('type', type);
        System.currentPageReference().getParameters().put('subtype', subtype);
        
        string servCharge;
        Map<String,Schema.SObjectField> fieldsMap1=ServiceCharges__c.sObjectType.getDescribe().fields.getMap();
        for(String field:fieldsMap1.keySet())
        {
            Schema.SObjectField F=fieldsMap1.get(field);
            Schema.DescribeFieldResult R=F.getDescribe();
            servCharge = R.getLabel();
        }
        
        TxnChargesToTaxMappingController testController = new TxnChargesToTaxMappingController(); 
        testController.serviceTaxesApplicable=true;
        testController.service_charge_applicable=true;
        testController.clickSrvcCharges();
        testController.clickSrvcTaxes();
        testController.save();
    }
}