src/objects/Default_Account__c.object
<CustomObject>
    <description>Contains TXN to financial Account Mapping</description>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>containing relation to financial account</description>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Default Accounts</relationshipLabel>
        <relationshipName>Txn_To_Financial_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Default Account</label>
    <nameField>
        <displayFormat>DA-{00000}</displayFormat>
        <label>Default Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Dues_Summary__c.object
<CustomObject>
    <description>the object is used to store due summary records and the failed records</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billing_Period__c</fullName>
        <description>the field is used to store billing month</description>
        <label>Billing Period</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Dues Summary</relationshipLabel>
        <relationshipName>Dues_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>field is used to store due summary record for dues created</description>
        <label>Dues Summary</label>
        <referenceTo>Dues_Summary__c</referenceTo>
        <relationshipLabel>Dues/Taxes</relationshipLabel>
        <relationshipName>Dues_Summary1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member_Dues__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Dues</label>
        <referenceTo>Member_Dues__c</referenceTo>
        <relationshipLabel>Dues Summary</relationshipLabel>
        <relationshipName>Dues_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Post_Date__c</fullName>
        <description>the field is used to store the due date</description>
        <label>Post Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Posted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Charge_Name__c</fullName>
        <label>Service Charge Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Service_Charge__c</fullName>
        <label>Service Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax_Amount__c</fullName>
        <label>Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax_Applied_On_Service_Charge__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Tax Applied On Service Charge</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tax_Name__c</fullName>
        <description>stores the name of the tax</description>
        <label>Tax Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <formula>Amount__c  + Service_Charge__c  +  Tax_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Dues Summary</label>
    <nameField>
        <displayFormat>DUESUM-{0000000}</displayFormat>
        <label>Dues Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dues Summary</pluralLabel>
    <recordTypes>
        <fullName>Dues</fullName>
        <active>true</active>
        <description>generated dues</description>
        <label>Dues</label>
    </recordTypes>
    <recordTypes>
        <fullName>Taxes</fullName>
        <active>true</active>
        <description>to store taxes for dues</description>
        <label>Taxes</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <fields>
        <fullName>Debit_Credit__c</fullName>
        <formula>CASE( Category__c , &apos;Asset&apos;, &apos;Debit&apos;, &apos;Liability&apos;, &apos;Credit&apos;, &apos;Equity&apos;,&apos;Credit&apos;,&apos;Income&apos;,&apos;Credit&apos;,&apos;Expense&apos;,&apos;Debit&apos;, &apos;&apos;)</formula>
        <label>Debit/Credit</label>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Journal_Line__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Financial Journal Lines</relationshipLabel>
        <relationshipName>Financial_Journal_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Journal Lines</relationshipLabel>
        <relationshipName>Financial_Journal_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Post_Date__c</fullName>
        <label>Post Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Posted?</label>
        <type>Checkbox</type>
    </fields>
    <label>Financial Journal Line</label>
    <nameField>
        <displayFormat>FINJRNL-{000000}</displayFormat>
        <label>Financial Journal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Journal Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Member_Dues__c.object
<CustomObject>
    <description>Dues  subscription for member on different categories</description>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Financial Account for crediting the amount charged through the due</description>
        <label>Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipName>Billing_Table</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Include_Billing_Period_On_SD__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check if billing period should get included on statement description</inlineHelpText>
        <label>Include Billing Period On SD</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Statements_Description__c</fullName>
        <label>Statements Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Member Dues</label>
    <nameField>
        <label>Due Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Dues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tax_To_Account_Mapping__c.object
<CustomObject>
    <description>This object contains the mapping records for each tax, service charge, and use tax when they are mapped to a Financial Account.</description>
    <fields>
        <fullName>Service_Charge__c</fullName>
        <description>Service Charge Names</description>
        <label>Service Charge</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Tax To Account Mapping</label>
    <nameField>
        <displayFormat>Tax-Acc-{000000}</displayFormat>
        <label>TaxToAccountMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax To Account Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TXN__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Credit_Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Transactions (Credit Financial Account)</relationshipLabel>
        <relationshipName>Transactions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Debit_Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Debit Financial Account</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Transactions (Debit Financial Account)</relationshipLabel>
        <relationshipName>Transactions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dues_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to relate unposted dues created before</description>
        <label>Dues Summary</label>
        <referenceTo>Dues_Summary__c</referenceTo>
        <relationshipLabel>Posted Dues</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Transactions (Financial Account)</relationshipLabel>
        <relationshipName>Transactions3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Journal_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Journal Line</label>
        <referenceTo>Financial_Journal_Line__c</referenceTo>
        <relationshipLabel>Debits</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member_Dues__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to fill the due id in this</description>
        <label>Member Dues</label>
        <referenceTo>Member_Dues__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Posted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Charge_Name__c</fullName>
        <description>name of the service charge applied</description>
        <inlineHelpText>name of the service charge applied</inlineHelpText>
        <label>Service Charge Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Charge__c</fullName>
        <description>service charge on this transaction</description>
        <inlineHelpText>service charge on this transaction</inlineHelpText>
        <label>Service Charge</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Statement_Description__c</fullName>
        <label>Statement Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Tax_Amount__c</fullName>
        <label>Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax_Applied_On_Service_Charge__c</fullName>
        <defaultValue>false</defaultValue>
        <description>checked if the tax is applied on service charge</description>
        <label>Tax Applied On Service Charge</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tax_Name__c</fullName>
        <description>used to store name of the tax</description>
        <label>Tax Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <formula>IF(
	(RecordType.Name==&apos;Charge&apos; || RecordType.Name==&apos;Adjustment&apos; || RecordType.Name==&apos;Dues&apos;),
	ROUND(Amount__c+Service_Charge__c+Tax__c,2),
	Amount__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Dues</fullName>
        <active>true</active>
        <label>Dues</label>
    </recordTypes>
    <recordTypes>
        <fullName>Taxes</fullName>
        <active>true</active>
        <description>Used to store tax amounts</description>
        <label>Taxes</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PostDuesBatch.cls
public class PostDuesBatch implements Database.Batchable<sObject>, Database.Stateful {
	
	@TestVisible
	private Default_Account__c defAcc;
	@TestVisible
	private Map<String, Tax_To_Account_Mapping__c> mapOfTaxes;
	@TestVisible
	private Set<Id> dueSummIds;
	@TestVisible
	private List<DueChargesStructure> chargesStructure;
	@TestVisible
	private Boolean isdueSummPosted;
	@TestVisible
	private Map<Id, Dues_Summary__c> duesSummaryObjs;
	@TestVisible
	private String postOrReject;

	public PostDuesBatch(Default_Account__c defAcc, Map<String, Tax_To_Account_Mapping__c> taxesMap, Set<Id> dueSummIds, String postOrReject) {
		
		chargesStructure = new List<DueChargesStructure>();
		this.defAcc = defAcc;
		this.mapOfTaxes = taxesMap;
		this.dueSummIds = dueSummIds;
		isdueSummPosted = false;
		duesSummaryObjs = new Map<Id, Dues_Summary__c>();
		this.postOrReject = postOrReject;
	}
	
	public Database.QueryLocator start(Database.BatchableContext BC) {
		return Data.locator('Select Amount__c, Contact__c, Due_Summary__c, Post_Date__c, Service_Charge__c,' 
							+ ' Service_Charge_Name__c, Tax_Amount__c, Tax_Applied_On_Service_Charge__c, Total_Amount__c'
							+ ' FROM Dues_Summary__c'
							+ ' WHERE RecordTypeId=:recId AND Due_Summary__c in :dueSummId'
			, new Map<String, Object> {'recId' => Utility.searchRecordType('Dues','Dues_Summary__c'),
									   'dueSummId' => dueSummIds});
	}

   	public void execute(Database.BatchableContext BC, List<sObject> scope) {
		Set<Id> duesMasterRecs = new Set<Id> ();
		List<Id> duesIds = new List<Id>();

		// store all incoming dues ids in a list
		// id of all incoming dues to fetch taxes related to each due
		for(Dues_Summary__c dueSummObj :(List<Dues_Summary__c>)scope)
		{
			duesMasterRecs.add(dueSummObj.Due_Summary__c);
			duesIds.add(dueSummObj.id);
		}
		Map<Id, List<Dues_Summary__c>> mapOfDueIdAndTaxes = new Map<Id, List<Dues_Summary__c>>();
		for(Dues_Summary__c dueSummObj :(List<Dues_Summary__c>) Data.Read('Select Id, Service_Charge__c, Due_Summary__c, Service_Charge_Name__c, Tax_Name__c, Amount__c, Tax_Applied_On_Service_Charge__c from Dues_Summary__c where Due_Summary__c in :duesIds AND RecordTypeId=:recId',
			new Map<String, Object> {'duesIds' => duesIds, 'recId' => Utility.searchRecordType('Taxes','Dues_Summary__c')}))
		{
			if(!mapOfDueIdAndTaxes.containsKey(dueSummObj.Due_Summary__c))
				mapOfDueIdAndTaxes.put(dueSummObj.Due_Summary__c,new List<Dues_Summary__c>());
			mapOfDueIdAndTaxes.get(dueSummObj.Due_Summary__c).add(dueSummObj);	
		}
		if(postOrReject=='Post'){
		List<Financial_Journal_Line__c> finJournalLineToUpdate = new List<Financial_Journal_Line__c>();
		List<TXN__c> txnListToUpdate = new List<TXN__c>();
		if(!isdueSummPosted)
		{
			List<Dues_Summary__c> dueSummList = Data.read('Select Id, Member_Dues__r.Financial_Account__c, Member_Dues__r.Financial_Account__r.Debit_Credit__c, Post_Date__c, Member_Dues__r.Name, Member_Dues__r.Statements_Description__c, Member_Dues__r.Include_Billing_Period_On_SD__c, Billing_Period__c from Dues_Summary__c where id in :dueSummIds', new Map<String, Object> {'dueSummIds' => dueSummIds});
			List<Dues_Summary__c> dueSummToUpdate = new List<Dues_Summary__c>();
			for(Dues_Summary__c dueSummObj :dueSummList)
			{
				dueSummObj.Posted__c = true;
				dueSummToUpdate.add(dueSummObj);
				duesSummaryObjs.put(dueSummObj.id, dueSummObj);
			}
			Data.modify(dueSummToUpdate);
			isdueSummPosted = true;
		}
		List<Id> customers = new List<Id>();
		
		for(Dues_Summary__c dueSummObj :(List<Dues_Summary__c>)scope){
			customers.add(dueSummObj.Contact__c);
		}
		Map<Id, Id> billToMembersToCustomerMap = Utility.getBillToMember(customers);
		List<Dues_Summary__c> dueSummObjsToUpdate = new List<Dues_Summary__c>();
		for(Dues_Summary__c dueSummObj :(List<Dues_Summary__c>)scope)
		{
			String statementDescription;
			if(duesSummaryObjs.get(dueSummObj.Due_Summary__c).Member_Dues__r.Include_Billing_Period_On_SD__c){
				statementDescription = duesSummaryObjs.get(dueSummObj.Due_Summary__c).Member_Dues__r.Statements_Description__c+' - '+duesSummaryObjs.get(dueSummObj.Due_Summary__c).Billing_Period__c;
			}
			else{
				statementDescription = duesSummaryObjs.get(dueSummObj.Due_Summary__c).Member_Dues__r.Statements_Description__c;
			}
			dueSummObj.Posted__c = true;
			dueSummObjsToUpdate.add(dueSummObj);
			TXN__c txnDueCharge = new TXN__c(RecordTypeId=Utility.searchRecordType('Dues','TXN__c'));
			txnDueCharge.Amount__c = dueSummObj.Amount__c;
			txnDueCharge.Statement_Description__c = statementDescription;
			if(dueSummObj.Tax_Amount__c==null){
				dueSummObj.Tax_Amount__c = 0.00;
			}
			if(dueSummObj.Service_Charge__c==null){
				dueSummObj.Service_Charge__c = 0.00;
			}
			txnDueCharge.Credit_Financial_Account__c = duesSummaryObjs.get(dueSummObj.Due_Summary__c).Member_Dues__r.Financial_Account__c;
			txnDueCharge.Debit_Financial_Account__c = defAcc.Financial_Account__c;
			txnDueCharge.Dues_Summary__c = dueSummObj.Due_Summary__c;
			txnDueCharge.Tax__c = dueSummObj.Tax_Amount__c;
			txnDueCharge.Service_Charge__c =dueSummObj.Service_Charge__c;
			txnDueCharge.Amount_Remaining__c = dueSummObj.Amount__c;
			if(billToMembersToCustomerMap.containskey(dueSummObj.Contact__c)){
				txnDueCharge.Bill_To_Member__c = billToMembersToCustomerMap.get(dueSummObj.Contact__c);
			}else{
				txnDueCharge.Bill_To_Member__c = dueSummObj.Contact__c;
			}	
				
			txnDueCharge.Customer__c = dueSummObj.Contact__c;
				
			txnDueCharge.Member_Dues__c = duesSummaryObjs.get(dueSummObj.Due_Summary__c).Member_Dues__c;	
			txnListToUpdate.add(txnDueCharge);
			DueChargesStructure dueStrucObj = new DueChargesStructure(txnDueCharge);

			// create taxes
			if(mapOfDueIdAndTaxes.containsKey(dueSummObj.id)){
				for(Dues_Summary__c taxesObj :mapOfDueIdAndTaxes.get(dueSummObj.id))
				{
					Txn__c taxTxn = new TXN__c();
					taxTxn.Debit_Financial_Account__c = defAcc.Financial_Account__c;
					taxTxn.Amount__c = taxesObj.Amount__c;
					taxTxn.Amount_Remaining__c = taxTxn.Amount__c;
					taxTxn.Dues_Summary__c = dueSummObj.Due_Summary__c;
					taxTxn.Customer__c = dueSummObj.Contact__c;
					if(billToMembersToCustomerMap.containskey(dueSummObj.Contact__c)){
						taxTxn.Bill_To_Member__c = billToMembersToCustomerMap.get(dueSummObj.Contact__c);
					}else{
						taxTxn.Bill_To_Member__c = dueSummObj.Contact__c;						
					}	
					taxTxn.Member_Dues__c = duesSummaryObjs.get(dueSummObj.Due_Summary__c).Member_Dues__c;
					if(taxesObj.Service_Charge_Name__c!=null || taxesObj.Tax_Applied_On_Service_Charge__c)
					{
						taxTxn.RecordTypeId = Utility.searchRecordType('Service Charges','TXN__c');
						if(taxesObj.Service_Charge_Name__c!=null){
							taxTxn.Service_Charge_Name__c = taxesObj.Service_Charge_Name__c;
							taxTxn.Credit_Financial_Account__c = mapOfTaxes.get(taxesObj.Service_Charge_Name__c).Financial_Accounts__c;
						}
						else{
							taxTxn.Tax_Name__c = taxesObj.Tax_Name__c;
							taxTxn.Credit_Financial_Account__c = mapOfTaxes.get(taxesObj.Tax_Name__c).Financial_Accounts__c;
						}
						taxTxn.Tax_Applied_On_Service_Charge__c = taxesObj.Tax_Applied_On_Service_Charge__c;
						dueStrucObj.taxes.add(taxTxn);
					}
					else
					{
						taxTxn.RecordTypeId = Utility.searchRecordType('Taxes','TXN__c');
						taxTxn.Tax_Name__c = taxesObj.Tax_Name__c;
						taxTxn.Credit_Financial_Account__c = mapOfTaxes.get(taxesObj.Tax_Name__c).Financial_Accounts__c;
						dueStrucObj.taxes.add(taxTxn);
					}
					taxTxn.Statement_Description__c = statementDescription;
					txnListToUpdate.add(taxTxn);
				}
			}
			chargesStructure.add(dueStrucObj);
		}

		Data.modify(dueSummObjsToUpdate);
		Data.create(txnListToUpdate);

		txnListToUpdate = new List<TXN__c>();

		for(DueChargesStructure charges :chargesStructure)
		{
			for(TXN__c chargeObj :charges.taxes)
			{
				chargeObj.Related_To__c = charges.dueCharge.id;
				txnListToUpdate.add(chargeObj);
			}
		}

		Data.modify(txnListToUpdate);
	}
	else if(postOrReject=='Reject')
	{
		List<Dues_Summary__c> duesAndTaxesToBeDeleted = new List<Dues_Summary__c> ();
		for(List<Dues_Summary__c> dueSummListObj :mapOfDueIdAndTaxes.values())
		{
			duesAndTaxesToBeDeleted.addAll(dueSummListObj);
		}
		if(!isdueSummPosted)
		{
			List<Dues_Summary__c> dueSummList = Data.read('Select Id, Member_Dues__r.Financial_Account__c, Member_Dues__r.Financial_Account__r.Debit_Credit__c, Post_Date__c, Member_Dues__r.Name, Member_Dues__r.Statements_Description__c, Billing_Period__c from Dues_Summary__c where id in :dueSummIds', new Map<String, Object> {'dueSummIds' => dueSummIds});
			Data.remove(dueSummList);
			isdueSummPosted = true;
		}
		duesAndTaxesToBeDeleted.addAll((List<Dues_Summary__c>)scope);
		Data.remove(duesAndTaxesToBeDeleted);
	}
	}
	
	public void finish(Database.BatchableContext BC) {
		AsyncApexJob a = (AsyncApexJob) Data.read('Select Id, Status, NumberOfErrors, JobItemsProcessed,TotalJobItems, CreatedBy.Email from AsyncApexJob where Id = :jobId', new Map<String, Object> {'jobId' => BC.getJobId()}).get(0); 
		if(a.TotalJobItems != 0)
		{
			// Send an email to the Apex job's submitter notifying of job completion.                                          
			Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();         
			String[] toAddresses = new String[] {a.CreatedBy.Email};         
			mail.setToAddresses(toAddresses);
			mail.setSubject('Post Dues Batch ' + a.Status);
			mail.setPlainTextBody('The batch Apex job processed ' + a.TotalJobItems + ' batches (' + ' items) with '+ a.NumberOfErrors + ' failures.');
			Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
		}
	}

	@TestVisible
	private class DueChargesStructure
	{
		TXN__c dueCharge;
		List<TXN__c> taxes;
		DueChargesStructure(TXN__c charges)
		{
			this.dueCharge = charges;
			taxes = new List<TXN__c>();
		}
	}
}