src/objects/Dues_Summary__c.object
<CustomObject>
    <description>the object is used to store due summary records and the failed records</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Member_Dues__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Dues</label>
        <referenceTo>Member_Dues__c</referenceTo>
        <relationshipLabel>Dues Summary</relationshipLabel>
        <relationshipName>Dues_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Charge_Name__c</fullName>
        <label>Service Charge Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Service_Charge__c</fullName>
        <label>Service Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax_Name__c</fullName>
        <description>stores the name of the tax</description>
        <label>Tax Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <formula>Amount__c  + Service_Charge__c  +  Tax_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Dues Summary</label>
    <nameField>
        <displayFormat>DUESUM-{0000000}</displayFormat>
        <label>Dues Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dues Summary</pluralLabel>
    <recordTypes>
        <fullName>Dues</fullName>
        <active>true</active>
        <description>generated dues</description>
        <label>Dues</label>
    </recordTypes>
    <recordTypes>
        <fullName>Taxes</fullName>
        <active>true</active>
        <description>to store taxes for dues</description>
        <label>Taxes</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Member_Dues__c.object
<CustomObject>
    <description>Dues  subscription for member on different categories</description>
    <label>Member Dues</label>
    <nameField>
        <label>Due Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Dues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TXN__c.object
<CustomObject>
    <fields>
        <fullName>Adjustment_Reason__c</fullName>
        <label>Adjustment Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Bill_To_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Bill To Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Bill To Member)</relationshipLabel>
        <relationshipName>TransactionBillTo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Member or Guest the Transaction applies to</description>
        <label>Customer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Customer)</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Dues_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to relate unposted dues created before</description>
        <label>Dues Summary</label>
        <referenceTo>Dues_Summary__c</referenceTo>
        <relationshipLabel>Posted Dues</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member_Dues__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to fill the due id in this</description>
        <label>Member Dues</label>
        <referenceTo>Member_Dues__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related To</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6 AND 7 AND 8)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Refund</value>
            </filterItems>
            <filterItems>
                <field>TXN__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Payment</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Adjustment</value>
            </filterItems>
            <filterItems>
                <field>TXN__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Charge, Dues, Taxes, Service Charges</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Refund</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Adjustment</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Dues</value>
            </filterItems>
            <filterItems>
                <field>TXN__c.RecordTypeId</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TXN__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Charge_Name__c</fullName>
        <description>name of the service charge applied</description>
        <inlineHelpText>name of the service charge applied</inlineHelpText>
        <label>Service Charge Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Charge__c</fullName>
        <description>service charge on this transaction</description>
        <inlineHelpText>service charge on this transaction</inlineHelpText>
        <label>Service Charge</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Statement_Description__c</fullName>
        <label>Statement Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Tax_Name__c</fullName>
        <description>used to store name of the tax</description>
        <label>Tax Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <formula>IF(
	(RecordType.Name==&apos;Charge&apos; || RecordType.Name==&apos;Adjustment&apos; || RecordType.Name==&apos;Dues&apos;),
	ROUND(Amount__c+Service_Charge__c+Tax__c,2),
	Amount__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Adjustment</fullName>
        <active>true</active>
        <label>Adjustment</label>
    </recordTypes>
    <recordTypes>
        <fullName>Charge</fullName>
        <active>true</active>
        <label>Charge</label>
    </recordTypes>
    <recordTypes>
        <fullName>Dues</fullName>
        <active>true</active>
        <label>Dues</label>
    </recordTypes>
    <recordTypes>
        <fullName>Taxes</fullName>
        <active>true</active>
        <description>Used to store tax amounts</description>
        <label>Taxes</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TxnChargesAdjustmentController.cls
/**
* @Description : controller for TxnChargeAdjustment page
* @Date : 2017
*/
public with sharing class TxnChargesAdjustmentController {

	public String recordTypeName {
		get{
			if(txnRecord!=null){
				return txnRecord.RecordType.Name;
			}
			else{
				return null;
			}
		}
	}

	public TXN__c txnRecord {
		get {
			if(txnRecord==null)
			{
				List<TXN__c> txnRecordsList = (List<TXN__c>) Data.read('Select Name, Amount__c, Customer__c, Bill_To_Member__c, Dues_Summary__r.Member_Dues__c, Member_Dues__c, Tax__c, Service_Charge__c, RecordType.Name, Related_To__c, Total_Amount__c from TXN__c where id=:recIdPassed', 
				new Map<String, Object> {'recIdPassed' => ApexPages.currentPage().getParameters().get('Id')});
				if(txnRecordsList.size()>0)
				{
					txnRecord = txnRecordsList[0];
				}
			}
			return txnRecord;
		}	
		set;
	}

	// variable storing all taxes and service charge recs related to incoming record
	private List<TXN__c> taxesAndSCRecords;

	// adjustment record
	public TXN__c adjustmentTxnRecord {get; set;}
	public boolean alreadyAdjusted {get; set;}

	public TxnChargesAdjustmentController() {
		if(recordTypeName == null)
		{
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Cannot procced further, Id passed is invalid.'));
			return;
		}
		if(recordTypeName!='Charge' && recordTypeName!='Dues')
		{
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Adjustment can be performed on either charge or due.'));
			return;
		}

		// check if due is already adjusted
		if(recordTypeName=='Dues'){
			List<TXN__c> ajustedRecs = Data.read('Select id from TXN__c where Related_To__c=:txnRecordId AND RecordTypeId=:adjustmentRecId',
				new Map<String, Object> {'txnRecordId' => txnRecord.id,
										 'adjustmentRecId' => Utility.searchRecordType('Adjustment','TXN__c')}
				);	
			if(ajustedRecs.size()>0){
				alreadyAdjusted = true;
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'This due is already adjusted.'));
				return;
			}
		}

		taxesAndSCRecords = Data.read('Select Id, Customer__c,Amount__c, Service_Charge_Name__c, Tax_Name__c from TXN__c where Related_To__c=:txnId',
				new Map<String, Object> {'txnId' => txnRecord.id}
				);	
		adjustmentTxnRecord = new TXN__c(RecordTypeId=Utility.searchRecordType('Adjustment', 'TXN__c'), Related_To__c=txnRecord.id, Customer__c=txnRecord.Customer__c, Bill_To_Member__c=txnRecord.Bill_To_Member__c, Date__c=Date.today(), Amount__c=-txnRecord.Amount__c);
		adjustmentTxnRecord.Member_Dues__c = txnRecord.Member_Dues__c;
		if(adjustmentTxnRecord.Member_Dues__c==null)
		{
			adjustmentTxnRecord.Member_Dues__c = txnRecord.Dues_Summary__r.Member_Dues__c;
		}
	}

	public PageReference saveDueAdjust()
	{
		if(adjustmentTxnRecord.Date__c==null || adjustmentTxnRecord.Statement_Description__c==null || adjustmentTxnRecord.Adjustment_Reason__c==null)
		{
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Required field is missing.'));
			return null;
		}
		Data.create(adjustmentTxnRecord);
		List<TXN__c> adjustmentTaxesRecords = new List<TXN__c>();
		for(TXN__c taxesSC : taxesAndSCRecords)
		{
			TXN__c taxObj = new TXN__c(RecordTypeId = Utility.searchRecordType('Adjustment','TXN__c'), Related_To__c = txnRecord.id);
			taxObj.Service_Charge_Name__c = taxesSC.Service_Charge_Name__c;
			taxObj.Tax_Name__c = taxesSC.Tax_Name__c;
			taxObj.Member_Dues__c = adjustmentTxnRecord.Member_Dues__c;
			taxObj.Amount__c = -taxesSC.Amount__c;
			taxObj.Date__c = adjustmentTxnRecord.Date__c;
			taxObj.Customer__c = adjustmentTxnRecord.Customer__c;
			taxObj.Statement_Description__c = adjustmentTxnRecord.Statement_Description__c;
			taxObj.Adjustment_Reason__c = adjustmentTxnRecord.Adjustment_Reason__c;
			adjustmentTaxesRecords.add(taxObj);
		}
		Data.create(adjustmentTaxesRecords);
		PageReference pg = new PageReference('/'+txnRecord.id);
		pg.setRedirect(true);
		return pg;
	}
}