src/objects/Event__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Line_Item__c.object
<CustomObject>
    <description>The role of this object is to include different kinds of products, services and fees for specific event. When events will get posted/closed it will generate the transactions for used resources from this object.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <formula>Qty__c *  Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reservation_line__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Reservation</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>Events</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LI-{0000000000}</displayFormat>
        <label>Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <recordTypes>
        <fullName>Charge</fullName>
        <active>true</active>
        <description>Use when entering items you wish to charge to your event.</description>
        <label>Charge</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Line_Item_Employee__c.object
<CustomObject>
    <description>Used to associate an employee(s) to each Charge Item.</description>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>Line_Item_Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Points the employee to the desired Event Charge Item.</description>
        <label>Line Item</label>
        <referenceTo>Line_Item__c</referenceTo>
        <relationshipName>Line_Item_Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Split_Amount__c</fullName>
        <label>Split Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Line Item Employee</label>
    <nameField>
        <displayFormat>ECIE-{00000}</displayFormat>
        <label>Line Item Employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Item Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LineItemEmployeeTriggerHandler.cls
/**
 * Handler class for EventChargeItemTrigger
 *
 */
public with sharing class LineItemEmployeeTriggerHandler {

    /**
     * OnBeforeInsert Handles before insert 
     * @param  newRecords
     */
    public static void OnBeforeInsert(List<Line_Item_Employee__c> newRecords)
    {
        preventGratuityOverAllocation(newRecords);
        UpdateEventOnInsert(newRecords);

    }
    /**
     * OnBeforeUpdate Handles before update 
     * @param  newRecords newRecords
     * @param  oldMap
     */
    public static void OnBeforeUpdate(List<Line_Item_Employee__c> newRecords, Map<id,Line_Item_Employee__c> oldMap)
    {
        preventGratuityOverAllocation(newRecords);
    }

    /**
     * preventGratuityOverAllocation Prevents the Gratuity splits from being greater than the EventChargeItem total amount
     * @param  records List of Line_Item_Employee__c
     * 
     */
    private static void preventGratuityOverAllocation(List<Line_Item_Employee__c> records)
    {
        //Map EventChargeItemEmployees in the current trigger context to their parent EventChargeItem
        Map<id,List<Line_Item_Employee__c>> lineItemEmployeeToChargeItemMap = new Map<id,List<Line_Item_Employee__c>>();
        Set<id> recordIDs = new Set<id>();
        for(Line_Item_Employee__c rec:records)
        {
            if(lineItemEmployeeToChargeItemMap.get(rec.Line_Item__c) == null)
            {
                lineItemEmployeeToChargeItemMap.put(rec.Line_Item__c,new List<Line_Item_Employee__c>{rec});
            }
            else
            {
                List<Line_Item_Employee__c> existingList = lineItemEmployeeToChargeItemMap.get(rec.Line_Item__c);
                existingList.add(rec);
                lineItemEmployeeToChargeItemMap.put(rec.Line_Item__c,existingList);
            }

            recordIDs.add(rec.id);
        }

        //Add sibling EventChargeItemEmployees to the map
        for(Line_Item_Employee__c rec:(List<Line_Item_Employee__c>) Data.read('Select id, Line_Item__c, Split_Amount__c from Line_Item_Employee__c where Line_Item__c in: keyset and Id NOT IN: recordIDs', new Map<String, Object>{'keyset' => lineItemEmployeeToChargeItemMap.keyset(), 'recordIDs' => recordIDs}))
        {
            if(lineItemEmployeeToChargeItemMap.get(rec.Line_Item__c) == null)
            {
                lineItemEmployeeToChargeItemMap.put(rec.Line_Item__c,new List<Line_Item_Employee__c>{rec});
            }
            else
            {
                List<Line_Item_Employee__c> existingList = lineItemEmployeeToChargeItemMap.get(rec.Line_Item__c);
                existingList.add(rec);
                lineItemEmployeeToChargeItemMap.put(rec.Line_Item__c,existingList);
            }
        }

        //Check whether the sum of the EventChargeItemEmployees Split Amounts is > the EventChargeItem Amount
        for(Line_Item__c eci:(List<Line_Item__c>) Data.read('Select id, Amount__c from Line_Item__c where Id in: keyset', new Map<String, Object>{'keyset' => lineItemEmployeeToChargeItemMap.keyset()}))
        {
            Decimal runningTotal = 0;
            for(Line_Item_Employee__c lineItemEmployee:lineItemEmployeeToChargeItemMap.get(eci.id))
            {
                if(lineItemEmployee.Split_Amount__c != NULL){
                     runningTotal += lineItemEmployee.Split_Amount__c;
                }               
            }

            if(runningTotal > eci.Amount__c)
            {
                lineItemEmployeeToChargeItemMap.get(eci.id)[0].adderror('Your split amounts are greater than your charge item total. Please update your split amount and click save.');
            }
        }
    }

    /**
     * Method to update the event on an Line_Item_Employee__c based on the Charge_Item selected.
     * @param records List of Line_Item_Employee__c
     */    
    public static void UpdateEventOnInsert(List<Line_Item_Employee__c> records){
       
        List<Line_Item_Employee__c> employeesToUpdate = new List<Line_Item_Employee__c>();
        Map<Id, Id> maplineItemEmployeeToChargeItem = new Map<Id,Id>();
        Map<Id, Id> mapEventToEmployee = new Map<Id,Id>();
        Set<Id> events = new Set<Id>();
        Set<Id> eventChargeItemIds = new Set<Id>();

        //Map the Employee to the Charge item
        for(Line_Item_Employee__c thisEmployee : records){
            if(thisEmployee.Line_Item__c !=NULL){
                maplineItemEmployeeToChargeItem.put(thisEmployee.Line_Item__c, thisEmployee.Id);
            }            
        }

        //Map the Event to the Employee based on the Charge Item
        for(Line_Item__c thisEventChargeItem : [SELECT Id, Reservation_Line__c FROM Line_Item__c WHERE Id IN :maplineItemEmployeeToChargeItem.keyset()]){
            if(thisEventChargeItem.Reservation_Line__c != NULL){
                mapEventToEmployee.put(maplineItemEmployeeToChargeItem.get(thisEventChargeItem.Id), thisEventChargeItem.Reservation_Line__c);
            }            
        }
                
        //Update the Event field on the Employee        
        for(Line_Item_Employee__c employee : records){
            if(employee.Event__c == NULL){
                employee.Event__c = mapEventToEmployee.get(employee.Id);
            }
        }        
    }

    public class LineItemEmployeeException extends Exception {}
}