src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>EndTime__c</fullName>
        <label>End Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Reservations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Tentative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed/Posted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospective</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-opened</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>North Campus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Campus</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Parent_Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Facility</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Facilities</relationshipLabel>
        <relationshipName>Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Use</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Repairs</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RoomsAgendaControllerTest.cls
/**
* @author joshi Prakash
* @date 09-22-2017
* @group Event management
* @description Controller class containing the test code for room agenda.
 **/
@isTest
private class RoomsAgendaControllerTest {
	@isTest
	static void addRoom() {
		/*Set Rooms Agenda as test page.*/
		PageReference pageRef = Page.RoomsAgenda;
		Test.setCurrentPage(pageRef);

		User ftUser = UserTest.createForeTeesUser();
		System.runAs(ftUser) {

			Event__c event = TestHandler.getEvent();
			event.RecordTypeId = Utility.searchRecordType('Sponsored Event', 'Event__c');
			update event;

			Location__c loc = new Location__c(Name = 'Test Location', Location__c = 'North Campus', Status__c = 'In Use');
			insert loc;

			Location__c loc2 = new Location__c(Name = 'child location', Location__c = 'North Campus2', Status__c = 'In Use', Parent_Facility__c = loc.id);
			insert loc2;

			ApexPages.currentPage().getParameters().put('id', event.id);

			Test.startTest();
			RoomsAgendaController apc = new RoomsAgendaController();
			//Create the related event without conflict
			apc.addNew();
			apc.clstGI.get(1).res.Location__c = loc.id;
			apc.addNew();
			apc.clstGI.get(2).res.Location__c = loc.id;
			apc.clstGI.get(2).res.StartTime__c = System.now().addHours(4);
			apc.clstGI.get(2).res.EndTime__c = System.now().addHours(6);
			apc.saveRec();

			System.assertEquals(apc.clstGI.size(), 3);
			//Create the reservation with time conflict
			apc.addNew();
			apc.clstGI.get(3).res.Location__c = loc.id;
			apc.saveRec();

			apc.BackToEvent();
			Test.stopTest();
		}
	}
}