src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Booked_Date__c</fullName>
        <defaultValue>IF(AND($RecordType.Name=&apos;Member Sponsored Event&apos;),NOW(),null)</defaultValue>
        <label>Booked Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CleanupTime__c</fullName>
        <formula>IF(AND(NOT(ISNULL(EndTime__c)), NOT(ISBLANK(EndTime__c)), NOT(ISPICKVAL(Cleanup_Time__c,&apos;&apos;))), IF(ISPICKVAL(Cleanup_Time__c,&apos;Half Hour&apos;), EndTime__c + 0.02083, IF(ISPICKVAL(Cleanup_Time__c,&apos;1 Hour&apos;), EndTime__c + 0.04166, EndTime__c + 0.08333)), IF(AND(NOT(ISNULL(EndTime__c)), NOT(ISBLANK(EndTime__c))), EndTime__c, null))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CleanupTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Cleanup_Time__c</fullName>
        <label>Cleanup Time</label>
        <picklist>
            <picklistValues>
                <fullName>Half Hour</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 Hour</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Hours</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contract_Due_Date__c</fullName>
        <label>Contract Due Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposit_Amount__c</fullName>
        <label>Deposit Amount Required</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Deposit_Received_Date__c</fullName>
        <label>Deposit Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deposit_Received__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deposit Received?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EndTime__c</fullName>
        <label>End Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>External_Location__c</fullName>
        <label>External Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Has_Children__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Children</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Clone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Clone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Reservations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Set</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Reservation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Reservation</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>Reservations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Post_Close_Date_Time__c</fullName>
        <label>Post Close Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Room_Setup_Details__c</fullName>
        <label>Room Setup Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SetupTime__c</fullName>
        <formula>IF(AND(NOT(ISNULL(StartTime__c)), NOT(ISBLANK(StartTime__c)), NOT(ISPICKVAL(Setup_Time__c,&apos;&apos;))), IF(ISPICKVAL(Setup_Time__c,&apos;Half Hour&apos;), StartTime__c - 0.02083, IF(ISPICKVAL(Setup_Time__c,&apos;1 Hour&apos;), StartTime__c - 0.04166, StartTime__c - 0.08333)), IF(AND(NOT(ISNULL(StartTime__c)), NOT(ISBLANK(StartTime__c))), StartTime__c, null))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SetupTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Setup_Time__c</fullName>
        <label>Setup Time</label>
        <picklist>
            <picklistValues>
                <fullName>Half Hour</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 Hour</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Hours</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Setup_Type__c</fullName>
        <label>Setup Type</label>
        <picklist>
            <picklistValues>
                <fullName>Classroom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crescent Rounds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exhibit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L-Shaped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Round Table</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>U-Shaped</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SponsoringMember__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sponsoring Member</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Your member sponsor must have a record type of Member.</errorMessage>
            <filterItems>
                <field>Contact.Record_Type_Name__c</field>
                <operation>equals</operation>
                <value>Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Events (Sponsoring Member)</relationshipLabel>
        <relationshipName>ReservationsContact</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sponsoring_Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account to Bill</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Events (Account to Bill)</relationshipLabel>
        <relationshipName>EventsSC</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartTime__c</fullName>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <label>State/Province</label>
        <picklist>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Tentative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed/Posted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospective</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-opened</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <recordTypes>
        <fullName>Reserved</fullName>
        <active>true</active>
        <label>Reserved</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>North Campus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Campus</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Parent_Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Facility</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Facilities</relationshipLabel>
        <relationshipName>Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Use</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Repairs</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RoomsAgendaController.cls
/*
@Name            : RoomsAgendaController
@Author          : joshi@3embed
@Date            : Sept 13, 2017
@Description     : Controller for display the related reservation and create and update the related reservation.
*/
public with sharing class RoomsAgendaController {

	//Class variables
	public Event__c res {get; set;}
	public List<GridItem> clstGI {get; set;}
	public Integer cIndex {get; set;}
	/*
	@Name : RoomsAgendaController
	@Description : Constructor to initalize the Rooms Agenda Page
	*/
	public RoomsAgendaController() {
		//Getting URL parameter to get reservation ID
		String recID = Apexpages.currentPage().getParameters().get('id');
		if (recID != null && recID != '') {
			Schema.SOBjectType sT = ((id)recID).getsObjectType();
			if (st.getDescribe().getName() == 'Event__c') {
				//Query Reservation
				List<Event__c> resLst = (List<Event__c>)Data.read('SELECT RecordType.Name,Location__r.Name,' + Utility.getFields('Event__c')
				                        + ' FROM Event__c WHERE ID =:eventid',

				new Map<String, Object> {
					'eventid' => recID
				});

				if (resLst.size() > 0) {
					res = resLst.get(0);
					prepareGridItemLst();
				}
			} else {
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Invaild banquet Id.'));
			}
		} else {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Invaild banquet Id.'));
		}
	}

	/*
	  @Name   :addNew
	  @Description :adds a new related reservation
	  */
	public void addNew() {
		GridItem gi = new GridItem();
		gi.index = 'new' + cIndex++;
		gi.isNew = true;
		gi.res = res.clone();
		gi.res.Is_Clone__c = true;
		gi.res.Parent_Reservation__c = res.Id;

		if (res.RecordType.Name == 'Sponsored Event' || res.RecordType.Name == 'Sponsored Event - Child') {
			gi.res.RecordTypeId = Schema.SObjectType.Event__c.getRecordTypeInfosByName().get('Sponsored Event - Child').getRecordTypeId();
		} 

		gi.res.Has_Children__c = FALSE;
		gi.res.Location__c = null;
		gi.res.Booked_Date__c = DateTime.Now();
		gi.res.Setup_Type__c = null;
		gi.res.Room_Setup_Details__c = null;
		gi.res.Post_Close_Date_Time__c = null;
		gi.res.Setup_Time__c = 'Half Hour';
		gi.res.Cleanup_Time__c = 'Half Hour';
		gi.res.External_Location__c = null;
		gi.res.Street_Address__c = null;
		gi.res.City__c = null;
		gi.res.State_Province__c = null;
		gi.res.Zip__c = null;
		gi.res.Deposit_Received_Date__c = null;
		gi.res.Deposit_Amount__c = null;
		gi.res.Deposit_Received__c = false;		
		gi.canFlag = false;
		clstGI.add(gi);
	}

	/*
	@Name   :saveRec
	@Description :Save multiple records
	*/
	public pageReference saveRec() {
		SavePoint sp = Database.setSavePoint();
		try {
	
			List<Event__c> resLst = new List<Event__c>();
			for (GridItem gi : clstGI) {
				gi.cErrorHighlight = '';
				//Check to get required information
				if (gi.res.Name == null || gi.res.Name == '' || gi.res.StartTime__c == null || gi.res.EndTime__c == null
				        || gi.res.Location__c == null) {
					throw new Utility.CustomException('Please enter the required information.');
				} else {
					if (gi.canFlag == true && gi.res.Status__c != 'Cancelled') { gi.res.Status__c = 'Cancelled'; }
					if (gi.res.Id != null && gi.res.Parent_Reservation__c == null && clstGI.size() > 1) {
						gi.res.Has_Children__c = true;
					}

					if(gi.isNew==true)
					{
						gi.res.Id = null;
					}

					resLst.add(gi.res);								
				}				
			}
		
			if (resLst.size() > 0 && Schema.sObjectType.Event__c.isCreateable()
			        && Schema.sObjectType.Event__c.isUpdateable()) {

				//upsert resLst;
				Data.upsurt(resLst, Event__c.Id.getDescribe().getSObjectField(), new Set<String>());
				Map<ID, Event__c> resMap = new Map<ID, Event__c>(resLst);
				Map<ID, ID> reserClubFa = new Map<ID, ID>();
				for (Event__c r : resLst) {
					reserClubFa.put(r.Id, r.Location__c);
				}

				List<Location__c> facilityLst = (List<Location__c>)Data.read('SELECT Id, Name, Parent_Facility__c FROM Location__c WHERE Id IN :locationIds',
				new Map<String, Object> {
					'locationIds' => reserClubFa.values()
				});

				Map<ID, List<Location__c>> facilityResLst = new Map<ID, List<Location__c>>();
				for (Location__c f : facilityLst) {
					facilityResLst.put(f.Id, new List<Location__c>());
					//Add all facilities parent and child				
					facilityResLst.get(f.Id).addAll(Utility.getChildFacilities(new List<Location__c> {f}));
				}

				List<Event__c> parentTrgEvent = (List<Event__c>)Data.read('SELECT Id, Location__c, Cleanup_Time__c, Setup_Time__c, StartTime__c, EndTime__c,'
												+ ' Status__c, SponsoringMember__c, Sponsoring_Customer__c, Contract_Due_Date__c, Max_Seats__c,'
												+ ' (SELECT Id, Name, StartTime__c, EndTime__c,'												
				                                + ' Location__c FROM Reservations__r WHERE RecordType.Name =:recordtype)'
				                                + ' FROM Event__c'
				                                + ' WHERE Id IN :eventIds',

				new Map<String, Object> {
					'recordtype' => 'Reserved',
					'eventIds' => reserClubFa.keySet()
				});
					
				List<Event__c> lstReservations = new List<Event__c>();
				List<Event__c> lstDelete = new List<Event__c>();

				for (Event__c pTrgEvt : parentTrgEvent) {
					List<Event__c> existingReserved = new List<Event__c>();
					for (Event__c rEvt : pTrgEvt.Reservations__r) {
						existingReserved.add(rEvt);
					}

					Map<Id, Event__c> mapFacEvents = new Map<Id, Event__c>();
					for (Event__c event : existingReserved) {
						mapFacEvents.put(event.Location__c, event);
					}
				
					Set<Id> setChainEventIds = new Set<Id>();
					if (facilityResLst.size() > 0 && facilityResLst.containsKey(pTrgEvt.Location__c)) {
						for (Location__c fac : facilityResLst.get(pTrgEvt.Location__c)) {
							if (mapFacEvents.containsKey(fac.Id)) {
								//Move the time
								Event__c event = mapFacEvents.get(fac.Id);
								event.StartTime__c = pTrgEvt.StartTime__c;
								event.EndTime__c = pTrgEvt.EndTime__c;
								event.Setup_Time__c = pTrgEvt.Setup_Time__c;
								event.Cleanup_Time__c = pTrgEvt.Cleanup_Time__c;								
								lstReservations.add(event);
								setChainEventIds.add(mapFacEvents.get(fac.Id).Id);
							} else {
								//Create the reservation
								Event__c event = new Event__c(
								    Name = 'Reserved',								  
								    StartTime__c = pTrgEvt.StartTime__c,
								    EndTime__c = pTrgEvt.EndTime__c,
								    Parent_Reservation__c = pTrgEvt.id,
								    RecordTypeId = Schema.SObjectType.Event__c.getRecordTypeInfosByName().get('Reserved').getRecordTypeId(),
								    Location__c = fac.id,
								    Setup_Time__c = pTrgEvt.Setup_Time__c,
								    Cleanup_Time__c = pTrgEvt.Cleanup_Time__c,
								    Status__c = pTrgEvt.Status__c,
								    Contract_Due_Date__c = pTrgEvt.Contract_Due_Date__c,
								    SponsoringMember__c = pTrgEvt.SponsoringMember__c,
								    Sponsoring_Customer__c = pTrgEvt.Sponsoring_Customer__c,
								    Max_Seats__c = pTrgEvt.Max_Seats__c
								);
								lstReservations.add(event);
							}
						}
					}
					//Delete the reserved events that are not part of the hierarchy
					for (Event__c event : existingReserved) {
						if (!setChainEventIds.contains(event.id)) {
							lstDelete.add(event);
						}
					}
				}			
				//upsert lstReservations;
				Data.upsurt(lstReservations, Event__c.Id.getDescribe().getSObjectField(), new Set<String>());
				Data.remove(lstDelete);
				resLst.addAll(lstReservations);

				List<Event__c> conflictList = new List<Event__c>();
				conflictList.addAll(resLst);

				Set<Id> locationIdSet = new Set<Id>();
				for (Event__c r : resLst) {
					locationIdSet.add(r.Location__c);
				}

				List<Event__c> allReservations = (List<Event__c>)Data.read(
				                                     'SELECT Id, Location__c, SetupTime__c, CleanupTime__c from Event__c'
				                                     + ' WHERE Status__c !=:Cancelled AND Location__c IN :locations',
				new Map<String, Object> {
					'Cancelled' => 'Cancelled',
					'locations' => locationIdSet
				});

				map<String, Double> setupCleanupMap = new Map<String, Double> {
					'Half Hour' => 0.02083,
					'1 Hour' => 0.04166,
					'2 Hours' => 0.08333
				};

				Datetime starttime;
				Datetime endtime;

				for (Event__c relatedEvent : conflictList) {

					starttime = relatedEvent.StartTime__c;
					endtime = relatedEvent.EndTime__c;

					if (relatedEvent.Setup_Time__c != null) {
						starttime = relatedEvent.StartTime__c - setupCleanupMap.get(relatedEvent.Setup_Time__c);
					}

					if (relatedEvent.Cleanup_Time__c != null) {
						endtime = relatedEvent.EndTime__c + setupCleanupMap.get(relatedEvent.Cleanup_Time__c);
					}

					for (Event__c existingEvent : allReservations) {
						if (existingEvent.Location__c == relatedEvent.Location__c && existingEvent.Id != relatedEvent.Id && ((existingEvent.SetupTime__c >= starttime && existingEvent.SetupTime__c <= endtime) || (existingEvent.CleanupTime__c >= starttime && existingEvent.CleanupTime__c <= endtime) || (starttime>= existingEvent.SetupTime__c && endtime<= existingEvent.CleanupTime__c))) {
							throw new Utility.CustomException('There is time conflict with an existing event. Please try again with a differet time.');
						}
					}
				}

				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Confirm, 'Saved Successfully!'));
				prepareGridItemLst();

			}
		} catch (DMLException e) {
			Integer numErrors = e.getNumDml();
			Integer iError;
			for (Integer i = 0; i < numErrors; i++) {
				iError = e.getDmlIndex(i);
			}
			if (iError != null) { clstGI.get(iError).cErrorHighlight = 'Error'; }			
			ApexPages.addMessages(e);			
			Database.rollBack(sp);
		} catch (Exception e) {			
			ApexPages.addMessages(e);
			Database.rollBack(sp);
		}
		return null;
	}

	//Prepare Grid Item list
	public void prepareGridItemLst() {

		cIndex = 0;
		clstGI = new List<GridItem>();		
		List<Event__c> relResLst = (List<Event__c>)Data.read('SELECT  RecordType.Name, Location__r.Name, ' + Utility.getFields('Event__c')
		                           + ', (SELECT RecordType.Name,Location__r.Name,' + Utility.getFields('Event__c')
		                           + ' FROM Reservations__r WHERE Parent_Reservation__c=:parenteventid AND (Status__c !=:childstatus)'
		                           + ' AND RecordType.Name!=:recordtype) FROM Event__c WHERE ID =:eventid AND (Status__c !=:eventstatus)',

		new Map<String, Object> {
			'parenteventid' => res.Id,
			'childstatus' => 'Cancelled',
			'recordtype' => 'Reserved',
			'eventid' => res.Id,
			'eventstatus' => 'Cancelled'
		});

		//Prepare Grid Item wrapper to bind the reservation values
		for (Event__c r : relResLst) {
			GridItem gi = new GridItem();
			gi.index = 'new' + cIndex++;
			gi.rccID = r.Id;
			gi.res = r;
			gi.canFlag = false;
			gi.isNew = false;
			clstGI.add(gi);
			//For child reservations
			for (Event__c res : r.Reservations__r) {
				GridItem gii = new GridItem();
				gii.index = 'new' + cIndex++;
				gii.rccID = res.Id;
				gii.res = res;
				gii.canFlag = false;
				clstGI.add(gii);
			}
		}
	}

	/*
	@Name   :backTORes
	@Description :backTORes records
	*/
	public pageReference BackToEvent() {
		return new PageReference('/' + res.Id);
	}
	/*
	@Name   :GridItem
	@Description :Inner class for grid items
	*/
	public class GridItem {
		public Event__c res {get; set;}
		public Boolean canFlag {get; set;}
		public String index {get; set;}
		public String rccID {get; set;}
		public String cErrorHighlight {get; set;}
		public Boolean isNew {get; set;}
	}
}