src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Cancellation_Date__c</fullName>
        <label>Cancellation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Parent_Reservation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Reservation</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>Reservations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Tentative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed/Posted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospective</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-opened</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CancelEventController.cls
public with sharing class CancelEventController {
	public boolean isShowPopUp {get; set;}
	public boolean isInfoPopUp {get; set;}
	public String eventId {get; set;}
	public Event__c event {get; set;}

	public CancelEventController() {
		isShowPopUp = false;
		isInfoPopUp = false;
		eventId = Apexpages.currentPage().getParameters().get('Id');

		//Query Reservation
		List<Event__c> eventList = (List<Event__c>)Data.read('SELECT Id, Name, Status__c, Cancellation_Date__c, Parent_Reservation__c'
		                           + ' FROM Event__c WHERE ID =:eventid',

		new Map<String, Object> {
			'eventid' => eventId
		});

		if (eventList.size() > 0) {
			event = eventList.get(0);
			if (event.Status__c == 'Cancelled'){
				isInfoPopUp = true;
			} else if (event.Parent_Reservation__c == null) {
				isShowPopUp = true;
			}
		}
	}

	public pageReference cancelChild() {
		if (event != null && isShowPopUp == false && isInfoPopUp ==false) {			
			return cancelEvent();
		}
		return null;
	}
	/*
	@Name   :backTORes
	@Description :backTORes records
	*/
	public pageReference backToEvent() {
		return new PageReference('/' + eventId);
	}

	public pageReference cancelEvent() {
		if (event != null) {
			List<Event__c> allEvents = new List<Event__c>();
			event.Cancellation_Date__c = System.today();
			event.Status__c = 'Cancelled';
			allEvents.add(event);
			//Query Reservation
			List<Event__c> eventList = (List<Event__c>)Data.read('SELECT Id, Name, Status__c, Cancellation_Date__c, Parent_Reservation__c'
			                           + ' FROM Event__c WHERE Parent_Reservation__c =:eventid and Status__c !=:Cancelled',

			new Map<String, Object> {
				'eventid' => eventId,
				'Cancelled' => 'Cancelled'
			});

			for (Event__c childEvent : eventList) {
				childEvent.Cancellation_Date__c = System.today();
				childEvent.Status__c = 'Cancelled';
				allEvents.add(childEvent);
			}

			Data.modify(allEvents);
			return backToEvent();
		}
		return null;
	}

}