src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <fields>
        <fullName>Debit_Credit__c</fullName>
        <formula>CASE( Category__c , &apos;Asset&apos;, &apos;Debit&apos;, &apos;Liability&apos;, &apos;Credit&apos;, &apos;Equity&apos;,&apos;Credit&apos;,&apos;Income&apos;,&apos;Credit&apos;,&apos;Expense&apos;,&apos;Debit&apos;, &apos;&apos;)</formula>
        <label>Debit/Credit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>North Campus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Campus</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/cmsft_FinancialAccountSelector.cls
/**
* @author Salesforce.com Foundation
* @date 2014
*
* @group Financial Management
*
* @description financial account trigger selectore to get the data from database.
*/

/**
 * Class encapsulates query logic for Financial_Account__c
 *
 * https://developer.salesforce.com/page/Apex_Enterprise_Patterns_-_Selector_Layer
 **/
public class cmsft_FinancialAccountSelector extends fflib_SObjectSelector
{
	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField> {
			Financial_Account__c.Id,
			Financial_Account__c.Debit_Credit__c
		};
	}
	public Schema.SObjectType getSObjectType()
	{
		return Financial_Account__c.sObjectType;
	}
	public List<Financial_Account__c> selectById(Set<ID> idSet)
	{
		return (List<Financial_Account__c>) selectSObjectsById(idSet);
	}
	public Map<Id, SObject> selectAllFinancialAccount(){
		assertIsAccessible();
		fflib_QueryFactory conAccQuery = newQueryFactory();
		return new Map<Id, SObject>(Database.query(conAccQuery.toSOQL()));
	}

		/**
	* @description Returns id,Location__c as pet the condition
	*/
	public List<Financial_Account__c> get_finAccountValues(string where_fieldName) {
		assertIsAccessible();
		string query_condition = where_fieldName + '= true';
		return (List<Financial_Account__c>) Database.query(
		           'select id,Location__c from Financial_Account__c ' +

		           'where ' + query_condition  );

	}

}