src/objects/Financial_Journal_Entry__c.object
<CustomObject>
    <label>Financial Journal Entry</label>
    <nameField>
        <displayFormat>FJE-{00000000}</displayFormat>
        <label>Financial Journal Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Financial_Journal_Entry__c</fullName>
        <formula>HYPERLINK(Journal_Entry__c,Journal_Entry__r.Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Financial Journal Entry</label>
        <type>Text</type>
    </fields>
    <label>Vendor Invoice</label>
    <nameField>
        <displayFormat>VNDRINVENTR-{0000000}</displayFormat>
        <label>Vendor Invoice Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/cmsft_AccountPayableService.cls
/**
 * https://developer.salesforce.com/page/Apex_Enterprise_Patterns_-_Service_Layer
 * @Date: 20th May - 2017
 * @Author: Jyotig@mobifyi.com 
 * @group: Financial Management 
 * @Description: service layer for AccountsPayableController
 */

public with sharing class cmsft_AccountPayableService
{
	/**
    * @Description : method to search vendor invoices that are not posted between startdate and enddate
    */
	public List<Vendor_Invoice__c> getVendorInvoiceListService(Date startDate, Date endDate){
		return cmsft_AccountPayableServiceImpl.getVendorInvoiceListImpl(startDate, endDate);
	}

	/**
    * @Description : method to post selected vendor invoices
    */
	public void postSelectedEnteriesService(List<Vendor_Invoice__c> unpostedVendInv, Date postDate, Date endDate){
		cmsft_AccountPayableServiceImpl.postSelectedEnteries(unpostedVendInv, postDate, endDate);
	}

	/**
    * @Description : method to get invoices that are posted today
    */
	public List<Vendor_Invoice__c> getListOfPostedInvoicesService(Date startDate, Date endDate){
		return cmsft_AccountPayableServiceImpl.getListOfPostedInvoices(startDate, endDate);
	}

	/**
    * @Description : method to get invoices that are selected for posting
    */
	public List<Vendor_Invoice__c> getListOfSelectedInvoicesForPostingService(List<Vendor_Invoice__c> vendInvList){
		return cmsft_AccountPayableServiceImpl.getListOfSelectedInvoicesForPosting(vendInvList);
	}

	/**
	* @Description : method to check amount of vendor invoice is equal to sum of vendor invoice line amount or not
	* @return : true if not equals
	*/
	public List<Vendor_Invoice__c> checkAmountService(List<Vendor_Invoice__c> vendInv, String amountEqualStatus)
	{
		return cmsft_AccountPayableServiceImpl.checkAmount(vendInv, amountEqualStatus);
	}

	/**
	* @Description : mark the passed vendor invoice post status as checked
	*/
	public List<Vendor_Invoice__c> markInvoicePostStatusCheckedService(List<Vendor_Invoice__c> unpostedVendInv, List<Vendor_Invoice__c> InvListToChangePS)
	{
		return cmsft_AccountPayableServiceImpl.markInvoicePostStatusChecked(unpostedVendInv, InvListToChangePS);
	}

	/**
	* @Description : change post date of financial journal entry
	*/
	public void changePostDateOfFJEService(List<Financial_Journal_Entry__c> finJeEntryList)
	{
		cmsft_AccountPayableServiceImpl.changePostDateOfFJE(finJeEntryList);
	}
}