src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Journal_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Entry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Post_Date__c</fullName>
        <label>Post Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Posted?</label>
        <type>Checkbox</type>
    </fields>
    <label>Financial Journal Entry</label>
    <nameField>
        <displayFormat>FJE-{00000000}</displayFormat>
        <label>Financial Journal Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Journal_Line__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Credit__c</fullName>
        <formula>IF((Financial_Account__r.Debit_Credit__c==&quot;Credit&quot; &amp;&amp; Amount__c&gt;0)||(Financial_Account__r.Debit_Credit__c==&quot;Debit&quot; &amp;&amp; Amount__c&lt;0),ABS(Amount__c),0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Credit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Debit__c</fullName>
        <formula>IF((Financial_Account__r.Debit_Credit__c==&quot;Debit&quot; &amp;&amp; Amount__c&gt;0)||(Financial_Account__r.Debit_Credit__c==&quot;Credit&quot; &amp;&amp; Amount__c&lt;0),ABS(Amount__c),0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Debit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Journal Lines</relationshipLabel>
        <relationshipName>Financial_Journal_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Journal_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Journal Entry</label>
        <referenceTo>Financial_Journal_Entry__c</referenceTo>
        <relationshipName>Financial_Journals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Post_Date__c</fullName>
        <label>Post Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Posted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <label>Financial Journal Line</label>
    <nameField>
        <displayFormat>FINJRNL-{000000}</displayFormat>
        <label>Financial Journal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Journal Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Financial_Journal_Entry__c</fullName>
        <formula>HYPERLINK(Journal_Entry__c,Journal_Entry__r.Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Financial Journal Entry</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Post_Date__c</fullName>
        <label>Post Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <formula>Post_Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Posted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoice_Check__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Invoice Check</label>
        <referenceTo>Vendor_Invoice_Check__c</referenceTo>
        <relationshipLabel>Vendor Invoices</relationshipLabel>
        <relationshipName>Vendor_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vendor Invoice</label>
    <nameField>
        <displayFormat>VNDRINVENTR-{0000000}</displayFormat>
        <label>Vendor Invoice Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice_Check__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Check_Number__c</fullName>
        <label>Check Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoice_Check_Batch__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vendor Invoice Check Batch</label>
        <referenceTo>Vendor_Invoice_Check_Batch__c</referenceTo>
        <relationshipLabel>Vendor Invoice Checks</relationshipLabel>
        <relationshipName>Vendor_Invoice_Checks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Void__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Void</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Voided_Financial_Journal_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Voided Financial Journal Entry</label>
        <referenceTo>Financial_Journal_Entry__c</referenceTo>
        <relationshipLabel>Vendor Invoice Checks</relationshipLabel>
        <relationshipName>Vendor_Invoice_Checks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vendor Invoice Check</label>
    <nameField>
        <displayFormat>VNDRINVCK-{0000000}</displayFormat>
        <label>Vendor Invoice Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice_Check_Batch__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Date__c</fullName>
        <label>Batch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Journal_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Journal Entry</label>
        <referenceTo>Financial_Journal_Entry__c</referenceTo>
        <relationshipLabel>Vendor Invoice Check Batches</relationshipLabel>
        <relationshipName>Vendor_Invoice_Check_Batches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Void__c</fullName>
        <defaultValue>false</defaultValue>
        <description>check if check batch is voided.</description>
        <label>Void</label>
        <type>Checkbox</type>
    </fields>
    <label>Vendor Invoice Check Batch</label>
    <nameField>
        <displayFormat>VICB-{0000000}</displayFormat>
        <label>Vendor Invoice Check Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Check Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice_Line__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Vendor Invoice Lines (Financial Account)</relationshipLabel>
        <relationshipName>Vendor_Invoice_Lines</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Journal_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Journal Line</label>
        <referenceTo>Financial_Journal_Line__c</referenceTo>
        <relationshipLabel>Vendor Invoice Lines</relationshipLabel>
        <relationshipName>Vendor_Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Check</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Post_Date__c</fullName>
        <label>Post Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Posted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoice_Check__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Invoice Check</label>
        <referenceTo>Vendor_Invoice_Check__c</referenceTo>
        <relationshipLabel>Vendor Invoice Lines</relationshipLabel>
        <relationshipName>Vendor_Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoice__c</fullName>
        <label>Vendor Invoice</label>
        <referenceTo>Vendor_Invoice__c</referenceTo>
        <relationshipLabel>Vendor Invoice Lines</relationshipLabel>
        <relationshipName>Vendor_Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vendor Invoice Line</label>
    <nameField>
        <displayFormat>VNDRSTMTLNE-{0000000}</displayFormat>
        <label>Vendor Invoice Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Paid__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount Paid</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <formula>Vendor_Invoice_Line__r.Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <formula>TEXT(Vendor_Invoice_Line__r.Payment_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoice_Check__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Invoice Check</label>
        <referenceTo>Vendor_Invoice_Check__c</referenceTo>
        <relationshipLabel>Vendor Invoice Payments</relationshipLabel>
        <relationshipName>Vendor_Invoice_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoice_Line__c</fullName>
        <label>Vendor Invoice Line</label>
        <referenceTo>Vendor_Invoice_Line__c</referenceTo>
        <relationshipLabel>Vendor Invoice Payments</relationshipLabel>
        <relationshipName>Vendor_Invoice_Payments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoice__c</fullName>
        <label>Vendor Invoice</label>
        <referenceTo>Vendor_Invoice__c</referenceTo>
        <relationshipLabel>Vendor Invoice Payments</relationshipLabel>
        <relationshipName>Vendor_Invoice_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vendor Invoice Payment</label>
    <nameField>
        <displayFormat>VNDRSTMTPAY-{0000000}</displayFormat>
        <label>Vendor Invoice Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/voidCheckorCheckBatchService.cls
public with sharing class voidCheckorCheckBatchService {
    public voidCheckorCheckBatchService() {

    }
    public Vendor_Invoice_Check__c getCheckDetail(string checkId) {
        Vendor_Invoice_Check__c VIC = (Vendor_Invoice_Check__c) Data.read('select id, Void__c, Amount__c, Check_Number__c, Vendor_Invoice_Check_Batch__r.Financial_Journal_Entry__c from ' +
                                      ' Vendor_Invoice_Check__c where id =:checkId',
        new Map<String, Object> {
            'checkId' => checkId
        }).get(0);
        return VIC;
    }
    public List<Vendor_Invoice_Check__c> getAllChecks(string batchId) {
        List<Vendor_Invoice_Check__c> VIC = (List<Vendor_Invoice_Check__c>) Data.read('select id, Void__c, Amount__c, Check_Number__c, Vendor_Invoice_Check_Batch__r.Financial_Journal_Entry__c from ' +
                                            ' Vendor_Invoice_Check__c where Vendor_Invoice_Check_Batch__c =:batchId',
        new Map<String, Object> {
            'batchId' => batchId
        });
        return VIC;
    }
    public Vendor_Invoice_Check_Batch__c getBatchDetail(string batchId) {
        Vendor_Invoice_Check_Batch__c VICB = (Vendor_Invoice_Check_Batch__c) Data.read('select id,Void__c, Batch_Date__c  from ' +
                                             ' Vendor_Invoice_Check_Batch__c where id =:batchId',
        new Map<String, Object> {
            'batchId' => batchId
        }).get(0);
        return VICB;
    }
    public void VoidCheck(List<Vendor_Invoice_Check__c> CheckDetails, date postedDate) {
        if (CheckDetails.size() > 0) {
            Vendor_Invoice_Check__c CheckDetail = CheckDetails.get(0);
            system.debug('check this entry  :' + CheckDetail.Vendor_Invoice_Check_Batch__r.Financial_Journal_Entry__c);
            List<Financial_Journal_Line__c> journalLines = (List<Financial_Journal_Line__c>)Data.read(
                        'select Financial_Account__c,Credit__c,Debit__c from Financial_Journal_Line__c where Financial_Journal_Entry__c =:entryId ',
            new Map<String, Object> {
                'entryId' => CheckDetail.Vendor_Invoice_Check_Batch__r.Financial_Journal_Entry__c
            }
                    );
            double Amount = math.abs(double.valueOf(CheckDetail.Amount__c));
            Financial_Journal_Entry__c fjEntry = new Financial_Journal_Entry__c();
            fjEntry.Description__c = 'voided Check #' + CheckDetail.Check_Number__c;
            fjEntry.Entry_Date__c = postedDate;
            fjEntry.Posted__c = true;
            fjEntry.Post_Date__c = postedDate;
            data.create(fjEntry);

            string CreditAccount = '';
            string DebitAccount = '';
            for (Financial_Journal_Line__c lines : journalLines) {
                if (lines.Credit__c != 0) {
                    DebitAccount = lines.Financial_Account__c;
                } else {
                    CreditAccount = lines.Financial_Account__c;
                }
            }
            Financial_Journal_Line__c CreditLine = new Financial_Journal_Line__c();
            Financial_Journal_Line__c DebitLine = new Financial_Journal_Line__c();

            string debitcredit = Utility.getCredDebitStatus(CreditAccount);
            CreditLine.Amount__c = Amount * -1;
            if (debitcredit == 'Credit') {
                CreditLine.Amount__c = Amount;
            }
            CreditLine.Financial_Account__c = CreditAccount;
            CreditLine.Financial_Journal_Entry__c = fjEntry.Id;
            CreditLine.Transaction_Date__c = date.today();
            data.create(CreditLine);

            debitcredit = Utility.getCredDebitStatus(DebitAccount);
            DebitLine.Amount__c = Amount;
            if (debitcredit == 'Credit') {
                DebitLine.Amount__c = Amount * -1;
            }
            DebitLine.Financial_Account__c = DebitAccount;
            DebitLine.Financial_Journal_Entry__c = fjEntry.Id;
            DebitLine.Transaction_Date__c = date.today();
            data.create(DebitLine);

            CheckDetail.Void__c = true;
            CheckDetail.Voided_Financial_Journal_Entry__c = fjEntry.id;
            data.modify(CheckDetail);

            List<Vendor_Invoice_Payment__c> PaymentDetail = (List<Vendor_Invoice_Payment__c>)Data.read(
                        'select Payment_Type__c,Amount_Paid__c,Amount__c ,Vendor_Invoice__c ,Vendor_Invoice_Line__c  from Vendor_Invoice_Payment__c where Vendor_Invoice_Check__c =:checkId ',
            new Map<String, Object> {
                'checkId' => CheckDetail.Id
            }
                    );
            for (Vendor_Invoice_Payment__c Oldpayment : PaymentDetail) {

                Vendor_Invoice_Payment__c payment = new Vendor_Invoice_Payment__c();
                payment.Amount_Paid__c = 0;
                payment.Vendor_Invoice__c = Oldpayment.Vendor_Invoice__c;
                payment.Vendor_Invoice_Line__c = Oldpayment.Vendor_Invoice_Line__c;
                Data.create(payment);
                Oldpayment.Amount_Paid__c = 0;
                data.modify(Oldpayment);
            }
        }
    }
}