src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Journal_Line__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Journal Lines</relationshipLabel>
        <relationshipName>Financial_Journal_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Posted?</label>
        <type>Checkbox</type>
    </fields>
    <label>Financial Journal Line</label>
    <nameField>
        <displayFormat>FINJRNL-{000000}</displayFormat>
        <label>Financial Journal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Journal Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FinancialJournalLineTriggerHandlerTest.cls
/**
* @author joshi Prakash
* @date 07-07-2017
* @group Financial Management
* @description Test class for adding credit debit total on financial account.
 **/
@isTest
private class FinancialJournalLineTriggerHandlerTest
{
	@isTest
	static void CreditDebitRollupLogic()
	{
		Financial_Account__c fa = TestHandler.getFinancialAccount1();
		Financial_Journal_Line__c journalLine=new Financial_Journal_Line__c();
        journalLine.Amount__c = 10;
        journalLine.Financial_Account__c = fa.id;
        journalLine.Description__c = 'Rollup';      
        journalLine.Posted__c=true;       
        Data.create(journalLine);
        
        List<Financial_Journal_Line__c> lines = (List<Financial_Journal_Line__c>)Data.read(
                     'Select id, Financial_Account__c from Financial_Journal_Line__c',null       
                 );

        System.assertEquals(lines.size(),1);

        lines.get(0).Amount__c=33;
        Data.modify(lines.get(0));
	}
}