src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Journal_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Posted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Recurring_Entry_Name__c</fullName>
        <label>Recurring Entry Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recurring_Entry__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recurring Entry</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Recurring_Journal_Frequency__c</fullName>
        <label>Recurring Journal Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Annually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financial Journal Entry</label>
    <nameField>
        <displayFormat>FJE-{00000000}</displayFormat>
        <label>Financial Journal Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Journal_Line__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Journal Lines</relationshipLabel>
        <relationshipName>Financial_Journal_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Journal_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Journal Entry</label>
        <referenceTo>Financial_Journal_Entry__c</referenceTo>
        <relationshipName>Financial_Journals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Posted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <label>Financial Journal Line</label>
    <nameField>
        <displayFormat>FINJRNL-{000000}</displayFormat>
        <label>Financial Journal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Journal Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RecurringJournalEntryControllerTest.cls
/**
* @author joshi Prakash
* @date 06-20-2017
* @group Financial Management
* @description Controller class to create update and delete financial manual journal entry
 **/
@isTest
private class RecurringJournalEntryControllerTest {
    @isTest
    static void RecurringJournalEntryControllerCRUDTest() {

        /*Create new finacial journal entry block*/
        PageReference pageRef = Page.RecurringJournalEntry;
        Test.setCurrentPage(pageRef);

        Financial_Account__c fa = TestHandler.getFinancialAccount1();
        Financial_Journal_Line__c fjl = new Financial_Journal_Line__c(Financial_Account__c = fa.id, Transaction_Date__c = Date.today(), Posted__c = true, Amount__c = 10);
        ApexPages.StandardController sc = new ApexPages.StandardController(fjl);
        RecurringJournalEntryController apc = new RecurringJournalEntryController(sc);

        Test.startTest();

        List<RecurringJournalEntryController.ManualJournalLine> initialGrids = apc.manEntry.getJournalList();
        system.assertEquals(initialGrids.size(), 10);

        apc.numberLinesToAdd = 10;
        apc.addNewEntryLines();
        initialGrids = apc.manEntry.getJournalList();
        system.assertEquals(initialGrids.size(), 20);

        apc.manEntry.fje.Recurring_Entry_Name__c = 'Test';
        apc.manEntry.fje.Recurring_Journal_Frequency__c = 'Monthly';

        apc.manEntry.mjlList.get(0).linecrd = '10';
        apc.manEntry.mjlList.get(0).fjl.Financial_Account__c = fa.id;
        apc.manEntry.mjlList.get(0).fjl.Description__c = 'Test finacial journal line';

        apc.manEntry.mjlList.get(1).debit = '10';
        apc.manEntry.mjlList.get(1).fjl.Financial_Account__c = fa.id;
        apc.manEntry.mjlList.get(1).fjl.Description__c = 'Test finacial journal line';
        apc.calDebCredTotal();

        apc.addNewEntry();

        List<Financial_Journal_Entry__c> fjeLst = (List<Financial_Journal_Entry__c>)Data.read(
                    'select Id, (select id from Financial_Journals__r) from Financial_Journal_Entry__c where Recurring_Entry__c = :isRecurring',
        new Map<String, Object> {
            'isRecurring' => true
        }
                );

        System.assertEquals(fjeLst.get(0).Financial_Journals__r.size(), 2);
        /**Insert new new entries ends**/

        /**Update existing entries start**/
        apc.cSelId = apc.getmanualEntries().get(0).fje.id;
        apc.setSelFJE();
        apc.numberLinesToAdd = 10;
        apc.addNewExistingLines();

        apc.selectedMe.mjlList.get(2).linecrd = '10';
        apc.selectedMe.mjlList.get(2).fjl.Financial_Account__c = fa.id;
        apc.selectedMe.mjlList.get(2).fjl.Description__c = 'Test finacial journal line';

        apc.selectedMe.mjlList.get(3).debit = '10';
        apc.selectedMe.mjlList.get(3).fjl.Financial_Account__c = fa.id;
        apc.selectedMe.mjlList.get(3).fjl.Description__c = 'Test finacial journal line';

        //Delete one manual journal line at the time of editing the grid
        apc.fjeId = apc.getmanualEntries().get(0).fje.id;
        apc.fjlId = apc.selectedMe.mjlList.get(1).fjl.id;
        apc.delFJL();

        apc.updateEntry();
        apc.closeSelectedME();

        fjeLst = (List<Financial_Journal_Entry__c>)Data.read(
                     'select Id, (select id from Financial_Journals__r) from Financial_Journal_Entry__c where Recurring_Entry__c = :isRecurring',
        new Map<String, Object> {
            'isRecurring' => true
        }
                 );

        System.assertEquals(fjeLst.get(0).Financial_Journals__r.size(), 3);
        /**Update existing entries end**/

        /**Clone selected template**/
        apc.cSelId = apc.getmanualEntries().get(0).fje.id;
        apc.setSelFJE();
        apc.cloneSelected();

        /**Delete manual journal entry start**/
        apc.cSelDelId = apc.getmanualEntries().get(0).fje.id;
        apc.delSelFJE();
        System.assertEquals(apc.getmanualEntries().size(), 0);
        /**Delete manual journal entry end**/

        Test.stopTest();
    }
}