src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Journal_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Entry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Manual_Entry__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Manual Entry</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Post_Date__c</fullName>
        <label>Post Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Posted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Recurring_Entry_Name__c</fullName>
        <label>Recurring Entry Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recurring_Entry__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recurring Entry</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Recurring_Journal_Frequency__c</fullName>
        <label>Recurring Journal Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Annually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financial Journal Entry</label>
    <nameField>
        <displayFormat>FJE-{00000000}</displayFormat>
        <label>Financial Journal Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Journal_Line__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Credit__c</fullName>
        <formula>IF((Financial_Account__r.Debit_Credit__c==&quot;Credit&quot; &amp;&amp; Amount__c&gt;0)||(Financial_Account__r.Debit_Credit__c==&quot;Debit&quot; &amp;&amp; Amount__c&lt;0),ABS(Amount__c),0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Credit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Debit__c</fullName>
        <formula>IF((Financial_Account__r.Debit_Credit__c==&quot;Debit&quot; &amp;&amp; Amount__c&gt;0)||(Financial_Account__r.Debit_Credit__c==&quot;Credit&quot; &amp;&amp; Amount__c&lt;0),ABS(Amount__c),0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Debit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Journal Lines</relationshipLabel>
        <relationshipName>Financial_Journal_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Journal_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Journal Entry</label>
        <referenceTo>Financial_Journal_Entry__c</referenceTo>
        <relationshipName>Financial_Journals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Post_Date__c</fullName>
        <label>Post Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Posted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Recurring_Journal_Line__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recurring Journal Line</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <label>Financial Journal Line</label>
    <nameField>
        <displayFormat>FINJRNL-{000000}</displayFormat>
        <label>Financial Journal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Journal Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ManualFinancialJournalControllerTest.cls
/**
* @author joshi Prakash
* @date 06-20-2017
* @group Financial Management
* @description Controller class to create update and delete financial manual journal entry
 **/
@isTest
private class ManualFinancialJournalControllerTest {
    @isTest
    static void ManualFinancialJournalCRUDTest() {

        /*Create new finacial journal entry block*/
        PageReference pageRef = Page.ManualFinancialJournal;
        Test.setCurrentPage(pageRef);

        Financial_Account__c fa = TestHandler.getFinancialAccount1();
        Financial_Journal_Line__c fjl = new Financial_Journal_Line__c(Financial_Account__c = fa.id, Transaction_Date__c = Date.today(), Posted__c = true, Amount__c = 10);
        ApexPages.StandardController sc = new ApexPages.StandardController(fjl);
        ManualFinancialJournalController apc = new ManualFinancialJournalController(sc);

        Test.startTest();

        List<ManualFinancialJournalController.ManualJournalLine> initialGrids = apc.manEntry.getJournalList();
        system.assertEquals(initialGrids.size(), 10);

        apc.numberLinesToAdd = 10;
        apc.addNewEntryLines();
        initialGrids = apc.manEntry.getJournalList();
        system.assertEquals(initialGrids.size(), 20);

        apc.manEntry.mjlList.get(0).linecrd = '10';
        apc.manEntry.mjlList.get(0).fjl.Financial_Account__c = fa.id;
        apc.manEntry.mjlList.get(0).fjl.Description__c = 'Test finacial journal line';

        apc.manEntry.mjlList.get(1).debit = '10';
        apc.manEntry.mjlList.get(1).fjl.Financial_Account__c = fa.id;
        apc.manEntry.mjlList.get(1).fjl.Description__c = 'Test finacial journal line';
        apc.calDebCredTotal();

        apc.addNewEntry();

        List<Financial_Journal_Entry__c> fjeLst = (List<Financial_Journal_Entry__c>)Data.read(
                    'select Id, Name, Entry_Date__c, Description__c, Notes__c, Posted__c, Post_Date__c, (select id, Name, Credit__c, Debit__c,Financial_Account__c, Description__c, Amount__c from Financial_Journals__r) from Financial_Journal_Entry__c where Manual_Entry__c = :isManual',
        new Map<String, Object> {
            'isManual' => true
        }
                );

        System.assertEquals(fjeLst.get(0).Financial_Journals__r.size(), 2);
        /**Insert new new entries ends**/

        /**Update existing entries start**/
        apc.cSelId = apc.getmanualEntries().get(0).fje.id;
        apc.setSelFJE();
        apc.numberLinesToAdd = 10;
        apc.addNewExistingLines();

        apc.selectedMe.mjlList.get(2).linecrd = '10';
        apc.selectedMe.mjlList.get(2).fjl.Financial_Account__c = fa.id;
        apc.selectedMe.mjlList.get(2).fjl.Description__c = 'Test finacial journal line';

        apc.selectedMe.mjlList.get(3).debit = '10';
        apc.selectedMe.mjlList.get(3).fjl.Financial_Account__c = fa.id;
        apc.selectedMe.mjlList.get(3).fjl.Description__c = 'Test finacial journal line';

        //Delete one manual journal line at the time of editing the grid
        apc.fjeId = apc.getmanualEntries().get(0).fje.id;
        apc.fjlId = apc.selectedMe.mjlList.get(1).fjl.id;
        apc.delFJL();

        apc.updateEntry();
        apc.closeSelectedME();

        fjeLst = (List<Financial_Journal_Entry__c>)Data.read(
                     'select Id, Name, Entry_Date__c, Description__c, Notes__c, Posted__c, Post_Date__c, (select id, Name, Credit__c, Debit__c,Financial_Account__c, Description__c, Amount__c from Financial_Journals__r) from Financial_Journal_Entry__c where Manual_Entry__c = :isManual',
        new Map<String, Object> {
            'isManual' => true
        }
                 );

        System.assertEquals(fjeLst.get(0).Financial_Journals__r.size(), 3);
        /**Update existing entries end**/

        /**Delete manual journal entry start**/
        apc.cSelDelId = apc.getmanualEntries().get(0).fje.id;
        apc.delSelFJE();
        System.assertEquals(apc.getmanualEntries().size(), 0);       
        /**Delete manual journal entry end**/

        /**Post journal entry section start**/
        //Create financial journal entry again to post it previously created entry is deleted.
        ManualFinancialJournalController postapc = new ManualFinancialJournalController(sc);    
        postapc.manEntry.mjlList.get(0).linecrd = '10';
        postapc.manEntry.mjlList.get(0).fjl.Financial_Account__c = fa.id;
        postapc.manEntry.mjlList.get(0).fjl.Description__c = 'Test finacial journal line';

        postapc.manEntry.mjlList.get(1).debit = '10';
        postapc.manEntry.mjlList.get(1).fjl.Financial_Account__c = fa.id;
        postapc.manEntry.mjlList.get(1).fjl.Description__c = 'Test finacial journal line';
    
        postapc.addNewEntry();
        postapc.getmanualEntries().get(0).post=true;
        postapc.postFJE();
        /**Post journal entry ends section**/

        /**Load and set recurring template**/
        Financial_Journal_Entry__c recurringEntry=new Financial_Journal_Entry__c();
        recurringEntry.Manual_Entry__c=false;
        recurringEntry.Recurring_Entry__c=true;
        recurringEntry.Recurring_Journal_Frequency__c='Monthly';
        recurringEntry.Recurring_Entry_Name__c='TestEntry';
        Data.Create(recurringEntry);

        Financial_Journal_Line__c recurringLine=new Financial_Journal_Line__c();
        recurringLine.Amount__c = 10;
        recurringLine.Financial_Account__c = fa.id;
        recurringLine.Description__c = 'Test finacial journal line';
        recurringLine.Recurring_Journal_Line__c = true;
        recurringLine.Financial_Journal_Entry__c=recurringEntry.id;
        Data.Create(recurringLine);

        postapc.recurringEntry.Recurring_Journal_Frequency__c='Monthly';
        postapc.loadTemplates();
        postapc.selectedTemplate=recurringEntry.id;
        postapc.setRecurringEntry();
        /**Load and set recurring template End**/
        Test.stopTest();
    }
}