src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Asset</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Income</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expense</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Administrative &amp; General</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aquatic Sports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clubhouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Common Area Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facility Maintenance &amp; Energy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fitness/Spa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Charges &amp; Income Taxes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Golf Course maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Golf Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Golf Shop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housekeeping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Technology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Locker Rooms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing &amp; Membership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Allocated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Operating Departments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overnight Rooms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payroll Taxes &amp; Employee Benefits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Racquet Shop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Racquet Sports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rentals &amp; Other Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special-purpose Funds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Club Rooms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Club Rooms (HSKP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gift Shop</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ServiceCharges__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>stored service charges</description>
    <fields>
        <fullName>Service_Charge_for_food__c</fullName>
        <description>Service Charge for food</description>
        <inlineHelpText>Service Charge for food</inlineHelpText>
        <label>Service Charge for food</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <label>ServiceCharges</label>
</CustomObject>

src/objects/Tax_To_Account_Mapping__c.object
<CustomObject>
    <description>This object contains the mapping records for each tax, service charge, and use tax when they are mapped to a Financial Account.</description>
    <fields>
        <fullName>Financial_Accounts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Accounts</label>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Tax To Account Mappings</relationshipLabel>
        <relationshipName>Tax_To_Account_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Charge_Value__c</fullName>
        <description>Service Charge Value</description>
        <label>Service Charge Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Charge__c</fullName>
        <description>Service Charge Names</description>
        <label>Service Charge</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Value__c</fullName>
        <description>Tax Value</description>
        <label>Tax Value</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Tax To Account Mapping</label>
    <nameField>
        <displayFormat>Tax-Acc-{000000}</displayFormat>
        <label>TaxToAccountMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax To Account Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Taxes__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <description>General Sales Tax</description>
        <label>Sales Tax</label>
        <precision>6</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transit_Improvement_Sales_Tax__c</fullName>
        <label>Transit Improvement Sales Tax</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <label>Taxes</label>
</CustomObject>

src/objects/TXN__c.object
<CustomObject>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Transactions (Financial Account)</relationshipLabel>
        <relationshipName>Transactions3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Charge__c</fullName>
        <description>service charge on this transaction</description>
        <inlineHelpText>service charge on this transaction</inlineHelpText>
        <label>Service Charge</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Tax</fullName>
        <active>true</active>
        <label>Tax</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TxnChargeToTaxMapping__c.object
<CustomObject>
    <description>This object contains the mapping records for Type and Subtype and their taxes and service charges.</description>
    <fields>
        <fullName>Charge__c</fullName>
        <description>charge - comes from the txn object.</description>
        <label>Record Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>If_Taxes_Are_Applicable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>If Taxes Are Applicable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Charge_applicable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if service charge is applicable then true.</description>
        <label>Service _Charge_applicable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subtype__c</fullName>
        <description>global subtype picklist value</description>
        <globalPicklist>SubType</globalPicklist>
        <label>Subtype</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TaxId__c</fullName>
        <description>tax id this is coming from customer setting and setting name taxes.</description>
        <label>TaxId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Taxes_applicable_on_service_charge__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if this is checked then the selected taxes will also apply on the service charge.</description>
        <label>Taxes_applicable_on_service_charge</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>global type picklist field</description>
        <globalPicklist>Type</globalPicklist>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>tax_on_service_charge__c</fullName>
        <description>if tax on service charge is applicable then this field will contain the tax id which is applicable</description>
        <label>tax_on_service_charge</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>TxnChargeToTaxMapping</label>
    <nameField>
        <displayFormat>ctot-{000000}</displayFormat>
        <label>TxnChargeToTaxMapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TxnChargeToTaxMappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MappingAndTaxUtilityTest.cls
public class MappingAndTaxUtilityTest {
  public static Integer financialAccountNumber = 1;
  
  //Create Financial Account
  public static Financial_Account__c createFinancialAccount(Integer financialAccountNumberL) {
    Financial_Account__c financialAccountForTest = new Financial_Account__c();
    financialAccountForTest.Name = 'Test finance' + financialAccountNumberL;
    financialAccountForTest.Account_Number__c = string.valueOf(financialAccountNumberL);
    financialAccountForTest.Category__c = 'Assets';
    insert financialAccountForTest;
    return financialAccountForTest;
  }

  //Create tax in customSetting for test coverage
  public static void CreateTax_And_ServiceCharge() {
    Taxes__c tax = new Taxes__c();
    tax.Sales_Tax__c = 6.65;
    tax.Transit_Improvement_Sales_Tax__c = 6.65;
    //insert tax;
    Data.create(tax);
    /*
    ServiceCharges__c sr = new ServiceCharges__c();
    sr.Service_Charge_for_food__c = 6.65;
    insert sr;
    */
  }

  //Create Tax Mapping
  public static TxnChargeToTaxMapping__c createTaxMapping(string type, string subtype) {
    TxnChargeToTaxMapping__c newTaxMapping = new TxnChargeToTaxMapping__c();
    // commenting this because of new type subtype structure without recordtype - jyoti - not changing the signature of this method currenctly.
    //newTaxMapping.Charge__c = Utility.searchRecordType(recordType, 'TXN__c');
    newTaxMapping.Type__c = type;
    newTaxMapping.SubType__c = subtype;
    Map<string, Schema.SObjectField> fieldsMap = Taxes__c.sObjectType.getDescribe().fields.getMap();
    string taxId;
    string taxANme;
    Double taxVal;
    for (string field : fieldsMap.keySet()) {
      Schema.SObjectField F = fieldsMap.get(field);
      Schema.DescribeFieldResult R = F.getDescribe();
      if (R.isCustom()) {
        taxId = R.getName();
        taxANme = R.getLabel();
        Taxes__c allTaxesHSettings = Taxes__c.getInstance();

        try {
          taxVal = double.valueOf(allTaxesHSettings.get(taxId));
        } catch (System.TypeException ex) {
          continue;
        }
        if (taxVal != null) {
          break;
        }
      }
    }

    financialAccountNumber++;
    newTaxMapping.Service_Charge_applicable__c = true;
    newTaxMapping.TaxId__c = taxId;
    newTaxMapping.If_Taxes_Are_Applicable__c = true;
    newTaxMapping.Taxes_applicable_on_service_charge__c = true;
/*
    Tax_To_Account_Mapping__c taxFinMapping = new Tax_To_Account_Mapping__c();
    taxFinMapping.Tax__c = taxANme;
    taxFinMapping.Tax_Value__c = '6.65';
    taxFinMapping.Financial_Accounts__c = createFinancialAccount(financialAccountNumber).id;
    insert taxFinMapping;
*/
    Map<string, Schema.SObjectField> fieldsMap1 = ServiceCharges__c.sObjectType.getDescribe().fields.getMap();
    string servCharge;
    string servName;
    Double serVal;

    for (string field : fieldsMap1.keySet()) {
      Schema.SObjectField F = fieldsMap1.get(field);
      Schema.DescribeFieldResult R = F.getDescribe();
      if (R.isCustom()) {
        servCharge = R.getName();
        servName = R.getLabel();
        //c62ServiceCharges__c allServiceChargeSettings = c62ServiceCharges__c.getInstance();
        try {
          //serVal = double.valueOf(allServiceChargeSettings.get(servCharge));
        } catch (System.TypeException ex) {
          continue;
        }
        if (serVal != null) {
          break;
        }
      }
    }
/*
    newTaxMapping.tax_on_service_charge__c = servCharge;
    financialAccountNumber++;
    Tax_To_Account_Mapping__c taxFinMappingse = new Tax_To_Account_Mapping__c();
    taxFinMappingse.Service_Charge__c = servName;
    taxFinMappingse.Service_Charge_Value__c = '6.65';
    taxFinMappingse.Financial_Accounts__c = createFinancialAccount(financialAccountNumber).id;
    insert taxFinMappingse;
    */
    insert newTaxMapping; 
    return newTaxMapping;
  }
}