src/objects/Financial_Account__c.object
<CustomObject>
    <description>Enter in the Account Name.</description>
    <fields>
        <fullName>Credit_Text__c</fullName>
        <description>Used on the visualforce page to show current up to date Credit</description>
        <label>Credit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Debit_Text__c</fullName>
        <description>Used on the visualforce page to show current up to date Debits</description>
        <label>Debit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Journal_Line__c.object
<CustomObject>
    <fields>
        <fullName>Credit__c</fullName>
        <formula>IF((Financial_Account__r.Debit_Credit__c==&quot;Credit&quot; &amp;&amp; Amount__c&gt;0)||(Financial_Account__r.Debit_Credit__c==&quot;Debit&quot; &amp;&amp; Amount__c&lt;0),ABS(Amount__c),0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Credit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Debit__c</fullName>
        <formula>IF((Financial_Account__r.Debit_Credit__c==&quot;Debit&quot; &amp;&amp; Amount__c&gt;0)||(Financial_Account__r.Debit_Credit__c==&quot;Credit&quot; &amp;&amp; Amount__c&lt;0),ABS(Amount__c),0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Debit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Financial_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Account__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Account__c</referenceTo>
        <relationshipLabel>Financial Journal Lines</relationshipLabel>
        <relationshipName>Financial_Journal_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Posted?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Recurring_Journal_Line__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recurring Journal Line</label>
        <type>Checkbox</type>
    </fields>
    <label>Financial Journal Line</label>
    <nameField>
        <displayFormat>FINJRNL-{000000}</displayFormat>
        <label>Financial Journal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Journal Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FinancialJournalLineTriggerHandler.cls
/**
* @author joshi Prakash
* @date 07-07-2017
* @group Financial Management
* @description Update the credit and debit total on financial account whenever the financial journal line is updated deleted or inserted.
 **/
public with sharing class FinancialJournalLineTriggerHandler {
	/**
	* @description Method to handle insert update and delete at same time. 
	* @param List of records which are affected during the trigger action.
 	**/
 	
	public static void AfterInsertUpdateDelete(List<Financial_Journal_Line__c> records) {
		CalculateCreditDebit(records);
	}

	/**
	* @description Calculates the credit and debit sum on the finacial account in credit and debit field.
	* @param List of records.
 	**/

	private static void CalculateCreditDebit(List<Financial_Journal_Line__c> records) {
		Set<id> financialAccountIds = new Set<id>();
		List<Financial_Account__c> financialAccountToUpdate = new List<Financial_Account__c>();

		for (Financial_Journal_Line__c item : records) {
			financialAccountIds.add(item.Financial_Account__c);
		}

		//Query all the finacial journal lines for each finacial account
		List<Financial_Account__c> finacialAccounts = (List<Financial_Account__c>)Data.read(
		            'select Id, Name, Credit_Text__c, Debit_Text__c, (select id, Credit__c, Debit__c, Posted__c, Recurring_Journal_Line__c from Financial_Journal_Lines__r) from Financial_Account__c where Id IN :financialAccountIds',
		new Map<String, Object> {
			'financialAccountIds' => financialAccountIds
		});

		//loop over to the finacial account and update credit and debit.
		for (Financial_Account__c faccount : finacialAccounts) {
			faccount.Credit_Text__c = 0.00;
			faccount.Debit_Text__c = 0.00;
			for (Financial_Journal_Line__c fjl : faccount.Financial_Journal_Lines__r) {
				if (fjl.Posted__c == true && fjl.Recurring_Journal_Line__c != true) {
					if (fjl.Credit__c != null) {
						faccount.Credit_Text__c += fjl.Credit__c;

					}

					if (fjl.Debit__c != null) {
						faccount.Debit_Text__c += fjl.Debit__c;

					}
				}
			}

			financialAccountToUpdate.add(faccount);
		}
		Data.modify(financialAccountToUpdate);
	}
}