src/objects/Member_statement_pdf__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>spacing for member statement pdf page.</description>
    <fields>
        <fullName>Current_left__c</fullName>
        <label>Current left</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_top__c</fullName>
        <label>Current top</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Note_1__c</fullName>
        <label>Note 1</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Note_2__c</fullName>
        <label>Note 2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>account_no_left__c</fullName>
        <label>account no left</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>account_no_top__c</fullName>
        <label>account no top</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>amount_paid_left__c</fullName>
        <label>amount paid left</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>amount_paid_top__c</fullName>
        <label>amount paid top</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>balance_due_left__c</fullName>
        <label>balance due left</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>balance_due_top__c</fullName>
        <label>balance due top</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>club_address_left__c</fullName>
        <label>club address left</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>club_address_top__c</fullName>
        <label>club address top</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>club_email_left__c</fullName>
        <label>club email left</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>club_email_top__c</fullName>
        <label>club email top</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>club_name_left__c</fullName>
        <label>club name left</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>club_name_top__c</fullName>
        <label>club name top</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>club_phone_left__c</fullName>
        <label>club phone left</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>club_phone_top__c</fullName>
        <label>club phone top</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>color__c</fullName>
        <label>color</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>column_order__c</fullName>
        <defaultValue>&apos;0,1,2,3,4,5,6,7,8,9&apos;</defaultValue>
        <label>column order</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>due_left__c</fullName>
        <label>due left</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>due_top__c</fullName>
        <label>due top</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>email_id__c</fullName>
        <label>email id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>fax_left__c</fullName>
        <label>fax left</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>fax_top__c</fullName>
        <label>fax top</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>logo_left__c</fullName>
        <label>logo left</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>logo_top__c</fullName>
        <label>logo top</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>notes_1_left__c</fullName>
        <label>notes 1 left</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>notes_1_top__c</fullName>
        <label>notes 1 top</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>notes_2_left__c</fullName>
        <label>notes 2 left</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>notes_2_top__c</fullName>
        <label>notes 2 top</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>over_30_left__c</fullName>
        <label>over 30 left</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>over_30_top__c</fullName>
        <label>over 30 top</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>over_60_left__c</fullName>
        <label>over 60 left</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>over_60_top__c</fullName>
        <label>over 60 top</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>over_90_left__c</fullName>
        <label>over 90 left</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>over_90_top__c</fullName>
        <label>over 90 top</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>page_no_left__c</fullName>
        <label>page no left</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>page_no_top__c</fullName>
        <label>page no top</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>statement_date_left__c</fullName>
        <label>statement date left</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>statement_date_top__c</fullName>
        <label>statement date top</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>statement_label_left__c</fullName>
        <label>statement label left</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>statement_label_top__c</fullName>
        <label>statement label top</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>table_header_10_Width__c</fullName>
        <label>table header 10 Width</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>table_header_10__c</fullName>
        <label>table header 10</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>table_header_10_hide__c</fullName>
        <defaultValue>false</defaultValue>
        <label>table header 10 hide</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>table_header_1_Width__c</fullName>
        <label>table header 1 Width</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>table_header_1__c</fullName>
        <label>table header 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>table_header_1_hide__c</fullName>
        <defaultValue>false</defaultValue>
        <label>table header 1 hide</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>table_header_2_Width__c</fullName>
        <label>table header 2 Width</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>table_header_2__c</fullName>
        <label>table header 2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>table_header_2_hide__c</fullName>
        <defaultValue>false</defaultValue>
        <label>table header 2 hide</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>table_header_3_Width__c</fullName>
        <label>table header 3 Width</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>table_header_3__c</fullName>
        <label>table header 3</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>table_header_3_hide__c</fullName>
        <defaultValue>false</defaultValue>
        <label>table header 3 hide</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>table_header_4_Width__c</fullName>
        <label>table header 4 Width</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>table_header_4__c</fullName>
        <label>table header 4</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>table_header_4_hide__c</fullName>
        <defaultValue>false</defaultValue>
        <label>table header 4 hide</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>table_header_5_Width__c</fullName>
        <label>table header 5 Width</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>table_header_5__c</fullName>
        <label>table header 5</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>table_header_5_hide__c</fullName>
        <defaultValue>false</defaultValue>
        <label>table header 5 hide</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>table_header_6_Width__c</fullName>
        <label>table header 6 Width</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>table_header_6__c</fullName>
        <label>table header 6</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>table_header_6_hide__c</fullName>
        <defaultValue>false</defaultValue>
        <label>table header 6 hide</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>table_header_7_Width__c</fullName>
        <label>table header 7 Width</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>table_header_7__c</fullName>
        <label>table header 7</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>table_header_7_hide__c</fullName>
        <defaultValue>false</defaultValue>
        <label>table header 7 hide</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>table_header_8_Width__c</fullName>
        <label>table header 8 Width</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>table_header_8__c</fullName>
        <label>table header 8</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>table_header_8_hide__c</fullName>
        <defaultValue>false</defaultValue>
        <label>table header 8 hide</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>table_header_9_Width__c</fullName>
        <label>table header 9 Width</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>table_header_9__c</fullName>
        <label>table header 9</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>table_header_9_hide__c</fullName>
        <defaultValue>false</defaultValue>
        <label>table header 9 hide</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>table_left__c</fullName>
        <label>table left</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>table_top__c</fullName>
        <label>table top</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>total_rows_to_show__c</fullName>
        <label>total rows to show</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Member statement pdf</label>
</CustomObject>

src/classes/MemberStatementPDFTestCont.cls
public with sharing class MemberStatementPDFTestCont {
    public Member_statement_pdf__c   spacing{get;set;}
    public MemberStatementPDFTestCont() {
        spacing = new Member_statement_pdf__c  ();
        if(Member_statement_pdf__c.getall().values().size()>0){
            spacing = new Member_statement_pdf__c  ();
        	spacing = Member_statement_pdf__c.getall().values();
        }else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Please set the values for check spacing in "Member statement PDF" custom setting first.'));
        }
    }
    @RemoteAction
    public static List<Member_statement_pdf__c> SpacingSetting(string fieldName,string top, string left){
        Member_statement_pdf__c setting =new Member_statement_pdf__c();
        List<Member_statement_pdf__c> AllCSData = Member_statement_pdf__c.getall().values();
        if(fieldName == 'LogoDrag'){
        	setting.logo_left__c  = double.valueOf(left);
            setting.logo_top__c  = double.valueOf(top);
            setting.Id=AllCSData[0].id;
        }else
        if(fieldName == 'ClubNameDrag'){
        	setting.club_name_left__c  = double.valueOf(left);
            setting.club_name_top__c  = double.valueOf(top);
            setting.Id=AllCSData[0].id;
        }else
        if(fieldName == 'EmailIdDrag'){
        	setting.club_email_left__c   = double.valueOf(left);
            setting.club_email_top__c   = double.valueOf(top);
            setting.Id=AllCSData[0].id;
        }else
        if(fieldName == 'faxDrag'){
        	setting.fax_left__c  = double.valueOf(left);
            setting.fax_top__c  = double.valueOf(top);
            setting.Id=AllCSData[0].id;
        }else
        if(fieldName == 'phoneDrag'){
        	setting.club_phone_left__c   = double.valueOf(left);
            setting.club_phone_top__c   = double.valueOf(top);
            setting.Id=AllCSData[0].id;
        }else
        if(fieldName == 'AddressDrag'){
        	setting.club_address_left__c   = double.valueOf(left);
            setting.club_address_top__c   = double.valueOf(top);
            setting.Id=AllCSData[0].id;
        }else
        if(fieldName == 'StatementLabelDrag'){
        	setting.statement_label_left__c   = double.valueOf(left);
            setting.statement_label_top__c   = double.valueOf(top);
            setting.Id=AllCSData[0].id;
        }else
        if(fieldName == 'note1Drag'){
        	setting.notes_1_left__c    = double.valueOf(left);
            setting.notes_1_top__c    = double.valueOf(top);
            setting.Id=AllCSData[0].id;
        }else
        if(fieldName == 'note2Drag'){
        	setting.notes_2_left__c    = double.valueOf(left);
            setting.notes_2_top__c    = double.valueOf(top);
            setting.Id=AllCSData[0].id;
        }else
        if(fieldName == 'AccountNoDrag'){
        	setting.account_no_left__c    = double.valueOf(left);
            setting.account_no_top__c    = double.valueOf(top);
            setting.Id=AllCSData[0].id;
        }else
        if(fieldName == 'StatementDateDrag'){
        	setting.statement_date_left__c    = double.valueOf(left);
            setting.statement_date_top__c   = double.valueOf(top);
            setting.Id=AllCSData[0].id;
        }else
        if(fieldName == 'pageNoDrag'){
        	setting.page_no_left__c     = double.valueOf(left);
            setting.page_no_top__c   = double.valueOf(top);
            setting.Id=AllCSData[0].id;
        }else
        if(fieldName == 'BalanceDueDrag'){
        	setting.due_left__c     = double.valueOf(left);
            setting.due_top__c    = double.valueOf(top);
            setting.Id=AllCSData[0].id;
        }else
        if(fieldName == 'amountPaidDrag'){
        	setting.amount_paid_left__c     = double.valueOf(left);
            setting.amount_paid_top__c   = double.valueOf(top);
            setting.Id=AllCSData[0].id;
        }else
        if(fieldName == 'tableDrag'){
        	setting.table_left__c     = double.valueOf(left);
            setting.table_top__c   = double.valueOf(top);
            setting.Id=AllCSData[0].id;
        }
        else
        if(fieldName == 'CurrentDrag'){
        	setting.Current_left__c      = double.valueOf(left);
            setting.Current_top__c    = double.valueOf(top);
            setting.Id=AllCSData[0].id;
        }else
        if(fieldName == 'over30Drag'){
        	setting.over_30_left__c     = double.valueOf(left);
            setting.over_30_top__c   = double.valueOf(top);
            setting.Id=AllCSData[0].id;
        }else
        if(fieldName == 'over60Drag'){
        	setting.over_60_left__c     = double.valueOf(left);
            setting.over_60_top__c   = double.valueOf(top);
            setting.Id=AllCSData[0].id;
        }else
        if(fieldName == 'over90Drag'){
        	setting.over_90_left__c     = double.valueOf(left);
            setting.over_90_top__c   = double.valueOf(top);
            setting.Id=AllCSData[0].id;
        }else
        if(fieldName == 'BalanceDue2Drag'){
        	setting.balance_due_left__c     = double.valueOf(left);
            setting.balance_due_top__c   = double.valueOf(top);
            setting.Id=AllCSData[0].id;
        }else
        if(fieldName == 'color'){
        	setting.color__c     = top;
            setting.Id=AllCSData[0].id;
        }/*if(fieldName=='reorderColumns'){
            integer fromm = integer.valueOf(top);
            integer to = integer.valueOf(left);
           	string temp='';
           	String[]  csvFieldNames = AllCSData[0].column_order__c.split(',');
            temp = csvFieldNames[fromm];
            csvFieldNames[fromm]=csvFieldNames[to];
            csvFieldNames[to]=temp;
            setting.column_order__c  = string.join(csvFieldNames,',') ;
            setting.Id=AllCSData[0].id;
           
        }*/
		    
        data.modify(setting);
        return null; 
    }
    
    public void save(){
        List<Member_statement_pdf__c> AllCSData = Member_statement_pdf__c.getall().values();
        AllCSData[0].Note_1__c =spacing.Note_1__c;
		AllCSData[0].Note_2__c =spacing.Note_2__c;
        AllCSData[0].table_header_1__c =spacing.table_header_1__c;
		AllCSData[0].table_header_2__c =spacing.table_header_2__c;
        AllCSData[0].table_header_3__c =spacing.table_header_3__c;
		AllCSData[0].table_header_4__c =spacing.table_header_4__c;
        AllCSData[0].table_header_5__c =spacing.table_header_5__c;
		AllCSData[0].table_header_6__c =spacing.table_header_6__c;
        AllCSData[0].table_header_7__c =spacing.table_header_7__c;
        AllCSData[0].table_header_8__c =spacing.table_header_8__c;
        AllCSData[0].table_header_9__c =spacing.table_header_9__c;
        AllCSData[0].table_header_10__c =spacing.table_header_10__c;
        
        AllCSData[0].table_header_1_hide__c =spacing.table_header_1_hide__c;
        AllCSData[0].table_header_2_hide__c =spacing.table_header_2_hide__c;
        AllCSData[0].table_header_3_hide__c =spacing.table_header_3_hide__c;
        AllCSData[0].table_header_4_hide__c =spacing.table_header_4_hide__c;
        AllCSData[0].table_header_5_hide__c =spacing.table_header_5_hide__c;
        AllCSData[0].table_header_6_hide__c =spacing.table_header_6_hide__c;
        AllCSData[0].table_header_7_hide__c =spacing.table_header_7_hide__c;
        AllCSData[0].table_header_8_hide__c =spacing.table_header_8_hide__c;
        AllCSData[0].table_header_9_hide__c =spacing.table_header_9_hide__c;
        AllCSData[0].table_header_10_hide__c =spacing.table_header_10_hide__c;
        
        AllCSData[0].table_header_1_Width__c =spacing.table_header_1_Width__c;
        AllCSData[0].table_header_2_Width__c =spacing.table_header_2_Width__c;
        AllCSData[0].table_header_3_Width__c =spacing.table_header_3_Width__c;
        AllCSData[0].table_header_4_Width__c =spacing.table_header_4_Width__c;
        AllCSData[0].table_header_5_Width__c =spacing.table_header_5_Width__c;
        AllCSData[0].table_header_6_Width__c =spacing.table_header_6_Width__c;
        AllCSData[0].table_header_7_Width__c =spacing.table_header_7_Width__c;
        AllCSData[0].table_header_8_Width__c =spacing.table_header_8_Width__c;
        AllCSData[0].table_header_9_Width__c =spacing.table_header_9_Width__c;
        AllCSData[0].table_header_10_Width__c =spacing.table_header_10_Width__c;
        
        AllCSData[0].email_id__c =spacing.email_id__c;
        AllCSData[0].total_rows_to_show__c=spacing.total_rows_to_show__c;
         
        
        
        data.modify(AllCSData);
    }
}