src/objects/ServiceCharges__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>stored service charges</description>
    <fields>
        <fullName>Banquet_Bar_Service_Charge__c</fullName>
        <description>each item service charge for banquet bar</description>
        <label>Banquet Bar Service Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Banquet_Beverage_Service_Charge__c</fullName>
        <description>service charge on beverages each item of banquet</description>
        <label>Banquet Beverage Service Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Banquet_Fitness_Service_Charge__c</fullName>
        <label>Banquet Fitness Service Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Banquet_Other_Service_Charge__c</fullName>
        <label>Banquet Other Service Charge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>ServiceCharges</label>
</CustomObject>

src/objects/Taxes__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Sales_Tax__c</fullName>
        <description>General Sales Tax</description>
        <label>Sales Tax</label>
        <precision>6</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Transit_Improvement_Sales_Tax__c</fullName>
        <label>Transit Improvement Sales Tax</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Use_Tax__c</fullName>
        <description>General Use Tax</description>
        <label>Use Tax</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <label>Taxes</label>
</CustomObject>

src/objects/UseTaxes__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>use taxes for vendor invoices</description>
    <fields>
        <fullName>Use_Tax__c</fullName>
        <label>Use Tax</label>
        <precision>15</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <label>UseTaxes</label>
</CustomObject>

src/classes/TaxToAccountMappingControllerTest.cls
@isTest
public class TaxToAccountMappingControllerTest {
    private testMethod static void runAll() {
        test.startTest();
        TaxToAccountMappingController TAM = new TaxToAccountMappingController();
        Taxes__c setting = new Taxes__c();
        /**setting.Catering_Bar_Sales_Tax_Percentage__c = 10;
        setting.Catering_Beverage_Sales_Tax_Percentage__c = 10;
        setting.Catering_Fitness_Sales_Tax_Percentage__c = 10;
        setting.Catering_Other_Sales_Tax_Percentage__c = 10;**/
        setting.Sales_Tax__c =10;
        setting.Transit_Improvement_Sales_Tax__c =10;
        insert setting;
        string settingId=setting.Id;
        /**Taxes__c taxes = [select Catering_Fitness_Sales_Tax_Percentage__c from Taxes__c];
        System.assertEquals(10, taxes.Catering_Fitness_Sales_Tax_Percentage__c);**/
        
        ServiceCharges__c sCharge =new ServiceCharges__c();
        sCharge.Banquet_Bar_Service_Charge__c=10;
        sCharge.Banquet_Beverage_Service_Charge__c=10;
        sCharge.Banquet_Fitness_Service_Charge__c=10;
        sCharge.Banquet_Other_Service_Charge__c=10;
        insert sCharge;
        string sChargeId=sCharge.Id;
        ServiceCharges__c sc = [select Banquet_Bar_Service_Charge__c from ServiceCharges__c];
        System.assertEquals(10, sc.Banquet_Bar_Service_Charge__c);
        
        UseTaxes__c useTx =new UseTaxes__c();
        useTx.Use_Tax__c=10;
        insert useTx;
        string useTxId=useTx.Id;
        UseTaxes__c ut = [select Use_Tax__c from UseTaxes__c];
        System.assertEquals(10, ut.Use_Tax__c);
        
        TAM.save();
        TAM = new TaxToAccountMappingController();
        
        setting = new Taxes__c();
        setting.Id=settingId;
        //setting.Catering_Bar_Sales_Tax_Percentage__c = 11;
        update setting;
        
        sCharge =new ServiceCharges__c();
        sCharge.id=sChargeId;
        sCharge.Banquet_Bar_Service_Charge__c=10;
        update sCharge;
        
        useTx =new UseTaxes__c();
        useTx.Id=useTxId;
        useTx.Use_Tax__c=11;
        update useTx;
        
        TAM.save();
        test.stopTest();
        
    }

}