src/objects/Statements__c.object
<CustomObject>
    <description>the object is used to store member statements</description>
    <fields>
        <fullName>Bill_To_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to store a member id</description>
        <label>Bill To Member</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.Record_Type_Name__c</field>
                <operation>equals</operation>
                <value>Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Statements</relationshipLabel>
        <relationshipName>Statements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Period__c</fullName>
        <description>the field is used to store the billing month and year for statement generation</description>
        <label>Billing Period</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Statement_Summary_Name__c</fullName>
        <description>contains the name of the summary record</description>
        <label>Statement Summary Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Statement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Statement</label>
        <referenceTo>Statements__c</referenceTo>
        <relationshipLabel>Statements</relationshipLabel>
        <relationshipName>Statements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <label>Statement</label>
    <nameField>
        <displayFormat>Stmt-{0000000}</displayFormat>
        <label>Statements Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TXN__c.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Bill To Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Bill To Member)</relationshipLabel>
        <relationshipName>TransactionBillTo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Statement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to store the statement line id</description>
        <label>Statement</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Statements__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Statement Line</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Statements__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Deposit</fullName>
        <active>true</active>
        <label>Deposit</label>
    </recordTypes>
    <recordTypes>
        <fullName>Taxes</fullName>
        <active>true</active>
        <description>Used to store tax amounts</description>
        <label>Taxes</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GenerateStatementController.cls
/**
* @Description : controller class for generating statements
*/
public with sharing class GenerateStatementController {

	public Statements__c statementSummaryRec {get; set;}
	public String monthYear {get; set;}
	public Id batchId {get; set;}
	public Boolean confirmOnDup {get; set;}
	public Boolean callRegenerate {get; set;}
	public Boolean noTxnsFound {get; set;}
	public String status {get; set;}
	public Boolean afterStmtError {get; set;}
	private Set<Id> membersForGenerating;
	private Statements__c stmtSummIdToDeleteOrRegen;


	public GenerateStatementController() {
		afterStmtError = false;
		batchId = GenerateDuesController.getStatusOfBatch('GenerateStatementBatch');
		if(batchId==null){
			batchId = GenerateDuesController.getStatusOfBatch('UpdateStatementBatch');
		}
		noTxnsFound = false;
		confirmOnDup = false;
		callRegenerate = false;
		statementSummaryRec = new Statements__c(RecordtypeId=Utility.searchRecordType('Statement Summary','Statements__c'));		
	}

	public void generate()
	{
		confirmOnDup = false;
		callRegenerate = false;
		noTxnsFound = false;
		afterStmtError = false;

		if(monthYear==null || monthYear=='' || statementSummaryRec.Statement_Summary_Name__c==null)
		{
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Please fill in the mandatory fields.'));
			return;
		}
		if(status=='Confirm'){
			statementSummaryRec.Date__c = Date.newInstance(Integer.valueOf(monthYear.split(' ')[0]), Integer.valueOf(monthYear.split(' ')[1])+1, 1);
			List<Statements__c> stmtList = getStatement(statementSummaryRec.Date__c);
			if(stmtList.size()>0)
			{	
				List<Statements__c> stmtListRelated = getRelatedToStmt(stmtList[0].id);
				if(stmtListRelated.size()>0){
					callRegenerate = true;
				}
				else{
					confirmOnDup = true;
				}
				stmtSummIdToDeleteOrRegen = stmtList[0];
				return;
			}
		}
		if(!confirmOnDup && !callRegenerate){
			statementSummaryRec.Billing_Period__c = String.valueOf(DateTime.newInstance(statementSummaryRec.Date__c.Year(), statementSummaryRec.Date__c.Month(), statementSummaryRec.Date__c.Day()).format('MMMM'))+' '+statementSummaryRec.Date__c.Year();
			if(getpreviousStatementSumm(statementSummaryRec.Date__c)!=null){
				statementSummaryRec.Statement__c = getpreviousStatementSumm(statementSummaryRec.Date__c).id;
			}
			if(status=='Generate'){
				ApproveRejectStatements ap = new ApproveRejectStatements(new List<Statements__c> {stmtSummIdToDeleteOrRegen}, 'Reject');
				Database.executeBatch(ap);
			}
			if(status=='Generate' || status=='Confirm'){
				Integer numberOfDays = Date.daysInMonth(statementSummaryRec.Date__c.Year(), statementSummaryRec.Date__c.Month());
				Date lastDayOfMonth = Date.newInstance(statementSummaryRec.Date__c.Year(), statementSummaryRec.Date__c.Month(), numberOfDays);
				statementSummaryRec.To_Date__c = lastDayOfMonth;
				List<Statements__c> afterStmt = getAfterStatement(statementSummaryRec.To_Date__c);
				if(afterStmt.size()>0){
					afterStmtError = true;
					return;
				}
				GenerateStatementBatch genStatBatch = new GenerateStatementBatch(statementSummaryRec.Date__c, lastDayOfMonth, statementSummaryRec, getAllStatementSummarioes());
				batchId = Database.executeBatch(genStatBatch, 2);
			}
			if(status=='Update'){
				stmtSummIdToDeleteOrRegen.Statement_Summary_Name__c = statementSummaryRec.Statement_Summary_Name__c;
				updateStatements(stmtSummIdToDeleteOrRegen);
			}
		}
	}

	/**
	* @Description : get statement summary with the passed in date
	*/
	public List<Statements__c> getStatement(Date billingDate){
		return Data.read('Select Id, To_Date__c, Date__c from Statements__c where RecordtypeId=:recId AND Date__c=:billingDate',
											new Map<String, Object> {'recId' => Utility.searchRecordType('Statement Summary','Statements__c'),
																	 'billingDate' => billingDate	
											});
	}

	/**
	* @Description : get statement summary with the passed in date
	*/
	public List<Statements__c> getAfterStatement(Date billingDate){
		return Data.read('Select Id, To_Date__c, Date__c from Statements__c where RecordtypeId=:recId AND Date__c>=:billingDate',
											new Map<String, Object> {'recId' => Utility.searchRecordType('Statement Summary','Statements__c'),
																	 'billingDate' => billingDate	
											});
	}

	/**
	* @Description : get relatedStatements
	*/
	public static List<Statements__c> getRelatedToStmt(Id stmtSummId){
		return Data.read('Select id from Statements__c where RecordtypeId=:recId AND Statement__c=:stmtId', 
					new Map<String, Object> {'recId' => Utility.searchRecordType('Statement Summary','Statements__c'),
											 'stmtId' => stmtSummId	
					});
	}

	public void cancel()
	{
		confirmOnDup = false;
		callRegenerate = false;
		noTxnsFound = false;
		stmtSummIdToDeleteOrRegen = null;
		status = '';
	}

	/**
	* @Description : get previous summary record
	*/
	public Statements__c getpreviousStatementSumm(Date billingDate)
	{
		List<Statements__c> statementsList;
		if(stmtSummIdToDeleteOrRegen==null){
			statementsList = Data.read('Select Id from Statements__c where RecordtypeId=:recId AND Date__c<:billingDate order by Date__c DESC',
												new Map<String, Object> {'recId' => Utility.searchRecordType('Statement Summary','Statements__c'),
																		 'billingDate' => billingDate	
												});
		}
		else{
			statementsList = Data.read('Select Id from Statements__c where RecordtypeId=:recId AND Date__c<:billingDate AND Id!=: summToDelId order by Date__c DESC',
												new Map<String, Object> {'recId' => Utility.searchRecordType('Statement Summary','Statements__c'),
																		 'billingDate' => billingDate,
																		 'summToDelId' => stmtSummIdToDeleteOrRegen.id	
												});
		}
		if(statementsList.size()>0){
			return statementsList[0];
		}
		return null;
	}

	/**
	* @Description : get all the statement summaries
	*/
	public List<Statements__c> getAllStatementSummarioes(){
		return Data.read('Select Id, Date__c, To_Date__c from Statements__c where RecordTypeId=:recId', 
			new Map<String, Object>{'recId' => Utility.searchRecordType('Statement Summary','Statements__c')});
	}

	public void updateStatements(Statements__c stmtIdToRegen){
		Set<Id> membersIds = new Set<Id>();
		Map<Id, Statements__c> mapOfStmtSumm = new Map<Id, Statements__c> ((List<Statements__c>) Data.read('Select id, Statement__c, Billing_Period__c, Date__c, To_Date__c from Statements__c where RecordtypeId=:recId AND Date__C>=:fromDate',
									new Map<String, Object> {'recId' => Utility.searchRecordType('Statement Summary','Statements__c'),
															 'fromDate' => stmtIdToRegen.Date__c 
								}
			));

		for(AggregateResult ar : (List<AggregateResult>) Data.read('Select count(Id) c, Bill_To_Member__c  from TXN__C where Date__c>=:fromDate AND Date__c<=:toDate AND Statement__c=:stmtId AND RecordTypeId not in:recId group by Bill_To_Member__c',
			new Map<String, Object> {'fromDate' => stmtIdToRegen.Date__c,
									 'toDate' => stmtIdToRegen.To_Date__c,
									 'stmtId' => null,
									 'recId' => new List<String> {Utility.searchRecordType('Deposit', 'TXN__C'), Utility.searchRecordType('Taxes', 'TXN__C'), Utility.searchRecordType('Service Charges', 'TXN__C')}
			}))
		{
			if(Integer.valueOf(ar.get('c'))>0){
				if(ar.get('Bill_To_Member__c')!=null && String.valueOf(ar.get('Bill_To_Member__c'))!=''){
					membersIds.add(String.valueOf(ar.get('Bill_To_Member__c')));
				}
			}
		}
		if(membersIds.size()>0){
			UpdateStatementsBatch ups = new UpdateStatementsBatch(stmtIdToRegen, membersIds, mapOfStmtSumm, null, null);
			batchId = Database.executeBatch(ups, 1);
		}
		else{
			noTxnsFound = true;
			Data.modify(stmtIdToRegen);
		}
	}
}