src/objects/Statements__c.object
<CustomObject>
    <description>the object is used to store member statements</description>
    <fields>
        <fullName>Bill_To_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to store a member id</description>
        <label>Bill To Member</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.Record_Type_Name__c</field>
                <operation>equals</operation>
                <value>Member</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Statements</relationshipLabel>
        <relationshipName>Statements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Period__c</fullName>
        <description>the field is used to store the billing month and year for statement generation</description>
        <label>Billing Period</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Statement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Statement</label>
        <referenceTo>Statements__c</referenceTo>
        <relationshipLabel>Statements</relationshipLabel>
        <relationshipName>Statements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <label>Statement</label>
    <nameField>
        <displayFormat>Stmt-{0000000}</displayFormat>
        <label>Statements Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TXN__c.object
<CustomObject>
    <fields>
        <fullName>Bill_To_Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Bill To Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions (Bill To Member)</relationshipLabel>
        <relationshipName>TransactionBillTo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Statement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used to store the statement line id</description>
        <label>Statement</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Statements__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Statement Line</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Statements__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <recordTypes>
        <fullName>Deposit</fullName>
        <active>true</active>
        <label>Deposit</label>
    </recordTypes>
    <recordTypes>
        <fullName>Taxes</fullName>
        <active>true</active>
        <description>Used to store tax amounts</description>
        <label>Taxes</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ScheduleUpdateStatementBatch.cls
public class ScheduleUpdateStatementBatch implements Schedulable
{
    public void execute(SchedulableContext sc)
    {
    	Set<Id> membersIds = new Set<Id>();
        for(AggregateResult ar : (List<AggregateResult>) Data.read('Select count(Id) c, Bill_To_Member__c  from TXN__C where Bill_To_Member__c !=:membersId AND Statement__c=:stmtId AND RecordTypeId not in:recId AND Date__C!=:dte group by Bill_To_Member__c',
			new Map<String, Object> {'membersId' => null,
									 'stmtId' => null,
									 'dte' => null,
									 'recId' => new List<String> {Utility.searchRecordType('Deposit', 'TXN__C'), Utility.searchRecordType('Taxes', 'TXN__C'), Utility.searchRecordType('Service Charges', 'TXN__C')}
			}))
		{
			if(Integer.valueOf(ar.get('c'))>0){
				membersIds.add(String.valueOf(ar.get('Bill_To_Member__c')));
			}
		}

		if(membersIds.size()>0){
			List<AggregateResult> arL = (List<AggregateResult>) Data.read('Select MIN(Date__C) d from TXN__C where Bill_To_Member__c in :membersId AND Statement__c=:stmtId AND RecordTypeId not in:recId AND Date__C!=:dte',
			new Map<String, Object> {'membersId' => membersIds,
									 'stmtId' => null,
									 'dte' => null,
									 'recId' => new List<String> {Utility.searchRecordType('Deposit', 'TXN__C'), Utility.searchRecordType('Taxes', 'TXN__C'), Utility.searchRecordType('Service Charges', 'TXN__C')}
									});
			Date minimumDate = Date.valueOf(arL[0].get('d'));

			Map<Id, Statements__c> mapOfStmtSumm = new Map<Id, Statements__c> ();

			List<Statements__c> allStatementSummary = ((List<Statements__c>) Data.read('Select id, Statement__c, Billing_Period__c, Date__c, To_Date__c from Statements__c where RecordtypeId=:recId',
									new Map<String, Object> {'recId' => Utility.searchRecordType('Statement Summary','Statements__c')
								}
			));

			Statements__c latestSumm;
			for(Statements__c stmts : allStatementSummary){
				Boolean isGetRelatedTo = false;
				if(stmts.To_Date__c>=minimumDate){
					mapOfStmtSumm.put(stmts.id, stmts);
				}
				for(Statements__c stmts1 : allStatementSummary){
					if(stmts1.Statement__c==stmts.id){
						isGetRelatedTo = true;
					}
				}
				if(!isGetRelatedTo){
					latestSumm = stmts;
				}
			}
			UpdateStatementsBatch ups = new UpdateStatementsBatch(null, membersIds, mapOfStmtSumm, allStatementSummary, latestSumm);
			Database.executeBatch(ups, 1);
		}
    }
}