src/objects/TXN__c.object
<CustomObject>
    <fields>
        <fullName>Reservation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>TXNs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TXN-{00000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AdjustChargeController.cls
public class AdjustChargeController {

    public String eventId{set;get;}
    public String transactionId {get; set;}
    
    public AdjustChargeController(ApexPages.StandardController controller) {
        transactionId = ApexPages.currentPage().getParameters().get('Id');
        //System.debug('transactionId=====>'+transactionId);
        List<TXN__c> txnTransactionList = Data.read('Select id, Reservation__c from TXN__c where id =: transactionId', new Map<String,Object> {'transactionId' =>transactionId});
        eventId = txnTransactionList[0].Reservation__c;
        //System.debug('eventId=====>'+eventId);
    }
}