src/objects/Vendor_Invoice__c.object
<CustomObject>
    <label>Vendor Invoice</label>
    <nameField>
        <displayFormat>VNDRINVENTR-{0000000}</displayFormat>
        <label>Vendor Invoice Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice_Check__c.object
<CustomObject>
    <fields>
        <fullName>Check_Date__c</fullName>
        <label>Check Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vendor Invoice Checks</relationshipLabel>
        <relationshipName>Vendor_Invoice_Checks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Vendor Invoice Check</label>
    <nameField>
        <displayFormat>VNDRINVCK-{0000000}</displayFormat>
        <label>Vendor Invoice Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Vendor_Invoice_Check__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Invoice Check</label>
        <referenceTo>Vendor_Invoice_Check__c</referenceTo>
        <relationshipLabel>Vendor Invoice Payments</relationshipLabel>
        <relationshipName>Vendor_Invoice_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoice__c</fullName>
        <label>Vendor Invoice</label>
        <referenceTo>Vendor_Invoice__c</referenceTo>
        <relationshipLabel>Vendor Invoice Payments</relationshipLabel>
        <relationshipName>Vendor_Invoice_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vendor Invoice Payment</label>
    <nameField>
        <displayFormat>VNDRSTMTPAY-{0000000}</displayFormat>
        <label>Vendor Invoice Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/cmsft_VendorInvoiceCheckSelector.cls
/**
 * @Description :Class encapsulates query logic for Vendor_Invoice_Check__c
 *
 * https://developer.salesforce.com/page/Apex_Enterprise_Patterns_-_Selector_Layer
 */

public class cmsft_VendorInvoiceCheckSelector extends fflib_SObjectSelector
{
	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField> {
				Vendor_Invoice_Check__c.Id,
				Vendor_Invoice_Check__c.Vendor__c,
				Vendor_Invoice_Check__c.Check_Date__c
			};
	}

	public Schema.SObjectType getSObjectType()
	{
		return Vendor_Invoice_Check__c.sObjectType;
	}

	/**
    * @Description : get all vendor invoice check records with the child vendor invoice payment records
    * @return list of query result vendor invoice check records with child records
    */
    public List<Vendor_Invoice_Check__c> getVendorInvoiceCheckWithPayments(String condition){
        assertIsAccessible();
        fflib_QueryFactory query = newQueryFactory(true, true, true);
        query.setCondition(condition);
        query.subselectQuery('Vendor_Invoice_Payments__r', true).selectFields(new cmsft_VendorInvoicePaymentSelector().getSObjectFieldList()).selectField('Vendor_Invoice__r.Invoice_Date__c');
        return (List<SObject>) Database.query( query.toSOQL() );
    }

}