src/objects/Vendor_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Vendor Invoice</label>
    <nameField>
        <displayFormat>VNDRINVENTR-{0000000}</displayFormat>
        <label>Vendor Invoice Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice_Line__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoice__c</fullName>
        <label>Vendor Invoice</label>
        <referenceTo>Vendor_Invoice__c</referenceTo>
        <relationshipLabel>Vendor Invoice Lines</relationshipLabel>
        <relationshipName>Vendor_Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vendor Invoice Line</label>
    <nameField>
        <displayFormat>VNDRSTMTLNE-{0000000}</displayFormat>
        <label>Vendor Invoice Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/vendorInvoiceLineTrigger_domain.cls
public class vendorInvoiceLineTrigger_domain extends fflib_SObjectDomain {
	public vendorInvoiceLineTrigger_domain(List<Vendor_Invoice_Line__c > records) {
        super(records);
	}
   
    //check before insert
    public override void onBeforeInsert() {
         //check sum of invoice lines amount should not be more then invoice total amount
        check_invoice_lines_total_amount(records,null,'insert');
    }

    public void check_invoice_lines_total_amount(List<Vendor_Invoice_Line__c > records,Map<Id, SObject> existingRecords,string type){

        for (Vendor_Invoice_Line__c  newRecord : (List<Vendor_Invoice_Line__c >) records) {
            double totalInvoiceAmount = new cmsft_vendorInvoiceLineTriggerSelector().getTotalInvoiceAmount(newRecord.Vendor_Invoice__c);
            //send one by one in voice number and check if its exist in db
            double checkForDuplicateInvoice = new cmsft_vendorInvoiceLineTriggerSelector().getInvoiceLineAmountTotal(newRecord.Vendor_Invoice__c);
            if(checkForDuplicateInvoice != null){ 
            	checkForDuplicateInvoice = checkForDuplicateInvoice + newRecord.Amount__c;
            }else{
                checkForDuplicateInvoice=newRecord.Amount__c;
            }
            Vendor_Invoice_Line__c oldRecord= null;
             if(type == 'update'){
                 //if updating then use new amount for checking the total amount
                oldRecord = (Vendor_Invoice_Line__c) existingRecords.get(newRecord.id);
            	checkForDuplicateInvoice = checkForDuplicateInvoice - oldRecord.Amount__c;
             }
            if(checkForDuplicateInvoice > totalInvoiceAmount){
                //if exist then give error message.
                newRecord.Amount__c.addError('Invoice lines total amount should not be more then invoice total amount');
            }
        }
    }
    //check before update
    public override void onBeforeUpdate(Map<Id, SObject> existingRecords) {
         //check sum of invoice lines amount should not be more then invoice total amount
        check_invoice_lines_total_amount(records,existingRecords,'update');      
    }
    
     public class Constructor implements fflib_SObjectDomain.IConstructable2 {
		public fflib_SObjectDomain construct(List<SObject> sObjectList) {
			return new vendorInvoiceLineTrigger_domain(sObjectList);
		}

		public fflib_SObjectDomain construct(List<SObject> sObjectList, SObjectType sObjectType) {
			return new vendorInvoiceLineTrigger_domain(sObjectList);
		}
	}  
    
}