src/objects/Vendor_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <label>Invoice #</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Vendor, Reciprocal Club</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vendor Invoices</relationshipLabel>
        <relationshipName>Vendor_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vendor Invoice</label>
    <nameField>
        <displayFormat>VNDRINVENTR-{0000000}</displayFormat>
        <label>Vendor Invoice Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/vendorInvoiceTrigger_domain.cls
public class vendorInvoiceTrigger_domain extends fflib_SObjectDomain {
    public vendorInvoiceTrigger_domain(List<Vendor_Invoice__c> records) {
        super(records);
    }
    
    public override void onBeforeInsert() {
        //check new records if anyone of them exist in database
        for (Vendor_Invoice__c existingRecord : (List<Vendor_Invoice__c>) records) {
            //send one by one in voice number and check if its exist in db
            List<Vendor_Invoice__c> checkForDuplicateInvoice = new cmsft_vendorInvoiceTriggerSelector().checkExistingRecord(existingRecord.Invoice_Number__c,existingRecord.Vendor__c);
            if(checkForDuplicateInvoice.size()>0){
                //if exist then give error message.
                existingRecord.Invoice_Number__c.addError('There is already an Invoice on this Vendor with that number, please update the field and click Save again.');
            }
        }
    }
    
  public class Constructor implements fflib_SObjectDomain.IConstructable2 {
  public fflib_SObjectDomain construct(List<SObject> sObjectList) {
   return new vendorInvoiceTrigger_domain(sObjectList);
  }

  public fflib_SObjectDomain construct(List<SObject> sObjectList, SObjectType sObjectType) {
   return new vendorInvoiceTrigger_domain(sObjectList);
  }
}
}