src/objects/Vendor_Invoice__c.object
<CustomObject>
    <label>Vendor Invoice</label>
    <nameField>
        <displayFormat>VNDRINVENTR-{0000000}</displayFormat>
        <label>Vendor Invoice Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Paid__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Amount Paid</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <formula>TEXT(Vendor_Invoice_Line__r.Payment_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Invoice__c</fullName>
        <label>Vendor Invoice</label>
        <referenceTo>Vendor_Invoice__c</referenceTo>
        <relationshipLabel>Vendor Invoice Payments</relationshipLabel>
        <relationshipName>Vendor_Invoice_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vendor Invoice Payment</label>
    <nameField>
        <displayFormat>VNDRSTMTPAY-{0000000}</displayFormat>
        <label>Vendor Invoice Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/cmsft_VendorInvoicePaymentSelector.cls
/**
 * @Description : Class encapsulates query logic for Vendor_Invoice_Payment__c
 * @Date : 6th June - 2017
 * https://developer.salesforce.com/page/Apex_Enterprise_Patterns_-_Selector_Layer
 */

public class cmsft_VendorInvoicePaymentSelector extends fflib_SObjectSelector
{
	public List<Schema.SObjectField> getSObjectFieldList()
	{
		return new List<Schema.SObjectField> {
				Vendor_Invoice_Payment__c.Id,
				Vendor_Invoice_Payment__c.Amount_Paid__c,
				Vendor_Invoice_Payment__c.Payment_Type__c,
				Vendor_Invoice_Payment__c.Vendor_Invoice__c
	    };
	}

	public Schema.SObjectType getSObjectType()
	{
		return Vendor_Invoice_Payment__c.sObjectType;
	}
}