src/objects/Vendor_Invoice_Check__c.object
<CustomObject>
    <fields>
        <fullName>Vendor_Invoice_Check_Batch__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vendor Invoice Check Batch</label>
        <referenceTo>Vendor_Invoice_Check_Batch__c</referenceTo>
        <relationshipLabel>Vendor Invoice Checks</relationshipLabel>
        <relationshipName>Vendor_Invoice_Checks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Void__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Void</label>
        <type>Checkbox</type>
    </fields>
    <label>Vendor Invoice Check</label>
    <nameField>
        <displayFormat>VNDRINVCK-{0000000}</displayFormat>
        <label>Vendor Invoice Check Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Checks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vendor_Invoice_Check_Batch__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Date__c</fullName>
        <label>Batch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Void__c</fullName>
        <defaultValue>false</defaultValue>
        <description>check if check batch is voided.</description>
        <label>Void</label>
        <type>Checkbox</type>
    </fields>
    <label>Vendor Invoice Check Batch</label>
    <nameField>
        <displayFormat>VICB-{0000000}</displayFormat>
        <label>Vendor Invoice Check Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Invoice Check Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/voidCheckorCheckBatch.cls
public with sharing class voidCheckorCheckBatch {
    public string batchId{get;set;}
    public string checkId{get;set;}
    public Vendor_Invoice_Check__c checkDetail{get;set;}
    public Vendor_Invoice_Check_Batch__c batchDetail{get;set;}
    public voidCheckorCheckBatchService serviceObj;
    public boolean alreadyVoided{get;set;}
    public voidCheckorCheckBatch(){
        serviceObj = new voidCheckorCheckBatchService();
        if(ApexPages.CurrentPage().GetParameters().Get('batchId')!='' && ApexPages.CurrentPage().GetParameters().Get('batchId')!=null){
            batchId=ApexPages.CurrentPage().GetParameters().Get('batchId');
            batchDetail=serviceObj.getBatchDetail(batchId);
            alreadyVoided=false;
            if(batchDetail.Void__c == true){
                alreadyVoided=true;
            }
        }else{
            checkId=ApexPages.CurrentPage().GetParameters().Get('checkId');
            checkDetail = serviceObj.getCheckDetail(checkId);
            alreadyVoided=false;
            if(checkDetail.Void__c == true){
                alreadyVoided=true;
            }
        }
        
    }
    public PageReference VoidCheck(){
        serviceObj.VoidCheck(new List<Vendor_Invoice_Check__c>{checkDetail},date.today());
        PageReference pg = new PageReference('/'+checkId);
        pg.setRedirect(true);
        return pg;
    }
    public PageReference VoidBatch(){
        List<Vendor_Invoice_Check__c> allChecks = serviceObj.getAllChecks(batchId);
        for(Vendor_Invoice_Check__c check : allChecks){
            if(check.Void__c != true){
                serviceObj.VoidCheck(new List<Vendor_Invoice_Check__c>{check},batchDetail.Batch_Date__c);
            }
        }
        batchDetail.Void__c=true;
        Data.modify(batchDetail);
        PageReference pg = new PageReference('/'+batchId);
        pg.setRedirect(true);
        return pg;
    }
    public PageReference returnToCheckPage(){
        PageReference pg = new PageReference('/'+checkId);
        pg.setRedirect(true);
        return pg;
    }
    public PageReference returnToBatchPage(){
        PageReference pg = new PageReference('/'+batchId);
        pg.setRedirect(true);
        return pg;
    }
}